### ISSUE TITLE
(bug) cash payment registry allow multiple cancellation

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1007]
The cash payment registry allow that a payment be cancelled more than one time 

![error_payment_registry](https://cloud.githubusercontent.com/assets/5445251/20812296/e6a51260-b7c5-11e6-8e14-9d8b4309782a.png)

The submit must not display `credit note` because it is not a credit note

![not_credit_note](https://cloud.githubusercontent.com/assets/5445251/20812330/02a0dad0-b7c6-11e6-9c87-0109f8ace811.png)

**Comment by jniles** [comment]
@mbayopanda, this was resolved, correct?

**Comment by mbayopanda** [comment]
@jniles, No, it wasn't resolved

**Comment by jniles** [comment]
Aha.  Okay, thanks!

**Comment by jniles** [comment]
Can you work on it @mbayopanda?
