### ISSUE TITLE
(Feature Request) Allow generic (recalculated) date intervals on filters

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1014]
Currently on all of our registry filters we give the option of selecting a date interval:
'Today'
'This Week'
'This Month'
'This Year'
![date_interval](https://cloud.githubusercontent.com/assets/2844572/20860674/3a2ebc3a-b986-11e6-8b07-3cbfbdaef048.PNG)

Currently the actual date values for these time periods is calculated on the client, these date values are then cached and sent to the server.

I suggest that unless the user has specified date intervals, we just cache the token 'Today'. This will then be calculated new every time the page is loaded (either on the client or the server). 
If this was the case a user could set their registry view to only show this weeks information by default and not have to update the search every time the page was refreshed.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1566
