### ISSUE TITLE
Services are no longer recoverable from cache

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1024]
When recovering a bill, the service can not be recovered.

Steps to reproduce:

Create a bill for TPA1.
Select distributable, 11/01/2016, and test service as details.
Make an invalid row (for example, with a negative cost)
Submit.
Refresh the browser.
Select TPA1.
Click "Recover Cache"
You will notice that distributable is set, 11/01/2016 is the date, and the old description is back. But test service is not set.

**Comment by jniles** [comment]
I'll tackle this.
