### ISSUE TITLE
Editing Posting Journal Transactions

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1030]
This issue tracks development on editing posting journal transactions in 2.X. 
There is currently client side infrastructure for the editing UX, this must be refined and connected to server side controllers to fully implement editing. 

Proposals for initial editing tools
* Scroll to current transaction being edited 
* Only allow one transaction to be edited at once 

Requirements
- [x] Basic validation on individual cells (Number/ Date etc.)
- [x] Adding and removing rows - any required rules/ validation 
- [x] Submit changed values to server on edit completion 
- [x] Respond to message from server and close edit session 
- [x] Implement server transaction update controller 
- [ ] Recipient/ Reference tagging components - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1031

**Comment by sfount** [comment]
Most of these were resolved in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1262

**Comment by jniles** [comment]
@lomamech implemented some basic validation for unbalanced transactions in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1465.

**Comment by jniles** [comment]
The only thing remaining on this is linking other invoices via modal.  That issue is being tracked in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1082.  I'm closing this one.
