### ISSUE TITLE
(Proposal) Editing posting journal transactions recipients/ references 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1031]
Advanced journal vouchers allow you to add a recipient or reference by searching for the entity using a modal. 

I suggest that the posting journal editing tools use exactly the same `ui-grid` cells and modal selection components as journal vouchers. This will provide huge maintainability benefits.

**Comment by jniles** [comment]
Superseded by https://github.com/IMA-WorldHealth/bhima-2.X/issues/2143.  Those modals are too heavy for the Vanga dataset (in its current design).
