### ISSUE TITLE
(Design) Journal Grouping Controls

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1032]
Currently the posting journal is grouped by transaction by default. 

I propose that by default the posting journal has no grouped rows and just displays a flat view of all lines. We can then add a tool to group rows by transactions (and potentially accounts etc.) 

The Accounts module currently uses a button toggle to indicate if in-line filtering is applied or not. This could also be used to demonstrate what groups are being displayed for the posting journal. 

If grouping has been applied we have to ensure that the behavior works predictably across totaling, filtering and sorting https://github.com/IMA-WorldHealth/bhima-2.X/issues/1033

**No groups/ filters applied**
![filter - not applied](https://cloud.githubusercontent.com/assets/2844572/21007807/d72fa696-bd3e-11e6-94d1-24c8f58a336b.PNG)

**Filtering (in this case the group name would be shown) applies**
![filter - applied](https://cloud.githubusercontent.com/assets/2844572/21007816/dd777e8e-bd3e-11e6-93e5-8dbc9e063ff8.PNG)

**Comment by jniles** [comment]
This task was completed on `master`.
