### ISSUE TITLE
(Bug) Unpredictable grouping behavior on posting journal filtering/ sorting

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1033]
When searching or in-line filtering on rows in the posting journal groups expand and collapse in an unpredictable way. 

* Results that are not included in the filter or search are collapsed when the filter is removed. It can be hard to keep track of what you're looking at when rows are constantly changing between expanded and collapsed.

**Comment by jniles** [comment]
This is no longer a factor after the  massive Journal rewrite.
