### ISSUE TITLE
(Proposal) Link receipts/ documents from posting journal rows

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1034]
Currently recipients (Debtors/ Creditors) and References (Invoices/ Cash Payments etc.) are shown in the posting journal as well formatted strings. 

I propose we make these links to documents and entities within BHIMA. This would provide valuable context for the transaction. 

**Current rows** 
![link documents](https://cloud.githubusercontent.com/assets/2844572/21008220/0d18e090-bd41-11e6-85c1-275731979280.PNG)

Each of these reference patient invoices or patients themselves. Linking to the invoice receipts or patient cards would allow an accountant to directly view relevant notes/ users/ inventory items processed etc. in a transaction.

**Comment by jniles** [comment]
How would you feel about storing these links in the database?  Currently, the references are stored in `reference_map`, with a (`uuid`, `text`) pair.  We could easily expand this to (`uuid`, `text`, `link`).

**Comment by sfount** [comment]
That sounds like a good idea to me. It would reduce a lot of calculations
or complexity on displaying the links.

This should consider if the link will be state based (displaying receipt
modal) or URL based.
