### ISSUE TITLE
(perf): use flatEntityAccess for the majority of our grids

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1039]
One useful performance increase might be to enabled `flatEntityAccess` for the majority of our grids, particularly the registries.  Since we are not mutating data at all in these pages, there is no need to do large , nested traversals of the dataset.

[Reference Documentation](http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance).

**Comment by jniles** [comment]
I'll tackle this issue.  I'll also work on adding:
 1. `fastWatch` to grids which can use it ([documentation](http://ui-grid.info/docs/#/tutorial/404_large_data_sets_and_performance)).
 2. 'ngTouch' support ([documentation](https://docs.angularjs.org/api/ngTouch))

**Comment by sfount** [comment]
Sounds good to me. 

I think that `ngTouch` support is primarily required for registries and modules that we expect to be used on mobile/ tablets. Modules like the posting journal may not want to implement these if this is a performance overhead on desktop.

**Comment by jniles** [comment]
If I understand `ngTouch` correctly, we will add it to the entire repository.  Is there something I am missing?

**Comment by sfount** [comment]
I had thought there was a directive you had to add to the grid to hook into
the events - briefly checking out the documentation it doesn't look like it.
