### ISSUE TITLE
(Proposal) Transactions collapsed by default in 'Transaction View'

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1044]
I propose that we do not automatically expand all transactions when the posting journal is opened. 

The default `ui-grid` behaviour is to group collapsed and this is uniformly followed when rows are removed and added with filtering. 

This would simplify additional custom logic on the posting journal and hopefully provide a more uniform UX. 

This could be tackled with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1032 and would contribute to https://github.com/IMA-WorldHealth/bhima-2.X/issues/1033.

**Comment by jniles** [comment]
@sfount, did this behavior get resolved?

**Comment by jniles** [comment]
I believe this has been resolved.
