### ISSUE TITLE
(Proposal) Don't show `trans_id` on every row in the posting journal 'Transaction View'

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1045]
Currently we show the transaction ID on every row in a transaction. Transaction View guarantees these will be grouped. Removing the duplicates should make it easier to scan down a page and find the transaction you need without looking at every single row. 

**Duplicated transaction IDs**
![removed](https://cloud.githubusercontent.com/assets/2844572/21082663/6abee4f0-bfe0-11e6-9332-cc12ba5ec250.PNG)

Could be tackled with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1032

**Comment by jniles** [comment]
This is a very good idea from a UI perspective.  :+1:

**Comment by sfount** [comment]
Still a work in progress but an example of how this proposal would look on a grid: 

![single_trans_id](https://cloud.githubusercontent.com/assets/2844572/21101061/a58cbed0-c077-11e6-8922-e081f5db93a7.PNG)
