### ISSUE TITLE
(Bug) Invoice item has no inventory assigned alert always shows during creation of invoice

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1046]
An alert informing the user that not all of the invoice items have been fully configured is constantly shown throughout the invoice creation process. 

This should only be shown once the user has tried to submit the invoice or presented in another way. 

**Incomplete Invoice - should not be presented as an error state**
![screenshot 2016-12-12 at 09 40 01](https://cloud.githubusercontent.com/assets/2844572/21092995/b7a3811c-c04f-11e6-9b8b-1f8fa8c3abb0.png)

**Comment by jniles** [comment]
I'll take this one.
