### ISSUE TITLE
(Feature) Additional filtered registry links

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1048]
https://github.com/IMA-WorldHealth/bhima-2.X/pull/1012 introduced the idea of requesting a filter from a registry by passing it through `ui-sref` params. 

I propose that we use this feature to give users convenient views into different entities data/ subscriptions. 

Some that I can think are: 
1. Patient record links to that patients invoices 
2. Patient record links to that patients cash payments 
3. " " relevant vouchers

**Comment by jniles** [comment]
I think all these have been completed.
