### ISSUE TITLE
Model the entire Primary Cash module as Journal Vouchers

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#105]
After some analysis of the bhima-1.X primary cash module, I think we could model the entire functionality of the primary cash, with the exception of payroll, as journal vouchers.
### Raison d'Etre

_**Benefits**_:
1. Fewer interfaces for users to learn and master.  More time can be spent on the user manual to explain the Journal Voucher module, rather than spending time maintaining multiple other modules.
2. No more confusing decisions - is this transaction a generic income, or is there a proper way to do this in the application?  Everything is a journal voucher!
3. Fewer modules for developers to maintain - less code means we can spend more time on testing and refinement of the module.  This cannot be overemphasized.
4. Opportunity to build reusable components/models for other pages to benefit from.  For example, the we may need a modal to look up accounts belonging to employees, conventions, suppliers, etc, we can develop it once, test it once, and use it to create employee payment journal vouchers, convention payment journal vouchers, and on any reports that we need may desire.

_**Costs**_:
1.  Requires completely scrapping the Primary Cash module's code and potentially API.
2. Requires retraining the users at our test sight.
### Design Proposal

In order to use Journal Vouchers for Primary Cash operations, we will need to have a Journal Voucher table in the database.  This is different from the current method, where Journal Vouchers simply send data directly to the `posting_journal`.  We need the voucher table so that we have an immutable record (like `sale` or `cash`) of the journal voucher created and can re-print the receipt at any time.

The table should be called `voucher` with fields `uuid`, `date`, `project_id`, `reference`, `currency_id`, `amount`, `description`, `document_uuid`, and `user_id`.  There will be a joiner table `voucher_items` with columns `uuid`, `account_id`, `debit`, `credit`, `voucher_uuid`.
### Additional Commentary

I strongly feel that our Primary Cash module is confusing and over-extended.  It also fits our test site well, but probably will not make any sense when scaling to other hospitals.  What happens if employees are not paid out of the primary cash, but instead the bank?  One whole part of the module is useless.

As we are focusing on Primary Cash next, I would be interested in having a discussion with @IMA-WorldHealth/local-contributors to get feedback on this proposal.

**Comment by DedrickEnc** [comment]
As discussed @jniles will come with a technical design even if the idea seems good.

**Comment by jniles** [comment]
Closing this as the Complex Journal Vouchers have landed in #396.
