### ISSUE TITLE
Make use of UI-Grid save state across registries/ tools

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1050]
UI-Grid provides an API called save state. (http://ui-grid.info/docs/#/tutorial/208_save_state). 

This provides method to export an object that defines the current state of the grid, when a page is refreshed we can use this object to reset the grid to the users preference.

I suggest we use this as a standard way of caching grid preferences across all modules.
This can also be used with services like the column service that currently manually cache column preferences.

**Comment by jniles** [comment]
Sounds good to me.  I see that it is a stable component of `ui-grid`, so we should be able to rely on it reasonably well.

**Comment by jniles** [comment]
This was implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1700.
