### ISSUE TITLE
Letting the user provide the report name instead of long uuid name

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1061]
Our report are generated by the server side and had given a automatic name which is a uuid, so that is difficult to recover when needed so I propose that the user provide him self the name for his report which can be considered as label.

**Comment by sfount** [comment]
Is this for the name of the actual PDF file saved to the disk? Storing the
file as `${uuid}`.pdf allows gives us a way to ensure file names never
conflict, it also is an easy way to look files up using the database UUID.

I agree that the user should never have to see the UUID though - we should
investigate changing the name of the file sent to the user (on download) to
`$[label}.pdf`

**Comment by jniles** [comment]
The way to do this is found in these two places: [res.sendFile()](http://expressjs.com/en/api.html#res.sendFile) and [this SO answer](http://stackoverflow.com/questions/7288814/download-a-file-from-nodejs-server-using-express).

It should be something like this:
```js
app.get('/files/:uuid', (req, res, next) => {
  const headers = {
    'Content-disposition' : 'attachment; filename='
  };

  db.one('SELECT * FROM report_saved WHERE uuid = ?;', [req.params.uuid])
    .then(file => {

       // set a nice file name
       headers['Content-disposition'] += file.name;

       res.sendFile(file.path, headers, error => {
         if (error) { throw error; }
       });
     })
    .catch(next)
    .done();
});
```

**Comment by lomamech** [comment]
@jniles 
I tried modifying the /server/controllers/report.js file as follows, but there is no effect because the file name of the report remains UUID
```js
function sendArchived(req, res, next) {
  lookupArchivedReport(req.params.uuid)
    .then(report => {
      const headers = {
        'Content-disposition' : 'attachment; filename='
      };      

      headers['Content-disposition'] += report.label;

      res.sendFile(report.link, headers, error => {
        if (error) { throw error; }
      });
    })
    .catch(next)
    .done();
}
```

I tried another solution, which allows to use the label of the report in place of the UUID but with this I can not display the file of the report in the system

```js
function sendArchived(req, res, next) {
  lookupArchivedReport(req.params.label)
    .then(report => {

      var options = {
        root: REPORT_PATH,
        dotfiles: 'deny',
        headers: {
            'x-timestamp': Date.now(),
            'x-sent': true
        }
      };

      var fileName = report.label;
      res.sendFile(fileName, options, function (err) {
        if (err) {
          res.status(err.status).end();
        }
      });
    })
    .catch(next)
    .done();
}

```

**Comment by jniles** [comment]
@lomamech, I think @sfount has already implemented the majority of this work... I remember reviewing a PR from him about it.  You can ask him how he succeeded in making it work.
