### ISSUE TITLE
(proposal) Put a `unique` flag on the inventory item table for services

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1065]
In bhima, we have a weird situation where services are bundled in with inventory items.   Other [inventory software](salesbinder.com/) handle this situation by creating "Unique Items" that always have a quantity of 1.  See below:

![inventory type](https://cloud.githubusercontent.com/assets/896472/21145579/13651060-c14f-11e6-998c-7e3c3dc432aa.png)
_Fig 1: SaleBinder's Unique Item Solution_

I propose we do a similar thing - the unique items will not appear in stock, since they do not have a quantity.  They will not appear as an option for ordering in the Purchase Order module.

This category could account for any of the hospital services, such as consultations or surgeries.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by DedrickEnc** [comment]
@jniles 
I don't fully understand the issue, but it seems like in bhima 1.x this category of article was indexed as no consumable so they could not be ordered right? so why not to keep this way of doing?

**Comment by jniles** [comment]
Does any logic in BHIMA currently depend on the consumable inventory flag?  My previous understanding of the consumable flag was determining if it was physical inventory (desks, books, etc) or inventory that will be consumed (medicine, bandages, etc).

The goal is to figure out how to assign Hystérectomie - it should never be ordered (so it must be excluded from purchase orders), it should always have either no quantity or a quantity of 1, and it shouldn't have any stock (excluded from both transfers of stock and stock integration).  Does the `consumable` flag currently handle this case?

**Comment by jniles** [comment]
Since we now have a `default_quantity`, this flag could show/hide the default quantity as well.

**Comment by jniles** [comment]
Looks like [this was already added](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/inventory/configuration/groups/modals/actions.modal.js#L100).
