### ISSUE TITLE
(Proposal) 'Receipt Type' in system settings

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1068]
With the ability to request a point of sale receipt (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1067) we will need to provide the user a way of setting which type of receipt they are capable of printing. This will then be passed through the `posReceipt` flag to the PDF renderer. 

I propose for now that this is set on the settings page under 'System Receipt Settings'. If a report does not support the `posReceipt` flag the normal PDF version of that report will still be returned.

**Comment by jniles** [comment]
Sounds good to me.  It will be nice to have a setting on the settings page that actually does something ...

**Comment by sfount** [comment]
Superseded by https://github.com/Vanga-Hospital/bhima-2.X/issues/8
