### ISSUE TITLE
(bug) Hitting "esc" on the voucher registry search button throws console error

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1073]
The voucher registry (`#/vouchers`) allows a user to search for a date range.  However, this filter is buggy, and will throw a console error when dismissed with the ESC key.

**Steps to reproduce**
 1. Navigate to the voucher registry
 2. Click "search"
 3. Hit "ESC" on your keyboard.

**Expected Result**
The modal disappears, returning the user to the same grid as before the search button was clicked.

**Actual Result**
The loading indicator loads indefinitely, and the console throws an error.

**Comment by mbayopanda** [comment]
LGTM
