### ISSUE TITLE
(bug) Billing services aren't displayed correctly in invoices 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1076]
We currently support both the application of billing services and subsidies to invoices. There are a number of places in invoices where we should verify that these are displayed correctly. 

Currently billing services aren't necesarily displayed in the correct currency and a number of the values are always 0.

![invoice_bug](https://cloud.githubusercontent.com/assets/2844572/21216798/15c7bcda-c2a9-11e6-89ae-2b7c3ee3bb37.PNG)

**Comment by jniles** [comment]
To tackle at the same time: we should refer to the total of the items as "Subtotal", and then the grand total as "Total".  I've seen this on some invoicing software recently and thought it was a good idea.

**Comment by lomamech** [comment]
#1196
