### ISSUE TITLE
Creating database schema and Implementing the server API

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1080]
This issue references #809, it is for creating the database schema and the server API as discussed in the referenced issue beyond here are the task to complete : 

- [x] updating the database structure 

- [x] Creating the server side API 

- [x] Test

**Comment by sfount** [comment]
This looks like a good base for building cost centers - if you begin by creating the database structure we can build on that. 

It might be good to think about what the server API will have to accomplish. 

* Read - List all cost centers or detailed information about a specific cost center 
* Create 
* Update 
* Delete - Does it make sense to delete a cost center? 

* Assign costs? - This API must be designed

EDIT: This has been discussed in https://github.com/IMA-WorldHealth/bhima-2.X/issues/809#issuecomment-254763835, this just needs to be verified and implemented
