### ISSUE TITLE
Automatically assigning cost centers

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1084]
In many cases cost centers can be automatically applied to transactions based on certain criteria. By allowing an enterprise/ head accountant to automatically link transactions to cost centers we should be able to facilitate more advanced reporting without less trained users having to be trained in cost centers. 

**Criteria** 
### Accounts 
Directly link an account to a cost center. Every time the account is written to the posting journal, this cost center will be available to be assigned automatically. 

### Service 
Services can be assigned to various entities in BHIMA. For now they can be assigned to entire patient invoices. When an entity tagged with a service is written to the posting journal, every row within that transaction is eligible to be assigned the service cost center. 

### Transaction Type
Currently vouchers/ simple vouchers allow assigning a transaction type. If transaction types were directly tied to a cost center this cost center could then be applied by default to all rows in these transactions. This also applies to the simplified generic income/ expense documents described in #1016 
If it is impossible to directly link transaction types and cost centers, we could also add a cost center tag for an entire voucher, allowing the creator to label the whole voucher with a cost center.

**Priority** 
It is important to consider the priority of automatic cost center application. 
Current proposal (from highest to lowest priority):
**1. Account** - If an account used is tied to a cost center, this will always be used
**2. Transaction Type**
**3. Service**

**Required Infrastructure** 
### MySQL Procedure
Each entity should not be responsible for assigning automatic cost centers, this would result in many different implementations that require maintenance. 
As different entities are written into the posting journal we could implement a MySQL procedure that checks the properties of a transaction for automatic criteria and ensures the correct reference is applied. 

### Account linking
The accounts management page should be able to link cost centers to accounts. 

### Service linking
Services could use the feature described https://github.com/IMA-WorldHealth/bhima-2.X/issues/933 to assign cost centers. 

### Review automatically linked 
You should be able to review all automatic assignments linked with a particular cost center

@IMA-WorldHealth/bhima-core If there are any more attributes that you know can be automatically linked they should be introduced in this thread.

**Comment by DedrickEnc** [comment]
@sfount, Awesome, but let talk about a global concept which is the fee center.

1. I am not understanding how and why we have to assign a fee center based on a transaction type can you clarify me more?
2. It is good to tail a cost center based on service, mostly that happen at patient invoice but we should take in count the priority degree, which means if an account is directly tailed to a fee center this fee center should be used even if the account is used in patient invoice.

Good idea!

**Comment by jniles** [comment]
@lomamech can this issue be closed?

**Comment by jniles** [comment]
This feature has been implemented.  See for example:

https://github.com/IMA-WorldHealth/bhima/blob/master/server/controllers/finance/cost_center.js#L404C1-L404C57
