### ISSUE TITLE
(design) Stock management database

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1089]
This issue is about the structure of stock database design. 

## 1. Tables

Tables to add for stock management : 

1.1. stock_entry : store all stock lots 

```sql 
CREATE TABLE stock_entry (
  uuid BINARY(16),
  inventory_uuid BINARY(16),
  lot_uuid BINARY(16), -- unique identifier for the lot
  purchase_uuid BINARY(16),
  document_uuid BINARY(16),
  depot_uuid BINARY(16),
  date DATE,
  lot_label VARCHAR(11),
  quantity INT,
  unit_price DECIMAL(19, 4),
  entry_source_id INT -- A reference for the source of entry (purchase_order, adjustment, movement) in entry_source table 
)
```

1.2. stock_exit : store all stock exit 

```sql 
CREATE TABLE stock_exit (
  uuid BINARY(16),
  document_uuid BINARY(16),
  depot_uuid BINARY(16), -- can be null if the out is not for a depot 
  date DATE,
  exit_destination_id INT, -- A reference for the destination of exit (patient, service, adjustment, movement) in exit_destination table 
  cancelled TINYINT(1)
)
```

1.3. stock_exit_item : store all stock exit item

```sql 
CREATE TABLE stock_exit_item (
  uuid BINARY(16),
  stock_exit BINARY(16), -- A reference of the stock exit 
  lot_uuid BINARY(16), -- A reference of the concerned lot
  quantity INT,
  unit_price DECIMAL(19, 4)
)
```
1.4. stock_exit_patient : store all stock exit reference for patient 

```sql 
CREATE TABLE stock_exit_patient (
  uuid BINARY(16),
  stock_exit BINARY(16), -- A reference of the stock exit 
  sale_uuid BINARY(16), -- A reference of the sale 
  patient_uuid BINARY(16), -- A reference of the patient 
)
```

1.5. stock_exit_service : store all stock exit reference for service 

```sql 
CREATE TABLE stock_exit_service (
  uuid BINARY(16),
  stock_exit BINARY(16), -- A reference of the stock exit 
  service_id INT
)
```

1.6. stock_exit_loss : store all stock exit reference for loss 

```sql 
CREATE TABLE stock_exit_loss (
  uuid BINARY(16),
  stock_exit BINARY(16), -- A reference of the stock exit 
)
```

1.7. entry_source : store all kind of source of stock (purchase order, adjustement, ...)

```sql 
CREATE TABLE entry_source (
  id INT,
  label VARCHAR(25)
)
```

1.8. exit_destination : store all kind of destination of stock (patient, service, adjustement, ...)

```sql 
CREATE TABLE exit_destination (
  id INT,
  label VARCHAR(25)
)
```

NORE: `entry_source` and `exit_destination` are helpful for filtering stock entry and stock exit by their sources or destinations 

## 2. Queries 

Tables above must help to : 

- Record stocks
- Get the stock status of a specific depot
- Get The stock status for each inventory 
- Provide all information required in stock documents
- Get The stock distributed to patients, services, depots or stocks loss 
- Get The stock adjusted 
- Cancel a stock distribution
- and more

## 3. Stock basic document 

This section contains some information to consider about basic stock document. 

A. Stock entry : 

A.1. Bon de reception : 
- Provenance du stock 
- Numero de commande (purchase order number)
- Date effective de la reception 
- Designation precise des stocks
- Les resultats de controle (manquants, erreur, moindre qualité, marchandise refusé)

A.2. Journal des entrees en stock : qui resume les donnees du bon de reception

B. Stock exit : 

B.1. Bon de sortie : 
- Le nom du (service) demandeur,
- La designation precise des stocks sortants
- Le lieu de livraison 
- La date
- La signature du responsable demandeur 

B.2. Journal des sorties en stock : qui resume les donnees du bon de sortie

C. Documents relatifs aux mouvements des stocks : 
- La date 
- Le numéro des documents 
- Le libellé
- Les quantités entrées
- Les quantités sorties
- Les quantités en stock
- Les valeurs des entrées 
- Les valeurs des sorties 
- Les valeurs du stock

This issue contains informations to consider about stock database

**Comment by jniles** [comment]
@mbayopanda, thanks for the detailed issue!

I have a few questions:
 1. You list `stock_exit_item` twice ... is there supposed to be another table?
 2. Why use a separate table for `stock_exit_item` but not for `stock_entry` items?
 3. Instead of using two separate tables for `stock_entry` and `stock_exit`, what do you think about having a `movements` table that captures both sets of data?  What are the advantages/disadvantages?

It seems to me these are too many tables for a simple operation.  We could consider stock exits as something generic, and then add tags, like the way `transaction_type` labels a transaction.  That would reduce the number of tables, and allow use to write queries like:
```js
const SERVICE_DISTRIBUTION_TYPE = 8;
const PATIENT_DISTRIBUTION_TYPE = 3;
const sql = `
  SELECT * FROM stock_exit WHERE 
    type_id = ${ SERVICE_DISTRIBUTION_TYPE } OR 
    type_id = ${ PATIENT_DISTRIBUTION_TYPE };
`;
```
... instead of selecting from two tables with a UNION or a JOIN.


Some more queries to consider:
 1. Are there any lots in danger of expiring?
 2. Are there any inventory items with low stock?
 3. Where are all lots number XYZ located?  In what depots?

**Comment by mbayopanda** [comment]
@jniles thanks for your feedback, it's very helpful : 

For the question 1 and 2, the current state of stocks tables doesn't have a mean to store low stock or lots in danger, so we can add them in the inventory table or in the stock_entry table or equivalent.

For the question 3, in the table `stock_entry` there is a column named `lot_label`: 

```sql 
CREATE TABLE stock_entry (
  uuid BINARY(16),
  inventory_uuid BINARY(16),
  lot_uuid BINARY(16), -- unique identifier for the lot
  purchase_uuid BINARY(16),
  document_uuid BINARY(16),
  depot_uuid BINARY(16),
  date DATE,
  lot_label VARCHAR(11), -- the lot number 
  quantity INT,
  unit_price DECIMAL(19, 4),
  entry_source_id INT -- A reference for the source of entry (purchase_order, adjustement) in entry_source table 
)
```
You're right there are a lot of tables, we have to reduce seriously the number of tables and handle stock movement.

Thank you for your feedback, i'm waiting for your proposal.

**Comment by jniles** [comment]
@mbayopanda, I'll do a design based off your initial proposal and try and submit something tomorrow.  The first step is always the hardest, and your proposal is a good start!

**Comment by mbayopanda** [comment]
@jniles, @sfount, @dedrick,

En suivant les recommandations de Jon, voici le design de la base de donnees.

La table `stock_entry` et `stock_exit` ont été melangé en `stock_movement`

La table `entry_source` et `exit_destination` ont été melangé en `movement_flux` qui contiendra le type des sources et des destinations : 

Movement_flux : 
- from_purchase_order (IN)
- from_other_depot (IN)
- from_adjustment (IN)
- to_patient (OUT)
- to_service (OUT)
- to_loss (OUT)
- to_other_depot (OUT)

![stock](https://cloud.githubusercontent.com/assets/5445251/22099660/186c018c-dde1-11e6-8971-3f86fc0c57f5.png)

**Comment by mbayopanda** [comment]
En ce qui concerne la fiche de stock : 

![fiche stock](https://cloud.githubusercontent.com/assets/5445251/22100078/cf2a0b16-dde2-11e6-9ced-8d25d2fd3fc2.png)

La production de ce document dependra de la methode de gestion de stock FIFI (First In First Out) ou CUMP (Cout Unitaire Moyen Ponderee). La donnees d'entree en stock et de sortie en stock peuvent etre obtenu dans la table `stock_movement` parcontre la situation du stock peuvent etre calculé coté serveur ou client; si ces données sont stocké dans une table cette table risque de vite devenir gigantesque.

En bref le module stock doit : 
- 1) Etre en mesure de produire la fiche de stock pour chaque produit

- 2) Produire la liste des items en stock avec leur niveau d'alerte

Pour le point 2), nous devons avoir une table stock_inventory qui contiendra : 
- le delai de livraison d'un article en stock
- le stock minimum

Grace au `delai de livraison` et `stock minimum` nous pourrons calculer le stock de securite, prevoire la date d'epuisement de stock.

**Comment by mbayopanda** [comment]
After discussion with @sfount we have proposed the design below : 

![database stock](https://cloud.githubusercontent.com/assets/5445251/22329053/5171f0ca-e374-11e6-83c1-c2ccbeaa3ecf.png)

Here is the main table of stock : 
- Lot : store lots
- Stock_movement : store all movements of lots
- Movement_flux : store types of flux in the stock movement

**Comment by sfount** [comment]
With @mbayopanda's design, also discussed this morning: 

*Lots*
* Lots are registered with the system at the point of stock entry, usually this comes from a purchase order but this is not required. **For stock to be entered into the system it must be in a lot.**
* Stock movement describes lot movement between depots and other entities, the system should be designed to work with stock entering and exiting only one depot as the base case, movement between multiple depots is supported

*Movements*
* Movement types can be considered like 'Transaction Types' for accounting, they describe exactly what the movement is for. 
* A movement is very simple, it is either into or out of a depot. 
* A movement can be tagged with an `entity_uuid`, this will directly link the entity that stock is entering or exiting from; this is most useful when stock is leaving from a pharmacy to a patient/ service. Between the `entity_uuid` and the `movement_flux_id` you can know exactly what was involved in the movement. 
* Movement types will stored as system constant definitions on the server and the client. (For example the client could use `bhConstants.STOCK_MOVEMENT.IN.PURCHASE`
* Once stock has been distributed to a service it is no longer considered by the stock tracking process.

A quick example that was discussed this morning. 

*Lot* (**LT.HEV.20**)

| Key | Value | 
| --- | --- |
| inventory | 'Aspirin' |
| purchase_order | **(PO.HEV.5)** |
| initial_quantity | 100 |

Depot ('Storage')
Depot ('Pharmacy')

*Movement Table* 

| movement | lot | quantity | is_exit | depot | flux_id (reason) | entity_id
| --- | --- | --- | --- | --- | --- | --- |
| MO.HEV.1 | LT.HEV.20 | 100 | FALSE | 'Storage' | _from_purchase_order
| MO.HEV.2 | LT.HEV.20 | 50 | TRUE | 'Storage' | _to_other_depot
| MO.HEV.2 | LT.HEV.20 | 50 | FALSE | 'Pharmacy' | _from_other_depot
| MO.HEV.3 | LT.HEV.20 | 20 | TRUE | 'Pharmacy' | _to_patient | (**PA.HEV.1250**)

*Questions* 

How much stock is left in lot **LT.HEV.20**
* Filter on lot in `movement` + 100 - 50 + 50 - 20 = 80

How much 'Aspirin' is in the 'Pharmacy'
* Filter on all lots containing 'Aspirin' - **LT.HEV.20**
* Filter on lots and depot in `movement` + 50 - 30 = 20 

What medicines have been distributed to **PA.HEV.1250**
* Filter on entity_uuid in `movement` 
* Join to lot to get the inventory_uuid of what was consumed

**Comment by jniles** [comment]
This looks good to me, good analysis @mbayopanda and @sfount.  Sorry I never got around to giving a more solid proposal to @mbayopanda.

The `purchase_uuid` should definitely _not_ be required in the **lot** table, but will likely be the general case.

Can users modify and add to the `flux_id`s?

As far as I'm concerned, we should implement this and see what the next steps are as we run into problems or queries that we cannot answer.  This looks like an excellent first step :+1:

**Comment by jniles** [comment]
@mbayopanda, can we close this issue?

**Comment by mbayopanda** [comment]
@jniles yes, we can.
