### ISSUE TITLE
Display information in the General Ledger in the correct way

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1097]
The general ledger is a book which contains sold of each accounts. The current General Ledger in BHIMA display information such as another Journal, 

This issue is about to display in the General ledger information that the General Ledger must display.

Here is a proposition : 

The grid in the General ledger must display accounts and their sold : 

![only gl](https://cloud.githubusercontent.com/assets/5445251/21806770/23be169e-d6f0-11e6-9a56-49dd8b5760d6.png)

To get more information about the sold of an account, we have just to click on the account row 

![gl](https://cloud.githubusercontent.com/assets/5445251/21806973/3a5f1046-d6f1-11e6-91f9-28de0c9c06c8.png)

In this way the General Ledger is more useful for the user for getting the sold of an account in the enterprise in a given date.

**Comment by jniles** [comment]
Very nice issue :+1:

I agree that we need a view of the data like this.  I also think the current General Ledger is a useful tool for finding transactions.  Should we replace the current General Ledger, or make them two different modules/reports?

**Comment by mbayopanda** [comment]
Normally, the journal must always keep information of transactions but in the current state of BHIMA transactions are removed from the journal when they are posted in the General Ledger.

The Journal must keep all transactions made in the enterprise, and the General ledger must have all accounts used in the enterprise and their sold.

**Comment by jniles** [comment]
That sounds like a _lot_ of data to have to ship to the client on every request...  It seems to me, technically, like we should separate the posted and unposted transactions.

Vanga has made 1715 lines in the Posting Journal in one week of operation, without even installing expenses and stock!

**Comment by mbayopanda** [comment]
The Journal is a daily registry of transactions, so we can just display by default only transactions of the day in the Journal and load others with tools. 

The idea here is to have a Journal for an accountant not just a module because when a transaction is posted into the General ledger the accountant must have the possibility to see the proof in the Journal (also with real "Pieces justificatives")

**Comment by jniles** [comment]
Hmm...  In my view, mixing transactions that an accountant is allowed to edit (unposted transaction) and transactions that they cannot (posted transaction) would be confusing.  I think we should keep them separate as much as we can.

I think loading only the transactions of the day is a good idea :+1:

I like the account view shown in your balsamiq mockups.  If we went from the Trial Balance to a view like that, it would be very nice.

**Comment by jniles** [comment]
@mbayopanda, what is missing from this issue?

**Comment by jniles** [comment]
Closing this as completed in #1212.
