### ISSUE TITLE
Unify posting journal interface

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#11]
The [current journal code](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/controllers/finance/journal.js#L70) uses string matching and a function that takes in six parameters - some of them objects, numbers, or functions.  We should re-write this interface to provide direct posting without the need for anything but a UUID.  For example:

``` js
// inside controllers/finance/sales.js
// create a sale with some uuid
journal.postPatientInvoice(uuid);

// inside controllers/finance/cash.js
// create a cash payment with some uuid
journal.postCashPayment(uuid);
```

All information needed to post any record should already exist in the database.

**Comment by DedrickEnc** [comment]
As we just finished to discuss about posting journal, I close it!
