### ISSUE TITLE
(bug) Users page dropdown falls off page

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1124]
The `ui-grid`'s dropdown in the `users` configuration page pushes the entire grid up as you get to the bottom of the page.  It also does not appear below the link in the page.  I have a feeling that it is not appended to the body, but someone should investigate.

![weirddropdownbehavior](https://cloud.githubusercontent.com/assets/896472/22649921/5cacc34a-ec7d-11e6-9f91-59cc2342535e.png)
_Fig 1: Users Dropdown Behavior_

**Comment by lomamech** [comment]
The same problem is also found in the list of registered patients and others
