### ISSUE TITLE
Transfer module

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#114]
During our daily meeting we decided to add a new module in finance to let the cashier veer money between the cash and the transfer account, so that the primary cash responsibility and auxiliary cash responsibility will be clearly separated.

Since the auxiliary cash is formatted for income only, the transfer module will write directly in the posting_journal table.

What do you think?
@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
I do not think this needs to be a separate module.  I imagine a button on the Cash Payments interface that is "Export Cash to Account" or something similar.  It will bring up a modal with the total amount in your current cash box and ask how much you'd like to transfer.

Ideally, it should also keep track of the currencies in the cash box as well.  That way it could recommend X numbers of USD and Y numbers of FC.

The problem with writing directly to the `posting_journal` is that it is editable ... but I do not have a better proposal at this time.

**Comment by sfount** [comment]
Is there a problem with recording all transfers between accounts that do not fit the categories `sale`, `cash`, `purchase_order` etc. under journal vouchers? Doing this gives us a paper trail (receipt) for almost ever transaction in BHIMA.

Given that the journal voucher interface is too complicated for standard use (debits + credits and multiple transaction lines) has building a module to do generic FROM ENTITY -> TO ENTITY transfers been discussed? If this tool was able to use the same components built for journal vouchers to allow easy selection of entities (like cash boxes) it might support what this module needs to do.
