### ISSUE TITLE
(refactor) Cashflow report logic

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1145]
Our current cashflow report was the first report that was created in 2.x. There are number of standards that have been developed since then that should be applied to the cashflow report. 

The current cashflow report is calculated using Javascript for totalling and grouping. All of this logic should be converted to MySQL to bring it in line with the other reports as well as to leverage the strong Maths library in MySQL. 
An example of logic being transferred to MySQL can be found in https://github.com/IMA-WorldHealth/bhima-2.X/pull/651

This report logic should be carefully tested with the latest installation dataset before closing this issue.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2578
