### ISSUE TITLE
(bug) Cannot switch projects

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1148]
**Steps to reproduce**
 1. Create two projects - XXX and YYY
 2. Log in to XXX - it will print XXX on the `project` panel.
 3. Log in to YYY - it will print XXX on the `project` panel.
 4. Create a patient - the identifier will be XXX even if you are in YYY.

I'm not entirely sure what the cause it yet, but it's somewhat annoying.

**Comment by DedrickEnc** [comment]
will investigate

**Comment by DedrickEnc** [comment]
@jniles
