### ISSUE TITLE
How to calculate the stock parameters for multiple depots ?

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1162]
There are a set of parameters which are important in stock management, we have : 
- Stock de securité (SS)
- Stock minimum (MIN)
- Stock maximum (MAX)
- Nombre des mois de stock (N) 
- Quantité à commander (Q)

These parameters are based on three important variables : 
- Consommation mensuelle (Moyenne) (CM)
- Intervalle de commande (IC)
- Delai de livraison (DL)

For each inventory in a stock we have to know these three variable CM, IC and DL. 

`CM = Quantité totale distribuée pandant les 6 derniers mois / 6`

`Stock de Securité (SS)= CM * DL`

`Stock Minimum (MIN)= SS * 2`

`Stock Maximum (MAX)= CM * IC + MIN`

`Mois de Stock = Quantité en stock / CM`

`Commande d'approvisionnement (Q) = MAX - Quantité en stock`

We are in a context of more than one depot, so we have to know these variables for each inventory in each depot.

![stock](https://cloud.githubusercontent.com/assets/5445251/22823690/8ca3af1e-ef39-11e6-884f-ca61dab79f7e.png)

We have : 
- Main Depot
- Pharmacy A
- Pharmacy B

All these depots contains inventories, the main questions are : 

1) How to calculates CM, IC and DL for each inventory in each depot ? 

2) How to store CM, IC and DL for each inventory in each depot ? or do we need just to calculate not to store

**Comment by mbayopanda** [comment]
I suggest to have `CM, IC and DL` in each inventory as field and set them manually or automatically by the system when requesting the report;

But the inconvenient is we have 3 depots and for each inventory in each depot `CM, IC and DL` are differents, so `CM, IC and DL` in inventory is useless in the case of more than one depot.

**Comment by jniles** [comment]
It seems to me `DL` doesn't make sense on a depot by depot basis, unless your purchase order specifies a particular depot.  Do our purchase orders specify a particular depot?

Either way, we can just calculate DL at stock_entry time, right?

_Edits for clarity_

**Comment by mbayopanda** [comment]
We must be able to answer to the question below for each depot : 
- What is SS, MIN, MAX, Q ?

For answering to the question above, we must have `DL, IC and CM`

Another temporary solution can be to consider DL = 1 (the minimum possible) for Pharmacies because their take inventory from the main depot (instantaneously)

**Comment by jniles** [comment]
I understand.

At stock entry, can we not just calculate:
```js
// this would be done for each inventory item and factored into the average
const DL = new Date() -  purchase.date;
```
and store that somewhere?  Instead of recalculating it whenever we request a report?

**Comment by jniles** [comment]
@mbayopanda does this issue still apply anymore, or have we come up with a solution for it?

**Comment by mbayopanda** [comment]
@jniles we have already implemented a solution for this issue. We just consider all depots as one depot

**Comment by jniles** [comment]
Great!
