### ISSUE TITLE
(feature request) Account Report Suggestions

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1170]
The Account Report presents a decent overview of the transactions involving a particular account.  Here are some improvements based on feedback from @imawh and personal observations.

- [ ] Move the date column to the far left
- [ ] Keep a running balance on the far right side.
- [ ] All currency amount should be right aligned (`text-right`).
- [ ] Include some indication of the date range spanned and number of transactions in the dataset.
- [ ] The account number and account label can be on the same line to save space.

For reference, see below the current rendering:

![2017-02-1111 33 09](https://cloud.githubusercontent.com/assets/896472/22853165/348dc1b8-f04f-11e6-87ae-5144be86b6f2.png)
_Report of Accounts_

**Comment by sfount** [comment]
There was also an issue with this report always showing the date of the report itself in each of the date columns. This should be addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1203/files

**Comment by sfount** [comment]
To add to this: Patrick has been reviewing a number of the reporting features in 2.x and has noted that a date range would be useful in this report. To be able to select only the month of January or only the previous year for example. 

This feedback should be formally compiled however this is relevant to this issue. 

- [ ] Date range added to report generation allowing the selection of a start date and an end date. 
- [ ] ~~Running balance should show previous balance of account before the date from begins for context~~
- [ ] Running balance should show the balance ONLY for the period selected for the report (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1170#issuecomment-280620654)

**Comment by patsonjunior** [comment]
In the context of a specific date or period, the current balance (running balance) should only present the amount in relation to the date or period considered for drawing the report.

**Comment by lomamech** [comment]
#1211
