### ISSUE TITLE
(bug) Cashflow Report always renders USD

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1180]
The Cashflow report does not respect the enterprise currency and always renders USD.  See below:

![cashflowusd](https://cloud.githubusercontent.com/assets/896472/22975379/d6c1f438-f386-11e6-844e-9e3a0292384d.png)
_Fig 1: Cashflow in USD despite enterprise currency in FC_

**Comment by mbayopanda** [comment]
Jon,

I sent a pull request in the vanga repository, so i don't know if i have to
send another to ima repository.

2017-02-15 4:58 GMT-08:00 Jonathan Niles <notifications@github.com>:

**Comment by jniles** [comment]
The Vanga repository is abandoned.  The IMA repository is the only one that code should be developed on.  We haven't removed the Vanga repository because it has lots of valuable issues to work on.

**Comment by mbayopanda** [comment]
I send another into IMA repository. Thanks

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1181.
