### ISSUE TITLE
(bug) Credit Note submission refreshes registry without taking into account filters.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1192]
After successfully making a credit for a credit note for an invoice, the modal disappears and the registry is refreshed without taking into account the filters.  This leaves a dangling filter label at the top of the grid.  Ideally, this should either:
 1. Remove all filters and labels OR
 2. Leave the filters applied.

![precreditnotefilters](https://cloud.githubusercontent.com/assets/896472/23010114/07ee45e6-f41a-11e6-8250-4399f8ac1353.png)
_Fig 1: Before Credit Note - one filter applied that limits grid to a single item_.

![postcreditnotefilters](https://cloud.githubusercontent.com/assets/896472/23010113/077bc3cc-f41a-11e6-8ecc-68c8d6fdbb08.png)
_Fig 2: After Credit Note - Registry refreshes without respecting filters_.

**Comment by sfount** [comment]
Note - this also happens when reversing cash payments. This should also be addressed.
