### ISSUE TITLE
(feature request) Print Barcodes on A4 Receipts

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1193]
Just because a barcode is ideal for a thermal receipt doesn't mean we should restrict it to only thermal receipts.  Putting them on the larger A4 receipts gives us the possibility to use barcode scanners to look up any receipt at any time.  It also means that users without a thermal printer will be able to benefit from a barcode scanner immediately, without accepting the limited durability of the thermal receipt.

**Comment by lomamech** [comment]
#1201
