### ISSUE TITLE
(refactor) Make report date ranges more prominent

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1199]
As described in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1169 it can be difficult to see the light grey date stamp underneath the report title on reports. We should have a standard method to display what time period a report reflects.

**Comment by jniles** [comment]
One issue is that many of the reports either accept a range or a date.  If we design a component that only allows limited selection (this month, this fiscal year, last three periods, etc), we would have a much easier time standardizing, I think.

**Comment by jniles** [comment]
Closed via the commits in #1296, #1295, and #1294.
