### ISSUE TITLE
(features request) Harmonize ui for creditor group module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1210]
This issue is about : 
- harmonization of ui of creditor group module for to be like the debtor group module 
- fix blanc area which is when there is not any creditor group

**Comment by jniles** [comment]
See also https://github.com/IMA-WorldHealth/bhima-2.X/issues/966.

**Comment by jniles** [comment]
Interestingly, if you double click "creditor groups management" in the tree, you get a blank view...
