### ISSUE TITLE
(proposal) Do not navigate to GL after posting

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1222]
Traditionally, we have navigated the user to the GL after completing the posting process.  The original design for the Trial Balance (https://github.com/IMA-WorldHealth/bhima-2.X/issues/585) called for the option to link to the GL, but not an immediate transition.

I propose we eliminate the transition altogether, instead offering the user the possibility to close the Trial Balance modal once the transactions are posted.  This will encourage our users to look at small groups of transactions at a time, posting in smaller number and verifying each one.

**Comment by patsonjunior** [comment]
After analysis of the General Ledger, we suggest that we add a filter option that allows to filter either by account or by transaction and another to allow to export in excel.

**Comment by jniles** [comment]
The accountant in vanga also asked for an option to download the GL as Excel.

**Comment by jniles** [comment]
Note that the GL has been available as Excel in `master` for quite some time.

This issue can be closed when the trial balance no longer navigates to the Posted Journal.
