### ISSUE TITLE
(bug) Location Management buttons broken with Angular 1.6.x

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1223]
The location management buttons are now broken to navigate to villages, sectors, provinces, and countries.  This is likely due to a hardcoded `#/url` and the routing changes with Angular 1.6.x.  I recommend someone fix this with `ui-sref` state routing instead of using hrefs or other routes.

**Comment by sfount** [comment]
I believe this should be resolved in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1279
