### ISSUE TITLE
(refactor) Standardise headercrumb module title links

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1224]
Currently different modules have different ways of displaying the module title in the headercrumb bar. This should be standardised across modules so that users can learn just one method for manipulating the system. 

For example: 

**Edit a fiscal year** 
**Headercrumb - Finance / Fiscal Year (EDIT)**
![screenshot 2017-02-20 at 14 11 22](https://cloud.githubusercontent.com/assets/2844572/23126355/8d1bf0e2-f776-11e6-838f-44e867349d4b.png)

**Edit Creditor Group**
**Headercrumb - Finance / Creditor Group Management (EDIT)**
![screenshot 2017-02-20 at 14 12 17](https://cloud.githubusercontent.com/assets/2844572/23126382/a9c8d0c0-f776-11e6-8636-c1280e7db7c4.png)

**Edit Debtor Group**
**Headercrumb - Finance/ Debtor Group Managment / Entity Name**
![screenshot 2017-02-20 at 14 13 07](https://cloud.githubusercontent.com/assets/2844572/23126405/c5f14124-f776-11e6-88ef-1bede18a3252.png)

I suggest we adopt a system like debtor groups allowing easy navigation up and down this structure 
1. View available data (Click to return to 1.)
2. Configure individual item

**Comment by jniles** [comment]
In my opinion, I personally like the title of the entity in the header... especially for editing. It give you are reference to know what the name used to be if you changed it.

In my mind, the syntax should be:
 1. Unit Group (Hospital, Finances, etc)
 2. Module title (Annee Fiscale)
 3.  [In Create Mode] Create Label (`label-success`)
 4.  [In Update Mode] The name of the entity (using `angular.copy()` to make sure it doesn't update.
 5. [In Update Mode] Update Label (`label-info`).

In all cases, the module title should link back to the list of the items

**Comment by jniles** [comment]
@sfount, what do you think of the status of this issue; can we either make it actionable or close it?

**Comment by jniles** [comment]
I believe this was closed in #1652.
