### ISSUE TITLE
(refactor) Improve patient registry links/ shortcuts 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1226]
Currently in the patient registry we allow the user to double click anywhere in a row and this will open up the receipt modal for that patient card. 

However this has proved confusing to users who are not proficient with a mouse and end up with the modal displaying sporadically. 

I suggest that we remove this and instead as it as a link on the `reference` column. This column represents the actual document so it makes sense that you would be clicking on that to bring up the modal. 

Example: 
![screenshot 2017-02-20 at 14 19 20](https://cloud.githubusercontent.com/assets/2844572/23126622/ef86f582-f777-11e6-984d-3cb68e5046bb.png)

Proposed changes: 
* `reference` column links to receipt (modal above page) 
* `name` column links to viewing that patients record page
* double clicking the row has no action

All actions would still be available through the actions dropdown on the right. 

@jniles As you are currently working at the primary installation site, do you think the users would understand this change?

**Comment by jniles** [comment]
@sfount, yes this is a great idea.

I would also have the option available in the dropdown menu if possible... some people struggle to keep multiple patterns in mind.
