### ISSUE TITLE
(bug) 'Back to Debtor Groups' link directs to 404

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1228]
The link 'Back to Debtor Groups' is no longer valid and results in a 404. This makes navigation very difficult. 

Link : 
![screenshot 2017-02-20 at 14 28 57](https://cloud.githubusercontent.com/assets/2844572/23126859/f9da6f04-f778-11e6-9d41-31260c8a955a.png)

Expected behaviour: 
Debtor groups list state is navigated to on clicking the 'Back to Debtor Groups' link.

**Comment by jniles** [comment]
Doesn't this use the History API?   If so, that is very weird.
