### ISSUE TITLE
Using page object design to organise our e2e test

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#123]
The page object design is very recommended when reading the protractor documentation.
It let you write clear test and very maintainable, it also let you reuse a page object some where else when necessary.

I applied this design to the project test and it was a success, I will walk through other test file to apply this design, see [here](https://angular.github.io/protractor/#/page-objects) for more information.
 What do you think?
@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
We are already doing something similar.  See [FormUtils](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/test/e2e/shared/FormUtils.js).

@lomamech has been using this quite successfully.

**Comment by jniles** [comment]
Oh!  That is also what the "test wrappers" for our components are supposed to do.  That is why we cannot accept components without a tests written for them.

**Comment by jniles** [comment]
Closing this as implemented in #189 and #143.
