### ISSUE TITLE
(Bug) Location management links lead to 404

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1230]
The links for all individual location management links are currently broken on master. 

Relevant links: 
![screenshot 2017-02-20 at 14 45 36](https://cloud.githubusercontent.com/assets/2844572/23127442/570958dc-f77b-11e6-9a85-57dbcd3121f8.png)

**Comment by jniles** [comment]
Adding to this: in each of the submodules, the links are broken as well.

**Comment by jniles** [comment]
Dup #1223

**Comment by sfount** [comment]
woops 😨. Didn't see that! This issue is recorded at https://github.com/IMA-WorldHealth/bhima-2.X/issues/1223
