### ISSUE TITLE
(bug) 'Download as PDF' downloads as a CSV file on all registries

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1239]
![screenshot 2017-02-21 at 15 27 06](https://cloud.githubusercontent.com/assets/2844572/23168941/3aa562e2-f84a-11e6-81f6-5b58dc0dfbf8.png)

Expected behaviour: 
- Browser downloads a PDF file 

Actual behaviour: 
- Browser downloads a CSV file 
![screenshot 2017-02-21 at 15 28 07](https://cloud.githubusercontent.com/assets/2844572/23168984/62144b2c-f84a-11e6-94a4-fa82bca6425e.png)

**Comment by sfount** [comment]
As an update it looks like whichever option is selected when the modules load is always chosen. Potentially this is a cache issue.

**Comment by jniles** [comment]
Hmm...  I'll take a look.  The download as CSV takes a terribly long time as well...
