### ISSUE TITLE
(proposal) Combine 'Posted Journal' and 'Posting Journal' 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1241]
A pull request https://github.com/IMA-WorldHealth/bhima-2.X/pull/1212 recently introduced the concept of a seperate 'Posted Journal' and 'Posting Journal' to allow the General Ledger to be an Account focussed report for the accountant. 

I propose that we combine the two journals into a 'Journal' module. This will by default just show transactions that have not yet been posted. 

From the 'Journal' you will be able to: 
* Edit transactions that have not yet been posted into the general ledger 
* Run a trial balance on transactions that have not yet been posted into the general ledger 
* View/ Search/ Filter all transactions that have ever been made in the system 

The problem right now is that maintaining all of these modules will be costly. As an example right now the configuration button on the posted journal throws an error but it works on the posting journal. The filters and searches have been improved in one for a recent pull request but not in the other.

**Comment by jniles** [comment]
We've received the following feedback from @WayneNiles:

> Journal Poste doit etre renome Releve du Compte (account statement)
Son but doit etre l'eximain des ecritures dans le GL dans UN compte.Il doit presenter maximum 200 ligne par defaut des derniers ecritures tout comptes confondus
Il doit se limiter a l'an fiscal par defaut (avec possibility de selectionner d'autres annees)
Il doit avoir une selection pour un compte et gamme de periods (mois)  ou meme dates
Il doit aussi faire des recherches sur presque tous ces colonnes avec input de text, chiffres, dates souhaites
Il doit exporter a Excel
En plus des totaux DR,CR il doit presenter les soldes avant, apres pour le filtre en cours (un seul compte) de preference avant au dessus, apres au fond dans le colonne approprie.

It seems that this view is useful - but needs a lot more research functionality.

**Comment by sfount** [comment]
This proposal has been superseded by the concept of an Account Statement module as described https://github.com/IMA-WorldHealth/bhima-2.X/issues/1638
