### ISSUE TITLE
Filtering invoice registry by service does not work when combined with other filter

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1245]
Action to perform : 
1. Go to invoice registry
2. Click to Rechercher
3. Choose a service (consultation for example)
4. Set an interval of date for example
5. Submit

Actual behaviour : even invoice made for other service than consultation are filtered

Expected behaviour : only invoices made for consultation should be filtered.

**Comment by jniles** [comment]
This is fixed on the latest master, I believe.

**Comment by sfount** [comment]
I cannot reproduce this on master.

**Comment by jniles** [comment]
@dedrickenc, can you reproduce this on master?

**Comment by jniles** [comment]
Closing this as cannot reproduce.
