### ISSUE TITLE
(refactor) Improvements to Subsidy Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1270]
The subsidy management page could use some improvements.  The page currently looks like this:

![refactorsubsidymanagement](https://cloud.githubusercontent.com/assets/896472/23358255/88951e66-fce1-11e6-9c24-b5226994bbc3.png)
_Fig 1: Subsidy management page_

As pointed out by @patsonjunior, there are several improvements that can be made to this page:
 1. The "value" input should indicate that it is a percentage (similar to Billing Services)
 2. Use `bh-loading-button` for the form.
 3. Render the value in the grid as a percentage.
 4. Use the `title` class on the headercrumb.
 5. Use `font-awesome` instead of `glyphicon`s.

**Comment by patsonjunior** [comment]
Good, problème bien rendu.
