### ISSUE TITLE
(bug) Very long request times for dashboard request

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1272]
Our dashboard is visited by every single person at least once a day.  The `invoices/stats` request takes _seven seconds_ to load on a local machine (i7 intel processor).  This is no network request made.  See below:

![invoicesperformanceissues](https://cloud.githubusercontent.com/assets/896472/23358886/fead3bd6-fce3-11e6-9446-1f5cf5743862.png)
_Fig 1: Tragic Invoice Performance Issues_

This is likely due to an unoptimal MySQL query.  I believe this query is the culprit:
```sql
 SELECT (debit - credit) as balance, project_id, cost
     FROM (
      SELECT SUM(debit_equiv) as debit, SUM(credit_equiv) as credit, invoice.project_id, invoice.cost
      FROM combined_ledger
      JOIN invoice ON combined_ledger.record_uuid = invoice.uuid OR combined_ledger.reference_uuid = invoice.uuid
      WHERE invoice.uuid NOT IN (SELECT voucher.reference_uuid FROM voucher WHERE voucher.type_id = 10)
        AND (MONTH(invoice.date) = MONTH('2017-02-27') AND YEAR(invoice.date) = YEAR('2017-02-27')) AND entity_uuid IS NOT NULL
      GROUP BY uuid
     ) AS i
     JOIN project ON i.project_id = project.id
```

Someone should take a look at what it will take to optimize this query better.

**Comment by jniles** [comment]
I'll tackle this one.

**Comment by jniles** [comment]
I've discovered a number of issues with this routes.
 1. No date parameters are ever sent.  The server sets the date.
 2. There are 31 overpaid invoices in the vanga dataset.  We should include a separate alert for these - it might be useful for a user to see and make corrections.
 3. The sums and paid calculations are performed in JS.

I'll work to correct or make issues about these while refactoring these routes.

**Comment by jniles** [comment]
This dashboard is confusing - what do we mean by "51 invoices paid" in March?  It could mean either:
 1. 51 of the invoices made in March have been paid OR
 2. 51 invoices (made whenever) have been paid in March

Which should we pick?

**Comment by sfount** [comment]
In my opinion either this should show all remaining invoices that have to be paid **(for all time)** 
OR 
Only the invoices that have been made in March that have been paid in March - this shows the average payment ratio for this month, which can be compared to the last month etc. I don't think just showing all of the payments that have been made in March has much meaning

**Comment by jniles** [comment]
I believe this has been addressed through the combination of https://github.com/IMA-WorldHealth/bhima-2.X/pull/1653 and https://github.com/IMA-WorldHealth/bhima-2.X/pull/1384
