### ISSUE TITLE
(proposal) Refactored standard report creation interface

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1275]
Users have reported issues with not being to effectively use our reports because it takes a long time to configure and then view a report, it also saves a report every time you click generate which leads to cluttering of the report module - ref #1260. 

I propose the following changes to the default report creation page: 
* Description of the current report and it's configuration options presented at top (one or two liner)
* The default page for viewing a report should show the configuration options (moved from modal into a module) 
* Cache configuration options allowing the user to set their standard defaults and generate that 
* Compile report on clicking generate - once the report has been compiled it can optionally be saved if everything is correct 
* Follow link to see grid of all reports that have been saved for
* ? 'Preview' first page of report inline with configuration to allow quicker feedback

**Comment by sfount** [comment]
To add to this: when a report is 'compiled' or 'generated' it could request an `HTML` document. This could then be displayed inline instead of always generating a PDF document. 

Pros: 
* Smaller machines with less processing power use a lot of resources to compile PDF documents with `wkhtmltopdf`; this would only be required if saving the report 
* A faster response on any machine as only a string (`HTML`) document will be returned

**Comment by jniles** [comment]
I believe this has been implemented.  If @sfount is still online, can you confirm what the status of this is?  Otherwise I will close it in a week.
