### ISSUE TITLE
(proposal) Updated period selection components/ modal 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1276]
Currently our 'period' selection component allows you to select from the following options : 'today' 'this week', 'this month', 'this year'. These options simply pre-populate two date inputs that can be changed at any time. 

I propose we create a component that provides discrete options and shows the selection as non-editable strings. If the user cannot select an input the last resort is selecting a specific period. 
The component could be placed inline or in a modal above configuration pages. 

* This
  * Day (today) 
  * Week 
  * Month
  * Year 
  * Period 
* Last 
  * Day (yesterday) 
  * Week 
  * Month 
  * Year
  * Period 

* Period selections shown from this fiscal year

* All time

Each configuration option could have the following information:
```js
{ 
  key : 'Yesterday', //human readable key to be shown in a label or title,
  startDateCalculation : function() {}, 
  endDateCalculation : function() {}, 
  numberOfDays : 0 // ?
}
```

* Unit test the selection options to test periods are always selected as expected (strange input days -> expected date period outputs) 

This issue may also be a good time to tackle https://github.com/IMA-WorldHealth/bhima-2.X/issues/1014 which should greatly improve the user experience.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1566
