### ISSUE TITLE
Inconsistency between Cash Flow Report and account Balance 

### ISSUE THREAD

**Issue by patsonjunior** [third-culture-software/bhima#1302]
Nous constatons qu'il ya incohérence de solde à la même date (du 01 Janvier au 02 mars 2017)  entre la Balance  et le Rapport Cash Flow pour le compte 570000 "Caisse FC". Ce qui dénote un problème lié plus au Rapport
![cash flow](https://cloud.githubusercontent.com/assets/25841277/23508861/d87cddaa-ff53-11e6-8909-4709c5b38675.png)
![balance](https://cloud.githubusercontent.com/assets/25841277/23508879/e68b62c2-ff53-11e6-833d-8575b4b0ff21.png)

 Cash Flow.

**Comment by jniles** [comment]
This is probably caused by the same bug as #1320.

**Comment by mbayopanda** [comment]
Error due to bad data set.
