### ISSUE TITLE
(bug) Journal vouchers - selecting a transaction type does not update validation

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1312]
The journal voucher module provides a warning for users stating that a transaction referencing cashboxes must have a transaction type. 

> Transactions involving cash accounts (banks or cashboxes) must have a transaction type specified to differentiate them in the cashflow report. Please select a transaction type.

However when a transaction type is selected the validation is not checked and the message remains. Altering a value like debits or credits forces the validation to be re-run and this clears the message. 

This can be resolved by running validation on the selection of a new transaction type.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1318
