### ISSUE TITLE
(refactor) Only display 'Scan another barcode on payment' if the scan tool has been used

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1335]
Currently on the cash window the option for 'Scan another barcode on successful payment' is activated and checked by default. 

I suggest that we hide this option unless the user has successfully used the scan barcode tool - in this case I think this option should be available and activated by default. 

As it is currently even if the user has no idea what the barcode tool is or what a barcode scanner is this option will be presented to them.

**Comment by sfount** [comment]
To add to this it doesn't look like the value for this input is cached - it would also help to remember the users decision.

**Comment by jniles** [comment]
This seems pretty easy to implement.  Maybe put a flag in the service for the input form?  Or in the controller itself?
