### ISSUE TITLE
(bug) User Management "deactivate a user" doesn't send the "locked" key to the server

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1346]
The "deactivate a user" feature doesn't change any information on the server.  The form doesn't send back the `deactivated` key.  See the image below:

![userdatasenttoserver](https://cloud.githubusercontent.com/assets/896472/23845392/11ab3ea6-07c8-11e7-8469-c0a09ed74c6d.png)
_Fig 1: The form data returned to the server when "deactivated" flag is toggled.  Not the "deactivated" key is missing._

**Expected Result**
The `locked` checkbox should deactivate a user.

**Actual Result**
Nothing about the user changes.

**Steps to Reproduce**
 1. Navigate to the User Management interface (`/users`)
 2. Select any user and click "Edit"
 3. Toggle the `locked` form field to `true`.
 4. Submit the user and observe the green success message
 5. Edit the same user
 6. Note that the `locked` form field is still `false`.

**Comment by DedrickEnc** [comment]
I will investigate

**Comment by DedrickEnc** [comment]
It is a problem in our user controller, the select request
