### ISSUE TITLE
(feature) Client side service for registry filters - FilterService

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1347]
Currently all of our registries implement custom search modals and controller logic. The leads to each registry being very difficult to maintain or fix. 

On the server we have a library called `FilterParser` that receives filters from the client and translates them into valid SQL. 

I propose that we add a client side service for interfacing with the library - a service that is used anywhere that filters are used and interfaces with the `bhFiltersApplied` component and the server `FilterParser`. 

It would be responsible for: 
* Defining a standard filter object that contains the information required by everything interfaced with (key, label, isDefault, timestamp, value, viewValue ngFilter)
* Formatting key/ value pair requests to be send to the server 
* Formatting viewValue's into a labels object (Array) to send to the server 
* Uniformly caching filters for each individual page
* Exposing the state of filters, number of filters, clear functionality, etc.

The `Filter` entity itself could be created with a constructor like:
```js
class Filter() { 

constructor (key, value, label=value, isDefault=false) { //... }
}
```

**Comment by jniles** [comment]
@sfount, can this be closed as implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1566?

**Comment by sfount** [comment]
@jniles good catch!

Proposal closed with https://github.com/IMA-WorldHealth/bhima-2.X/pull/1566
