### ISSUE TITLE
(feature request) Download Journals as Excel 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1348]
As pointed out by @patsonjunior, we cannot download the Posting (or Posted) Journal as Excel.  This would be helpful in finding transactions that have gone astray.  We should support downloading as Excel from those modules like we do the General Ledger.

**Comment by sfount** [comment]
This seems like the most supported library for these requirements https://github.com/SheetJS/js-xlsx. There are others with simpler interfaces however they generally have very little activity.

**Comment by jniles** [comment]
That's a really good find!

I think we can do an initial version with the CSV module that we already have, then swap out for `js-xlsx`.  It looks like a really robust implementation.
