### ISSUE TITLE
(feature request) Flexible parameters in FilterParser.custom() 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1359]
The `FilterParser` library allows a user to define a custom filter via the `custom()` method.  It would be ideal if this method could correctly handle a single or or multiple parameters without having to resort to extending `FilterParser`.

~~I propose the API signature be the following:~~
```js
filter.custom(preparedStatement, parameters, type);
```
... with a proposed call such as this ...
```js
filter.custom('(table.dateFrom <= ? AND table.dateTo > ?', [opts.date, opts.date], 'multi');
```

~~The following types should be supported:~~
 1. ~~'none'~~
 2. ~~'single' (default)~~
 3. ~~'multi'~~

A better proposal has been made that retains `db.exec()`'s API.  See https://github.com/IMA-WorldHealth/bhima-2.X/issues/1359#issuecomment-287002426 for the updated proposal.

A feature such as this would make `FilterParser` extremely flexible.

**Comment by sfount** [comment]
This is a great proposal; it would be much easier to add custom logic to FilterParser if it accepted something like this. 

Do you think it would be possible to derive the type from the number of parameters passed in? If an array is passed in the length could be used and if anything else is passed in it could be wrapped in an array and treated exactly the same. (`[param]`). 

Potentially we could check for the number or parameters in the SQL query and verify that this is the same number that is passed in from the array. Something like 
```js
preparedStatement.split('?').length === params.length
```
(I'm sure there may be a more optimal way to do this!). 

This could then throw a BadRequest error or something. This should only ever be introduced with programmer error so it would mostly be a convenience. 

@jniles what do you think?

**Comment by jniles** [comment]
I don't think it is possibly to derive the type from the parameters passed in.  That would eliminate custom `IN (?)` queries.

You might be able to do it from the prepared statement, but that code would likely be a nightmare to maintain and may bite a developer one day.

**Comment by sfount** [comment]
I'm not 100% on this but I think `IN (?)` have to be passed to the database library as an array anyway? 

For example: 
```js
// outputs SELECT * FROM entity WHERE id IN (1)
db.exec('SELECT * FROM entity WHERE id IN (?)', [1, 2, 3, 4, 5])
```

In order for a developer to use an `IN` like this they have to pass the values as an array: 
```js
// outputs SELECT * FROM entity WHERE id IN (1, 2, 3, 4, 5)
db.exec('SELECT * FROM entity WHERE id in (?)', [ [1, 2, 3, 4, 5] ])
```

I think that one item in the array will always map directly to one `?` in the statement.

**Comment by jniles** [comment]
Yeah, I guess I considered that a design weakness of `db.exec()` that makes it hard to work with.  At least, in the past, this has presented trouble in the past for developers.  Should we build the same functionality into `FilterParser`?

**Comment by sfount** [comment]
`db.exec` just wraps the mysql libraries [format](https://github.com/mysqljs/mysql#preparing-queries) method.

I don't have a proposal for what would be simpler given that in can accept Objects, Arrays and values (Strings/ Numbers etc.) and can't make guarantees about this. The logic therefore is that you're passing your parameters as an array - if the parameter you're passing in is a list it should be an array in the array of parameters you're passing in. 

As `FilterParser` is just combining small sections of a larger statement with params that will be passed to exec there are pros and cons. 

Designing a new interface would require developers to know both how `exec` accepts multiple parameters AND how `FilterParser` accepts multiple parameters. However the updated interface may be simpler and easier to understand.

**Comment by jniles** [comment]
Okay, sounds good.
