### ISSUE TITLE
(refactor) Patient Invoice Form needs loading button 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1366]
The Patient Invoice Form does not have a `bhLoadingButton`.  This causes users to click the button multiple times and query the database several times for the same invoice payment.  Most other forms use a loading button to both provide feedback to the user and to provide security by disabling submission.  A `bhLoadingButton` should be placed on the Patient Invoice module as soon as possible.

**Comment by sfount** [comment]
To add to this I don't think it should be possible to clear the form whilst the form is trying to submit to the server. The loading process here should also block the cancel button from being pressed.

**Comment by jniles** [comment]
I agree.  A fieldset can be used to disable the whole thing.

Is someone working on this?  I've already written a patch for Vanga that needs to be updated to latest standards, but if no one else is working on it, I'll take it.

**Comment by sfount** [comment]
No one else has taken this yet - @jniles if you've already done a patch it would probably be fastest for you to take it. Even if you just want to submit your patch branch and we can improve it through code review.
