### ISSUE TITLE
Service Management Refactoring

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1369]
Since now, our service module is very simple in terms of structure and very old. It has no link to a fee center and does not follow our standard in coding (no ui-grid to list records, no ui-router to handle user interface state).

This module should be refactored so that it can follow our current standard and will be simple to maintain.
Here are some components to include in the service module

1. ui-grid to list registered services
2. ui-router to handle user interface state

A piece of work has been done in terms of service structure (adding a link to the fee center), in a feature branch called ```feature-fee-center``` so the pull request for this issue should be addressed to the ```feature-fee-center``` branch not to master branch.

**Comment by jniles** [comment]
This has been completed in master.
