### ISSUE TITLE
Cash Flow Report

### ISSUE THREAD

**Issue by patsonjunior** [third-culture-software/bhima#1370]
Le cash Flow présente parmi ses rubriques du côté des dépenses, les rubriques: "Note de Crédit" pour la petite caisse et "Transfert d'argent" pour la grande. Ce qui n'est pas logique.

![cash flow 3](https://cloud.githubusercontent.com/assets/25841277/24093494/62395cea-0d54-11e7-9c38-294b45b82ec8.png)

![cash flow 2](https://cloud.githubusercontent.com/assets/25841277/24093076/50a6a76e-0d52-11e7-9edc-e7e0abe74d20.png)

**Comment by DedrickEnc** [comment]
@patsonjunior peux tu argumenter ton point de vue?

**Comment by patsonjunior** [comment]
1. Je pense que pour la petite caisse, le cash flow doit présenter un solde nul du fait que c'est une caisse censée reverser en chaque fin de journéee à la grande caisse. Aussi, le fait qu'elle contient la rubrique note de crédit qui n'est qu'une preuve qui atteste qu'une écriture à été annulée et corrigée, en est une des raison  car, logiquement une écrture annulée suppose la passation d'une autre écriture qui va remplacer la première annulée et donc la rubrique note de crédit n'aura pas de sens dans le cash flow.

2. Je pense également que la rubrique "Transfert d'argent" du côté dépense peut avoir du sens pour la petite caisse et non pour la grande caisse du même côté (voir le montant 5 578 250 cdf et 6 662 000 cdf: Cash Flow/Caisse CDF) dans le sens où l'argent doit quitter la petite caisse pour la grande caisse.

**Comment by patsonjunior** [comment]
Supposons ce qui suit:
1. Facturation du client: 
Débit  4111      10 usd
Crédit 7011                    10 usd

2. Paiement du client:
Débit  5711      10 usd
Crédit 4111                    10 usd

3. Extourne ou annullation du paiement (Note de crédit) pour avoir se tromper de client:
Débit 4111       10 usd
Crédit 5711                   10 usd

4. Passation du paiement dans le bon compte:
Débit  5711      10 usd
Crédit 4111                    10 usd

4. Conséquence sur le Rapport cash Flow
Côté rescette : 10 usd cad, la prise en compte de l'écriture de correction passée après annulation de la première lié au paiement dans le mauvais compte client.
Côte dépense: 0 usd cad, la note de credit ne peut pas apparaître dans le rapport comme rubrique de dépense.
[CASH FLOW.xlsx](https://github.com/IMA-WorldHealth/bhima-2.X/files/861261/CASH.FLOW.xlsx)
