### ISSUE TITLE
(performance) Remove expensive dashboard components from being displayed on every login

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1374]
We are currently investigating the poor performance on the dashboard module with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1272. 

However this module is causing issues at installations right now. We should remove components until they are well designed and tested on the hardware we are actually using at installations. 

Specifically: 
* Remove the aged debtors report component.
* Remove the invoice and billing information component - this could potentially be hidden behind a different route or even a show/ hide button.

**Comment by sfount** [comment]
@DedrickEnc This would be a good one to tackle. The main focus/ requirement is to remove the expensive components on the dashboard page. 

If there is time it would be good to implement the invoice and billing information component in another module (statistics module or something) that can then be linked from the dashboard. This would not require the user to load it on every page load.

**Comment by jniles** [comment]
I would just comment these components out for the moment - the debtors one doesn't even work, and the other one takes _forever_ to load.
