### ISSUE TITLE
Implémentation du rapport "Balance Agée Fournisseurs"

### ISSUE THREAD

**Issue by patsonjunior** [third-culture-software/bhima#1387]
Je suggère qu'il soit implémenté un autre rapport dit: "Balance Agée Fournisseurs" qui sera un outil devant permettre de suivre l'ancienneté des dettes que les intitutions sanitaires ont vis-à-vis de leurs fournisseurs afin de programmer les paiements sur base de l'évolution de la trésorerie.

A noter que ce rapport suivra la même présentation que celui de la "Balance Agée Clients".

**Comment by jniles** [comment]
Bonne idee.
