### ISSUE TITLE
(performance) Optimising queries through correct use of indexes 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1388]
There are two urgent issues that must be addressed: 
1. There are no `INDEX`s used on the general ledger - that means that all queries involving the **25000+** records from our current installation in the general ledger must check **every row** for searching on `entity_uuid`, `reference_uuid`, `trans_date` 
2.  MySQL is not by default using `INDEX`s for **any** combined ledger queries, this means that every query using the combined ledger must search every single row in the `posting_journal` **and** in the `general_ledger` 

This impacts almost every query discussed in the performance review: 
#1375 - Calculating balance uses the combined_ledger to scan entity_uuid and record_uuid
#1378 - Uses the combined_ledger multiple times to calculate caution payments using reference_uuid and entity_uuid
Query 5 - Post cash uses the combined_ledger to check balances 
Query 6 - direct query on combined_ledger 
Query 7 - direct query on combined_ledger 
Query 8 - direct query on combined_ledger 
Query 9 - direct query on combined_ledger 
Query 10 - direct query on combined_ledger 
Query 11 - direct query on combined_ledger 
Query 12 - direct query on combined_ledger 
Query 13 - direct query on combined_ledger 

---

Some analysis to prove that we can greatly improve our queries by rethinking how we search for combined ledger results: 

**This scenario assumes the first issue has been addressed and that an `INDEX` has been made on `entity_uuid` and `record_uuid` on the `general_ledger`**

Summary Table: 

'   | Number or rows examined | Time Taken |
--- | --- | --- |
Using a view (indexes not available to MySQL) | 93013 | 0.256186 |
UNION ALL results (indexes available to MySQL) | 3 | 0.001386 |

**This is 185x faster for a very simple query**

A query performed to calculate balances on a debtors invoice balance (I have used an example known invoice and debtor in this case): 
```sql
SELECT cl.record_uuid AS uuid, cl.debit_equiv as debit, cl.credit_equiv as credit, cl.entity_uuid, cl.trans_date as date
FROM combined_ledger AS cl
WHERE cl.record_uuid IN (HUID('97b3420c-b86c-4616-91a8-fcc388b5220c')) AND cl.entity_uuid = HUID('04a9fc82-5ab4-4cef-8969-152b96b81e69');
```

The result of this query: 
```
# Time: 170321 13:01:33
# User@Host: root[root] @ localhost []  Id:   469
# Query_time: 0.256186  Lock_time: 0.001573 Rows_sent: 1  Rows_examined: 93013
```

If we change this query to not use the view but to perform the condition on the tables individually allowing MySQL to use this index: 
```sql
SELECT cl.record_uuid AS uuid, cl.debit_equiv as debit, cl.credit_equiv as credit, cl.entity_uuid, cl.trans_date as date
FROM (
  SELECT record_uuid, debit_equiv, credit_equiv, entity_uuid, trans_date
  FROM posting_journal
  WHERE record_uuid IN (HUID('97b3420c-b86c-4616-91a8-fcc388b5220c')) AND entity_uuid = HUID('04a9fc82-5ab4-4cef-8969-152b96b81e69')
  UNION ALL
  SELECT record_uuid, debit_equiv, credit_equiv, entity_uuid, trans_date
  FROM general_ledger
  WHERE record_uuid IN (HUID('97b3420c-b86c-4616-91a8-fcc388b5220c')) AND entity_uuid = HUID('04a9fc82-5ab4-4cef-8969-152b96b81e69')
) as cl;
```

**This is exactly the same query, and returns the same results**

The result of this query: 
```
# Time: 170321 13:15:48
# User@Host: root[root] @ localhost []  Id:   469
# Query_time: 0.001386  Lock_time: 0.000436 Rows_sent: 1  Rows_examined: 3
```

---

@IMA-WorldHealth/bhima-core It is urgent that everyone is aware of these issues. I will be tackling this today but this thread will track progress.

**Comment by jniles** [comment]
This is a fantastic analysis and a huge help to our installations.  Well done!

**Comment by sfount** [comment]
Point 1 was addressed by adding indexes to the general ledger table (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1389). Point 2 was implemented with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1405 and closed out via multiple pull requests removing each referenced instance of the combined_ledger.
