### ISSUE TITLE
(bug) Fix error 403 on landing page detail when refresh

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1397]
The new feature of the app on the main page throw error 403 when refresh the page.

How to reproduce : 
- Login into the page
- On the landing page click on the "click ici" button
![landing_page](https://cloud.githubusercontent.com/assets/5445251/24186091/dd76f698-0e93-11e7-9d25-dcdf28c498fe.png)

- After the click, the detail page is displayed
![detail_page](https://cloud.githubusercontent.com/assets/5445251/24186127/102d1586-0e94-11e7-8315-ed29ba5bc2d9.png)

- Refresh the page F5
![error_detail](https://cloud.githubusercontent.com/assets/5445251/24186225/90811dfe-0e94-11e7-879f-001126a29fd1.png)

**Comment by mbayopanda** [comment]
Also, i noticed that there is no more link to the homepage. The link that existed was removed

**Comment by sfount** [comment]
Great catch @mbayopanda. This should be an easy fix and we should get it in soon so that users don't come across this.
