### ISSUE TITLE
(bug) Posting Journal suffers JS rounding flaws

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1402]
The Posting Journal's aggregation functions seem to suffer from the addition flaws that JavaScript has when adding two floating point numbers.  MySQL's Trial Balance thinks this transaction balances, but the Posting Journal is displaying a different view.

![unbalancedbalancedtxn](https://cloud.githubusercontent.com/assets/896472/24197082/78ed6f28-0f00-11e7-948f-1f138c776ea1.png)
_Fig 1: Unbalanced (but actually balanced)  transaction_

**Comment by sfount** [comment]
We could use a small library like https://github.com/MikeMcl/bignumber.js/ to try and address this. By specifying a maximum precision (potentially defined by the currency) we can make sure numbers that can't be represented well by JS can be used with guaranteed results. This would however mean writing custom SUM methods for any currency/ financial grid columns.
