### ISSUE TITLE
(bug) Patient Financial Activity should sort on timestamp

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1410]
The patient financial activity can give confusing results because it doesn't sort properly - the date sort works on dates but not on timestamps.  This makes cash payments look like they were paid before the invoice was prepared.  It will make it much easier to interpret these reports if the ordering is strictly enforced.

**Comment by jniles** [comment]
This might actually be a misconfigured date on the client machines.  I'll investigate.

**Comment by lomamech** [comment]
I just checked the data from the Patient Financial Activity report are sorted in ascending order by trans_date, I confirmed it with the data of VANGA
![activite1](https://cloud.githubusercontent.com/assets/8035588/24804685/8b0f6056-1baf-11e7-9509-93f71d4dec05.png)
![activite1](https://cloud.githubusercontent.com/assets/8035588/24804727/c0ab2376-1baf-11e7-97e4-d0fb332c8d56.png)

**Comment by jniles** [comment]
@lomamech Thanks!
