### ISSUE TITLE
Outil Transfert d'argent dans le module d'application Paiement

### ISSUE THREAD

**Issue by patsonjunior** [third-culture-software/bhima#1417]
Je constate que le tranfert d'argent de la petite caisse vers la grande caisse ne génère qu'une seule écriture comptable automatiquement et la seconde à passer manuellement via le module "Bordereau de Transfert" ou "Ajout de Transaction": Débit: 588 ou 591 par Crédit 571 "petite caisse"  alors que ce transfert devait normalement généré automatiquement deux écritures: Dt 588 ou 591 par Cr 571 et Dt 572 "grande caisse" par Cr 588 ou 591.

Je suggère donc la revision du code relatif au transfert d'argent pour la générer désormais les deux écritures automatiquement au risque d'omettre de passer la seconde et de surcharger le chargé de la grande caisse et d'avoir par effet d'entrainement, des comptes à soldes éronnés.
![outil transfert d argent](https://cloud.githubusercontent.com/assets/25841277/24287404/d564d94c-1079-11e7-8bf8-9272780340eb.png)

**Comment by jeremielodi** [comment]
@lomamech proposed to close this issue
