### ISSUE TITLE
(build) Use sauce labs to run end to end tests 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1427]
I propose that we use [sauce labs](https://saucelabs.com/open-source#automated-testing-platform) to run our end to end tests during the CI process. 

Advantages: 
* speed up integration process by allowing travis to focus on unit and integration tests, running end to end primarily on sauce labs 
* test across different browsers/ platforms easily
* review logs and archives of tests, this should make it clearer why a build has failed

**Comment by jniles** [comment]
Earlier reference issue: https://github.com/IMA-WorldHealth/bhima-2.X/issues/25

**Comment by jniles** [comment]
I thought I had closed this already.  SauceLabs website isn't available from the DRC (for some reason), so this isn't feasible.  It's why I decided to use BrowserStack in a subsequent PR.
