### ISSUE TITLE
(design) Journal Module

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1432]
This proposal follows on from https://github.com/IMA-WorldHealth/bhima-2.X/issues/1241 with specific details on how this could be accomplished. 

Objectives of the Journal: 
* View all financial transactions in the system 
* 'Post' records that are verified/ complete (view only unposted records to keep on top of this process)
* Correct mistakes on transactions that have not been posted/ finalised
* Provide a view into any of the billing entities within BHIMA 
  * Patients 
  * Invoices
  * Cash Payments 
  * Vouchers 
  * Accounts 
  * Periods
* **(optional)** Add a comment/ note to any line in the journal, filter on these notes to have custom views into the data
* Ability to quickly export any group of transactions/ rows to CSV to be manipulated in excel

Technical objectives of the Journal: 
* Remember your exact configuration settings
  The journal is a complicated module and it is frustrating to constantly need to resize, move and show/ hide columns according to your required configuration 
* Responsive load times
* Tested filter/ grouping functionality
* Default and custom filters
  * Transaction date default filter 
  * Posted/ not posted default filter
  * Other custom filters
* Allow optimised custom filters 
  * Only show transactions relating to invoices 
  * Only show transactions relating to cash payments
  * Only show transactions relating to vouchers

Work focus: 
* Performance - ensuring that features/ refactors applied to the journal can be run on low end hardware 
* Functionality - common questions asked by an accountant should be able to be researched using the journal module

Required steps to implement the Journal: 
* Remove additional modules that require maintenance 
  * Remove posted journal - this module will require exactly the same 
  * Change structure of current General Ledger (all research for transactions should be through the journal)
* Formally propose migration of General Ledger to report structure 
  * Propose design for reports interactively linking to each other (Through HTML preview?)
* **[Requires Issue]** Research saving ui-grid state
* **[Requires Issue]** Refactor posting journal export to CSV 
* **[Requires Issue]** Validate posting journal edits on save
* **[Requires Issue]** Split journal filters into default and custom filters

**Comment by jniles** [comment]
1. Research ui-grid save state - #1050.
 2. Validating Posting Journal Edits - #1501.
 3. Refactoring Posting Journal Export to CSV - #1506.

**Comment by jniles** [comment]
Fascinatingly, I think all of these are actually completed in the system.  Let me know if anything is missing and I'll re-open.
