### ISSUE TITLE
(feature) Journal Comments

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1437]
As part of the Journal module work I propose we add the ability to assign comments to rows. The would allow accountants to filter the Journal on any arbitrary rows according to their comments. 

Design: 
* If one or more rows have been selected a button is displayed on the top utility bar that allows comments to be assigned to these rows. (Using http://fontawesome.io/icon/comment/ icon) 
* Clicking the comment button brings up the 'Journal / Comment' tool. 
* Tool has a brief description with an text input 
* Tool can be submitted or cancelled 
* Submitting the tool updates the selected transactions with the value entered into the comment box
* Allow filtering on columns

**Comment by sfount** [comment]
I believe the initial implementation for this feature has been developed for the 'Account Statement' module. https://github.com/IMA-WorldHealth/bhima-2.X/pull/1672

**Comment by jniles** [comment]
Closing this as completed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1672.
