### ISSUE TITLE
Fixation du Module Paiement

### ISSUE THREAD

**Issue by patsonjunior** [third-culture-software/bhima#1445]
1. Nous constatons que lorsqu'on veut payer une facture libéllée CDF en USD, la conversion est faite normalement mais sans afficher le taux de change utilisé.
Suggestion: fixer le taux de change utilisé lors de la conversion.
![module paiement](https://cloud.githubusercontent.com/assets/25841277/24445554/33a73b30-1462-11e7-84fd-f0004ea8b53e.png)

2. Nous constatons également que lorqu'on veut payer une facture en USD, après avoir cliquer sur "Soumettre", il est renvoyé un message d'erreur. Si possible de fixer en cas d'une veritable erreur lié au système.
![paiement facture en usd et msg erreur](https://cloud.githubusercontent.com/assets/25841277/24445653/8c6b81f4-1462-11e7-8e03-31f744e372b3.png)

**Comment by mbayopanda** [comment]
Le taux de change est `$0.00` parce que en realité c'est  `$0.0008` et le systeme a tendance à tronquer le nombre à deux chiffres après la virgule.

**Comment by jniles** [comment]
I'll take a look at this one.
