### ISSUE TITLE
(refactor) Deprecate automatic equals filters 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1454]
The `FilterParser` service on the server currently will use ALL options that are passed from the client, if no rule or exception is provided it will try to run the `equals` method on the key and the value (`table.[options.key] = options.value`). 

This behaviour was convenient when we had a small number of filters and it was easy to see that this was happening. Now that we have many different modules performing complex filters I propose that we remove this default functionality and require the programmer to specify each `equals`. 

Benefits: 
* No 'magic' behaviours - if a filter is supported by a server side API it will have to be specified in the code
* Simpler to pass additional options that are not necessarily required by filters, the client will not have to worry about these being matched automatically by the server

APIs that have to be updated: 
* Patient invoices 
* Cash payments
* Vouchers 
* Patients 
* ...

**Comment by jniles** [comment]
Closing this since it has been in master for over a month at this point.  We can always reference this later.
