### ISSUE TITLE
Malfunction of the search filter of the voucher register

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1466]
This is error in the Console of Browser 
![errorplus](https://cloud.githubusercontent.com/assets/8035588/24657358/3675c97e-1946-11e7-86e4-55436ebfb496.png)

**Comment by jniles** [comment]
@mbayopanda, can you look into this?

**Comment by jniles** [comment]
Oh, nevermind - I see @lomamech has it.
