### ISSUE TITLE
(feature) Add Additional Stock Registry - Consumption Registry

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1485]
The consumption registry (cahier des consommations) records all consumption of medicines and must be able to inform about the consumption (Consommation Mensuelle, Consommation Mensuelle Moyenne) of each inventory in stock.

**Comment by jniles** [comment]
@mbayopanda do you think we need this still?

**Comment by jniles** [comment]
I'm going to close this.  I don't think we probably need it - the movements registry can be filtered to get this information easily enough.
