### ISSUE TITLE
(feature) Add Additional Stock Registry - Service Distribution Registry

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1487]
The service distribution registry records all distribution of medicines to services and must also be able to inform about the lots of stock concerned by the distribution as a receipt

**Comment by jniles** [comment]
It seems to me that this issue should be combined with #1486, and potentially with #1485.  Since they are all looking at consumption, we can just build search filters to search on patient distributions or service distributions as needed.

**Comment by mbayopanda** [comment]
Closed by #2717
