### ISSUE TITLE
(feature) Accounting for stock

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1488]
This issue is about the crucial functionality of stock management : Accounting for stock

Add accounting entries for all stock operations : 
- [x] Stock Entry : 
  - [x] Purchase
  - [x] Donation
  - [x] Integration

- [x] Stock Exit : 
  - [x] Distribution to patient
  - [x] Distribution to service
  - [x] Loss

**Comment by jniles** [comment]
@mbayopanda @DedrickEnc could you review these issues and close the ones with are completed?
