### ISSUE TITLE
(chore) Transactions Export

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1494]
This issue is about the export into `csv` file for : 

- The posting journal
- The posted journal
- The account slip (extrait de compte) in the general ledger 

## Posting Journal

Add a new item named `Export CSV` in the `util` dropdown button

## Posted Journal

Add a new item named `Export CSV` in the `util` dropdown button (to create)

## General Ledger - Account slip

Add a new item named `Export CSV` in the `Action` dropdown button for each account.

**Comment by jniles** [comment]
@mbayopanda, I think the CSV export should give the possibility of only exporting the current view for the Posting Journal.  I'm not sure if you are planning on providing that functionality, but it would be good to have!
