### ISSUE TITLE
Validate Transaction 

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1498]
Allow the validate transaction function to check whether a transaction is valid, and that it will not generate any errors if it is to be inserted into the general ledger

- Date in the wrong period
- Debit and Credit should not be Zero
- A transaction must have the same date
- A transaction must not have a single row

**Comment by jniles** [comment]
Taking into account the feedback in #1499:

 1. it seems that the debit/credit balance calculation needs to be reviewed.  See:
> *Adding a line and dividing the CR amount 50% between the lines gave unbalanced txn error when it was balanced
 2. 
> -*allowed me to change date of one row of txn w/out error. Best behavior would be to change all dates of txn when one is changed (w/ confirmation message)
