### ISSUE TITLE
Changes to posting journal

### ISSUE THREAD

**Issue by WayneNiles** [third-culture-software/bhima#1499]
- ~~*should filter to last day of data by default~~ (#1523)
- *should have two boxes (at bottom?) indicating returned xxx of yyy unposted txns for all filter states
- ~~*When clicking editer the txn must expand automatically~~ (issue: #1516, fix: #1518).
- ~~Adding a line and dividing the CR amount 50% between the lines gave unbalanced txn error when it was balanced~~  Addressed by @lomamech in #1501.
-*allowed me to change date of one row of txn w/out error.  Best behavior would be to change all dates of txn when one is changed (w/ confirmation message) (requires proposal)
- ~~*Editing a txn needs a SAVE button to close it~~  (fix: #1514)
- ~~*when filtered red 'refraicher le filter' on top should really say 'desactiver filter' or 'montrer tout' or something else.~~ (Fix: #1514)
- *~~after posting took me to journal poste - bad idea~~ (issue: #1222, fix: #1522).
- would like to be able to scroll side ways in Description field when not editing and in Transaction mode also
- would like to see first 25 chars of account name text in addition to number in compte field
- ~~would like compte+25 chars and filter as you type drop down in compte field in edit mode~~ (fix: #1507, #1513)
- would like a warning when too many records are accumulating in posting journal (requires proposal)
- date column too wide, description too narrow - need to save column widths (by user?) (issue: #1473)
- consider posting session number so you can record 'who posted what when', would need a new module (requires proposal)

**Comment by jniles** [comment]
It looks like we can break some of these into UI refactors and tackle them separately/in isolation.

The following are UI issues:
 1. Editing a transaction needs to say "Save Transaction" on the button
 2. Show the first 25 characters of the account name text in the "Account" field
 3. Date column too wide by default.
 4. Rename "Refraichir le Filter" to "Desactiver Filter"

**Comment by jniles** [comment]
I'll tackle some of these UI issues with translation.

**Comment by jniles** [comment]
Closing this as outdated.
