### ISSUE TITLE
Create a "Type Text to Confirm Delete" modal

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#150]
One several pages, we allow uses to delete cashboxes, projects, enterprises, or others.  Currently, we create a `$window.confirm()` instance such as the one shown below
##### $window.confirm()

![window confirm](https://cloud.githubusercontent.com/assets/896472/13419746/ebc21cac-df80-11e5-9383-7ee56ada5ac9.png)

There are a few small problems with this:
1. After some number of alerts, the user can click the checkbox "prevent this window from making any more dialogs", disabling some functionality in the application.
2. A click-to-confirm is better than no click at all.  However, for processes that have huge implications, we might want more security -- typing in the name of the cashbox/project/entity would ensure the use knew exactly which entity they were removing.
3. From a developer perspective, this isn't a great solution:
   1. A developer has no control over the style of the `$window.confirm()` window.
   2.  A developer must manually translate the text using the `$translate` filter in the controller before display
   3. The dialog blocks the view without the choice of making a "click somewhere else to close".
   4. The user can disabled this feature by accident.
4. From a user perspective, this isn't a great solution:
   1. `$window.confirm()` windows look very different from the application, potentially leading to confusion.
   2. The text size and font is independent of the application's size and font, making this choice less accessible.
   3. The user could disabled this feature without realizing it by simply clicking a checkbox.  It is unclear how to re-enable the delete process without shutting down the browser and restarting.

I propose that we create a confirm modal similar to Github's.  See below:
##### Confirm Modal

![confirmmodal](https://cloud.githubusercontent.com/assets/896472/13419940/690dcb56-df82-11e5-95c7-ddb435044f37.png)

This could be imported into any module and used similar to how we use `$window.confirm()`, except with promises.  For example:

``` js
angular.module('bhima.controllers')
.controller('ExampleController', ExampleCtrl);

ExampleCtrl.$inject = [ 'ConfirmModalService' ];

/**
 * Modal.open() looks like this:
 *  service.open = function openModal(match) { 
 *  var instance = $uibModal.open({
 *     controller : 'ConfirmModalController as ConfirmModalCtrl',
 *    templateUrl : 'path/to/the/template.tmpl.html',
 *    resolve : { match : function () { return match; } }
 *    size : 'md'
 *  });
 *  return instance.result;
 * };
 */

function ExampleCtrl(Modal) {
  vm.confirm = function confirm() {
    Modal.open(vm.textToMatch)
    .then(function () {
      // the user typed and clicked "confirm action"!
    })
    .catch(function () {
      // the user canceled the action.
    });
  }
}
```

**Comment by jniles** [comment]
@mbayopanda Can you work on this while waiting for a review on #575?

Let me know if you need clarification.  This modal will be useful when we begin working on the posting journal trial balances and editing records inline.

**Comment by mbayopanda** [comment]
@jniles no problemo... i'm working on it...
