### ISSUE TITLE
Add search feature in posted journal

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1534]
This issue is about to add the search feature in the posted journal. We can use the same logic such as in the posting journal

**Comment by jniles** [comment]
I know @WayneNiles has specific features he wants in the "Posted Journal", including renaming it.  We can probably do a sprint on it.

**Comment by sfount** [comment]
I believe that the work on Account Statement module https://github.com/IMA-WorldHealth/bhima-2.X/issues/1635 supersedes this issue.
