### ISSUE TITLE
Commentaires sur journal de saisie #2

### ISSUE THREAD

**Issue by WayneNiles** [third-culture-software/bhima#1541]
Dans le vu groupe (non transactions) ajoute a la ligne du groupe CLI17 (2), la date et Enregistrement.  Comme ca je vois quelle sont les dates a filtres. (fix: #1542)

Pour editer un compte, la cas doit etre selectionnez apres double clique pour que la recheche commence avec des chiffres entrees du claivier; preferablement avec drop down ouvert sur l'ancien compte.

J'aimerais avoir le nombre des lignes recuperes indiqué au footer.(fix: #1551 )

Besoin d'export a CSV pour le tableau raprochement.

Quand rien n'est selectionne le rapprochement donne erreur "no such table" et "une erreur est servenue";  c'est plus tot, "rein selectionne".  Ou "Selectionner au moins une ligne idiot!"(fix: #1553)

Serait-il possible de demander un nom de fichier avant d'export a csv?

Export a csv suive les colonnes selectionnes dans configuration avec les memes noms des colonnes dans le csv.

Appliquer un nouveau filtre et les soldes au footer (20873400) ne figure pas dans mode transactions.
Solde au fond doit avoir des separateurs des groupes (, ou .). (fix: #1557 )

Dans Recherche par Compte - enlevez les comptes titres du drop down.

**Comment by jniles** [comment]
> Quand rien n'est selectionne le rapprochement donne erreur "no such table" et "une erreur est servenue"; c'est plus tot, "rein selectionne". Ou "Selectionner au moins une ligne idiot!"

^ That shouldn't happen...  and I cannot reproduce it on the IMA server.  I get the warning below:
![transactionselectionwarning](https://cloud.githubusercontent.com/assets/896472/25275425/2859768e-268d-11e7-8127-bdc7a2618f3d.png)
_Fig 1: No Transactions Selected Warning_

**Comment by jniles** [comment]
I believe all these have been closed.
