### ISSUE TITLE
(chore) Add more tools for cash in the journal voucher

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1550]
The use of journal voucher is easy for qualified and experimented accountants, not so easy for not experimented accountants

To make life easier for users of journal voucher, we have to add tools for : 

- Money Transfer (Auxiliary cash => Principal cash)
- Generic incomes
- Generic expenses

These tools will prevent errors relatives to confusion with debit and credit

### Tools in the tools drop-down

![voucher_tools](https://cloud.githubusercontent.com/assets/5445251/25524063/d0c58f4e-2bbd-11e7-886c-78f57a60d74c.png)

### Cash Transfer

![voucher_transfer](https://cloud.githubusercontent.com/assets/5445251/25524241/aa3633e6-2bbe-11e7-8158-b1e67d55e189.png)

### Generic Income

![voucher_gen_income](https://cloud.githubusercontent.com/assets/5445251/25524306/e11119c6-2bbe-11e7-8cca-142da3ca160d.png)

### Generic Expense

![voucher_gen_expense](https://cloud.githubusercontent.com/assets/5445251/25524318/ea51e95c-2bbe-11e7-9566-042b10047f11.png)

**Comment by mbayopanda** [comment]
@jniles @sfount @lomamech 

What do you think about those UI ?

**Comment by sfount** [comment]
I think these tools are very similar as those described in this issue https://github.com/IMA-WorldHealth/bhima-2.X/issues/1309. 

The referenced issue proposes that these tools are implemented on the cash box page itself, each of the tools uses a cash box so having the tool on the cash box page would set one of the accounts automatically. I assume using components we could actually have the same tool used on both modules - what do you think the priority should be?

**Comment by mbayopanda** [comment]
The cash box page is for auxiliary cash box, for operations relatives to a principal cash box there is no module for that (in 1.x there was `Primary Cash`), so the accountant have just the journal voucher (or simple voucher) for those operations

**Comment by mbayopanda** [comment]
Completed by #1586
