### ISSUE TITLE
Trial Balance security

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1559]
The trial balance module is very important because it posts transactions in the general ledger.

In the current state of `Trial Balance` there is no way to control and to secure the posting in the general ledger.

This issue is about to implement : 

- An authentication with special password or pin for authorized users
- A way for tracking user who post in the general ledger

**Comment by jniles** [comment]
We used to have a "Posting Session" table in 1.x that contained the user_id, timestamp, and uuids of the records posted.  Maybe that would address point 2?

**Comment by jniles** [comment]
I think this is probably a good use for roles.  Pins or other authentication would probably get annoying quickly..

**Comment by jniles** [comment]
Closing as better suited to limiting users rights via roles.
