### ISSUE TITLE
(bug) Journal Vouchers do not render the correct currency of the Transaction

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1595]
The Journal Vouchers seem to confict on when currency to use between the footer and the contents of the voucher.  See below:

![vouchercurrencyrenderingissues](https://cloud.githubusercontent.com/assets/896472/25701182/1d7eab86-30c3-11e7-9d6a-c17ef9573b36.png)
_Fig 1: Journal Voucher Currency Confusion_

This a bug in the rendering that should be resolved.  Everything should be made in the transaction currency.

**Comment by mbayopanda** [comment]
It is fixed with the PR #1586

**Comment by jniles** [comment]
Ah.  Cool :+1:
