### ISSUE TITLE
(feature request) Dropdown to Edit Transaction Types in Posting Journal

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1609]
The Posting Journal does not allow one to view or edit the transaction type (`origin_id`).  This is critical for proper classification of transactions, research, and generation of meaningful reports (such as the cash flow report).

We need to be able to:
 1. Show the transaction's type in the Posting Journal
 2. Edit it via a <select> box in the ui-grid.

**Comment by mbayopanda** [comment]
Completed by #1616
