### ISSUE TITLE
Improve bhCurrencyInput

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#161]
The `bhCurrencyInput` is just barely functional.  Here are some tasks to complete before it could be production-ready.
- [ ] Default text when no currency is selected
- [ ] `max-value` option, passed in from the parent controller
- [x] ~~`min-value` option, passed in from the parent controller~~
- [ ] Optionally save currency values in AppCache (configurable via the settings page)
- [ ] `strict` option, making the currency input not accept parts of a currency (45 FCs, 0.0034 USD, etc)
- [ ] remove the binding to the parent form (`form`), and use a child form instead to do local validation.

**Comment by DedrickEnc** [comment]
The min value seems nit important since we are applying the min value for a currency, but the max value is very usefull.

Envoyé depuis mon HTC

----- Reply message -----
De : "Jonathan Niles" notifications@github.com
Pour : "IMA-WorldHealth/bhima-2.X" bhima-2.X@noreply.github.com
Objet : [bhima-2.X] Improve bhCurrencyInput (#161)
Date : jeu., mars 3, 2016 12:14 PM
The bhCurrencyInput is just barely functional.  Here are some tasks to complete before it could be production-ready.

Default text when no currency is selected

max-limit option, passed in from the parent controller

min-limit option, passed in from the parent controller

Optionally save currency values in AppCache (configurable via the settings page)

&mdash;

**Comment by DedrickEnc** [comment]
> remove the binding to the parent form (form), and use a child form instead to do local validation.

@jniles can you send me some link which encourage developer to use this design? because I think it is recomanded if you are using cascaded components.

**Comment by jniles** [comment]
There is no link, this is an optimization I personally developed.  The only reason we are injecting the parent form is to know what the form name is.  Instead of injecting a form, the child component can create its own form and avoid the need to inject the parent form.  It makes the component self-contained.

**Comment by DedrickEnc** [comment]
@jniles 
Thank you for the feeback : 
1. `strict` option, the currency input doesn't accept a parts of a currency already. you can not submit 45 FC for example, so what do you mean exactly?
2. Where can I put this default text? it is possible to just change the color of the input?
3. I am not at easy with this idea, a component is created to be integrated in the parent form, once  integrated, it becomes one of form members, creating an other form just to avoid sending the form name to a component seems not natural.
   This situation will leads us to have nested forms in one form, if we have ten components in a form we will have ten small forms nested into the parent.

**Comment by jniles** [comment]
1. The currency input should not accept 134.34 FCs with `strict` mode.  We know that this is not an achievable amount of money.  This feature might be useful at the cash window, and we can ask our users if they think it is useful in testing.
2.  When there is no currency passed in, the currency input should default to some text.  Specifically [this line](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/partials/templates/bhCurrencyInput.tmpl.html#L9) could be changed to read:
   
   ``` html
   <span class="input-group-addon">{{ $ctrl.currency.symbol || '...' }}</span>
   ```
   
   to make the input default to '...', for example.
3. That is correct.  Just like if we have ten components on a page, we will have ten smaller, isolated scopes on the page.  That is not a bad thing!  Here are some reasons why this is a good idea:
   1.  Avoids repetition:  If we have multiple form components on a page, you will see this code:
   
   ``` html
   <bh-component-1 form="ParentForm"></bh-component-1>
   <bh-component-2 form="ParentForm"></bh-component-2>
   <bh-component-3 form="ParentForm"></bh-component-3>
   
   <!--- etc ... -->
   <!-- can we do better? -->
   ```
   1. Reduces `$watch`es on component border.  Whenever you have a binding like `<` or `=`, angular will set up a `$watch` on the parent scope.  In the `=` case, it will set up a `$watch` in both scopes, even if the scope is isolated.  Removing the binding avoids this behavior.  See the [$compile](https://docs.angularjs.org/api/ng/service/$compile#-scope-) documentation for more information.
   2. By default, Angular will attach the child form to the parent form.  Why do that work twice?
