### ISSUE TITLE
(proposal) Make Period IDs YYMM instead of AUTO INCREMENT

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1625]
The application currently generates a `period_id` from the database using an autoincrement system.  This means that there is no association between the period date and the ID of the period.

I propose that we make `period_id`s uniformly four digits:
 1. The first two digits will be the last two digits of the current year - 17 for the current year.
 2. The last two digist will be the current month, indexed at 1 _not zero_.  This is how MySQL indexes months, but not JavaScript.

This will make the `period_id` predictable.  That way, if we have a date on the client, we can generate the period ID without even a trip to the database.  This is advantageous for numerous reasons:
 1. We can automatically compute the `period_id` for the posting journal.
 2. In the future, a filter could turn "this month" into `period_id = XXXX` for a faster lookup.
 3. `period_id`s will be human-readable in database dumps or Excel exports.

I can't see any downsides to this proposal besides marginally larger space used storing integers instead of SMALLINTs.

**Comment by DedrickEnc** [comment]
Except the fact that we will use many digit to represent a period_id, I agree. There many advantageous

**Comment by jniles** [comment]
The good thing is that I don't think it will change the datatype size from INT.  Even if we run for a couple of years, 210001 is still an INT!  :)
