### ISSUE TITLE
(design) Deceased Patient Feature

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1629]
**Motivation**
One function we do not currently have is a way to indicate that a patient has died.  This is useful for a number of reasons:
 1. Data Integrity - once a patient has died they should not being receiving medicines.  They may have past debt to pay off, but they should not be starting new patient visits.  We can do these validation checks in software.
 2. Statistics - if a patient dies at the hospital, we can compute statistics for mortality rates at the hospital.  We can even break down by patient population (women, children, infants, HIV+ patients, etc).  Eventually, we may be able to give year-end stats by ward.
 3. Ratio analysis - one of the criteria of ratio analysis is "% Deceased".  The only thing we are missing is an indication that this patient is deceased.

**Design**
The ideal place for this function would be on the Patient Record page.  We would put a button "Record Patient Death" that would allow a user to put in the patient's date (and possible time) of death, the person responsible to certifying that the patient died, and a notes field.

On the backend, the database would be structured similar to Patient Visit - although I would propose putting in a `dod` - date of death column in the patient table so we can easily tell if the patient is deceased.

`patient_death` would contain:
  1. `patient_uuid`
  2. `notes`
  3. `user_id`
  4. `created_at`
  5. `updated_at`

**Validation**
A patient that has a `dod` can still have bills made them and can still have cash payments in their name.  However, they should not receive any more stock distributions, nor should they be able to be checked into that hospital again.

**Comment by lomamech** [comment]
The management of the patient's death in my opinion is more related to the Hospital's Patient Management, if not we should also handle admission as well as discharge patients.

There is also one thing we do not yet manage, the presence of a patient in the hospital because until then, limited access to services only to patients who are present at the hospital

Concerning the billing module for hospitals that have morgues one can charge a deceased patient for the number of days that the corpse remains at the morgue, one can also distribute the products used for embalming.

**Comment by jniles** [comment]
We do provide patient management.  Patients can be "admitted" to the hospital (and then "discharged"), but it is not deployed anywhere currently.  You can even put the medical diagnosis using the ICD10 codes (in French!).  This feature landed in December (https://github.com/Vanga-Hospital/bhima-2.X/pull/93).

I agree that billing for death is a bit complicated.  This can probably wait for later - user feedback will be valuable.

**Comment by jniles** [comment]
Perhaps a more limited proposal would be better - simply blocking certain patients.  If we come up with a good workflow, that should be good enough to cover the financial motivations behind this proposal.
