### ISSUE TITLE
(feature request) Automatically create a Patient when registering an Employee

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1631]
When an employee is registered in the BHIMA software, it would be ideal to create a Patient entity for them in the `patient` table.  This implies that the `patient` information is a _subset_ of the `employee` information.

To accomplish this goal, the following changes needs to be made:
 1. `POST /employee` must result in a `db.transaction()` to ensure that either the patient or employee are not created without the other.
 2. The employee registration page must contain both Origin Location and Current Location location selects.
 3. The employee registration page must contain a hospital number - this is likely going to be their medical license number in practice.
 4. The `employee` table should be modified to contain a `patient_uuid` foreign key.

**Comment by DedrickEnc** [comment]
I think, it is a good idea. But the all employee page should be refactored to follow our current standard

**Comment by DedrickEnc** [comment]
already addressed by #1691
