### ISSUE TITLE
Account Statement Work

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1635]
This issue tracks the work on the module "Account Statement", showing the details of posted transaction by account.  It is derived from discussions with @IMA-WorldHealth/bhima-core and @WayneNiles .

**Issues to Create**
 1. **Basic User Interface** - we have decided that the interface will be a `ui-grid` similar to `Posting Journal`. 
    a. The module is named `Account Statement/Releve de Compte`.
    b. It consists of a full page `ui-grid` with data filtered by account.
    c. It has `ui-grid-selection` but not `ui-grid-grouping` or `ui-grid-edit` plugins enabled.
    d. It has a button for searching using the same `Posting Journal` search modal.

@mbayopanda, you should make an issue describing how this should work.

 2. **Transaction Detail Slave Grid** - we have proposed viewing transactions in a separate slave grid below the main grid.
     a. This grid shows all lines in the transaction that is clicked on by the user.
     b. The records are loaded over HTTP on click.

This will take some research.
  
 3. **Comment Feature** - we have proposed allowing a user to comment on the grid via a modal.
     a. This issue is basically #1437, but on the `Account Statement`.
 
~~@sfount, you should make the necessary updates to this issue so that it can be implemented by anyone.~~

 4. **Opening Balance/Final Balance Display** - we need to show the beginning balance _at the beginning of the view_. This should be, at minimum, a `period_total` lookup + adding offset for the in between time.
    a. This issue should propose how to look up the balance for any date range, independent on how we decide to model dates.  Assume there is just a `start_date`.
 
I'll take a look at this one - @jniles.

**Comment by mbayopanda** [comment]
👍 LGTM

**Comment by jniles** [comment]
A prototype proposal for looking up the opening balance of an account for a given date has been implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1644.

**Comment by jniles** [comment]
Everything here has been completed except the transaction slave grid.  At the moment, all values are displayed by default, so there isn't really a need for the slave.  We can make a specific design issue if this need comes up in the future.
