### ISSUE TITLE
Account Statement - basic use interface

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1638]
This issue is a proposal for the account statement #1635  basic user interface

1. The user interface seems like the posting journal with those differences : 
- Display single line of accounts, there is not any grouping by transaction
- The default filter is based on : an account, a date range and a limit
![grid](https://cloud.githubusercontent.com/assets/5445251/25905228/4a1426b6-3556-11e7-98de-6db81e5e4d5f.png)

2. There is also a column filter such as in the posting journal
![grid filter](https://cloud.githubusercontent.com/assets/5445251/25905277/6c56b220-3556-11e7-9d88-9b7efd9300ad.png)

3. Comment line for analysis 
- The user can comment lines for need of analysis by selecting rows and clicking on the `comment` button
![grid comment](https://cloud.githubusercontent.com/assets/5445251/25905357/aea4e8e0-3556-11e7-945e-44f9bbc61bf2.png)

4. There is also a search menu like in the posting journal but with a new field for account as default filter
![grid search](https://cloud.githubusercontent.com/assets/5445251/25905507/0aaed6d2-3557-11e7-90be-542f9ddd02a6.png)

5. Utils drop down for exporting to PDF, CSV and printing
![grid utils](https://cloud.githubusercontent.com/assets/5445251/25905564/337f673e-3557-11e7-9957-e7f0327fea4d.png)

NOTE: The UI for details of a row is not described here

**Comment by jniles** [comment]
Closed in #1672.
