### ISSUE TITLE
About changing the date of a transaction in the posting journal

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1640]
My preocupation is the following, what may be the reasons that may need to change a date in the posting journal,

In my opinion the Modules Journal voucher ansi that Simple Voucher already gives the possibility of anti date a transaction

And the modification of the date of a transaction does not repercute on the documents that generated this transaction

**Comment by jniles** [comment]
@lomamech, I agree - it is weird to change the date of a transaction without modifying the original documents.

For most journal voucher transactions, I assume that no receipt will be necessary - for example, it will record a bank transfer, or a purchase of material, or an amortissement.  It doesn't make sense to print out a document for amortissement - but it might make sense to modify the date if you find out that you made a mistake.

However, you are correct that for things like cash payments it doesn't make any sense.  Perhaps we can allow a user to print out the transaction directly from the Posting Journal and sign it to show they have made a correction...
