### ISSUE TITLE
(proposal) Remove the ability to select a source from the report selection interface

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1641]
If we have a good Trial Balance and Posting Journal (we are getting there!), we should encourage users to post to the GL by requiring it for before generating reports.  I propose we remove the `source` selection so that all reports are generated off of posted data.

**Advantages**
 1. No more of this `combined_ledger` or `UNION` nonsense.
 2. All totals are precalculated in `period_total` table
 3. Encourages users to post regularly - something all our installations haven't mastered yet.
 4. Significantly lowers risk of values in reports changing after being reported on.

**Drawbacks**
 1. We have to be certain errors are _obvious and loud_ before a user posts incorrect data.  This leans heavily on our Posting Journal and Trial Balance
 2. We may run up against installation limitations that prevent us from actually getting away with this change

@IMA-WorldHealth/bhima-core this needs discussion before we could actually remove the `source`.  What do you guys think?

**Comment by sfount** [comment]
I agree with this proposal - most core financial reports should be based on the `period_total` tables, this information is guaranteed to be balanced and should have been verified by an accountant. 

Users may blame the reports if there are inconsistencies, allowing them to create reports on unverified data could well lead to this.

**Comment by jniles** [comment]
I believe the majority of these have been removed with the new report structure.

**Comment by jniles** [comment]
Closed.  See #1642.
