### ISSUE TITLE
(design) Closing/Opening a Fiscal Year via Period Totals

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1651]
It doesn't seem to me that there is any reason to write transactions into the Posting Journal or GL.  See  this source for a detailed overview: [Démarche pour clôturer un exercice Comptable.pdf](https://github.com/IMA-WorldHealth/bhima-2.X/files/995805/Demarche.pour.cloturer.un.exercice.Comptable.pdf)

I propose that, when closing a fiscal year and opening a new one, we operate entirely on the `period_total`s table without introducing any transactions into the `posting_journal` or `general_ledger`. 
  1. This prevents the issues encountered in https://github.com/IMA-WorldHealth/bhima-2.X/issues/761. 
  2. It also prevents double-counting in reports that pull their opening and closing balances from period totals ... no need to filter the GL on the opening/closing transaction.

**Design: Fiscal Year Closing Algorithm**
When closing a Fiscal Year, the following actions occur:
 1. The application checks that there are no unposted transactions against the Fiscal Year.  If so, it must reject the procedure.  This directly prevents #1647.
 2. If (1) passes, _this means all balances are already in the `period_total`'s table_.  The user should confirm those balances.  At this point, the user should also specify the gain or loss account that will hold the balance of the `INCOME - EXPENSE` accounts.
 3. If the user confirms (2), the Fiscal Year should be closed by:
    a. Sum the balance of all balance accounts from Period 0 through Period 12 in the `period_total` table.  These numbers are then written to Period 13 by account.
    b. Write 0 for the `period_total`s of all `INCOME` and `EXPENSE` accounts in Period 13.
    c. Write the result of the `INCOME - EXPENSE` into Period 13 of the user-defined balance account.
    d. Mark the Fiscal Year as closed.

After this procedure is done, Period 13 will have 0s for all INCOME and EXPENSE accounts.  All other accounts will contain the sum of Period 0 through Period 12 in their Period 13.

**Design: Opening a Fiscal Year**
If we adopt the above procedure, the way to open a new Fiscal Year is to copy Period 13 from the previous Fiscal Year into Period 0 of the new Fiscal Year.  That is all.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
This is a very good analysis. I agree with everything here, it does not make sense to me to write an actual transaction to move the difference of income expense into a class 1 account, this is more of a theoretical transaction that locks in values to be reported on. 

I think it's also important the the UI very clearly shows what is happening to each account and where it gets totals from.

I'll take a look at what it would take to implement this.

**Comment by jniles** [comment]
The opening of the Fiscal Year was addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1840.
