### ISSUE TITLE
When searching by date using the custom mode

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1655]
When searching by date using the custom mode, one is obliged to click on two submit buttons, which can induce a user to the error
![imm](https://cloud.githubusercontent.com/assets/8035588/26065393/162699f0-3994-11e7-984e-6f7a591965f2.png)

**Comment by jniles** [comment]
This is a really nice issue!  I agree with the analysis - it's one of the reasons we didn't want to use `bhFindPatient` on search forms.
