### ISSUE TITLE
Bug in the display of data in posting journal,

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1659]
Bug in the display of data in posting journal,
![fileerror](https://cloud.githubusercontent.com/assets/8035588/26108301/665fc140-3a4c-11e7-9466-5b8e57020f55.png)

Some transactions are mixed in the posting, which disrupts the operation of updating the data

**Comment by jniles** [comment]
I think this has to do with our test data - `TRANSXXX` transaction IDs cannot be generated from the current data, which makes reasoning about this problem difficult.  Furthermore, we cannot reproduce this in our production dataset.

Let's build an appropriate test dataset and then try to debug this.  Good bug report @lomamech !
