### ISSUE TITLE
Improvements to the Users and Permission Module

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#166]
This issue is to track improvements and refinements to the users and permission module (`/permissions`).  Though not frequently used, user management is one of the most important aspects of the application.
- [x] Add an indicator for weak or strong password.  This indicator should be hidden until the password input is `$dirty`.  It is a separate utility from checking if passwords match.  The rankings should be on this scale:
  - `Weak` - passwords less than six characters in length
  - `Medium` - passwords between six and ten characters in length
  - `Strong` - Passwords greater than ten characters in length OR passwords greater than eight characters with at least one uppercase, lowercase, symbol, and number in the password.
- [ ] Implement asynchronous validator on the username field to check if the username is unique.
- [x] Implement user roles (see #170).

**Comment by DedrickEnc** [comment]
@jniles 
Can you be more clear about user role?

**Comment by jniles** [comment]
@DedrickEnc, sure.  See #170.

**Comment by jniles** [comment]
For inspiration on password strength meters, see [this article](https://scotch.io/tutorials/password-strength-meter-in-angularjs) which implements something similar in Angular.

**Comment by Scholldier** [comment]
Is all that's left here a check to make sure the username is unique?

**Comment by jniles** [comment]
Aha, looks like this issue has already been taken care of - the most recent work on the username validation was done in https://github.com/IMA-WorldHealth/bhima-2.X/pull/3071.  I'll close it.
