### ISSUE TITLE
Implement a "Report an Issue" link on settings page

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#167]
One issue we've consistently faced is getting reliable user feedback.  We can attempt to facilitate better user feedback by making it easy to send an email to the development team with a bug report, using an [email link](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Email_links) with an automatically templated bug report.

This is a proposal to add a button to the `/settings` page that will read "Report a Bug".  This button is a `mailto` link that creates an email with the following information:
###### Subject: [bhima] Bug Report (02-01-2015)

Thank you for filing a bug!  Please read the following message and replace the text surrounded by brackets ({{}}) with your report.

Where did the bug occur?
{{ ENTER TEXT HERE }}

What task were you trying to accomplish?
{[ ENTER TEXT HERE }}

What result did you expect?
{{ ENTER TEXT HERE }}

Any other relevant information or comments?
{{ ENTER TEXT HERE }}

May we contact you for more information?
[x] YES  [ ] NO

---

We can also attach a client log file automatically, and a timestamp as needed.  Since this is simply a mailto link, we can easily translate it just like the rest of the application.

**Comment by DedrickEnc** [comment]
What is the scenario, if the system is running in the hospital without internet? in other word this feature depends to the internet availability?

I am not providing information when using a software which fails, I just ignore and retry, may be there are many people like me, can't we send this report automatically (at least have this option), taking in account that the user can give bad informations.

**Comment by jniles** [comment]
If there is no internet, the email will not be able to be delivered.

We can definitely gather our own information automatically and should gather our own information.  But every software product that I have used has a "bug report" section where I can go fill out specific bugs or feature requests.

**Comment by DedrickEnc** [comment]
ok
