### ISSUE TITLE
(error) Landing page details

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1675]
There is an error on the landing page details : 
- 400 : BAD REQUEST
- SQL ER_PARSE_ERROR

![landing-page-error](https://cloud.githubusercontent.com/assets/5445251/26396828/336d6d68-4029-11e7-94b8-4f1e49bcac4c.png)

**Comment by jniles** [comment]
The error is because this line:
```js
  const dbPromise = [db.exec(sqlInvoices, [date, date]), db.exec(sqlBalance, [date, date])];
```
Should be 
```js
  const dbPromise = [db.exec(sqlInvoices, [date, date, date, date]), db.exec(sqlBalance, [date, date, date, date])];
```

**Comment by jniles** [comment]
Also, the `sqlInvoices` query could be greatly improved by only scanning the `invoices` table instead of the invoices JOINed with voucher.

**Comment by jniles** [comment]
I'll take this.
