### ISSUE TITLE
(bug) general ledger and balance report are corrupted

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1693]
[ ] General ledger :
	- Bug: The amount of the balance doesn't correspond to the sold of the account
	- Fix: the french translation "Grande Livre" to "Grand Livre"

[ ] Report / Balance : 
	- Bug: The report is crashed

[ ]  Report / Balance agee des creances :
	- Bug: Error in the console

**Comment by jniles** [comment]
Also, a translation bug: "Util" should be "Outil" on the Journal page.

**Comment by jniles** [comment]
This was closed on accident.

**Comment by jniles** [comment]
This was closed on accident.
