### ISSUE TITLE
refactor: Restructure account slip structure

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1706]
Currently the account slip is used to show detailed information on transactions that have hit an account. It is very similar as the 'Account Report'. I suggest that we restructure these reports to minimise the amount of code to be maintained and simplify future development. 

File structure: 
- [ ] Move account slip under the `accounts` report folder so that it can be found at `finance/reports/accounts/slip`
- [ ] Separate the account slip code from the general ledger controller so that it can be found at `finance/reports/accounts/slip.js`

UX structure: 
* Use the exact same template/ controller for both the report and the slip that can be displayed within modules
* Allow easy filtering of the slip to only show data from a specific time period

Report logic: 
- [ ] Use MySQL or well defined JavaScript to calculate totals so that the template is not responsible for this - contributes to https://github.com/IMA-WorldHealth/bhima-2.X/issues/1668
- [ ] Separate `getAccountTransactions` from the `reportAccounts.js` controller so that it can be used by other services/ controllers

**Comment by jniles** [comment]
I'll tackle this in my General Ledger refactor (#2462).  The account report has evolved quite a bit, so this will probably link directly to the account report for the selected FY.
