### ISSUE TITLE
chore: add new maintainer to package.json

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1709]
We recently gained a new developer: @jeremielodi!  Welcome!

I propose that @jeremielodi implement a Pull Request (PR) that adds his name to the [package.json](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/package.json#L38) file under the key "maintainers".  This PR will be reviewed and promptly merged.

@jeremielodi how does this sound?  Can you tackle it?

**Comment by jeremielodi** [comment]
I am ready to do it

**Comment by jniles** [comment]
Closed in #1726.
