### ISSUE TITLE
Design: Simple Journal Vouchers for Cash Transactions

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#172]
This proposal is to create a simplified interface to the journal vouchers module for use as a cash payments slip.  The goal is to reduce the amount of accounting a user needs to perform, and focus instead on recording information about the transaction.

![simple journal vouchers](https://cloud.githubusercontent.com/assets/896472/13566472/16cc8264-e456-11e5-8a01-8cf69a7fbd75.png)

A mockup of the proposed user interface is shown above.  The form would be a simple "From Account" -> "To Account" and "Amount".  It fills in a (disabled) description field by default based on the values a user inputs, but allows them edit it for more specificity.  The user is automatically recorded to be stored in the journal vouchers table.

The "From Account" and "To Account" fields will be powered by an account selection input.  This input will be a typeahead on the account number field.  If the user double-clicks the input, the account finder modal will be displayed, allowing them to specify an account by cashbox, supplier, patient, etc...  The choice is persisted in AppCache.

This simplified form should take care of the concerns about confusion with the debit/credit fields at the Journal Voucher page.  It should be a way to rapidly record new transactions to the Posting Journal that only require two rows.  Between this proposal, and the full Journal Vouchers page, we should be able to model the entire primary cash module easily in the application.

Interested in what @IMA-WorldHealth/local-contributors think of this proposal.

**Comment by sfount** [comment]
This is a well laid out proposal - mockup makes it very clear!

This is what I had in mind when we were discussing as a team how journal vouchers could replace a lot of the main cash modules that make up a lot of the 1.X codebase. It seems simple enough to use to be able to perform a lot of functions:
- One time payments from a cashbox to an employee for quick errands etc. 
- Resolving mistakes in cashbox transfers
- Resolving issues with a patients bill and providing a clear receipt 
- Paying back the cashbox with additional money left over from a purchase

Potentially the only alteration I would make is to always use to the 'Find Account' modal to populate the fields and have a 'search for account by account number' in there, emphasising how this if 'From Entity' -> 'To Entity' and you do not need to know the accounts - this is a fairly small change though and it would be good to see how it looks.
