### ISSUE TITLE
feat: Inventory search modal requires more parameters

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1721]
The Inventory Search Modal is quite limited.  This is the current version on master:
![inventorysearchform](https://cloud.githubusercontent.com/assets/896472/26630578/418f966a-45ff-11e7-939f-e0f9260015bc.png)
_Fig 1: The most recent inventory search modal form_

We are missing the following fields:
 1. `code` - the unique inventory item code
 2. `price` - the sales price
 3. `inventory_type` - the type of inventory
 4. `inventory_unit` - the unit of the inventory
 5. `consumable` - a flag to see if it is consumable

These inputs should be implemented with the latest `FilterService` on both the client and server.  They should also take into account #1702.

**Comment by jeremielodi** [comment]
Closed in #1996.
