### ISSUE TITLE
Insuffisance de test e2e pour les filtres

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1733]
They exist of the numbers filters the data search but there are not always tests to check the good functionality of component of the search forms

**Comment by jniles** [comment]
What do you mean by good functionality?

**Comment by lomamech** [comment]
Currently in the register of the patients there is a bug when we search the patients with their debtor_group.uuid this bug was not detected just because there was never a test on the debtor_group

**Comment by jniles** [comment]
Ah, I understand.  So we are missing tests.  Good catch!
