### ISSUE TITLE
(feature) Report Client

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1736]
Re: https://github.com/IMA-WorldHealth/bhima-2.X/pull/1362 

Proposed changes during team meeting: 
* Add the option to download/ print the report from the preview page 
* Use latest components on Account Report (bhAccountSelect, bhPeriodSelect) 
* Fix 403 on 'Back to report options' from the Report Archive
* Report archive grid updated to latest standards 
* Update to `master` branch

**Comment by mbayopanda** [comment]
Close by #1765
