### ISSUE TITLE
(refactor) Grid features

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1737]
Re: https://github.com/IMA-WorldHealth/bhima-2.X/pull/1700

Grids are used throughout many BHIMA modules that are used every day by current installation sites. 

We have many different grids/ registries that have different standards and versions of features. It is important to bring these up to date to reduce technical debt. 

* Using the latest `FilterService` on all relevant grids 
* Using the updated `GridStateService` on all grids 
* Using the same tools menu style on all grids
* Using uniform totals/ aggregate data on all grids

**Comment by jniles** [comment]
I'll make a series of issues to denote the work that needs to be done in these.

**Comment by jniles** [comment]
I believe this has been completed satisfactorily.  There may be some trailing edges, but specific issues can be open for those.
