### ISSUE TITLE
(refactor) Journal module grid state

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1738]
After meeting and discussing the refactor required in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1737 it is proposed that we should remove all implicit state saving as a standard on grid modules. This behaviour is currently implemented in the Journal module so this should be updated. 

Proposed behaviour: 
Grid state should only ever be saved if the user select 'Save grid configuration'

**Comment by jniles** [comment]
@sfount, what is the status of this issue?

**Comment by jniles** [comment]
This was closed some time ago.
