### ISSUE TITLE
Improve bhDateEditor

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#174]
This issue is to track improvements to the `bhDateEditor` component.
- [ ] The input should be be `readonly` instead of `disabled`, like the `bhFindPatientComponent`.  The disabled state can be confused with actually disabling the input.
- [ ] The component doesn't enforce `max-date` or `min-date`.  It should either:
  1. disallow the user to input the max date or min date OR
  2. show an error message that the date is too great or small
- [ ] The buttons should be `i18n`.
- [ ] If possible, remove the option to "clear" the date.
- [ ] Include the label "Date" in the component by default.  Support the binding `label-key` to allow a controller to alter the label to another text.  The `label-key` will be passed through the translation filter in the view.
- [ ] Make the test harness actually work.

**Comment by sfount** [comment]
Is there actually any need for any of the utility bar buttons? 

From a (very) quick review 
- Today - the component opens on the current day anyway (in the case of the cash module)
- Clear - not sure why you would ever need to clear a date - I believe this is what is up for discussion.
- Close - this can be accomplished by clicking anywhere other than the date component.

If it is deemed these aren't actually needed we could make use of the `show-button-bar` flag on the directive to address the "Clear" date issue.

**Comment by jniles** [comment]
~~Is it possible to remove the buttons?  I haven't checked.  If so, removing them is a good suggestion.~~

EDIT: It is possible.  Just add `show-button-bar="false"` to the component. [src](http://stackoverflow.com/questions/19030675/how-to-remove-ui-bootstrap-datepicker-footer-angularjs)

**Comment by jniles** [comment]
Another quick addition:
1. `uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead`.

**Comment by jniles** [comment]
I'll take a look at tackling these tomorrow.
