### ISSUE TITLE
refactor: Improvements to the Voucher Registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1742]
This issue is to track improvements to the Voucher Registry to be tackled while the team is working all registries.

Parent Issue #1737.

-------

The follow changes should be made to the Voucher Registry:
 - [x] Make a "Menu" dropdown with the following options:
   1. Column Configuration
   2. Saving the Grid Configuration
   3. Resetting the Grid Configuration
   4. Download View as CSV
   5. Download View as PDF
 - [x] Implement the Grid State work on the grid (See #1738)
 - [x] Implement the latest FilterService, replacing the old `bhFiltersApplied` with the new `FilterService`
 - [x] Remove the `bhRendererDropdown`
 - [x] Implement downloading as CSV using the `ui-grid` exporter (See https://github.com/IMA-WorldHealth/bhima-2.X/pull/1554)

**Comment by sfount** [comment]
From working on the development data set I have seen that it would be very useful to filter vouchers on their type, being able to get the total of a specific type of voucher over a given time would provide a lot of insight. For example all money transfers in June or all bills paid in June. 

- [x] Add filter by 'Transaction Type'
