### ISSUE TITLE
refactor: Improvements to Cash Payments Registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1744]
This issue is to track improvements to the Cash Payments Registry to be tackled while the team is working all registries.

Parent Issue #1737.

-----

The follow changes should be made to the Cash Payments:
 - [x] Make a "Menu" dropdown with the following options:
   1. Column Configuration
   2. Saving the Grid Configuration
   3. Resetting the Grid Configuration
   4. Download View as CSV
   5. Download View as PDF
 - [x] Implement the Grid State work on the grid (See #1738)
 - [x] Make sure Search Form is up to standards with `bhClear` on each optional input (see #1702)
 - [x] Remove the `bhRendererDropdown`
 - [ ] Implement downloading as CSV using the `ui-grid` exporter (See https://github.com/IMA-WorldHealth/bhima-2.X/pull/1554)

**Comment by sfount** [comment]
To add to this: 
- [ ] Grid should not overflow on the bottom of the page 

As discovered in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1760

**Comment by DedrickEnc** [comment]
@jniles 
Is the last point of the issue relevant? because the invoice registry is using the server side logic for exporting to csv and I would like to do so. (Discussed during your presentation of invoice registry).

**Comment by jniles** [comment]
@DedrickEnc, no problem using CSV server-side rendering.  I'll make an issue about it so that it's clear the decisions we've taken and we can plan ahead.
