### ISSUE TITLE
refactor: deprecate bhRendererDropdown

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1745]
The `bhRendererDropdown` provided a stand-in until we had a better way to download CSVs on the client.  We now have that - introduced in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1554.  The `bhRendererDropdown` shouldn't really be used anymore in modules.  Reports should implement their own CSV export using the report route in real dropdown menu, and PDF download separately.

**Comment by jniles** [comment]
@lomamech, what is the status of this issue?

**Comment by lomamech** [comment]
After checking, this component is still used in the employee registry, I do not know if there are PRs tracking down this problem.

**Comment by jniles** [comment]
Good to know!
