### ISSUE TITLE
refactor: Invoice registry

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1749]
References issue https://github.com/IMA-WorldHealth/bhima-2.X/issues/1737

The patient registry should be updated to meet the latest standards in order to reduce technical debt and give clients required features: 

- [ ] Use the latest FilterService in favour of the hardcoded deprecated method
  - [ ] Update the InvoiceService to use FIilterService 
  - [ ] Update the search modal to use 'default' and 'custom' filters
- [ ] Integrate grid save state (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1738)
  - [ ] Save configuration 
  - [ ] Load default configuration
- [ ] "Menu" dropdown for core utilities
  * Column configuration
  * Download view as CSV
  * Download view as PDF 
- [ ] Remove bhRenderer dropdown 
- [ ] Use bhClear on search modal (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1702)
- [ ] Remove 'Print' action favouring the 'Download as PDF'
- [ ] Ensure links to other registries work correctly

**Comment by jniles** [comment]
I'll take this one!
