### ISSUE TITLE
proposal: write 2.x's documentation using gitbook

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1757]
I propose that we write 2.x's documentation using [gitbook](https://www.gitbook.com/).  Previously, we used LaTeX in a hosted repository [here](https://github.com/IMA-WorldHealth/bhima-user-manual).  This was a pain to write and compile.

The advantages of GitBook I see are:
 1. We get a hosted website and nice reading experience online for free.
 2. We can update the online manual and instruct our users via an email link to download the latest version.
 3. We can version the manual to correspond with 2.x's versions.  The changelog can inform us of any areas that need to be updated between versions.
 4. Much, much easier to edit and spellcheck.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by mbayopanda** [comment]
It's will be a good experience also for the team, and this is what is being done today.

LGTM 👍

**Comment by jniles** [comment]
I've started this, just to see how it works.  

https://www.gitbook.com/book/ima-worldhealth/bhima-user-manual/details

If other devs want to try and contribute, that would best inform this decision.

**Comment by jniles** [comment]
Now at https://manual.bhi.ma.
