### ISSUE TITLE
Refactoring Employee management module

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1764]
The employee manage module is now merged in the master branch, after his presentation some suggestions has been made : 

- [ ] The default filter ```limit``` should be set by the user (search modal page)

- [ ] The modal column configuration shows two columns telephone (employee registry page)

- [ ] Split employee information and patient information (employee registration page)

- [ ] The localisation component should be set to the enterprise localization by default (employee registration page)

- [ ] The date of birth should be well formatted (Employee registry page)

- [ ] Investigate the color around the register button (Employee registration page)

- [ ] Sort the grid by display name (Employee registry page)

- [ ] Dynamically adding a function and grade from the registration page (Employee registration page)

- [ ] Remove lock component from the registration page (Employee registration page).

**Comment by sfount** [comment]
This is a good write up from the meeting. I agree with all of these points. 

For the second point I would specify: 
* Split employee information and patient information 
   * Employee details - Grade, code, name, etc.
   * Patient details - Location, hospital number, etc. 
   * Optional information - Parents name etc. 

And add: 
- [ ] Employee registration and employee registry should be translated.
- [ ] PDF/ CSV download should either be removed or implemented 
- [ ] Registry 'Actions' should either be removed or implemented

**Comment by jniles** [comment]
I would also add:

 - [ ] Make sure all keys are translated before code is merged into master.

**Comment by jniles** [comment]
Closed in #2091.
