### ISSUE TITLE
(refactor) Account statement report

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1784]
- [ ] Remove the custom period selection allowing only fiscal years and periods to be selected. (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1783)
- [x] Remove the 'source' options, reports should only be build based on proven data. (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1641)
- [x] Thoroughly test the outputs of the report using the new development data set. (https://github.com/IMA-WorldHealth/bhima-2.X/pull/1782)
- [x] Cache all options so that the report options are always remembered. Add a clear options to default button.
- [x] Improve the description (en + fr). 
- [x] Add form error handling to the create form, right now no error message or red outlines are displayed if there is missing information. 
- [x] Ensure beginning and ending balances are calculated correctly for the account statement. 
- [x] Update name in tree and translations to be standardised 'Account Statement'

**Comment by DedrickEnc** [comment]
Good feedback, just a note, sometimes IMCK was building deport by specifying a custom date range. It will be wise for BHIMA to let data available anytime.

**Comment by jniles** [comment]
I'm pretty sure this has been satisfactorily addressed.  We can re-open if not.
