### ISSUE TITLE
(bug) Updated permissions do not refresh until the session is destroyed 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1819]
When permissions to new modules are granted to a user, the permissions will not be applied until the user has destroyed their current session and opened a new one (new tab or logged out logged back in). 

**Example:** 
User 'user' is currently logged in, he is granted access to 'Module' 

'user' clicks on the 'Module' in the tree. 

**Expected behaviour:** 
User currently has access to 'Module', module should load.

**Current behaviour:** 
User currently has access to 'Module', 403 page restricted message shows because the permissions have been recently updated. 

This is relevant to work on the users and permissions module found https://github.com/IMA-WorldHealth/bhima-2.X/issues/166

**Comment by jniles** [comment]
In my view, the ideal implementation should attach a `refresh()` method to the `SessionService`.  The `Session.refresh()` will simply load the user's permissions, enterprise, project, and information.  Once a user changes the permission successfully, the session can be refreshed automatically on the background.

This issue most visibly changes the permissions, but this also affects things like updating the project name in the top left corner of the application, or the enterprise name other places it is rendered.

**Comment by lomamech** [comment]
I tried with SessionService.reload and it works very well

**Comment by jniles** [comment]
@lomamech, I forgot that was implemented.  Excellent!
