### ISSUE TITLE
(bug) Reports module does not update report definition on transition 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1821]
Currently the reports module structure (title and archive button) is in an external `reports.html`. This allows the structure to share the report definition details with the report generation template (in a `ui-view`). 

The report details are not updated or refreshed when the user transitions to another report. This leaves invalid archive links as well as the incorrect title displayed for the report.

**Comment by jniles** [comment]
@sfount what is the progress on this one?  Can I tackle it?
