### ISSUE TITLE
(feature) Show invoice details on Cash Receipt

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1824]
This bug was submitted to the BHIMA `support@bhi.ma` thread. 

**Proposal** 
> Cash payment of patient 2 000FC against TF bill for c-section of 200 000FC
I can see the bill was from maternity department and the Facture number.
"Paiement par Sedi Lubutu Marie (PA.HEV.4555) contre les facture(s) IV.HEV.20724. -- Maternite"
Could this line also include the following text from the Facture/Invoice Description
In this example the description of the item is: Cesariene TF3.03 (Tarif Forfetaire)
This would help make it clear what the patient is paying towards on the printed quittance.  

* Add the invoice description to the cash payments receipts - this should consider both the POS simplified receipts as well as the more complex PDF receipts

**Comment by jniles** [comment]
@lomamech what is the progress on this?

**Comment by lomamech** [comment]
Sorry, before I had not understood the problematic of this issue (Translation problem). Therefore the only problem is only to add the descriction to the cash payments receipts

**Comment by jniles** [comment]
Okay, just curious :)

**Comment by lomamech** [comment]
I'm working on

**Comment by sfount** [comment]
As I understand it they are asking for the description of the **invoice item** on the invoice here. If we displayed the description for every invoice item on every cash payment that has the potential to become a very large invoice... 

In his example here I believe they will always have only one invoice item, however that is not something we can guarantee. 

@jniles 
Do you think this is worth pursuing further with an optional flag to show all invoice items in the cash payment or would that be an additional level of complexity we do not need to support?

**Comment by jniles** [comment]
We could probably support this with an additional flag - I can't see it as detrimental.  However, I would make is a rendering flag ... so that the receipt fetched all the details of the invoice, rather than storing any extra information in the database.  That way we don't have to worry about updating data if the user toggles the flag - just behavior.

**Comment by jniles** [comment]
Relabeling as "Feature Request" since that is more appropriate here.
