### ISSUE TITLE
(proposal) rethink linking entities from reports 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1833]
Our core tools and reports are currently being used frequently. In many cases the best way to look up a document is to go to the relevant registry, search for the reference and then download the document. This might take 5 or 6 clicks and if you are quickly verifying 100s of transactions it could take hours. 

I propose in our core tools (journal, account statement, general ledger) we provide links to documents that open the documents in a new tab. We could provide a convenience route in BHIMA that accepts the human reference (IV.HEV.20) and returns the PDF document.

This method would allow us to add these hyperlinks without any additional queries. 

Opening the document in a new tab would allow us to write limited code with the user coming back to exactly the same context they were in before. It also gives more screen real estate than a modal. 

Convenience methods like this can save hundreds of hours when auditing many transactions.

(An issue should also be created re: exporting to CSV being performed in one click - it is done frequently and should not require options and naming).

**Comment by jniles** [comment]
This seems like a good idea :+1:

Maybe this is getting ahead of ourselves, but should we allow the user to change a setting to render HTML versus PDF in the new tab?  I can imagine that HTML would be much faster ... and if they were simply wanting to see it, it should work just as well, right?

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1886
