### ISSUE TITLE
(bug) Latest invoice statement has no loading indicator

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1837]
At a number of installations with limited hardware the latest invoice statement (on the patient record module) can take up to 20 seconds - this query will need to be optimised. 

Right now a partially filled in component is displayed without any indication of loading. It is important to hide the components display until the content is loaded, displaying a loading indicator would also help the user know that the data is not yet ready.

**Comment by jniles** [comment]
This component was supposed to have a loading indicator.  Is this the same bug as https://github.com/IMA-WorldHealth/bhima-2.X/issues/1141?
