### ISSUE TITLE
(bug) Trial Balance initialises with no data

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1839]
I think this bug report may have been made before. Sometimes the trial balance loads with a blank interface displaying no transactions. When this happens it is necessary to close the trail balance and open it again. This is a very bad user experience, especially when the trial balance takes a long time to load.

**Comment by jniles** [comment]
This is a really difficult one to track down - I initially noticed this, but couldn't get it to reproduce in a local environment.  I imagine it has something to do with the ordering of HTTP requests and painting of the ui-grid.  Somehow the Trial Balance doesn't repaint data if it takes a while to load.
