### ISSUE TITLE
(refactor) Purchase order functionality refactoring

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1842]
The purchase order is on master now, so here are some noticed problems when using the module

1. The payment mode should be default on **LORS DE L'ACHAT** 

2.  Change ```FORM.INFO.INVALID_ITEMS``` into ```FORM.ERRORS.INVALID_ITEMS``` and translate it

3. Remove the button **RETROUVER UN ARCTICLE** or implement it

These points can be discussed to find the final task list

**Comment by jniles** [comment]
All those suggestions look good to me :+1:

If someone is going to tackle this, they should also tackle https://github.com/IMA-WorldHealth/bhima-2.X/issues/1063 which suggests improvements to the Purchase Order module.

**Comment by jniles** [comment]
I'll tackle this.
