### ISSUE TITLE
(refactor) Purchase Order Registry refactoring functionality

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1843]
The purchase order registry is reviewed and is in master branch, after trial here is points to address

1. Applying registry standard #1749

2. **MODIFIER ETAT** seems not useful and can not see how this can work with a purchase order of type **PAYER LORS DE L'ACHAT** and it is also easy to forget updating it!

These point can be discussed to have final point to address.

**Comment by jniles** [comment]
See as well https://github.com/IMA-WorldHealth/bhima-2.X/issues/1746 which discusses point 1 in detail.

**Comment by DedrickEnc** [comment]
Can be closed, if there is a point not tackled, a separated issue can be created
