### ISSUE TITLE
(feature) Purchase order validation and authorization

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1845]
After trying the stock management modules, I have noticed that there is no intermediate step between purchase order creation and expense for that purchase order.
At bhima 1.x we had an intermediate process, which consist in validating/authorizing a purchase order.
This step is very important to help the cashier not expending money without the chef account and administrator authorization.
A purchase order is like a PRF so it must pass through some authorization before being acted.
The challenge is to find a good way of presenting this process (at bhima 1.X it was two different modules).
what do you think @IMA-WorldHealth/bhima-core

**Comment by jniles** [comment]
At IMA, with our PRFs, we simply have people sign the physical copy of the PRF.  As far as I know, there is no representation of this in Sanru Trakker.  Can we not just have the administrator sign the printed out document?

**Comment by DedrickEnc** [comment]
Well, it is also a good idea, however IMA is a international organization, fraud is almost absent and IMA is audited every year which is not the case of an institution located at the periphery of a village. it makes many years since the IMCK was audited for the last time.
We are dealing with hospital which are not able to respect some business logic and it is easy for them to ignore some of them. 
We don't need necessarily a module to validate and authorize purchase order like at BHIMA 1.X, we have just to find the way of forcing this process/rule to be there, because it is not good to expend money without administrator and chief of finance authorization. If only BHIMA can guaranty that.

**Comment by jniles** [comment]
In my mind, the administrators should force that procedure.  I'm not sure why people would respect the software more than their management ... if they are willing to spend money without the Admin's approval, they certainly will without BHIMA's approval!

**Comment by DedrickEnc** [comment]
I close this issue, it can be reopened if there is a need.
