### ISSUE TITLE
(refactor) Stock entry module

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1846]
The stock entry module is already merged in, these are what I found as problems when trying to use the module : 

# ACHAT

1. Confusing behavior when you click on **ACHAT** and select a purchase order (P.O) and when you click again on it, it shows all P.O while **ACHAT** contains now the ID of the previous P.O chosen

2. The suspend button is confusing, and what is his purpose? can't choose a better name?

3. The lot recorder should not refuse to register a lot which will expire today and if it refuses, it should print a message to inform the user.

4. The receipt of stock entry, confuse the number of lot and the number of inventory item (see the header)

# INTGERATION

1. The dialog box of stock integration is submit-able even if no lot detail is provided

2. the integration should not restrict the user to provide a expiration date because the lot is considered as an existent lot.

3. confusion between inventory and lot, in the receipt

4. What is the meaning of **AUCUNE SOURCE DEFINIE**

# AJUSTEMENT

1. The quantity should be well presented, it is a add-on and a remove-on quantity
2. The receipt should show the old quantity and the new quantity of the lot.

**Comment by jniles** [comment]
It looks like the following have been fixed:
 - [x] The dialog box of stock integration is submit-able even if no lot detail is provided.
 - [x] Confusion between inventory and lot on receipt.

**Comment by jniles** [comment]
I think all these have been tackled.
