### ISSUE TITLE
(refactor) Inventaire en Stock

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1847]
The inventaire en stock module is on master, here is some noticed points when using it : 

1. the record is grouped by depot, is it a way to remove depot name in the record item?

2. Inventaire table should be refactored #1749 

3. The total as aggregate is not important since it is semantically incorrect or not meaningful.

4. columns ```CM``` and ```SS``` must be more clear let's choose other name

5. What is the meaning of the last column?

**Comment by jniles** [comment]
@DedrickEnc @mbayopanda - I know @WayneNiles wants to begin testing this in-house at IMA World Health.  If this registry is still confusing, we should come to a decision about it and clean it up.

**Comment by DedrickEnc** [comment]
@jniles
It seems like, it is already cleaned.

**Comment by jniles** [comment]
Great!  Can this issue be closed yet, or are there still points to address?

**Comment by DedrickEnc** [comment]
It should be closed.
