### ISSUE TITLE
(bug) Ensure latest reports are presented in the correct currency 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1852]
Many of the up to date reports did not correctly factor in the enterprises currency when display totals - all reports should be checked for using the currency ID correctly. 

- [x] Income/ Expense is always presented in dollars 
- [x] Account statement current period totals are always presented in dollars

**Comment by sfount** [comment]
@DedrickEnc If you could quickly address the Income/ Expense report, I'm sure it is just a handlebars scope issue.

**Comment by jniles** [comment]
I believe the income/expense was addressed in #1855.

**Comment by sfount** [comment]
Account statement was addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1906 closing this issue.
