### ISSUE TITLE
Convert period keys to human readable format

### ISSUE THREAD

**Issue by WayneNiles** [third-culture-software/bhima#1871]
While poking around the db I noticed the keys in Period, GL, Budget, and PeriodTotals are 1,2,3 ... whereas 201701, 201702 are human readable and also no bigger than the mediumint size used for the key .  Furthermore the tests to see if a date falls in a given period  require two tests: xdate <= period.minimumdate or xdate >= period.maxdate  whereas I assume there's function that formats a date into the yyyymm form which can be directly compared with the period in question.    I would also use the sql between function to see if a date falls within a range.  Not urgent.

**Comment by jniles** [comment]
See https://github.com/IMA-WorldHealth/bhima-2.X/issues/1625 for a similar proposal.
