### ISSUE TITLE
(refactor) Ensure all registry links work 2

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1873]
like #1828 This issue will make it possible to verify in all the modules of bhima if it exits still links that no longer works or not work

**Comment by jniles** [comment]
@lomamech, one bug is going from Patient Groups -> Patient Registry, this breaks.  Same with Debtor Groups.

**Comment by lomamech** [comment]
Exactly, I also think of adding E2E tests to verify that the links work

**Comment by jniles** [comment]
That's a great idea!
