### ISSUE TITLE
(test) ensure all link work

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1878]
In the PR #1877  We had remove some test links that do not work,
like:
- Check link betwen Invoice Registry -> Patient Registry
- Check link betwen Cash Registry -> Patient Registry
- Check link betwen Patient Registry -> Cash Registry
- Check link betwen Inventory Group -> Inventory Registry

**Comment by jniles** [comment]
@lomamech, you have mostly completed these, right?  I see many of them in `master` already.

**Comment by lomamech** [comment]
Yes that already was completed
