### ISSUE TITLE
Fixing the report e2e test

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1884]
Currently, we are supposed to refresh the page before every test case to make our report e2e test passing, since it is not correct logically (because the user will not refresh the page after every use case). 
These ~`browser.pause()`~ `browser.refresh()` should be removed and the test should be updated for best practice.

**Comment by jniles** [comment]
I'll take a look at these tests this weekend to avoid another https://github.com/IMA-WorldHealth/bhima-2.X/issues/2110.
