### ISSUE TITLE
(bug) Problem with Account Report

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1891]
There is a difference in value when looking for the account statement using a date range (2015-01-01 and 2015-12-31) with (2015-01-01 and 2016-01-01) ,

NB: these tests were carried out with the development-build.sql database

**Comment by sfount** [comment]
It looks like this has been introduced recently with some significant changes to account balance calculations code - I will investigate this bug.

**Comment by lomamech** [comment]
I analyzed the code and concluded that the query should be used
````
  const periodCondition = `
    (period.number = 0
    OR
    DATE(period.end_date) <= DATE(?))
  `;
````
 instead 
````
  const periodCondition = `
    (period.number = 0
    OR
    DATE(period.end_date) < DATE(?))
  `;
````
 to account for transactions that occurred during the last period of end_date

**Comment by lomamech** [comment]
With @mbayopanda  we noted some inconsistencies with the database development-build.sql for which several corrections were made to the table period_total

But with regard to the use of <= And < the report of the accounts 'Eau' and 'Electricite' are correct in the case where one uses <= and incorrect in <

But also of the checkout account 'Caisse Principale USD' is correct with < and incorrect with <=

But the PR #1892  fix the data and we can view the result with the report 'Balance of Account' and 'Balance sheet'
