### ISSUE TITLE
(refactor) Open Debtors Report

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#1893]
Following an e-mail from Vanga, there is a problem with the Open Debtors Report, because this report displays all patients without debt filters and generates errors
![bhima error screen shot](https://user-images.githubusercontent.com/8035588/28621146-467a83e6-7210-11e7-85c9-da777e93ebed.jpg)

**Comment by jniles** [comment]
It looks like this report has a massive JOIN that eliminates all benefits due to indexing.  @sfount and I will tackle this issue this morning.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1908.
