### ISSUE TITLE
(feature request) show default filters on registry PDFs

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1909]
Some of our registry PDFs include the search filters sent back to the server on them.  However, these are limited to only the custom filters and do not include default filters.   Default filters (particularly the LIMIT) provide important contextual information.  We should include them on the printed PDF registries.  See below:

![patientregistrationnodefaultfilters](https://user-images.githubusercontent.com/896472/28783058-fff0685a-7606-11e7-917d-5df7021aa7f9.png)
_Fig 1: Patient Registrations without any custom filters_

**Comment by jniles** [comment]
@jeremielodi, can you look into this?

The basic idea is to put the filters that we see on the client like this:

![defaultfilters](https://user-images.githubusercontent.com/896472/29116032-7b79be18-7cf1-11e7-944e-cded8fd9af93.png)
_Fig 1: Default Filters_

.. on the server PDF reports.

To render on the PDF report.  A good example of how filters can be rendered on the server is seen in [the Patient Registrations Report](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/controllers/medical/reports/registrations.handlebars#L9).

It should be pretty straight-forward.  Let me know if you need any help!

**Comment by jeremielodi** [comment]
Yes, I can look into it but my internet connection is very slow now

**Comment by jniles** [comment]
Closed in #1947.
