### ISSUE TITLE
(proposal) standardize account management UI

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1914]
The account management UI is a bit dated at this point.  Most other registries have migrated to dropdown menus to better implement a variety of features.  Considering that account management still has [some open issues](https://github.com/IMA-WorldHealth/bhima-2.X/labels/accounts), a user interface refresh would allow us to slot in any future changes.

For reference, here is the Account Management module:
![accountmanagmentui](https://user-images.githubusercontent.com/896472/28866054-b33eb9bc-7769-11e7-8f2e-b5585eba0c6f.png)
_Fig 1: The Account Management UI_

I propose the following:
 1. We implement a drop down at the top of module with the following features:
   a. Download as PDF
   b. Download as CSV
   c. Grid Save-State
 2. We implement a dropdown on the ui-grid as an "action" with the following features:
   a. Edit Account
   b. [For Parent Accounts] Add Child Account
   b. [In the Future] Lock Account
   c. [In the Future] Add Account Tag

 /cc @IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
Agreed - I think that in particular the ability to export your account structure to CSV for quick changes/ review would be very useful. 

I don't think that this module has a need for saving the grid state as it is a very limited grid in terms of number of columns or data points. Other than adding complexity to the user experience I can't think of a reason to not however.

**Comment by jniles** [comment]
I agree about Grid State.  No problem there. :+1:
