### ISSUE TITLE
(bug) Patient support tool does not work when patient is selected by ID

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1915]
The patient support tool works as expected when a patient is selected by name search - it returns two lines in a voucher debiting the new account and crediting the patient's account. 

However if a patient is selected by ID this process fails and only one line is shown on the voucher. 

This is a critical bug. 

Additional refactors: 
* Voucher account select shows title accounts and account number and text are not aligned 
* Patient support tool - submitting without an account selecting does nothing when the account should be highlighted in red and shown as required data

**Comment by jniles** [comment]
I'll tackle the additional refactors.

**Comment by jniles** [comment]
I'll tackle the additional refactors.

**Comment by jniles** [comment]
Also, the currencies ought to be right aligned.  I'll tackle this as well.
