### ISSUE TITLE
refactor: standardize display of credit amounts in BHIMA

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1919]
In BHIMA, we have two ways that we display negative/credit amounts.  Either with a negative sign or with parentheses in red.  Here are two typical examples:

![creditsongeneralledger](https://user-images.githubusercontent.com/896472/28878300-bf8c482e-7796-11e7-96e9-3dd0c655c453.png)
_Fig 1: Negative Numbers have a Preceding minus sign_

![creditsonpatientfinancialrecord](https://user-images.githubusercontent.com/896472/28878299-bf814316-7796-11e7-9e9c-0fadac7e5ad4.png)
_Fig 2: Negative Number are in Red with Parens_

 Typically, spreadsheet systems (like Excel or Sanru Trakker) choose a standard way of displaying these amounts.  BHIMA should adopt a standard and use it everywhere.

In my opinion, the preferable way to display these numbers is as in **Fig 2**, with a **red highlight and surrounding parentheses**.  That way, even in small cells that cut off part of the text you will always know that it is a credit balance.

@IMA-WorldHealth/bhima-core what do you guys think?

/cc @WayneNiles

**Comment by sfount** [comment]
I agree with showing negative values in brackets - this is easier to consider a credit rather than negative money.

**Comment by jniles** [comment]
Reopening this issue because we don't have a way of displaying credits on the client in the red fashion.

**Comment by jniles** [comment]
Looks like this is how to do it: https://stackoverflow.com/a/30122327

**Comment by jniles** [comment]
Related to https://github.com/IMA-WorldHealth/bhima/pull/3957
