### ISSUE TITLE
(proposal) Make the patient financial history easily available

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1921]
Our patient financial history report ties together all of the financial entities in BHIMA that relate to a patient. Primarily invoices and cash payments but also vouchers that reference the patient. 

Right now it is hidden in the patient overview module: I propose we make this easily accessible to the user in a number of ways: 
1. Directly link the patient financial report _anywhere_ that a patient human readable ID is used. This would use the work done in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1886 and https://github.com/IMA-WorldHealth/bhima-2.X/pull/1916.
(the patient card could also be linked in a multi-part component. For example [PA.HSP.100](https://patient-link) [[C]](https://card-link)
2. Register it a BHIMA report just like the account statement  - the user would be able to select a patient and preview and save the report. 

Additionally it would be good to treat this as an up to date report and test the data values produced by the financial history.

**Comment by jniles** [comment]
I think it would be surprising to click the PA.HSP.100 link and find a financial history of a patient.  Potentially it makes sense on the ledger-style modules (Journal, GL, Account Statement), but on the Patient Registry it feels like it should produce either their information page or their card.

What do you think?

**Comment by sfount** [comment]
Agreed this would only be from financial tool modules - the patient registry could continue as it is right now.
