### ISSUE TITLE
(refactor) Unify date component across modules

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1940]
We currently have a mix of HTML date components and the angular UI bootstrap date components. Users seem to better understand and use the UI bootstrap date component - it also allows the user experience to be uniform across browsers. 

I suggest that we update any use of the HTML date input to the bootstrap component:
- [ ] Period select component used in all search modals

**Comment by jniles** [comment]
I'm pretty sure this has been taken care of.  I'll take a look at it today and make sure.

Relevant PRs: #2091 and #2198.
