### ISSUE TITLE
Deprecate and remove DepricatedFilterService

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1942]
As part of our sprint on registries, we have attempted to remove all instances of `DepricatedFilterService` in favor of the new `FilterService`.  We should go through and clean out all instances of `DepricatedFilterService`, replacing them with the latest standard to ensure a uniform user experience.

**Comment by jniles** [comment]
@dedrickenc, what is the status of this issue?

**Comment by DedrickEnc** [comment]
@jniles
I was lost, I have one more file to refactor before closing this issue.
I do it today or tomorrow morning. So it still remain opened

**Comment by jniles** [comment]
Cheers, sounds good!  Just trying to clean up old issues :)
