### ISSUE TITLE
fix(posting journal) scroll to edited transaction

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1943]
After editing a transaction it is difficult to find the edited  transaction line directly.

This issue is about to scroll or add highlight to the edited transaction

**Comment by jniles** [comment]
I've been working on this and got it working on my own branch.  It'll be introduced with a PR soon.

**Comment by sfount** [comment]
To add to this, I have been working on https://github.com/IMA-WorldHealth/bhima-2.X/issues/1832. This feature allows the transaction to be edited **away** from the journal's context - the values in the posting will then be updated but the user will be looking at exactly the same lines that they were before editing without any scrolling.
