### ISSUE TITLE
Setting date range for custom period is complex

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1946]
The default filters are used a lot (posting journal for example), so setting the date range for custom period is a long process for the user and sometime the Validating button is skipped or forgotten

**Comment by jniles** [comment]
Note, this can be tackled at the same time as https://github.com/IMA-WorldHealth/bhima-2.X/issues/1940 and https://github.com/IMA-WorldHealth/bhima-2.X/issues/1718.

**Comment by jniles** [comment]
Prior art: #1655.

**Comment by jniles** [comment]
This is partially fixed - @jeremielodi implemented the logic so that the submit button can be skipped, but the button remains.

I'll remove it.
