### ISSUE TITLE
The posted transactions must be accessible

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1950]
By the fact that users can't use the posted journal (performance issue) there is no possibility to see if posted transactions are really in the general ledger

**Comment by sfount** [comment]
There is a proposal for tackling this with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1432. I think both the Account Statement and the Journal should be able to temporarily view both posted and non posted transactions. 

There is also a proposal for a document/ transaction search that would make this information available.
