### ISSUE TITLE
fix(posting journal) : mark transactions as comment

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1951]
A comment tool like in the account statement module is necessary for marking transactions

**Comment by jniles** [comment]
@sfount, what do you think - should we include this in `feature-journal-tools`?

**Comment by sfount** [comment]
@jniles I think this feature can be included in `feature-journal-tools`. It should introduce very little new code but adds a lot of functionality to working with the Journal.

**Comment by jniles** [comment]
I'll take it then.

**Comment by jniles** [comment]
Whoops - the mobile UI doesn't show assignments.  It looks like @jeremielodi is already assigned.  It's all yours!

**Comment by jeremielodi** [comment]
closes #2065

**Comment by jeremielodi** [comment]
closed in #2065
