### ISSUE TITLE
refactor: improvements to the Purchase Order Registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1964]
The Purchase Order Registry was refactored extensively in #1907 that brought it partially up to standards with the other registries.  Here are some further improvements to bring it completely in line with standards:
 1. Use a dropdown menu to view the document
 2. Make the "Search" text hidden on small screens -- not the icon.
 3. Add inline filtering to the registry
 4. Make the PO.PROJ.XXX identifier into a link to the receipt.

**Comment by DedrickEnc** [comment]
@Knowles
I am working on purchase order to remove deprecated filter. I will address these points also

**Comment by DedrickEnc** [comment]
@jniles
I am working on purchase order registry #1942 to remove deprecated filter. I will address these points also

**Comment by jniles** [comment]
Sounds good!
