### ISSUE TITLE
(refactor) Transaction editing corner cases 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1972]
This issue references work done in open PR https://github.com/IMA-WorldHealth/bhima-2.X/pull/1970. The following corner cases exist in the current systems editing however they should be addressed once this work has been merged. 

- [x] **(bug)** Entering and then removing an entity or recipient reference during an editing session will fail with an indirect error message. Given this behavior it is impossible to remove references or entities, they can only be changed to another valid entity. 
- [ ] **(refactor)** All rows that have been updated should 'flash' for a few seconds when the editing session has been completed - this would give the user visual indication that changes have been confirmed. 
- [x] **(bug)** Removing all rows during an editing successfully deletes all transaction rows however a `404` is then returned as the module cannot find the transaction. Requesting all rows to be removed should either be blocked or this use case handled on the server to return an empty array. (if blocked this may require a method for completely removing transactions - implications on referenced document should be considered). 
- [x] **(proposal)** Documents that have had their underlying transactions edited should be updated with a simple flag showing that their values may no longer represent the financial transaction.

**Comment by sfount** [comment]
- [ ] **(proposal)** Use $state based `onEnter` and `onExit` methods to allow programmers to view/ edit any transaction by navigating to a client URL - this removes the need for any imports and would allow static reports to link to transactions. For example `#/transaction/:id/view` and `#/transaction/:id/edit`. 

- [x] **(proposal)** Search both the posting journal and the general ledger for the transaction requested - this route should set a `posted` flag depending on which table the record is selected from.

**Comment by jniles** [comment]
> (proposal) Use $state based onEnter and onExit methods to allow programmers to view/ edit any transaction by navigating to a client URL - this removes the need for any imports and would allow static reports to link to transactions. For example #/transaction/:id/view and #/transaction/:id/edit.

This sounds like a really good idea :+1:

**Comment by sfount** [comment]
@jniles 👍. To add to this many controllers (Posting Journal/ Account Statement) need to receive the values passed back from the Transaction modals edit session - this would be impossible to do through state based transition. 

I think a way to work around this would be to have the `#/transaction/` route set up as a convenience for modules or reports that need to link a transaction in a stand alone action - any module that needs to update the underlying data should call it through the Service to enable data returned from the query.

**Comment by jniles** [comment]
Note that the "removing all rows" corner case was handled when validation was added.

Additionally, the search setting the "posted" flag was addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2170.

**Comment by jniles** [comment]
We've covered all these cases satisfactorily.  In the future, there are some "nice to have" features (such as flashing), but they have performance implications that are rather serious.
