### ISSUE TITLE
discussion(stock): does invoice must be required before distribution to patient ?

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1974]
This issue is about the need of having invoice when distribute medicine to patient.

Do we need to restrict medicine's distribution to patient who have invoice or not. For a secure system, it will be good to restrict distribution to patient to only patient who have invoices (paid) in the system, but in the real world there are some case where the patient doesn't have an invoice, for example for hospitalized patient.

![stock exit](https://user-images.githubusercontent.com/5445251/29265182-ec362c56-80d7-11e7-81f5-d08554fbfc3a.png)

**Comment by jniles** [comment]
I would say we do not need to restrict a distribution to an invoice, however, users are encouraged to link a patient's invoice.  That step would be optional.

**Comment by jniles** [comment]
@mbayopanda, how is this currently treated in the application?  Is it required?

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2743
