### ISSUE TITLE
(bug) Cash window gives no indication of only loading cash boxes from current project

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1976]
The cash window currently selects only cash boxes from the users current project (chosen at sign in time). It can be very confusing to users to not see any cash boxes even though the configuration is set up with multiple cash boxes. 

I think the two options are to clearly demonstrate that these are only the cash boxes that exist in the currently signed in to project, for example 'Hospital's cash boxes:'  or to just show all cash boxes with the project shown next to the name. 

I propose that for now we just show all cash boxes that exist with the project name next to the box - if hospital's become overwhelmed with multiple projects and cash boxes we can look at changing this in the future. 

For example: 
* Cash Window (Hospital) 
* Primary Cash Box (Hospital) 
* Cash Window (Pharmacy)

**Comment by jniles** [comment]
This is a really bad bug.  In theory, if the hospital is not changing cashboxes all the time, showing all of them should be fine.  If they were doing it a lot, the risk of them picking the wrong one is a lot higher.
