### ISSUE TITLE
Make the client side default filters static 

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#1988]
In all our registry at the client side, we are defining filter object to manage filtering, so there is three major step which are : 

- Filter object creation
- Default filter registration on the filter
- Custom registration on the filter

Notice the default filter is always the same : 
exemple : 
```
[
    { key : 'period', label : 'TABLE.COLUMNS.PERIOD', valueFilter : 'translate' },
    { key : 'custom_period_start', label : 'PERIODS.START', comparitor: '>', valueFilter : 'date' },
    { key : 'custom_period_end', label : 'PERIODS.END', comparitor: '<', valueFilter : 'date' },
    { key : 'limit', label : 'FORM.LABELS.LIMIT' }]
```
So it is common for every filter instance, I propose to make it static so that we will not need to pass it every time we are creating a filter object.

Any thougth ?
@IMA-WorldHealth/bhima-core

**Comment by jniles** [comment]
I'm not sure what you mean by "static", but I think we could easily put them in `bhima.constants` or `bhima.services`.  That way we could simply extend the filter service with default filters when we need them.

Something like:
```js
// inject bhFilterConstants to get the default filters
var DEFAULT_FILTERS = bhFilterConstants.DEFAULT_FILTERS;

// register all or part of them.
filters.registerDefaultFilters(DEFAULT_FILTERS);
```

**Comment by DedrickEnc** [comment]
Yes, of course. 
By static I was talking about class property, the contrary can be the instance property.

**Comment by jniles** [comment]
Sounds good to me!

**Comment by DedrickEnc** [comment]
Some how tackled!
