### ISSUE TITLE
(proposal) make the stock modules depot selection the same as cash window 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#2003]
The cash window proposed a method for selecting a 'Cash Box' using a modal selection and including the name of the cash box in bold in the headercrumb ™️ . 

I propose that we use this same UX pattern for the stock modules. Anything to help users know exactly which depot they are currently in will be a benefit. It will also make all of BHIMA feel like the same product. 

I do not think this has to be state based like the cash window - I think the cash window should no longer be state based.

**Comment by jniles** [comment]
I'll take this over.
