### ISSUE TITLE
fix(entry transfer): modal of transfers must signals already used transfers

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2005]
This issue is about to have a good tool for importing transfer with more information about transfer : 
- Used transfers must have an indicator (new column `status`) which signals that it is already used
- Transfer document ID (ex. `DO.4400`)

![gridtransfer](https://user-images.githubusercontent.com/5445251/29465614-ce212f92-8431-11e7-809e-b01804d920c0.png)

**Comment by jniles** [comment]
@mbayopanda, what is the status of this issue?

**Comment by jniles** [comment]
@mbayopanda what is the status of this issue?
