### ISSUE TITLE
(bug) General Ledger module briefly shows "No data available" before loading

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2010]
The General Ledger module has a `bhGridLoadingIndicator` component on it that flashes "No Records Found" prior to loading.  This is likely because the loading state is asynchronously triggered.  We should update this module so that the loading indicator initializes immediately.

This can be seen on heavily metered connections.

**Comment by mbayopanda** [comment]
@jniles i cannot reproduce it.

**Comment by jniles** [comment]
It's probably out of date then :)
