### ISSUE TITLE
(refactor) Improvements to the Stock Entry from Purchase Order

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2015]
Here are some ideas to improve the Stock Entry modal when importing stock from a purchase order:
 1. Use the headercrumb class to reduce space in the modal header
 2. Add "Importing Stock" or a similar text to the modal header to give context
 3. Make the inventory item inputs into [form-control-static tags](https://getbootstrap.com/docs/3.3/css/#forms-controls-static) instead.  Since the user will never be able to edit these, let's just show it like a static display.  This will also reduce space.
 4. Use `aggregationHideLabel: true` on the colDefs to remove the untranslated footer text.
 5. Make sure validation messages appear ... I tried to submit with the expiration dates as the current date and nothing happened. It was confusing.
 6. You are allowed to add floats as quantity ... not sure if this is a good thing or not.
 7. Turn off all validation until the submit() method is called.

See below a screenshot:
![stockentryfrompurchaseordermodal](https://user-images.githubusercontent.com/896472/29484775-a478937e-84bd-11e7-80d3-268a12bab444.png)
_Fig 1: Stock Entry From Purchase Order_

This is related to #2000 .

**Comment by lomamech** [comment]
@jniles I have just done a quick check, several forms accept floats as quantity, I do not think it's a good thing
