### ISSUE TITLE
proposal: rename "Posting Journal" into "Journal"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2031]
Since we have deprecated the "Posted Journal" and moved it's view into a filter on the regular "Posting Journal", I think it might reduce a lot of confusion by renaming the "Posting Journal" to the "Journal".  It will be easier to refer to, and more semantically correct since we now allow viewing of posted records in the journal.

References work done in [refactor-journal-tools](https://github.com/IMA-WorldHealth/bhima-2.X/tree/refactor-journal-tools).

\cc @IMA-WorldHealth/bhima-core what do you all think?

**Comment by sfount** [comment]
Note that this is related to https://github.com/IMA-WorldHealth/bhima-2.X/issues/1432 and is similar to the proposal https://github.com/IMA-WorldHealth/bhima-2.X/issues/1241. 

I agree with this decision.
