### ISSUE TITLE
feature request: cashbox create should default to user's current project

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2034]
The Cashboxes management module should automatically propose to the user that the cashbox will be created in their current project, instead of relying on the user to select the correct project from the dropdown menu.  If the user would look to change the cashbox, they can open up the select menu and choose a new one.

![selectcashboxoncreate](https://user-images.githubusercontent.com/896472/29570149-800d7eae-874d-11e7-8a0f-ba9cd1f3ad03.png)
_Fig 1: Select Cashbox on Create_

**Comment by jeremielodi** [comment]
closes #2034

**Comment by jniles** [comment]
It looks like this isn't fixed yet - there are some failing tests on https://github.com/IMA-WorldHealth/bhima-2.X/pull/2088 unrelated to the bug reported in https://github.com/IMA-WorldHealth/bhima-2.X/issues/2094.

**Comment by jeremielodi** [comment]
okay

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2088.
