### ISSUE TITLE
bug(stock): Bugs in Stock Origins

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2038]
~~Three slight improvements to the Stock Origins Registry:~~
 1. ~~The Stock Origins Registry Search doesn't seem to work.~~
 2. ~~The group header in the registry displays "Actions", but will not be able to give an origin/entry document. This should be removed.~~
 3. ~~When no data is available, the page looks broken - there is no loading indicator or "No data available" sign.~~

EDIT: Superseded by deprecation notice https://github.com/IMA-WorldHealth/bhima-2.X/issues/1850.

**Comment by DedrickEnc** [comment]
@jniles 
I referenced this issue some days ago #1850 up to me this feature can be removed because it has information which can be found easily in other registries.

**Comment by jniles** [comment]
Aha, okay.  Then let's remove it.
