### ISSUE TITLE
Financial Writing for stock entry confirmation

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#2042]
Our Stock module is getting ready little by little so I propose the first financial writing about stock.
Wen the stock is entered in the depot two things should happen as a transaction : 
- The stock level should increase 
- The stock account should increase also
We should make those two operations unique and transactionnal.
@IMA-WorldHealth/bhima-core 
Any thought?

**Comment by mbayopanda** [comment]
The question is, the stock is come from which entities : depot, purchase , integration, donation, adjustment ?

- If the stock come from **another depot**, which is just a transfer so i think the value of stock account must not be increased 

- If the stock come from a purchase, the stock level increase and the value of stock account increase also with the **cost of purchase** (purchase price + other charge) as value

- If the stock come from an integration, the stock level increase and the value of stock account increase also

- If the stock come from a donation, the stock level increase and the value of stock account increase also

**Comment by DedrickEnc** [comment]
tacked
