### ISSUE TITLE
(proposal) Deleting financial entities

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#2044]
The corner case of allowing a user to completely remove a financial transaction by removing all its rows during an editing session has recently been patched in the work on refactoring the journal tools #2006.

The method of deletion was not designed and didn't factor in many complexities to removing a transaction:
* What happens to transactions that either reference or are referenced by this transaction?
* What happens to the underlying financial document that BHIMA creates (invoice, cash payment, voucher etc.)

I propose that we allow and implement deleting of financial entities from a Transaction (journal writing) perspective. 

**Proposed API:**
`HTTP DELETE` `/transactions/:uuid`

Because all invoices, cash payments and vouchers share the same UUID with journal writings, the entity's UUID can be directly used from the respective modules - the journal will have direct access to the record UUID. This will allow: 
`HTTP DELETE` `transactions/{{invoiceUuid}}`
`HTTP DELETE` `transactions/{{cashPaymentUuid}}`
`HTTP DELETE` `transactions/{{voucherUuid}}`

Each entity will provide its own helper method for safely being removed as each may involve different steps - these will be connected using the `identifiers.js` map. 

1. Determine entity type from transaction id (record_uuid) (for example `IV.HSP.10`) 
2. Queue BHIMA entity deletion from identifier map (`IV` -> `safelyDeleteInvoice(invoiceUuid)`)
3. Check for transactions referencing this transaction and transactions being referenced 
4. Queue transaction deletion from the posting journal 
5. Execute transaction - report to client on any issues returned by safely removing the entity or by removing the posting journal

**Rules:**
1. If a transaction has been posted (moved to the general ledger), entity deletion will not be allowed
2. If a transaction is referenced by other transactions, entity deletion will not be allowed 
3. If a transaction references additional transactions, those entities may require updating (depending on the document type)

**Safely removing entity methods**
`safelyDeleteInvoice(uuid)`
* delete invoice items 
* delete invoice 

`safelyDeleteCashPayment(uuid)`
* delete cash payment items 
* delete cash payment

`safelyRemoveVoucher(uuid)`

**Update entity methods**
If a transaction (for example a credit note) is delete and refers to another transaction (an invoice), the referred to entity should be updated indicating that it is no longer reversed. 

We will need a reliable method of confirming that it was this credit note that reversed the invoice - the flag can be updated in this case. 

@IMA-WorldHealth/bhima-core What do you think? This feature should be supported to reduce the number of noise in creating reversals for just badly created entities. Allowing the user to delete mistakes will help keep real reversals clear.

**Comment by jniles** [comment]
I think this is a really good feature to have.  It would reduce the number of extraneous/erroneous transactions we generate trying to clean up past mistakes.  It also has the advantage of treating everything as a transaction instead of individual preference for Cash Payments, Invoices, and Vouchers. :+1:

The logic you have described looks sound - the may be some hidden corner cases, but it will take a prototype implementation to find them.

**Comment by jniles** [comment]
I wonder if we should make aggressive deletion an option to toggle.  One could imagine adding a column indicating `deleted` onto the three tables and then simply toggle it to `1` when an entity is deleted.   It would behave like the entity was deleted by filtering the view on it.  The Posting Journal transaction would be deleted of course.

The downsides are:
 - Every SQL query would have to filter out the `deleted` flag.  This can get very hairy when you think of the number of SQL queries that hit these tables. 
 - Takes up space ... which is one of the primary motivators of this issue.

The upsides ares:
 - We retain a full log of what was deleted.
 - Gives the enterprise better control over the application.

The "aggressive delete" option might be an enterprise setting, where they can opt to aggressively delete by removing the record completely or opt to passively delete by simply switching a flag.  On the client-side the result would be the same, save the tiny amount of processing it would to filter on more records.

**Comment by jniles** [comment]
Closed in #2188.
