### ISSUE TITLE
(proposal) Journal transaction editing history

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#2046]
We currently have no way of differentiating transactions that have been edited and transactions that were directly written by the system. 

If an accountant or developer is trying to audit the system to find out where something has gone wrong it would be very useful to know if something has been changed to know where to look for the issue. 

I propose we introduce a new table `transaction_history` that we will write in every time an editing session is successfully run on a transaction. 

The columns would be 
* uuid 
* transaction_uuid
* timestamp 
* user_id 
* (optional) Operations ['EDITING', 'DELETING', 'ADDING']

Whilst this doesn't give us a history of the full transaction it will be a good first step towards answering questions: 

Has a transaction been edited? 
```sql
SELECT COUNT(uuid) as numberOfEdits FROM transaction_history WHERE transaction_uuid = ?
```

Who has edited a specific transaction? 
```sql
SELECT user_id, timestamp FROM transaction_histroy JOIN user ON user_id = user.id WHERE transaction_uuid = ?
```

**Comment by jniles** [comment]
To clarify, `transaction_uuid` should be `record_uuid`, correct?

This proposal LGTM.  Just knowing if a transaction has been messed with can inform us what next questions to ask.

**Comment by jniles** [comment]
Note - this is tangentially related to https://github.com/IMA-WorldHealth/bhima-2.X/issues/1559

**Comment by jniles** [comment]
I'll tackle this one.

The optional fields don't make much sense to me - this kind of resolution needs to be available on a line-by-line basis, not a transaction basis.

The only update I'll make is renaming `transaction_uuid` -> `record_uuid` since that is the column name found in the `posting_journal` and `general_ledger`.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2156.
