### ISSUE TITLE
(proposal) Underlying `EDITED` flag on financial entities 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#2047]
Currently there is no way of knowing if a BHIMA document has had its underlying transaction edited or changed during the posting process. There currently is not a use case for this however it may be useful to show on an invoice that the financial details of this document may have changed. 

I propose that when an editing session is complete on a transaction it then uses the `identifiers.js` map to lookup the reference table and set an `EDITED` flag to `TRUE` .

The `EDITED` flag would be added to: 
* invoices
* cash payments 
* vouchers

For example: 
```js
const transactionIdentifier = 'IV';
const documentTable = Identifiers[transactionIdentifier].table;

const sql = `UPDATE ${documentTable} SET edited = TRUE WHERE uuid = ?`;
db.exec(sql, transactionUuid)
  //...
```

**Comment by jniles** [comment]
I'll take this one.
