### ISSUE TITLE
Patient Registration 2.x Review

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#205]
Patient registration has been updated to the 2.x build using the latest technology stack; this is an issue to track the review/ refactor process through completion (`PRODUCTION READY`)
### Form Validation
- [x] Refactor to use the latest form validation techniques; this includes ng-messages etc. 
### Testing
- [x] E2E tests updated to latest standard (Page objects etc.) 
- [x] Integration tests for `/patients` route uses latest standards
### Error Handling
- [x] Module displays errors globally (handles errors globally) 
- [x] `/patients` route throws meaningful errors to the latest standard 
### Server Side API
- [x] Binary UUIDs used for all relevant tables (`patients`, `debtors`)
- [x] Transactions are used anywhere with multiple writes 
### Code
- [x] Code is documented producing JSDoc page 
- [x] Service architecture is used to the latest standard (complete separation of concerns) 
- [x] Database is verified with tests to be strict on rejecting incorrect values
- [x] Dates are handled uniformly to the latest standards (+tested)

Any discussion relevant to patient registration can be commented below - anything that has been missed will be added into the issue. Once these things have been verified the module will be reviewed and marked as complete.

**Comment by jniles** [comment]
Two issues of interest before declaring this module done:
1. ~~The date input should be a datepicker.~~  DONE
2. The location inputs do not reload the enterprise's location, now that the page no longer navigates away.  This is a problem with the `bhLocationSelect` rather than the page itself, but must be resolved before shipping.

**Comment by jniles** [comment]
Also has some form validation issues, especially on the optional information.
