### ISSUE TITLE
Breaking up the procedure.sql file into small files

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#2051]
The ```procedure.sql``` is getting bigger and bigger now it has 1335 lines which is so huge and very tough to read.
I propose to break it up to small pieces and combine it during the build process

@IMA-WorldHealth/bhima-core 
Any thought?

**Comment by jniles** [comment]
I agree with this. We could make a new subfolder for `procedures`.  I imagine that we could break it up by function.  Such as:
 1. `trialbalance.sql`
 2. `cash.sql`
 3. `voucher.sql`
... etc.

**Comment by ghost** [comment]
So if I understand this correctly you want sh/init-db.sh, sh/build-database.sh and sh/build-development-database.sh to concatenate some new SQL files in server/models/procedures/, which will result in the large procedure.sql ready to be processed.
Does this sounds right? And should server/models/procedure.sql be added to .gitignore now?

**Comment by jniles** [comment]
Hey @jambroo!  Welcome back :smile: 

That isn't quite right.  To clarify, the file `server/models/procedures.sql` is currently ~1500 lines.  Most procedures are limited to a certain operation.  This issue asks that those operations be grouped together in a file apart from all other stored procedures.

Below, I'll give a deep-dive example for Cash Payments.  It should give you a (brief) overview of how the cash payment process works.  This is not required to implement the issue - the important part is understanding what stored procedures are used to be grouped together.

For example, the way we create a cash payment, it writes a record into the `cash` table.  Then, it is immediately copied into the `posting_journal` by calling the following stored procedures.  [The process starts on cash.create.js#L131](https://github.com/IMA-WorldHealth/bhima-2.X/blob/e3487aa5084d74aef92a47abbf1dbf31e058ef10/server/controllers/finance/cash.create.js#L131).

The order of operations is:
 1. `CALL StageCash()` - this copies all the information out of JS into SQL for faster processing.  Only concerns the `cash` table.
 2. `CALL StageCashItem()` - same as 1) but for the `cash_item` table.
 3. `CALL CalculateCashInvoiceBalances()` - make sure we have the balances of paid invoices at hand.  This is necessary later.  We allow a patient to pay a fixed amount for multiple invoices.  Our algorithm for posting cash payments in `PostCash()` will use these balances to determine how much money to allocate to each invoice being paid.
 4. `CALL WriteCash()` - writes the payment to the `cash` table.
 5. `CALL WriteCashItems()` - writes into the `cash_item`s table.
 6. `CALL PostCash()` - writes the correct transaction into the `posting_journal` based off all the previous calculations.

All of this takes place in lines 131 - lines 145 of [cash.create.js](https://github.com/IMA-WorldHealth/bhima-2.X/blob/e3487aa5084d74aef92a47abbf1dbf31e058ef10/server/controllers/finance/cash.create.js#L131).  From this analysis, this issue asks that we create a separate file called `procedures/cash.sql` and put in it the definition of `StageCash`, `StageCashItem`, `CalculateCashInvoiceBalances`, `WriteCash`, `WriteCashItems`, and `PostCash`.

This can be done for every stored procedure - looking at its usage and then putting it in its own file.

**Comment by ghost** [comment]
Thanks a lot for the cash payments overview @jniles. I should have some time early next week to look into creating these separate files in the new procedures dir.

**Comment by ghost** [comment]
Hi @jniles, so if I understand correctly you want this StageCash function called in the link you provided in cash.create.js to still run "CALL StageCash(?)", however you would like this to be defined in procedures/cash.sql instead of in procedures.sql
https://github.com/IMA-WorldHealth/bhima-2.X/compare/master...jambroo:refactor-break-up-procedure-sql?expand=1#diff-ca0cf2916327156108015bdc3c07d059

Also, did you want to use something like "SOURCE procedures/cash.sql" in original SQL?

**Comment by jniles** [comment]
Hi @jambroo.  Yes, that is correct - the JS shouldn't really be changed, it's only breaking out those procedures into their own files.  It looks like you are off to a good start!

Oh, I had thought about concatenating the files together in a build script (like `sh/build-database.sh`), but your `SOURCE` idea is much better.  That sounds really good :+1:

**Comment by jniles** [comment]
Closed in #2142.
