### ISSUE TITLE
(refactor) Editing transaction dates

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#2052]
Currently during transaction editing, dates can be changed for every row in the transaction directly. However this does not have any effect on the period_id or fiscal_year_id that are also included in transaction information. This will definitely cause upstream logic to fail as it assumes that dates and period assignments are well formed. 

It is necessary to update the period_id and fiscal_year_id appropriately when changing the date, this should be done on the server (similarly to how debit and credit equivalents are updated) so that any contextual information can be used to block inappropriate dates from being accepted.

**Comment by jniles** [comment]
If #2045 lands, this will be much easier.
