### ISSUE TITLE
(design) Super User Editing (of Posted Records)

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2056]
We have been requested to implement a feature to edit posted records.  This should ease the use of BHIMA from an "all or nothing" approach and allow users full control over their financing.  However, it is not recommended best practice.

**Unposting Transactions**
The core of this feature is to simply unpost a transaction and then use the existing tools to edit it.  The unposting procedure will do the following:
 1. Move the transaction from the `general_ledger` to the `posting_journal`.
 2. Recompute Period Totals for the entire fiscal year affected to ensure they are up to date.  Technically, you might be able to only recompute the ending balances and the period(s) affected, but it may be difficult to get right the first time.  Better safe than sorry.

**Permissions**
The most difficult part of this operation is the permissions to allow a user to unpost records.  We do not have a good permissions model (#170) to selectively allow certain users that privilege.  I propose, therefore, we have the "unpost" operation behind a predefined password, set as a constant on the server, pending a better way of certifying the user's role.

@IMA-WorldHealth/bhima-core what have I forgotten?

**Comment by lomamech** [comment]
@jniles Before implementing this functionality that I will like to ask myself this one, what can make an accountant can be forced to want to modify the General Ledger, I really fear that this functionality can facilitate the Fraud , Misappropriation of money, an ill-intentioned accountant to really use it to manipulate financial data as he sees fit,

**Comment by jniles** [comment]
@lomamech, that is a good question.

Fundamentally, we won't be able to prevent users from creating fake transactions or removing real ones.  They can already do that with our Credit Note and Journal Voucher tools.  What they cannot do is correct mistakes that they have already posted to the GL.

If we implement @sfount's proposal to keep an "edit" history (https://github.com/IMA-WorldHealth/bhima-2.X/issues/2046), this will help us directly catch fraud.  We'll be able to show exactly when the accountants unposted data, manipulated it, and produced numbers that came from nowhere.

The reality is that lots of mistakes were made in 1. x and 2.x - this would be an experiment to see if "unposting", as requested by both HEV and @WayneNiles, will be a sufficient solution to avoid this problem.

**Comment by jniles** [comment]
We have the ability to correct and reverse transactions easily.  The issue is now moot.
