### ISSUE TITLE
bug: Payments Registry "Exclude Reversed Payments" doesn't work

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2059]
On the Cash Payments Registry, the "reversed" search parameter can either be:
 1. Include uniquely reversed records.
 2. Exclude all reversed records.

While (1) works perfectly, the (2) option doesn't seem to register at all.  This should be fixed as soon as possible since it is helpful to remove records that have been reversed from the analysis.  This bug does not  affect the Patient Invoice Registry.

**Comment by DedrickEnc** [comment]
Thanks to see it, I will have a look
