### ISSUE TITLE
The lots origin registry is removed

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2082]
The lots origin registry is removed, this issue is about to know the reason of that.

The lots origin registry is important for to knowing for existing lots in the stock where they come from : 
- Purchase order 
- Integration

**Comment by jniles** [comment]
Can this information not be made available on the Movements Registry?

**Comment by jniles** [comment]
@mbayopanda, what is the status of this issue?

**Comment by mbayopanda** [comment]
This issue can be closed now because it is not relevant now, and so that we can focus on the enhancement of other stock modules and registries.
