### ISSUE TITLE
chore: migrate `modules/` from $translate filter to $translate directive

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2100]
This issue has been discussed many times before, however, we are nearing the end of this task.  A quick scan of the `modules/` directory shows:
```sh
$ grep -r "| translate" | wc -l
380
```

This means we only have 380 lines left to change in the modules directory!  Someone could easily go through and clean all these references up.

**Comment by jeremielodi** [comment]
closed in #2155
