### ISSUE TITLE
refactor: make sure all "actions" links have a caret 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2123]
We have two types behavior for links in BHIMA.
 1. Navigate the page to some other location (such as filtering a registry on a value or opening a modal/tab with a receipt).
 2. Open a drop down menu to perform an action.

Most of the (2) links are labeled "actions", but not all of them have a caret ( :arrow_down_small: ) that informs the user what will happen after they click it.  Two examples are shown below:

![niceactionslinks](https://user-images.githubusercontent.com/896472/30740948-e958b680-9f8a-11e7-8f0a-4e5913a046ff.png)
_Fig 1: Nice Actions Links with Carets_

![badactionslinks](https://user-images.githubusercontent.com/896472/30740954-ee93bed8-9f8a-11e7-9df2-4fde5324cef6.png)
_Fig 2: Bad Actions Links without Carets_

It is a small change, but very helpful for usability.  Someone should go through the entire application and make sure that every dropdown has a `<span class="caret"></span>` on it.

**Comment by jeremielodi** [comment]
closed in #2135

**Comment by jniles** [comment]
#2135 wasn't merged into master.  You closed it.  So, this issue is still open - as far as I'm aware, nothing has changed.
