### ISSUE TITLE
Reset default filters from filter links

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2129]
We have a slight problem with our filter links; the ones that link between registries and into registries.  If the user has set a specific query - such as a patient uuid - but the user has not set their default limits to a reasonable range, the query return no results.  This can be confusing.

I propose that we always reset the default filters when the user clicks a link into registries.  This can be accomplished by passing multiple filters through `$state` parameters - as proposed in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1935.  In this fashion, we should be able to add in the default filter keys (`limit`, `account_id`, `period`, etc) to ensure that the query is answered correctly.

**Comment by DedrickEnc** [comment]
@jniles
But this limit value will still stored and will impact the destination registry.
When the user will access this registry, the limit will be the previous set limit. (Sorry for the english)

**Comment by jniles** [comment]
Unless we don't cache it!  Which might a reasonable thing, since we expect links to not be user searches.

**Comment by jniles** [comment]
Okay, we've had a lot of confusion in training due to this.  Most users want to see all the invoices tied to a patient for all time, instead of with their old filter query applied.

I'll work on this over the next two days.

**Comment by jniles** [comment]
This got closed at some point ... I'm not sure when.
