### ISSUE TITLE
refactor: make all links use a human-readable name

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2130]
Many of our links between modules/registries do not show human-readable strings in the filter bar.  An example is shown below:
![nonhumanreadablelinkstart](https://user-images.githubusercontent.com/896472/30800449-ecb3ed6e-a1d7-11e7-918d-4b1cb765e44d.png)
_Fig 1: Click this link to show all debtors_
![nonhumanreadablelink](https://user-images.githubusercontent.com/896472/30800448-eca55eb6-a1d7-11e7-855a-3d203cf7f3b4.png)
_Fig 2: The Debtor Group is unreadable!_

We have the tools to make sure that these are shown using [the `displayValue` property](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/FilterService.js#L60) in Filter Service.  This can be set by the sending module as the filters are passed through `$state` parameters.  By implementing this, it would significantly increase the usability of the registry system.

**Comment by lomamech** [comment]
I want to close both issues at the same time

**Comment by jniles** [comment]
@lomamech, no problem.  Close whichever one you feel is best.

**Comment by jniles** [comment]
Closed in a series of PRs: #2186, #2184, #2182, #2170, #2178.
