### ISSUE TITLE
(feature request) Merge Patient Records

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2138]
We discussed a simple duplicate patient detector in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1578, but this feature alone does little good - we need some way to fix records that are duplicated.  I propose that we implement a "Merge Patient" function, available in the Patient Registry.

There will be three components to this:
 1. A Stored Procedure called `MergePatient()` that will take two patient uuids and make them into the same entity.
 2. A dropdown on the Patient Registry that allows users to click "Merge Patients" when two patients are selected.  This means the Patient Registry must have selection enabled.
 3. A modal that will display the two patients to be merged and the end result of the merge.  The basic information should shown by default for each patient (name, date of birth, origin location, etc), with the option to expand and show all relevant patient fields.

The patients will be compared side-by-side in the modal before asking to submit.

_Graphical Design to Follow_

**Comment by mbayopanda** [comment]
How can we handle financial activities of those duplicated patients ?

**Comment by jniles** [comment]
Just merge the `debtor_uuid`s.  The financial history should stay intact.

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
Looks like this got merged in https://github.com/IMA-WorldHealth/bhima/pull/3751.
