### ISSUE TITLE
Troubleshoot ID Display Problems in Some Filters

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2139]
We note that with several filters and for some registers, the filter directly displays a very long UUID or an ID that are generally incomprehesive for a user

![image](https://user-images.githubusercontent.com/8035588/30814740-53f38dfc-a211-11e7-9ea8-ec3c46cbdf7b.png)

**Comment by jniles** [comment]
This is related to https://github.com/IMA-WorldHealth/bhima-2.X/issues/2130. :+1:

This is an excellent thing to work on!

**Comment by jniles** [comment]
Closed in a series of PRs: #2186, #2184, #2182, #2170, #2178.
