### ISSUE TITLE
Disabled Editing Account Types after Account Creation

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2149]
Our account management module lets a user edit and change the account type whenever they desire.  From an accounting standpoint, this does not make any sense.  If an account has been operating as income and expense for several months, it cannot be suddenly changed to a balance account.  We should remove the ability to edit the account type (with `form-static` class) from the account management page.

**Comment by DedrickEnc** [comment]
@jniles
Are you sure this is a good solution? So what will happen if an account was registered with mistake and the account type must be changed?
These kind of mistakes are frequent at the field.

**Comment by jniles** [comment]
It would be much better for them to lock and forget about the account than try to change it.  If you make a debtor account into an expense account, and then later into an asset account, it will completely confuse the reports at the end of the year.
