### ISSUE TITLE
Order the Patient Financial Activity report sensibly

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2150]
The Patient Financial Activity report is one of the core reports required to view the debts of the patients, their payments, and their running account balance.  Unfortunately, this report doesn't sort well by date.  You can see this below:

![patientfinancialactivity](https://user-images.githubusercontent.com/896472/30852582-29538622-a2a4-11e7-903b-0664dff680f8.png)
_Fig 1: Poorly ordered Patient Financial Activity Report_

In reality, all the invoices (`IV.HEV.*`) occurred before any voucher payments (`VO.HEV.*`).  Because these are not reflected in the report, it makes understanding the financial history very difficult.

This report should be re-looked at to make sure it can order sensibly by date.

**Comment by ghost** [comment]
Hi @jniles, could I get some more information on this report and how I could go about generating it locally. I think I need to generate a user in my local environment to be able to log in and generate it. Any tips on that? I can't see any user being made in the sql files in server/models/.

**Comment by jniles** [comment]
Hey @jambroo!  Glad to have you back!  No one has really taken the time to document all this (yay), so this is an excellent excuse to. :)

We've prepped some sample data that we generated a while ago called [build-developmental-database](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/sh/build-development-database.sh).  It's written in bash, but should run without _too_ much issue under git bash on Windows, if that is your developmental environment.

It pulls all its information out of the [.env.development](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/.env.development) file to figure out what the database should be and so forth.

Once that file is built, it can can be used to run trials of the application.  Our team is split into Linux and Windows devs and so we try to support both for development:
 
**Linux**
```sh
npm run dev
```

**Windows**
```cmd
npm run dev_windows
```

Now you should have a server up and listening on whatever port you put in your `.env` file - by default it is [8080](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/.env.development#L2).  Opening http://localhost:8080 in your browser will get you to the login page.

Note - we serve Africa so everything might be in French by default :D.  If so, you can change the language with the little caret in the top left corner of the login panel.  As shown below:
![loginpagelanguagechange](https://user-images.githubusercontent.com/896472/30957605-a501337a-a432-11e7-80f6-2b83f90c1000.png)
_Fig 1: Changing the Language on the Login Page_

The username will be **admin** and the password **admin**.  It will automatically reroute you to the landing page.  There should be a folder tree to the left side of the page.  If there is not, click the bar that says "Navigation" and it will appear.

The "Patient Financial Activity" report is found under "Hospital" > "Patient Registry".  The screenshot below shows it in detail.
![patientregistryintree](https://user-images.githubusercontent.com/896472/30957700-edc9991c-a432-11e7-8f55-ec2001391b0c.png)
_Fig 2: Patient Registry In Tree_

Clicking this link will take you to the Patient Registry.   You may get a page that says "No Records to Display".  It looks like this:
![patientregistrynorecordstodisplay](https://user-images.githubusercontent.com/896472/30957898-7143f04e-a433-11e7-9895-decc12ae3eb2.png)
_Fig 3: Patient Registry No Records to Display Message_

Don't panic!  This is normal.  We aggressively limit records downloaded to the last day since our target is low-end hardware.  There are two purple labels in the top left of the screen that show the data is limited to "today".  You can change the limit by clicking on the "Search" button.  A modal will appear:
![patientregistrysearchmodal](https://user-images.githubusercontent.com/896472/30959193-4c2ce726-a437-11e7-9dbc-773bb478c8e6.png)
_Fig 4: The Search Modal Form that appears after clicking the "Search" Button_

To change the limit of records displayed, click the tab that says "Default Filters" and afterwords "Select Limit".  This will give a series of options shown below:
![defaultfiltersalltime](https://user-images.githubusercontent.com/896472/30958254-71e62f98-a434-11e7-8337-d9f254e8aeae.png)
_Fig 5: Default Filters > All Time_

Finally, you can click submit and you should have a registry full of patients.  Below, I've reordered the page by the reference column and clicked the "Actions" link on the record of "Salvador Barker", who's reference is PA.HSP.1.  You can see that there are a variety of options in a dropdown, one of them is "View Financial Activity".
![viewfinancialactivityonslavadorbarker](https://user-images.githubusercontent.com/896472/30958483-399fa7c6-a435-11e7-8879-26e57f43625f.png)
_Fig 6: Salvador Barker's Actions Dropdown_

Clicking that will open a new tab with a PDF rendering his financial activity.  The PDF will have a link like this: ` http://localhost:8080/reports/finance/financialPatient/7f658e13-21a0-43ec-8b75-669964fcfe4b`.  If a PDF does not render, it likely means wkhtmltopdf is not installed or is having difficulty.

-----

So that is the _proper_ way to get to the financial activity report.  It is useful to try and get that far, just to make sure your development environment is behaving properly.  Once you get that far, I usually just copy the link and simply refresh the PDF report to see the changes.

Our tooling is really bad around developing on the server (see: https://github.com/IMA-WorldHealth/bhima-2.X/issues/365), so you'll have to restart the server manually to reflect the changes you've made.

---

As far as this issue goes, the Patient Financial Activity report template is [server/controllers/finance/reports/patient.financial.handlebars](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/controllers/finance/reports/financial.patient.handlebars) and written in handlebars.  The controller that templates in values is [server/controllers/finance/reports/patient.financial.js](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/controllers/finance/reports/financial.patient.js).

If any of the above steps don't work, or if my explanations were wonky, just chime back!  We've really appreciated the contributions so far and continued involvement is an excuse for me to make our project way more accessible to new contributors.

**Comment by ghost** [comment]
Thanks so much for the detailed guide @jniles. At this point I have set up the .env.developement file, however I get some errors when trying to run the build-development-database.sh file, which I can look into with a bit more detail over the next few days. Once I am up and running I will try to generate the PDF report like you explained :)

**Comment by jniles** [comment]
After some more exploration, I think this was an artifact of the dataset and not an actual ordering bug.  Closing until a better reproduction can be made.
