### ISSUE TITLE
Design: Deleting Invoices

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2160]
This issue covers the design for deleting Invoices using the proposal described in #2044.

**Design**
Deleting invoices will be performed from the Invoice Registry and the Posting Journal (via the transaction edit modal).  It is not allowed on posted records.  A deleted invoice will remove the lines from the `posting_journal`, `invoice`, `invoice_item`, `invoice_billing_service`, and `invoice_subsidy`.   It will also remove the `record_uuid` from the `document_map`.

There are some conditional rules on this operation:
 1. If the invoice has been posted, it cannot be deleted.  The only way to reverse a posted record is by using a reversing voucher.
 2. If the invoice has a referencing transaction, it cannot be deleted.  This is most likely a voucher that is reversing the invoice or a cash payment against the invoice.

The steps to implement this are:
 1. Create a routing function from `HTTP DELETE /transactions/:uuid` that will determine if the transaction is a cash payment, voucher, or invoice.
 3. Create the `safelyDeleteInvoice(uuid)` in the `finance/patientInvoice.js.` module.
 2. Write the SQL logic to determine if the invoice should be deleted as described in the above rules.

**Comment by DedrickEnc** [comment]
@jniles
Why not ```HTTP DELETE /invoices/:uuid``` as route?

**Comment by jniles** [comment]
It makes it much easier to write a single controller on the client.

**Comment by jniles** [comment]
Closed in #2188.
