### ISSUE TITLE
Consider using yarn/npm to replace bower

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2164]
When you run any newer version of bower, it asserts that you should try yarn or webpack for new project.  The commit which introduced it is https://github.com/bower/bower.github.io/commit/12566e5b777ef4c93c525cf3d2fa35ebc9f4d2e5.  Some people [consider yarn to be a viable replacement for bower](https://stackoverflow.com/questions/43562645/can-yarn-be-considered-a-viable-option-as-a-replacement-for-bower-and-npm).  Unfortunately, yarn officially removed bower support (https://github.com/yarnpkg/yarn/pull/1441), so it would be a little bit of work to combine them all together.

Still, it seems like bower is on its way out and we might consider `npm` or `yarn` as a viable alternative before we migrate to something extreme like webpack.

**Comment by DedrickEnc** [comment]
Aie... that too bad.

**Comment by jniles** [comment]
Note that bower is now [officially recommending yarn](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

**Comment by jniles** [comment]
Note: there is a module [bower-away](https://github.com/sheerun/bower-away) to automate a lot of this.
