### ISSUE TITLE
Remove Posting Journal and General Ledger from test/data.sql

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2168]
We have a few lines of the Posting Journal (e.g. https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/data.sql#L382) and the General Ledger (e.g. https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/data.sql#L461).  Let's get rid of these.  They break links between the Journal and each module that creates them.  It also makes the period totals behave strangely since not all transaction that happened are reflected in the ledgers.

Instead, we should do this - after every invoice, voucher, or cash payment is defined in the `test/data.sql`, we use `CALL PostMethod(uuid)` to post the value into the posting journal.  Then, we can use `PostToGeneralLedger()` to post the transactions that we wish to the General Ledger.  In this way, all tables will be in sync.

**Comment by DedrickEnc** [comment]
I agree completely
