### ISSUE TITLE
There is no possibility to delete inventory

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2172]
In bhima there is no possibility to delete an inventory we can just update it.

If we must add an option to import inventory from `csv` file for example, it will be necessary to have a way of deleting inventories (In the case we have imported bad inventories).

**Comment by jniles** [comment]
Note that we will need to make sure that these inventory items are not used elsewhere.

We should make a separate issue to track importing inventory items from CSV.  We should also support important a chart of accounts from CSV as well.

**Comment by jniles** [comment]
Closed in #2381
