### ISSUE TITLE
Patient Update - 2.x Review

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#219]
This issue tracks the current state of the patient update 2.x review - once the issue has been completed it can be submitted for `PRODUCTION READY` review. 
(Detailed progress is represented visually [here](https://docs.google.com/spreadsheets/d/1sAEIbcAY2x-EVPCTKmMacn5LL3mtw9x7GM0P-eyJxjs/edit?usp=sharing))
### Essential updates
- [x] Resolve bug introduced into `master` branch causing the patient update module to not load 
### Form
- [ ] Make use of ng-messages to provide form feedback 
- [ ] Latest form validation standards 
### Tests
- [ ] Implement end to end tests to cover editing patient groups, debtor groups and patient attributes.

**Comment by jniles** [comment]
Commenting to add:
- [x] Use ui-router to manage state (with selected patient and without)
