### ISSUE TITLE
Ratio Analysis Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2192]
Formally opening an issue about Ratio Analysis, something we've discussed previously, but is beginning to be possible as the application matures.  For example, the [nonmedical employees](https://github.com/IMA-WorldHealth/bhima-2.X/pull/2191) will allow us to do medical/non medical employee ratios.

**Ratios To Calculate**

> Taux Occupation de Lit
Calcul: journée réalisées / 365 / nombre des lits
Signification: l’usage d’investissement, l’acceptation par la communauté et une mesure des tarifs appropriés
Norme ou But: entre 60% et 90%

> Jours hospitalisés 
Calcul: Nombre de jours total que les malades restent à l'hôpital / hospitalisés
Signification: l’efficacité de soin et la sévérité de la maladie
Norme ou But: 8 à 10 jours

> Consultations / Jour
Calcul: nombre des consultations externes fait par jour
Signification: le niveau d’activité et l’acceptation par la communauté
Norme ou But: la population servit divisée par 1460

> Hospitalisé / jour
Calcul: nombre de malades hospitalisés par jour
Signification: le niveau d’activité et l’acceptation par la communauté
Norme ou But: 

> % Décès
Calcul: nombre de morts à l’hôpital divisé par le nombre de malades hospitalisés
Signification: l'efficacité de soin et la sévérité de la maladie
Norme ou But: Le plus bas possible, en général moins de 4 %

> Personnel Médical / Personnel Total
Calcul: les médecins, infirmiers et aide-soignants divisé par l’effectif total
Signification: le potentiel pour les soins de qualité 
Norme ou But: entre 50% et 60%

Relevant Issues:
 1. Medical/Nonmedical Employees -  https://github.com/IMA-WorldHealth/bhima-2.X/issues/1630
 2. Deceased Patients - https://github.com/IMA-WorldHealth/bhima-2.X/issues/1629

**Comment by jniles** [comment]
@lomamech, can you look into this once you are done with payroll?

**Comment by lomamech** [comment]
Hello Bhima team @jniles @sfount @mbayopanda @jeremielodi,
I found a way to solve this issue, most of these analysis ratios usually come from data collection, to solve this issue I will get inspired by ODK (Open Data Kit) for the design of the interfaces of the collects of the data and experiences I had with the work I did at the time with the Care2X system installed at Heal Africa Goma

**Comment by lomamech** [comment]
This issue was resolved by @mbayopanda

**Comment by lomamech** [comment]
closes #2192
