### ISSUE TITLE
Component Proposal: bh-unique-input

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#220]
This proposal is a design for a generic asynchronous validator that checks the existence of records on the server.
#### Motivation

There are many places where a dynamic, asynchronous check to the server may save the user some time while creating new records.  One current example in bhima-2.X is the [hospital number](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/partials/patients/registration/hospitalNumberInput.js) input validator, written by @sfount.  Telling the user that a unique field (in this case, the hospital number) is already used _before_ they submit the form is a great user experience.  Here are some other places this type of check would be useful:
1. Usernames
2. Inventory Codes
3. Account Numbers
4. Employee Codes

Because this type of check is useful in a number of places, we should abstract it into a single, tested validator.
#### Proposal: `bh-unique-input`

I propose we develop a component, `bhHttpValidator` that will perform the generic asynchronous validation to a target url.  The component's signature looks like this:

``` html
<bh-unique-input target="/some/route" model="Controller.model.value">
</bh-unique-input>
```

The component will validate an `<input>`s ng-model value via a GET HTTP request to the target URL as the user enters characters.  The target URL is responsible for returning a 200 response, with the following  JSON object:

``` js
{
  valid : true,  // or false, depending on the validation
  code : 'SOME.TRANSLATABLE.KEY'  // to be passed to $translate
}
```

In general the routes should be named with the property they are checking.  For example:
1. `/accounts/number/:number`
2. `/inventory/code/:code`
3. `/users/username/:value`

It will be the template's responsibility to provide the target URL as a string.
#### Behavior

Similar to the hospital number input, the component should use bootstrap's [feedback icons](http://getbootstrap.com/css/#forms-control-validation) to inform the user when the data is valid, invalid, or loading with appropriate icons.  If the data is invalid, the user should be informed via the translated `code` property sent back from the server, displayed in a help block.

What do you think @IMA-WorldHealth/local-contributors ?  I'm particularly interested in suggestions for a better name.

**Comment by sfount** [comment]
I can see many uses for this component - very clearly presented idea. 

Why not call it something to do with it's intended abstract purpose vs. it's technical description? Something along the lines of `bh-unique`.

**Comment by jniles** [comment]
`bh-unique` is a good start.  It should have some sort of "async" or "http" or something thrown in there, so that everyone is reminded that it will result in an asynchronous HTTP request.

`bh-unique-lookup`?  `bh-unique-input`?

**Comment by sfount** [comment]
Sure - that's much less ambiguous.  

I think it could be any of those suggestions - if anyone else has any thoughts that would decide it. 
`bh-unique-input` 
`bh-async-unique` 
`bh-async-input`

**Comment by sfount** [comment]
If it fits in with your development @jniles - I'll take this. It would get me up to date on the ever slightly changing component architecture.

**Comment by jniles** [comment]
Sounds good.  We'll select `bh-unique-input` (to remind devs it's an `<input>` element underneath the component) for the moment.  Updating the issue...

**Comment by jniles** [comment]
Sure!  It's not particularly high priority, but it would be a handy feature to have when we iterate over some of the admin modules again.

**Comment by jniles** [comment]
**Update**  Upon second thought, this component might be better written as a directive, which registers a unique `$error` on the form element's ng-model.  The signature would look like this:

``` html
<div class="form-group">
  <label class="control-label">Hospital Number</label>
  <!-- unique input -->
  <input type="number" name="model" ng-model="SomeCtrl.model.input" bh-unique="/some/url" required>

  <!-- validation bindings -->
  <div class="help-block" ng-messages="Form.model.$error" ng-show="Form.$submitted">                                                                                                                                                 
    <div ng-messages-include="partials/templates/messages.tmpl.html"></div>                                                                                                                                                                               
  </div>                           
</div>
```

The reasons behind this idea follow: 
1. Greater flexibility in styling the form.
2. The user would have to pass in the error text anyway - might as well leverage ng-messages instead!
3. Cleaner code - the directive would just modify the ng-model's `$asyncValidators` like the current hospital input.
