### ISSUE TITLE
bug(location editing): Cannot edit an enterprise location

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2213]
This issue is about an error which occurs when we try to edit the location of the enterprise.

![error-edit-location](https://user-images.githubusercontent.com/5445251/31713682-ec79f89e-b3f6-11e7-938a-5b16fa006cea.png)

**Comment by jniles** [comment]
To fix this, define the `name` on the component boundary to be `origin_location_id` or `current_location_id`.

**Comment by jniles** [comment]
Closed in #2250.
