### ISSUE TITLE
design(depot) : Add permissions to depot for entry/exit operations

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2218]
This issue is about to : 
- add permissions to depot for entry/exit operations by selecting needed operations in the depot management page

![depot-management](https://user-images.githubusercontent.com/5445251/31762346-d1b2756a-b4b2-11e7-90e7-c14297312f20.png)

We can add to depot table these columns : 
- allow_in_purchase : entry from a purchase order
- allow_in_integration : entry form an integration
- allow_in_donation : entry from a donation
- allow_in_transfer : entry from another depot
- allow_exit_debtor : exit to a debtor (patient, person, invidious)
- allow_exit_service : exit to a service
- allow_exit_depot : exit to other depot
- allow_exit_loss : exit as loss

**Comment by jniles** [comment]
I like it.  I would change the column names a bit: `out` is the opposite of `in` and `entry` is the opposite of `exit`.  So, this should either be `allow_entry_purchase` and `allow_exit_service` OR `allow_in_purchase` and `allow_out_service`.

I prefer the `entry`/`exit` style myself.  It fits with the rest of the application better.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2227
