### ISSUE TITLE
Turn on strictComponentBindingsEnabled()

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2223]
With the Angular 1.6.6. release, the option to turn on [strictComponentBindings](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#new-features) was added.  This means that if a component requires a parameter and it is not supplied, the application will break at runtime.   Using this option would enforce the component's API contract and ensure developers are properly using components the way the component designer intended.

We should experiment to see if we can get away with turning this option on.  It may be that our underlying libraries will break (e.g. ui-bootstrap).  Still, if possible, it would be one extra check to make sure developers are respecting the component APIs.

**Comment by DedrickEnc** [comment]
Let try and see

**Comment by jniles** [comment]
This will need us to update ui-grid first.  See #2285.
