### ISSUE TITLE
Use a real chart of accounts in test data

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2225]
I've run into a couple errors based on accounts not having the proper type.  For example, the cashbox account is currently a title account.  This makes testing difficult - tests fail not because the logic is incorrect, but because the data is improperly made.

We could improve our tests greatly by using an actual chart of accounts, such as the one in the development dataset.  This would allow us to reason about our tests in a much more profound way and avoid errors based on improperly created data.

[Motivated by this annoyance](https://github.com/IMA-WorldHealth/bhima-2.X/pull/2226#discussion_r145977608).

**Comment by DedrickEnc** [comment]
I had also this problem when testing cash report. I think the earliest this problem will be solve, better it will be because it will lead us to review almost the entire integration and end to end test.

**Comment by jniles** [comment]
I'm going to tackle this.
