### ISSUE TITLE
Proposal: Code Standards

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#223]
**Motivation**
With the recent styleguides and discussion around contributions, I propose that we adopt an official, immutable styleguide.  We will enforce this styleguide in our lint checks, and it will be equivalent to tests in terms of blocking/allowing pull requests.

**Proposal**
I propose we switch from the inflexible jshint to the much more flexible [ESLint](http://eslint.org/).  ESLint allows users to write custom plugins which makes it easy to encode a styleguide into the lint checks.

I propose we use [AirBnB's styleguide](https://github.com/airbnb/javascript).  The benefits I see are the following: 
1. modern - it is updated frequently and built with the future of javascript in mind
2. automatic lint checks - if we choose AirBnB's styleguide + eslint, we can automatically check that code is compliant with an [eslint plugin](https://www.npmjs.com/package/eslint-config-airbnb).
3. respected - [a lot of projects use it](https://github.com/airbnb/javascript#in-the-wild).

I think these standards will help settle a lot of discussions about code standards.

@IMA-WorldHealth/local-contributors, what do you think?  Are there any alternative proposals for styleguides?

Also of interest, [here is an ES6 compatibility table](https://kangax.github.io/compat-table/es6/).

**Comment by jniles** [comment]
This winter break seems like a really good time to roll out these standards.  Node 6 is the current LTS release with ES6 support, and our application is fairly stable.

There are a lot of cool rules that would help me write code better in ESLint!  [Here is the full list](http://eslint.org/docs/rules/).

I'll look into implementing this in the coming weeks.

**Comment by mbayopanda** [comment]
Thanks Jon

2016-12-16 12:47 GMT-08:00 Jonathan Niles <notifications@github.com>:

**Comment by jniles** [comment]
This wasn't actually supposed to be closed.  My mistake!
