### ISSUE TITLE
Standardize Text Sizes and Labels for Registry PDFs

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2231]
As you can see from https://github.com/IMA-WorldHealth/bhima-2.X/pull/2230, each registry will often have its own size of text and style of rendering.  To look professional, we should really have a uniform output.

I propose the following:
 1. All registries should be called "X Registry".
 2. No registry should have `table-striped`.  This will waste ink when printed, and is much more useful for screens.
 3. Every registry should use `table-report` to make the font size smaller.
 4. Every registry should include "Number of Xs" in the bottom left hand corner instead of the "Total" in the bottom right.

**Comment by jniles** [comment]
@jeremielodi, when you are done with https://github.com/IMA-WorldHealth/bhima-2.X/issues/2280, could you look into this one?

Basically, we want to standardize the way our registries look.  When you print a registry, it should look the same as every other registry.

**Comment by jeremielodi** [comment]
@jniles, tell me please, what do you call registry, is it the handlebars file we use for rendering report or some thing else

**Comment by jniles** [comment]
The handlebars file is correct.
