### ISSUE TITLE
Useful Form Input Validators (directives)

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#224]
This issue is a request for the following ng-model $validators:
1. `nonzero` - error if the input is `===` 0
2. `positive` - error if the input is `<` 0.
3. `integer` - error if the input is not an integer.

These $validators would register errors on the ng-model to be picked up by angular's form validation.  In general, they should be able to be added to any `<input>` easily like angular's native form directives.  For example, here is an input that will throw an error if a number is not an integer greater than zero.

``` html
<input type="number" name="integer" ng-model="FormCtrl.model.integer" bh-nonzero bh-postive bh-integer required>
```

Many of the forms I've built would benefit from stricter validation.  This would allow the developer to show (more) meaningful error messages.  For example, trying to do the above with `ng-min` would tell the user "this number is too small", instead of "this input cannot be zero".

**Comment by jniles** [comment]
@sfount, how many of these have been implemented so far?

**Comment by sfount** [comment]
Only bh-integer (bh-unique is discussed in another issue). The code for
doing simple validations like this is often one line so it should be
straight forward to use the same pattern.

**Comment by jniles** [comment]
Good to know.  Thanks!

**Comment by jniles** [comment]
Of note: `bhInteger` has been implemented.

**Comment by jniles** [comment]
Other validators can be accounted for via `ng-min` and such.  I am closing this issue as resolved.
