### ISSUE TITLE
Links in Stock Registries

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2257]
In the same way that invoices, cash payments, and vouchers are all tied around the concept of moving money, stock management is tied around the concept of moving around stock items.  In the financial registries, each registry links the others.

For stock management, we can do something similar.  Each registry should link (at minimum):
 1. The purchase order registry to show where that particular lot came from.
 2. The inventory registry to show what items each stock lot is.

It would also be nice to view:
 1. All the movements associated with a particular lot.

Finally, it would be nice to link various stock registries from the depot management page, in the same way that debtor groups link the patient registry page.

**Comment by mbayopanda** [comment]
For the point 1 related to purchase order registry, we have to know that not all lots come from purchase order, some come from : donation, integration or transfer from other depot. 
The solution can be create another registry for origins, or create registries for donation and integration

**Comment by jniles** [comment]
I don't think we should consider transfer from another depot to be an origin.  We should trace it all the way back to the stock entry itself - that will be the most likely question from an overall managers perspective.

We might be able to just hide the option to view the origin if it comes from an integration.  It may also encourage people to use the purchase processes instead of simply integrating stock.

**Comment by jniles** [comment]
Sounds like @mbayopanda is working on this.

**Comment by jniles** [comment]
I believe these are all closed now.
