### ISSUE TITLE
Clients Report debtor group selection broken

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2267]
The Clients Report seems to be broken.  When you attempt to select a debtor group a console error gets thrown, but no report is output.  See below:
![clientsreport](https://user-images.githubusercontent.com/896472/32216458-593ee81c-be25-11e7-9acc-394113995d8b.png)
_Fig 1: Broken Clients Report_

**Comment by jeremielodi** [comment]
Hi @jniles , is this still a problem? it works flawlessly for me.

**Comment by jniles** [comment]
Ah, no.  It was a bug in `ui-select` that we reverted to `v0.17.1`.
