### ISSUE TITLE
(refactor) Employee Management

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2279]
The employee management module was never completed, because there are no forms for updating employee information, this issue proposes to complete this module

**Comment by lomamech** [comment]
After resolving and adding the ability to update an employee's information, my finding is that updating an employee's information should impact a patient's of an employee, this duplication of information is not a good thing from a logical point of view, so I will close this issue and open another

#2282 for resolve this problem

**Comment by jniles** [comment]
Sounds like a good idea. :+1:
