### ISSUE TITLE
Rename "assignation_patient" to "patient_assignment"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2280]
In keeping with our practice of writing variables and tables in English, we should clean up the `assignation_patient` table and all references to it.  It should be spelled `patient_assignment`.

**Comment by jniles** [comment]
@jeremielodi, can you work on this?  This issue is just renaming the table which joins `patient` and `patient_group`.  You will have to do the following:
 1. Change all instances of `assignation_patient` to `patient_assignment`.
 2. Update the test dataset to make sure that, if we use `assignation_patient`, it is now changed to `patient_assignment`.
 3. Make sure tests still pass.
 4. Make sure comments still make sense.

Let me know if you have any questions!

**Comment by jeremielodi** [comment]
Okay, thanks

**Comment by jeremielodi** [comment]
I have renamed the table as expected, now tell  me where in the user interface I
can test to affect a patient to a specific group so that I could see if this link
works

**Comment by jniles** [comment]
Edit a patient and change their patient groups.  I think the end to end test should be enough though.

**Comment by jeremielodi** [comment]
Ok, it works, now tne e2e test

**Comment by jniles** [comment]
Closed in #2287
