### ISSUE TITLE
Allow users to specify landscape or portrait registry printing

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2294]
Our registries have been developed by different developers for different purposes and all have a different default set of configurations.  One configuration is the landscape/portrait mode of printing.  We should put this option in the hands of our users so that they can decide how they want their registries printed.

**Comment by jeremielodi** [comment]
@jniles , can you please specify by a picture or just steps so that we could see how you want it to look like?

**Comment by jeremielodi** [comment]
@jniles can you propose a design of how this should look like?

**Comment by jniles** [comment]
It should just be a radio button for now, until we get more options for report rendering.  Like this:

![example](https://user-images.githubusercontent.com/896472/37954760-ae0d8050-319e-11e8-906e-9a0e69a6f40b.PNG)

It probably should have the title "Page Orientation".
