### ISSUE TITLE
Sloppy Error on the Cashbox Currency Configuration Modal

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2337]
The Cashbox Management page allows a user to configure accounts used for the each currency associated with a cashbox.  The error handling on this page is really sloppy.  See below:
![sloppyerroroncashboxmodal](https://user-images.githubusercontent.com/896472/33603459-e03674cc-d9b2-11e7-8444-a82522c2f1c3.PNG)
_Fig 1: This error pushes the button out of the way_

This is a really sloppy way to handle errors.  It would be much better if the error appeared above the buttons at least, or maybe even in the modal body itself.  For example:

![bettererroroncashboxmodal](https://user-images.githubusercontent.com/896472/33603497-02dd75f2-d9b3-11e7-8101-58453a59c664.PNG)
_Fig 2: A better error positioning_

You don't have to implement the proposal above ... but it should avoid moving the buttons too much.  It's distracting when an error message suddenly replaces the button you clicked on!

**Comment by jeremielodi** [comment]
If the error message remains at the same place as it was before, the submit button will at any case move. I think @jniles proposal is much better.
