### ISSUE TITLE
The "Services" name is too close to "Services de Facturation"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2354]
While training a user, we noted that the Patient Invoicing page (translated "Facturation") requires a service.  This service is used for cost center analysis, allocating profits to the centers that bear profits as well as incur costs.  Unfortunately, if you wish to add a service, there are two options in the tree "Services" and "Service de Facturation".  Confusingly "Service de Facturation" is a _billing service_, but not the service that you should create.

I propose we rename "Billing Services" as another name to avoid this scenario.   Some proposals (english/french):
 1. Upcharges / Majoration
 2. Invoicing Fees / Frais de Facturation
 3. Administrative Fees / Frais Administratifs

**Comment by DedrickEnc** [comment]
I will take this one
