### ISSUE TITLE
(stock lot) Some inventory doesn't not need expiration date

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2378]
When we are defining lots for a stock, some inventory doesn't need expiration date but BHIMA obliges the user to enter a fake expiration date so that the lot be accepted.

**Comment by jniles** [comment]
Could we define this on the inventory group?  I can imagine the following options:
 1. Expires?  Yes / No
 2. Unique Item?  Yes / No (https://github.com/IMA-WorldHealth/bhima-2.X/issues/1065)

What do you think?

**Comment by jeremielodi** [comment]
okay @jniles, this way the problem can be solved

**Comment by jniles** [comment]
@jeremielodi, did this get solved?

**Comment by jeremielodi** [comment]
Yes, already
Le 10 janv. 2018 14:03, "Jonathan Niles" <notifications@github.com> a
écrit :

**Comment by jniles** [comment]
Thanks!
