### ISSUE TITLE
(stock) Handle correctly individual inventory state

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2379]
The current state of stock in `bhima` cannot handle individual inventory data such state of the inventory (good/broken)

**Comment by jniles** [comment]
Can we just add notes about the inventory item?  I imagine that we'll want more information than just "works/broken", like why it is broken.  Alternatively, some items may work, but not have the required materials to complete them (like a printer may be out of gas or a motorcycle out of gas).

What do you think?

**Comment by mbayopanda** [comment]
To have a note is good thing, i was wondering about if we need to search for example broken inventories.

**Comment by jeremielodi** [comment]
I think it will be a good idea if we add note and isBrocken columns,
