### ISSUE TITLE
(stock report) some information in header of report are missing

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2380]
Some report (stock integration) doesn't have **email** and **phone** data displayed.

**Comment by jniles** [comment]
This is enterprise data?  Or the user that created the movement?  Or contact information on the movement itself?

**Comment by mbayopanda** [comment]
email and phone data are not displayed

**Comment by mbayopanda** [comment]
I found the problem ! When we update enterprise information, we have to logout and login so that enterprise information can be visible to reports.
