### ISSUE TITLE
Update fiscal periods

### ISSUE THREAD

**Issue by jeremielodi** [third-culture-software/bhima#2397]
Yesterday I was studying the process for creating a fiscal Year, I notice That there are procedures that create a period for each month of the fiscal year, but when I tried to update the interval (start date -- end date)   the periods remained the same. Is this a problem? or I just misunderstood.

**Comment by jniles** [comment]
This is a bug.  Other details are https://github.com/IMA-WorldHealth/bhima-2.X/issues/2434.

**Comment by jniles** [comment]
Closed In https://github.com/IMA-WorldHealth/bhima-2.X/pull/2542
