### ISSUE TITLE
Improvements to Account Statement

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2408]
The following refinements need to be made to account statement:
 1. Use human-readable filters.   The "account" filter shows the account ID rather than the Account Number.
 2. The records need links.  The patients and references have links.  But the records are missing links.  See below:

![referenceneedslink](https://user-images.githubusercontent.com/896472/34034268-0b27125e-e17e-11e7-8bbd-47501a2d7c3e.PNG)
_Fig 1: I'd like a link, please_.

**Comment by jeremielodi** [comment]
I think this problem has already been solved
