### ISSUE TITLE
Viewing lots in stock should not depend on the Fiscal Year existing

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2482]
It would be helpful if we could divorce the stock registry from the financial data.  We recently ran into a case where we couldn't view the articles in stock because the fiscal year was not defined.  This is problematic, since viewing the data already registered should _not_ depend on the fiscal year.

**Comment by jeremielodi** [comment]
I think the soft option to solve this problem could be just displaying a more understandable message to the user so that they could fix the fiscal year problem. If we try to remove periods information from stock staff, we'll go out of the philosophy of this module.

**Comment by jniles** [comment]
I agree!  Sounds good!

**Comment by jniles** [comment]
@jeremielodi, did this ever get fixed?

**Comment by jniles** [comment]
I'm pretty sure this has been fixed.
