### ISSUE TITLE
Allow editing lots after stock entry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2489]
Lots are created on stock entry, but as we all have experienced, users make many mistakes.  Imagine a simple mistake to make - entering the wrong expiration date.  This will fundamentally affect the functioning of the stock modules and all other reports/alerts generated off of the database.

We need a (privileged) way to allow a user to edit a lot.  A lot is mostly just a lot number and an expiration date.  This should be regarded as a "super user" style action.

**Comment by jeremielodi** [comment]
This can be solved until #2461 will land,

**Comment by jniles** [comment]
What is the status of #2461?  I never heard back from you about it.
