### ISSUE TITLE
Proposal: Increase the size of the tree parent nodes

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#251]
Currently all nodes in the navigation tree are the same height; when the user has many modules this can be difficult to visually distinguish. 

Proposal: 
Increase the size of the tree parent nodes 

Example: 
![tree mockup](http://i.imgur.com/7GlcmAH.png)

Additionally we could close all other folder when opening a new one (only allowing one open at a time). I can't think of an immediate benefit of opening multiple folders at once.

**Comment by jniles** [comment]
This design of larger parents and smaller children looks good to me.  If we need to nest more than two levels, we'll have think on it a little bit more... of course, this could easily be handled by a single css query.

I'm a little hesitant about only allowing one tree branch open at a time.  The advantage of having multiple open is that nothing is hidden.  If we start hiding items, it might be slightly more inconvenient for users ... but we can subject that to A/B testing.  It should be a pretty easy switch to turn on and off!

**Comment by jniles** [comment]
@sfount, did you ever investigate this?  Does it work well in bhima or does it seem out of place?

**Comment by jniles** [comment]
Closing this as outdated.
