### ISSUE TITLE
(Testing) Use ng-describe to reduce boilerplate in unit tests

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#252]
Unit tests have recently been (will be) added in https://github.com/IMA-WorldHealth/bhima-2.X/pull/250. NgDescribe will allow us to remove a great deal of the unit test boilerplate. 
- [ ] Write full description of the benefits of ngDescribe.

**Comment by jniles** [comment]
Here's a [link](https://github.com/kensho/ng-describe) to the github site, and [some examples](https://github.com/kensho/ng-describe/blob/master/docs/examples.md).  It looks useful to me!

**Comment by jniles** [comment]
As we currently have several more unit tests, one (`SessionService`) that wraps critical application functionality, I think now a developer should look into this as an testing tool.  @sfount, what do you think?

**Comment by jniles** [comment]
@dedrickenc, these ideas might help you with #510.  If you want to investigate both at the same time, feel free!

**Comment by jniles** [comment]
Note - `ng-describe` doesn't look like it is maintained anymore.  We seem to be getting by fine with our current implementation.
