### ISSUE TITLE
Export Receipts/Reports as Excel

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2538]
We had a request for a stock receipt as an Excel document.  This probably isn't too hard to do, but will need some careful designing.  Ideally, the same format should be used for every single receipt/invoice in the system.  It will definitely make it easier to export data from BHIMA to use in other contexts.

**Comment by jniles** [comment]
This looks like a library worth investigating: https://github.com/dtjohnson/xlsx-populate

Demo: https://gitcdn.xyz/cdn/dtjohnson/xlsx-populate/32921c0b357828cf4c9065c60aa5ab9ad5aefd62/examples/browser/index.html

**Comment by jeremielodi** [comment]
I have discover this <a href='https://www.npmjs.com/package/excel4node'>excel4node</a>
I'm tring to use it
