### ISSUE TITLE
Design: Linking Cautions/Deposits to Patient Invoices

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#254]
##### Motivation

Both bhima-1.x and bhima-2.x calculate a patient's debt on individual invoices via queries of the posting journal and general ledger.  While general accounting is only concerned about the balance in a debtor's account, the application tries to align payments with specific invoices for a better user experience.  This way, the cash window will select a single invoice (or series of invoices) to pay and set up the links in the posting journal.

One major problem is that paying bills can happen in two forms:
1. Cash Payment - occurs after the invoice is made and directly links that invoice in the posting journal.  This was done via the `inv_po_uuid` column in bhima-1.x, and will now be done via the `reference_uuid` column in bhima-2.x.
2. Caution/Deposit - this operation _credits_ the patient's account before an invoice is created.

Because a patient can either pay against a prior invoice or a future one, it is difficult to link the payment to the patient's invoices uniformly.
##### Proposal

To solve this problem, I propose we implement the following algorithm:
1. When patient invoice is made, the patient invoice module will look up the balance on the patient's account.  It will do this by scanning the general ledger and posting journal for payments made by the patient in the past, against their account.  If the debtor has a credit balance, they have funds available to pay against the sale immediately.  This should be shown on the invoice page as an alert "This patient has a caution balance".
2. When the invoice is posted to the Posting Journal, the patient invoice controller, if the patient has a caution, the amount of the invoice covered by the caution is written on a separate line from the regular debit to the patient.  If the caution is covering the entire invoice, there will be only one debit line to the patient.  If there are multiple small cautions not covering the whole invoice, there will be multiple debit lines in the transaction.   The `reference_uuid` column will contain the journal or general ledger uuid of the caution payment.
3. Once the invoice transaction is written to the posting journal, the algorithm will attempt to link the previous caution payments to their lines in the patient invoice using the `reference_uuid` column.  The lines in the caution payments crediting the debtor's account will have the `reference_uuid` column filled in with the `record_uuid` of the invoice transaction.

At the end of this algorithm, the posting journal should be in the following state: a new patient invoice will have been written to with one or more lines debiting the debtor's account.  If there were no previous caution payments, there will only be one line debiting the debtor's account for the full cost of the sale.  If there were one or more previous caution payments, the patient invoice will have at least one line that directly links a previous payment's posting journal `record_uuid` in the `reference_uuid` column.  Each of those referenced caution payments will have the `record_uuid` of the patient invoice in their `reference_uuid` column, on the transaction line the credits the patient's account.
##### Example

How does this actually work?  Here's an example of a patient who made two cautions/deposits and a later invoice for part of the bill.  This is a "pseudo" posting journal, simplified to help demonstrate the idea.

For clarity, the `record_uuid` is the same thing as a transaction number.  The debtor is called `TPA1` and found in the `entity_uuid` column (like `deb_cred_uuid` in 1.x... we don't have to rename this column).

The patient makes Caution Payment T1.
![patient invoice balance algorithm 1](https://cloud.githubusercontent.com/assets/896472/14218489/64151a40-f84c-11e5-8ad7-5125cfed2bbc.png)

The patient makes a second Caution Payment T2
![patient invoice balance algorithm 2](https://cloud.githubusercontent.com/assets/896472/14218488/6412bd04-f84c-11e5-98d8-5fab256a7e2c.png)

**NOTE** The following two diagrams happen in the same _database transaction_ object, but are separated for clarity.

The patient invoiced for several services + medicines.

Step 1: The transaction is written, with links to previous cautions T1 & T2 in `reference_uuid`
![patient invoice balance algorithm 3](https://cloud.githubusercontent.com/assets/896472/14218487/640f470a-f84c-11e5-99a0-cc05b3985e59.png)

Step 2: The previous cautions T1 & T2 are located, and the `record_uuid` of the invoice transaction is written to the `reference_uuid` columns of the transactions.
![patient invoice balance algorithm 4](https://cloud.githubusercontent.com/assets/896472/14218486/640e6e02-f84c-11e5-9df5-fa3f3088a6cb.png)
##### Analysis

This is a powerful method for (soft) linking payments that could happen in either the future or the past.   The benefits are as follows:
1. Looking up the balance on a particular caution is very easy.  Just `SUM(debits - credits) as balance WHERE record_uuid = { caution_uuid } OR reference_uuid = { caution_uuid}`.
2. Looking up the cautions paid to a particular invoice is very easy.  Simply `SELECT reference_uuid WHERE entity_uuid = { debitor_uuid } AND reference_uuid IS NOT NULL;`.
3. Looking up the balance of an invoice is pretty easy.  Simply `SUM(debits - credits) as balance WHERE record_uuid = { invoice_uuid } OR reference_uuid = { invoice_uuid }`.

cc/ @IMA-WorldHealth/local-contributors

**Comment by sfount** [comment]
This looks like a well thought through process for soft linking sales and caution payments. My first thought is that while everything goes through the system (patient invoice is responsible for assigning the correct sale to the correct caution payment - through this algorithm) everything is fine; however if the head accountant tried for example to back pay an existing sale with multiple cautions or something like that it wouldn't be straight forward. I guess this could either be achieved by explaining the process in the manual or providing a tool to that (either a module or a filter/ view on the posting journal).

**Comment by sfount** [comment]
This links well with (and somewhat relies on) https://github.com/IMA-WorldHealth/bhima-2.X/issues/112. My recommendation is that we put together a small proposal of work and begin on the posting journal core as soon as possible. 

This will help drive and finalise [journal vouchers](https://github.com/IMA-WorldHealth/bhima-2.X/issues/207), invoices, cash payments, reports.

**Comment by jniles** [comment]
It shouldn't be too difficult to link cautions manually if necessary.  However, I do agree that it is potentially a confusing process to do.  If necessary, we can build tooling to link records this way.

**Comment by jniles** [comment]
One bug in this proposal on re-analysis -- there is no guarantee that a caution will be completely used up by an invoice.  That means, the caution cannot be linked to invoice during the final step.  What would happen if many invoices tried to use the same caution?  What would the caution reference?

**Comment by jniles** [comment]
This has been implemented for the most part.
