### ISSUE TITLE
Allow ReceiptModal to render HTML receipts as well as PDF

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2549]
One of the largest loads on our server (particularly the raspberry pi) is the rendering of PDFs using wkhtmltopdf.  We could eliminate or reduce a lot of this load by allowing the user to turn off the rendering of PDF reports on the client side using a user setting.

The basic idea is to set `Session.settings.receiptRenderer = 'html';` on the settings page as a yes/no option.  Then, instead of using `renderer='pdf'` for all receipt HTTP requests, we would use HTML and inject it into the receipt page.

There are also usability reasons for doing this - the PDFs render in really small format, and can be hard to read.  It may be easier for users to read an HTML receipt, where their browser can format the text, than the PDF one.

**Comment by sfount** [comment]
It looks like this was a duplicate of https://github.com/IMA-WorldHealth/bhima-2.X/issues/2876 and closed by https://github.com/IMA-WorldHealth/bhima-2.X/pull/2879

**Comment by jniles** [comment]
Correct!
