### ISSUE TITLE
Payroll Multiple 

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2558]
This issue proposes to redo the module Payroll Multiple of Bhima 1.X whose main interface is presented in the following way
![payroll1](https://user-images.githubusercontent.com/8035588/36533259-47f41e0e-17c3-11e8-867f-9de2a3d73593.png)

in the first version of Bhima it was question of selection the Period as well as the currency to be used for the payment of the employees

The Multiple Payroll module displayed a list of all employees who are not yet paid for the pay period select
![payroll2](https://user-images.githubusercontent.com/8035588/36533496-034d4f40-17c4-11e8-8071-8f375cba30ee.png)
![payroll3](https://user-images.githubusercontent.com/8035588/36533858-1fec9b78-17c5-11e8-9d50-acce3aee46f0.png)

By default all employees were considered as present, and for those who had periods of leave, their number of days of their attendance was deducted from the number of working days of their vacation period, the IPR tax was calculated automatically and the other items was either deducted or calculated automatically

**Comment by lomamech** [comment]
@jniles  @mbayopanda  @jeremielodi 

I proposed to use an ui-grid to list the list of patients, a drop box to define period as well as the currency to use for the payment of agents,

For the edition of the payroll headings a modal window, and for the payment of the employees I propose checkboxes allowing to select either all the employees or one by one,

I also propose to be able to update a status property which would allow to modify the elements of the payroll of an employee in case it will be validated by mistake (What was not possible in bhima 1.X)

**Comment by jniles** [comment]
@lomamech, this looks fine to me.  

> I also propose to be able to update a status property which would allow to modify the elements of the payroll of an employee in case it will be validated by mistake (What was not possible in bhima 1.X)

What do you mean by status?  Will the payroll take multiple steps?

**Comment by lomamech** [comment]
@jniles 
the status of a payment will allow to know:
1. if the employee the elements allowing the calculation of the payment of an agent are already registered
2. If the employee is waiting for payment
3. If the payment is effective

For an agent who is waiting for the payment one could modify in case of error the elements necessary for the calculation of his salary for example, the number of days of presence; transportation, family allowance ...
