### ISSUE TITLE
Embed exchange rate in the general_ledger

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2560]
We have not put the exchange rate in the General Ledger or Journal to date.  There reasons for this were:
 1. Save a tiny bit of space
 2. Make it easier to change an exchange rate without rewriting a ton of lines in the journal.

However, it would really help.  With our reports, we are currently needing to calculate rates for every single line using `GetExchangeRate()`, which is a costly function.  Perhaps just storing it is the best approach.

@mbayopanda @lomamech @jeremielodi What do you think?

**Comment by jeremielodi** [comment]
In general_ledger and journal we have these columns
- debit
- credit
- debit_equiv
- credit_equiv
if we assume that all of their values are correct, we calculate the currency this way:
Let take a case,
if the enterprise currecy is $ for instance, and the exchange rate is 1$ = 10Fc
A transaction in Fc can be represented like this in the journal 
<table>
<tr>
<th>debit</th><th>debit_equiv</th><th>currency</th>
</tr>
<tr>
<td>20</td><td>2</td><td>Fc</td>
</tr>
</table>
So the exchange can be calculated easily :
 <b>debit/debit_equiv</b>

**Comment by jniles** [comment]
@jeremielodi this is a good solution. Didn't think of it 👍
