### ISSUE TITLE
Home Page Exchange Rate sometimes shows incorrect date

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2562]
The exchange rate component on the main page sometimes shows the incorrect date.  It may also show the incorrect rate at times too. See the screenshot below:

![badexchangerate](https://user-images.githubusercontent.com/896472/36596816-4465f85e-18a7-11e8-889c-6297e1840505.PNG)
_Fig 1: Exchange Rate Date?_

This is likely due to a request which does not order the exchange rate values by date, but instead just queries them in the order they were written to the database.

**Comment by jeremielodi** [comment]
@jniles, was this problem solved? The exchange_rate  works very well for me

**Comment by jeremielodi** [comment]
Oh!, I have seen the problem when using vanga database
