### ISSUE TITLE
(Design) Core receipts feature 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#257]
Receipts were implemented in 1.x in a number of different ways and had two major iterations. This design/ proposal aims to take all lessons learned from that and propose a method of modelling and implementing receipts to meet 2.x's design values.

The two main problem this design aims to address are: 
- Never considering how a receipt can be optimally built - 1.x used the generic client side database query route `/data` and never considered how to optimally fetch and collect data. It also never considered how the data should be rendered, 2.x should consider PDF requirements from the outset. 
- Previously receipts have been build using one massive controller that takes care of defining and requiring relevant data, driving the view and handling any utilities that are required. 2.x requires features to be implemented in small, easy to test and well verified modules.

![board design](http://i.imgur.com/vsNgzuQr.jpg)
_Fig. 1 - White board design_

Figure 1 shows how each of the proposed elements fits together. In summary: 
- Server side controller is responsible for responding to the `/reports/invoices/:uuid` route. This collects all relevant data for an invoice receipt. 
- Controller imports `lib/renderers/json` to render the report - based on the options query string past from the client this could be passed to a json/html/pdf renderer. 
- Client side service `ReceiptsService` interacts with end point and passes the invoice (in this case) UUID.
- Client controller calls a modal instance that requests the invoice from the server and displays it above the current page (in this case patient invoice). The proposed method of submission progress is:
  - Submit (patient invoice) 
  - On confirmation clear form 
  - Open modal driven by `/reports/invoices/:uuid`
  - On modal exit page (invoices) can be used as if it had just been opened (reset)

I recommend this proposal is implemented for patient invoices to begin with, developing the tiny core files required to put together receipts. If anyone has any comments or suggestions for this feature they can be commented on this thread.

**Comment by jniles** [comment]
Closed in #325.
