### ISSUE TITLE
feat(stock) : import stock from csv file

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2571]
This issue is about to allow bhima to import stock data from other environment in csv format.

Here is a proposal : 

![import model](https://user-images.githubusercontent.com/5445251/36664380-ccfe6bee-1ae4-11e8-908c-b8dfa230d427.png)

We can add : 
- A link for downloading a template document for an import
- A link for uploading the filled template document as an import, this action will import inventories and the quantities as a stock integration.

The challenge will be to handle inventories and their groups and related accounts.

**Comment by jeremielodi** [comment]
@mbayopanda I think for this case we should use excel, it will be easy to separate each table in a worksheet(excel tab). I'm investigating for a way to load xlsx file in node

**Comment by mbayopanda** [comment]
@jeremielodi Excel is owned by Microsoft and if we don't have the software (`Excel`) we cannot import a stock (by uploading the Excel file), the good deal i think will be to use `CSV` in this way the user can use any text editor for writing the file to upload.

**Comment by jeremielodi** [comment]
Okay then

Sent from Mail for Windows 10

**Comment by jniles** [comment]
@mbayopanda, did this not get fixed?

**Comment by mbayopanda** [comment]
@jniles it is already done...
