### ISSUE TITLE
Account Statement Account Filter should set displayValue of account

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2576]
The Account Statement report shows the id of the account in the default filter instead of the account number/text.  See below:

![accountstatementaccountfiltershouldshowdisplayvalue](https://user-images.githubusercontent.com/896472/36784304-33b5e3b2-1c7f-11e8-8838-324b40a25b4d.PNG)

This should be fixed.

**Comment by jmuzsik** [comment]
Hi! 
I would like to begin contributing to this repo. I will fork it now, and if you can email me (jerrymuzsik@gmail.com) or point me to whichever issues you feel are most paramount, by all means do so as there are quite a few issues that are not touched.
Thanks very much

**Comment by jniles** [comment]
Hi @jMuzsik, welcome!  Thanks so much!

Unfortunately, getting up and running is sometimes a hurdle.  You can see the [installation guide](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/docs/INSTALL.md) and the [getting up and running](https://github.com/IMA-WorldHealth/bhima-2.X/wiki/Getting-Up-and-Running) wiki to help with that.  Once you have the installation to a point where you can log in, you are ready to roll!

Let me know if you have any questions or need any help!

**Comment by jeremielodi** [comment]
This works already correctly
