### ISSUE TITLE
Change `debitor` references to `debtor` in the database

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#261]
We are in the middle of a massive refactor of our database, including transitions to binary uuids and new table schemas.  I propose we take this opportunity to clean up poor naming conventions we adopted in the past.

Most importantly, `debitor` should be renamed `debtor` as well as all linked tables and columns.  The word `debitor` isn't proper English.  Might as well clean it up while we have the chance.

**Comment by jniles** [comment]
Today, I will submit a binary uuid PR (if all goes well) that moves all `uuid`s to being BINARY(16).  After that, I propose that @lomamech take a look at doing this migration while I continue on the journal core.  

@sfount, @lomamech  What do you think?

**Comment by sfount** [comment]
Approved; there are a number of database/server re-factors that could be grouped together.
