### ISSUE TITLE
Remove permissions from user management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2620]
We recently replaced individual module permissions with user roles.  However, the old links to permissions exist and no longer make sense to users who are used to the previous way of assigning a permission to each user.  See for example the workflow below that I tried:

![2018-03-27_09-40-46](https://user-images.githubusercontent.com/896472/37956342-fd884fbc-31a2-11e8-8351-c8693a8e34de.gif)
_Fig 1: Trying to create a user the old way_

There are a couple of problems with this:
 1. It gets the user into a really confusing state that they never could have gotten into previously.  We blocked users who didn't have permissions previously.
 2. It's unclear what the user did wrong.  What good are permission if there are no roles?

I propose that we remove the ability to set permissions per user completely.  We should also list the roles of the user in the user list.

**Comment by jniles** [comment]
Curious - the gif is cut short.  In short, the user can log in but there are no permissions visible in the tree.

**Comment by jeremielodi** [comment]
once #2629 will land, an unauthorized user cannot log in. permissions are now 'assigned roles'.
