### ISSUE TITLE
Role Management should subselect all permission of a parent node 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2621]
The Role Management module contains a tree of modules that a user should set permissions on.  However, the tree is not really usable.  If you wanted to make an accountant role with permissions to all the finance and reporting modules, you would need to click every single permission in the tree.

We can make this easier by allowing a user to click the top module of a tree to subselect all children in the tree.

Compare the two following user experiences:

**User Management Permissions Modal**
![2018-03-27_09-53-37](https://user-images.githubusercontent.com/896472/37957029-d5a182a0-31a4-11e8-91bb-2f42199f9fe9.gif)
_Fig 1: User Management Selection_

**Role Management Permission Modal**
![2018-03-27_09-49-55](https://user-images.githubusercontent.com/896472/37957060-eb351492-31a4-11e8-8b5b-c9b62498f34b.gif)
Fig 2: Role Management Selection_

**Proposed Solution**
I propose we use the same modal for both the user management and role management.  Probably the best way to do this is create a component for setting permission on individual modules.   It would be called `<bh-permissions-tree></bh-permissions-tree>` or something similar.  That way, we could write unit tests for it to unsure that the functionality is always preserved.

**Comment by jniles** [comment]
@jeremielodi, did this ever get solved?

**Comment by jeremielodi** [comment]
Yes

Le jeu. 7 juin 2018 15:13, Jonathan Niles <notifications@github.com> a
écrit :

**Comment by jniles** [comment]
Looks like this didn't get solved :(
