### ISSUE TITLE
(Feature Proposal) Badge/ Label Combo

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#263]
Bootstrap has two components for displaying small amount of information, [Labels](http://getbootstrap.com/components/#labels) and [Badges](http://getbootstrap.com/components/#badges).

I propose we develop a mixture of these two to show contextual information in the `headercrumb (tm)`

**The problem**
![Label problem](http://i.imgur.com/29Knvso.png)
A label works well and can be flexibly styled however because of how labels line text up it can look misaligned, especially when zoomed out. 

![Badge problem](http://i.imgur.com/cCtWYWJ.png)
Badges a perfectly aligned however they cannot be styled using primary, danger, success and are more intended to contain single digit numbers (very rounded corners) 

**Suggestion**
![Suggested component](http://i.imgur.com/LSK5eqg.png) 
This class would allow us to flexibly style like a label but have more appropriate positioning. 

![Additional Suggestion](http://i.imgur.com/BORBBJ5.png)
It could also be used to show the current state of a `headercrumb (tm)` module.

**Comment by jniles** [comment]
I like this proposal.  Having small badges for state would be really useful, and combined with `ui-router`, I can imagine really simply representing (logically) complex states to the client.

**Comment by imawh** [comment]
Not sure what the issue is.  I don't see poorly aligned text/numbers in the example.  Are badges oval and labels rectangles?  I like the idea of putting them in the headercrumb module.

**Comment by sfount** [comment]
Correct, badges are oval and labels are rounded rectangles. The issue is only clearly visible when you are zoomed out but the elements look misaligned (neither labels nor badges were designed for this purpose). 

Thanks for the feedback! (An example/proposal for how they could be used in the headercrumb can be seen [here](https://github.com/IMA-WorldHealth/bhima-2.X/issues/267) and [here](https://github.com/IMA-WorldHealth/bhima-2.X/issues/269))

**Comment by jniles** [comment]
@sfount, can this be closed or are you still planning on working on it?
