### ISSUE TITLE
Write unit tests for uuid service

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2646]
The [uuid](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/uuid.js) service would be a quick win for anyone wanting to practice writing unit tests.  The following tests need to be written:

 1. The service should return a function.
 2. The function should return a string with the number `4` in position `14`.
 3. Calling the function multiple times should returns unique values.

**Comment by jniles** [comment]
@jeremielodi, what is the progress on this issue?

**Comment by jniles** [comment]
@jeremielodi what is the progress on this issue?

**Comment by jeremielodi** [comment]
I still have some troubles about writing unit test. maybe I will need your help for this first one and will write others myself

**Comment by jniles** [comment]
Alright, let me know when you need help.
