### ISSUE TITLE
Additional unit tests for client services/util.js

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2648]
We already have some unit tests for [services/util.js](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/util.js) ([here](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/test/client-unit/services/util.spec.js)).  These only cover the Dojo-style before(), after(), once() functions.  We need to extend our tests coverage for this file.

**Tests To Write**
 1. `formatDate()` should take a date and transform it into a string.
 2. `formatDate()` should take a date and transform it into a format passed in as a second argument.
 3. `formatDate()` should default to `null` if nothing is passed in.
 4. `filterFormElements()` should return an empty object if provided an empty object.
 5. `filterFormElements()` should return `$modelValue` or `$bhValue` properties of sub-objects.
 6. `filterFormElements()` should filter out values that are not `$dirty` if `requireDirty = true` is passed in as a second parameter.
 7. `clean()` should filter out all properties that have empty values or that begin with `$`.
 8. `getMomentAge()` should return a string.
 9. `defaultBirthMonth` should be defined.
 10. `uniquelize` should turn an array into unique values.
 11. `isEmptyObject()` should return true for `{}`.
 12. `isEmptyObject()` should return true for `[]`.
 13. `isEmptyObject()` should return false for an object that has keys.
 14. The `xor` versus each entry in the [XOR Truth Table](https://en.wikipedia.org/wiki/Exclusive_or).
 15.  `maskObjectFromKeys()` should return an object with only the properties specified as a second value.
 16. `maskObjectFromKeys()` should return an empty object if given empty keys.
 17. `debounce()` should fire a function in the future.

We also have `arrayIncludes`, but this is just a mask for `array.includes()`.  Since we use ES2015+, we could remove it and change all references to `array.includes()`.

**Comment by jniles** [comment]
@jeremielodi, can you work on this?

**Comment by jeremielodi** [comment]
okay

**Comment by jniles** [comment]
Closed in #3448.
