### ISSUE TITLE
Remove Primary Cash tables + routes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#265]
With #105, we no longer need a `primary_cash` entity in bhima.  However, we have not fully refactored and removed the extra modules and routes.

In order to tighten up our codebase, and ensure we are only using clean, testable code, I propose we remove these extra routes and modules.  Specifically:
1. `/cash/conventions`
   1.  `controllers/finance/convention.js`
   2. `test/api/conventions.js`
2. `controllers/finance/journal/primarycash.js`
3. `controllers/finance/transfers.js`
4. The primary cash references and links in `schema.sql`

This changes will remove a massive amount of code (and features) from bhima-2.x, making it easier to organize both our code and future development tasks.

**Comment by sfount** [comment]
I agree with the proposal laid out in this issue - a key area that was difficult in 1.x was the number of modules and the difficulty of maintenance. This will help address that issue.
