### ISSUE TITLE
Write unit tests for renderers/csv.js

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2651]
We heavily depend on our [CSV renderer](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/lib/renderers/csv.js) for the downloads of almost all registries.  Writing unit tests will enable us to have confidence in the code.

**Tests to Write**
 1. The library should set three public properties: `extension`, `render` and `headers`.
 2. `render(data)` should return a promise.
 3. `render({ csv : [ /* some array */ ] })` should return a known string for a known input.
 5. `render()` should use a different key for finding if `options.csvKey` is set.
 6. `render()` should remove empty rows by default.
 7. `render()` should not remove empty rows is `suppressDefaultFiltering` is set.
 4. `render()` should convert dates if dates are passed in by default.
 8. `render()` should not convert dates if dates are passed with the `suppressDefaultFormatting` option.

**Comment by jniles** [comment]
@jeremielodi, are you working on this?  If not, I can take it.

**Comment by jeremielodi** [comment]
I started  working on this but I got a lot of difficulties and stopped, the problem was if I can remember : "the injection of many services before testing".
If your can work on this , it will be nice, then I will solve others issues about unit test by following your example

**Comment by jniles** [comment]
Cheers, will do.
