### ISSUE TITLE
Write tests for the bhSubmit directive

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2657]
We use a lot of loading buttons in the application.  Every single one of those is powered by the [bhSubmit](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/directives/bhSubmit.js) directive which is attached to a form and is fired on the 'submit' event.

**Tests to Write**
 1. The `bhSubmit` requires an `ngForm` element.
 2. The `bhSubmit` sets a property `$loading` to false on the `FormController`.
 3. The `bhSubmit` sets the `$loading` property to true when the `submit` event is triggered on the form.
 4. The `bhSubmit` calls the `bhSubmit` function callback when the `submit` even is triggered on the form.
 5. The `bhSubmit` directive will set the `$loading` to false if the callback resolves its promise.
 6. The `bhSubmit` directive will set the `$loading` to false if the callback rejects its promise.

**Comment by jniles** [comment]
@jmcameron stock is definitely the priority, but if you have downtime, this would be an easy thing to hack on without conflicting with anything else anyone else is doing.  Since you mentioned client unit tests work on your machine, it might be a good exercise?

**Comment by jmcameron** [comment]
Must have forgotten a "not".  Client unit tests do NOT work on my machine
(e2e do not either):  Client-server and integration work on my system.

**Comment by jniles** [comment]
Aha, nevermind then.

**Comment by Buzunda** [comment]
Hello, 

I think my unit tests are working, is this correct?
![Screen Shot 2021-01-18 at 21 49 58](https://user-images.githubusercontent.com/4948776/104974563-2cd61380-59d7-11eb-9a61-0eea75866da5.png)

If so, may I get this assigned to me please?

**Comment by jniles** [comment]
Hi @Buzunda, that is correct!  I've assigned the issue to you.

**Comment by Buzunda** [comment]
The PR was merged but the issue still remains

**Comment by jniles** [comment]
You are right!  Thanks for pointing it out.
