### ISSUE TITLE
Proposal: Routing In the Cash Window Module

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#266]
This issue is an improved design for routing in the "Cash Window Module".
##### Motivation

The routing on the Cash Window module is a [kluge](http://www.catb.org/jargon/html/K/kluge.html).  It uses hacks with AppCache + the router to make sure that the user cannot get into the Cash Window without a cashbox selected.  This makes a poor UX, and breaks the browser's "Back" button (try navigating from the cash page backwards after selecting a cashbox).

In brief, the routing is totally broken.
##### Proposal: New Cash Window UX/UI

This proposal suggests a new Cash Window design that allows the user to easily change Cashboxes without a jarring user experience, and doesn't break the browsing experience.

Cashbox selection should be a modal, like the one shown in Figure 1 below.
![cash window 1](https://cloud.githubusercontent.com/assets/896472/14280938/efd80504-fb2d-11e5-877c-bcf01145776c.png)
_Fig 1. The Cashbox Selection Modal_

Using a modal has numerous advantages:
1. The back button does not break (the modal is not based on a URL, but on a state).
2. Allows a cleaner presentation of cashboxes for selection
3. Does not feel like a separate module from the Cash Window, but instead complements it
4. No page reloading/refreshing!  The cash window controller can be fired once when the router enters the `#/cash` state, and does not have to be fired again until a page refresh.  This means it can download information in parallel (currencies, exchange rates, etc) while waiting for the user to choose a cashbox.

Instead of having large buttons on the side of the module, the user will find a list of links that will open modals, as shown in Figure 2 below.
![cash window 2](https://cloud.githubusercontent.com/assets/896472/14281167/5623bdfc-fb2f-11e5-84e3-4c5eebbba999.png)
_Fig 2. The Cash Window Module_

This is a much cleaner presentation.  Instead of having many buttons on the page, the user will be presented links to modal actions.

Finally, the "Transfer Funds" button will be renamed "Export Funds" (since it is an export from the cashbox, and it is impossible to transfer funds in any other direction using the modal) and will have a slight user interface change.  See Figure 3.
![cash window 3](https://cloud.githubusercontent.com/assets/896472/14281328/4ee2d5ae-fb30-11e5-8a9a-982b261bc424.png)
_Figure 3: The Export Funds Modal_

This presentation clearly shows all the important information of the transfer.
1. In the modal header, the cashbox is show clearly presented, along with the action.
2. In the main text body, the "From" and "To" fields tell the user exactly what accounts/entities are being concerned in the transaction.
3. The user only has to indicate the currency and amount of money they are transferring/exporting.  We should not have a _hard_ limit on the amount to transfer, but should show a warning if we detect that the user is transferring more money than bhima has recorded in the cashbox.

With these improvements, the cash module will almost be up to 2.x standards and polish.

cc/ @IMA-WorldHealth/local-contributors

**Comment by sfount** [comment]
It looks to me like this addresses many of the user experience issues from the first development (breaking the back button etc.).

What happens the first time a user ever loads the page, does the modal come up automatically? It might be a good idea to hide the page until the modal is ready to be shown to avoid displaying a module that looks like it can be used and then forcing a blocking modal. 

(From these designs, I think with many operations in the side bar using links looks cleaner 👍)

**Comment by jniles** [comment]
I was thinking that the first load (or anytime the user does not have a local cashbox selected), the user would be shown the modal.  Do you think it will be a jarring a user experience?

**Comment by sfount** [comment]
I don't think it will be jarring if the module knows to wait for the modal to be initialised before displaying anything at all (or a loading indicator until this point). 

**I think this should be avoided:** 
1. Module loads showing all editable fields, buttons and configuration options (these don't mean anything yet as there is no cash box) 
2. Modal loads as displayed in front of the module (say 0//3/5/10 seconds depending on internet speed)

**Possibility:** 
1. Module loads and displays either nothing (ng-if/ng-show?) or a simple text/ icon indicator demonstrating that something is loading 
2. Once all modal elements have been loaded this is opened along with the page being displayed

It's something that will be much clearer after an initial implementation though!

**Comment by DedrickEnc** [comment]
The proposal seems correct for me but I have some comments : 
1. I think showing only the date at the right (Modal for changing the cash box) is less intuitive. It will be difficult to the user to guess the meaning of this information at the first view. We can use moment librairy and a text like **_last update_** before.
2. It seems like export funds is not used in accounting and financial jargon, it is very used for technical domaine and abstract things like **stock, work, ...**
3. Transferring much money can make the source cash value negative which is critical and could break accounting.
4. After discussions, we decided to transfer money from cash to a transfer account but in the picture of the design, it seems like it is a cash to cash operation.

Thanks

**Comment by sfount** [comment]
@DedrickEnc @jniles 
1. 👍  I agree with point 1. It is a good suggestion to show them which cash box they have used before but contextual information like last update would be great!
4. I think this is just an abstraction for the end user? I think the accounting here could be as complex as it needs to be (using an intermediate account). Is it true that this just shows the two end points?

EDIT: Comment formatting on addressing specific numbers

**Comment by jniles** [comment]
@DedrickEnc @sfount,

Thanks for your feedback.
1. Good suggestion.  We'll use `angular-moment` for timestamps and put "Last used % minutes ago" or something like that.
2. I agree "Export Funds" is not a good term.  "Transfer" also sounds like it could be either direction (in or out).  We should reflect on this and see if we can find a better term.
3. It would make the account balance negative, but shouldn't break accounting.  It would indicate that a user made a mistake very obviously to the accountant, who could then correct it using a journal voucher.  I think this is a better option than users not recording the real amount just to make the `<input>` happy.
4. Yes, the mockup isn't reflecting reality - it was just an example!  I should have used a different account name.  It should be to a transfer account. 

I'll begin to work on this next, if @sfount thinks it is a good idea.

**Comment by jniles** [comment]
@sfount, to directly address your point 4, the target account will be configurable - something like "transfer_account".  If the accountant directly sets it to another cash account, that is their business!  Admittedly, the mockup didn't do a good job of showing that.

**Comment by sfount** [comment]
@jniles this is a very worthwhile and should be included in the current round of 2.x development however I would suggest it is added as a refinement after posting core + receipts are implemented through core finance (registration, invoice, cash, posting journal). 

My proposal is that the next piece tackled is the core journal interface required to post in 2.x. This means creating an issue with the proposed (small) problem to solve - namely implementing the basic interface as described in meetings the team held many weeks ago. 

Now that https://github.com/IMA-WorldHealth/bhima-2.X/pull/289 has landed this should be the last significant change to the database. 

This proposal issue should factor in https://github.com/IMA-WorldHealth/bhima-2.X/issues/254 and https://github.com/IMA-WorldHealth/bhima-2.X/issues/11. 

---

Perspective: 
1. base controllers and services required for registrations, invoices, cash transactions and posting core `(Complete)`
2. posting journal server interface core developed as an example (potentially for cash) `(Proposed)`
3. complex journal vouchers developed with core posting journal `(2.x process)` 
4. receipt core merged `(2.x process)` `feature-receipt-core`
5. transfers (simplified journal vouchers), invoices, cash transfers, complex journal vouchers re-factored to ensure they meet 2.x standards and use the latest core posting code. `(2.x process)`
6. receipts applied to all previously stated modules leading into reports

**Comment by jniles** [comment]
@sfount sounds good.  I'll work on posting `voucher`s into the posting journal via a clean interface, and gradually work towards posting cash transactions.
