### ISSUE TITLE
feat(stock): Adding a tag system for stock entry

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2662]
This issue is about to have a mean of tagging the stock with any key words (project name).

This feature will be useful for knowing in a given depot, the stock which correspond to one or more tags.

**Comment by jniles** [comment]
I propose tagging be implemented as two separate tables - one that holds the tags and a second that maps the tags to the depots.

The schema would be `tag (id, label)` and `depot_tag(depot_id, tag_id)`.  This will allow us to easily have an N - to - N relationship between depots and tags.  It will also make lookups faster by searching on a JOIN between tag and depot.
