### ISSUE TITLE
Inventory Search Modal radio buttons need labels

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2666]
There are a couple of options that are radio buttons on the inventory's search modal.  They need labels - currently they look like they might be part of the same set of options, just overflowing onto several lines.

See below:
![inventoryradiobuttonsshouldhavelabels](https://user-images.githubusercontent.com/896472/38410343-362f4a06-397c-11e8-8632-75100eb12fd3.PNG)
_Fig 1: How many options are here?  One or Two?_

**Comment by jeremielodi** [comment]
@jniles, why not to use checkboxes instead

**Comment by jniles** [comment]
@jeremielodi, what would be the difference between all unchecked and all checked?

**Comment by jeremielodi** [comment]
To my mind we can use a checkbox for each property, a checkbox can be true when checked and false when not. we will save more spaces

**Comment by jniles** [comment]
And if it is unchecked, is it true or false?

EDIT: if the user hasn't touched it, that is.

**Comment by jeremielodi** [comment]
false, we can define ng-true-value and ng-false-value properties
