### ISSUE TITLE
refactor(location ui): use of 2.x standard with grid and modals

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2669]
This issue is about to refactor the location module by applying the 2.X standard related to grid and modals (if it is possible)

**Comment by jniles** [comment]
See https://github.com/IMA-WorldHealth/bhima-2.X/issues/273 for previous art.  Note that it wasn't complete, sadly.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/3700.
