### ISSUE TITLE
(Design) Budgets

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#267]
This issue describes a design for the budgeting utility. 
`Finance / Budget`

The design focuses on creating reliable well tested tools that can be applied to many different situations and are not tied to one operation (creating an explosion of modules as we have seen before). 

![Budget module](http://i.imgur.com/OCSKKh4.jpg)

**Key points**
- Module consists of one large UI-Grid that shows all accounts in a tree structure 
- By the time the module has loaded the fiscal year that the user is budgeting for has already been selected (in this case Fiscal Year 2016) - this is demonstrated with a label as shown described here https://github.com/IMA-WorldHealth/bhima-2.X/issues/263
- The first two columns, `account` and `Annual Total` are pinned to the left, the other columns can overflow-x : auto;
- `split` allows the accountant to enter a value into the total and have that split (shared) amongst each of the periods, this should come with a warning if any of the periods have non-zero values
- Total row along the bottom shows this years entire budget
- Cells can be edited in each of the period columns automatically updated the annual amount for that line (and subsequently the total for the year)

![Budget export CSV](http://i.imgur.com/v8Kstdc.jpg)

**Export to CSV**
A major benefit of the structure proposed in https://github.com/IMA-WorldHealth/bhima-2.X/issues/257 is the ability to request the same data with multiple different 'renderers'. In this case the `json` renderer would be used to initially populate the UI grid. Selecting `export` -> `csv` would request **exactly the same data, from the same route** but passed through a `csv` renderer. 

![Budget export PDF](http://i.imgur.com/hPva10m.jpg)

**Export to PDF**
PDF budget report would be in lined just like receipts. This would allow it to be previewed, downloaded and printed. 

Any discussions relevant to the Budget module can be added to this thread! Once we have reviewed this process it can be assigned and a module proposal issue can be created to track progress. [(2.x development process)](https://docs.google.com/document/d/1Opak2BgrhXte0DzbKPmziY-aL7jIBj4PCnYhALmiy4w/pub)

**Comment by imawh** [comment]
Because Excel is so good at budgeting Tracker Exports to Excel and then Imports back over writing whatever budget you had entirely.  A bit scary but works.
Needs totals by level.  You already have that in posting journal right?
Split will need to be translated.  Use a button with a hatchet splitting wood.
The split will open a modal asking how to do the split: monthly, quarterly, semi-annually and where to put the remainder - first or last period.  The business logic needs to handle FYs down to 1 month.

**Comment by jniles** [comment]
Further notes on here:
 1. The order and selection of account should be determined by using the `account_type` table.  These are broken down by `title`, `income`, `expense`, and `balance`.
 2. The columns of this budget table are drawn from the `period` table.
 3. Each line in this table will appear in a `budget` table.  [It is already defined in the schema](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/models/schema.sql#L76) but may need to be updated.
 4. The export to Excel functionality can use our [csv renderer](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/lib/renderers/csv.js) on the server.  Similarly, the export to PDF can use the [PDF renderer](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/lib/renderers/pdf.js).
 5. An issue about parsing CSV/Excel should be made before it is actually implemented.

For the implementer of this proposal, the [Accounts Module](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/partials/accounts/accounts.js) is a really nicely implemented `ui-grid` that could be used for inspiration.

**Comment by jniles** [comment]
Note: An XLS exporter already exists on the server.

**Comment by jniles** [comment]
Note: https://github.com/IMA-WorldHealth/bhima-2.X/pull/2628 will implement _import_ functionality.
