### ISSUE TITLE
Where should submit buttons be?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#268]
In bhima-1.x, and so far in 2.x, we have unpredictable button placement.  Here are some sample forms/modals in 2.x.

**Journal Vouchers**
![rightsubmitbutton1](https://cloud.githubusercontent.com/assets/896472/14282541/bc3a0a7c-fb36-11e5-8a51-5b0b96f8fefc.png)
**Patient Registration**
![patientregistrationsubmitbuttons](https://cloud.githubusercontent.com/assets/896472/14282559/d33eb1c8-fb36-11e5-8dc7-b57533ff5c5a.png)
**Cash Window**
![cashsubmitbtn](https://cloud.githubusercontent.com/assets/896472/14282665/4b519d6a-fb37-11e5-9c49-5083518e7fce.png)
**Confirm Modal**
![modalsubmitbutton](https://cloud.githubusercontent.com/assets/896472/14282543/bc8bd582-fb36-11e5-8cf1-a5126a1fbcfb.png)
**Location Modal**
![locationmodalsubmitbuttons](https://cloud.githubusercontent.com/assets/896472/14282542/bc89560e-fb36-11e5-8ed4-484463eefdc4.png)
**Transfer Modal**
![transfermodalsubmitbtn](https://cloud.githubusercontent.com/assets/896472/14282678/5aacae8a-fb37-11e5-9084-0c6f39653ad7.png)
##### Questions
1. Where should the submit buttons be placed?  On the right or the left hand side of the form?  What about for a modal?
2. Where should the "Submit" button be placed if there is a "Cancel" button as well?  On the left or the right hand side of the "Cancel" button?
3. Should the buttons be placed differently depending on where the form is on the page?  For example, if a form is on the left side of the module, should the buttons be on the right side of the form, but if the form is on the right, the buttons be placed on the left?  Or is that too confusing?
4.  Should submit/cancel buttons be placed in a `panel-footer` or the `panel-body`?

cc/ @IMA-WorldHealth/local-contributors

**Comment by sfount** [comment]
From my experience with BHIMA and research on other products so far my opinion is: 
1. The right hand side is the natural progression looking down a form for submission (reading from left to right, left to right. Right would be the final place you focus)
2. Again I think it makes sense for the final intended action to be placed in the bottom right - anything optional (cancelling, etc.) could come before this 

_For an example close to home:_
![screenshot 2016-04-05 at 14 52 06](https://cloud.githubusercontent.com/assets/2844572/14284100/fd01c840-fb3d-11e5-900a-082d2666cb12.png)
This demonstrates the close button to the left of the intended action. 

3 .I would have to see how that looks but I think consistently placing them either left or right would be best.

**Comment by imawh** [comment]
Bottom right for sure but need to make sure it doesn't disappear or get hidden on some screens / screen resolutions.
Visual Basic Message boxes put the buttons left to right with the desired action far left and selected
![buttons](https://cloud.githubusercontent.com/assets/16554641/14286283/6fe069d6-fb46-11e5-98b1-7c5f6f89c66a.png)

**Comment by jniles** [comment]
@imawh, @sfount, thanks for the feedback!

It sounds like the consensus is this:
1. Buttons should be floated to the right of any container - form or modal.
2. The "action" button (submit, confirm, ok, etc) should be far right, and any other buttons (cancel, close. etc) can be stacked to the left of them.

With our new CSS application structure, we've been pretty good at getting things to render on the smallest screen we can emulate in the Chrome DevTools.  Should be fine there!

**Comment by jniles** [comment]
Marking this as resolved.
