### ISSUE TITLE
Turn off consumption, and expiration tracking for groups of inventory items

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2683]
We've mentioned this in various issues, but we haven't really ever tackled this formally.

I propose that we put flags on the `inventory_group` table that will determine a lot of the display properties of the stock in the depots.
 1. `should_track_consumption`
 2. `should_track_expiration`

These show columns would have the following impact:
 1. During the creation of the a `lot` for an inventory item with `should_track_expiration` set to `0`, the `ui-grid` would not have the `expiration_date` column in it, and the expiration date would be set to something very, very far in the future by default.
 2. During all calculations for expiration dates, the lot would be avoided.
 3. In the "stock lots" registry, the column for "expiration date" and "expiration" would display nothing if `should_track_expiration` is set to `0` for that lot/inventory/inventory_group.
 4. If `should_track_consumption` is `0`, the stock will not show up in any of the consumption reports, and will never be available for automatic re-order.

**Comment by jniles** [comment]
@jeremielodi, can you see if this has been done?

**Comment by jniles** [comment]
@jeremielodi, any follow up on this?

**Comment by kwilu** [comment]
Hello @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
We recently received a complain from a user about this.  Specifically, their feedback was:

> Vous remarquerez pour certains items comme le sachet plastique pour médicaments, lame de rasoir avec manche qui n'ont pas de date de péremption, j'ai due en inventer parce que le programme en exigeait une, est ce normal?

We should probably focus on implementing this soon.
