### ISSUE TITLE
(Design) Accounts

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#269]
This issue describes a design for re-factoring the current accounts utility to create a tool that can be used to configure accounts and reports ([#209 Account Tags](https://github.com/IMA-WorldHealth/bhima-2.X/issues/209)).

![Account Home](http://i.imgur.com/8CuUMDv.png)

**Key Points**
- Expandable tree of accounts in a full page UI-Grid (the same tools can be used to build #267) 
- `Last Transaction Hit` shows the time that the account was last hit in the posting journal/ general ledger - simply ordering by this would give an idea of which accounts are currently 'active' and which are no longer used/ have never been used.
- Tags can be updated by double clicking the account cell - I suggest we look into something like [Angular UI Select 2 component](https://github.com/angular-ui/ui-select) to add combo boxes + tags
- Accounts can either be added to the root object (header button) or each title account provides a link/button to pre-populate the account creation modal (with parent relationship) 

![Account create](http://i.imgur.com/OGgDxOM.jpg)
Accounts are created in a modal, this would allow many accounts to be created at once without being removed from the accounts utility context - accounts would be added to the underlying grid modal with the option of creating many accounts at the same time ('Create another account option')

The `Create` status object can be implemented using #263.

Any discussions relevant to the Account module can be added to this thread! Once we have reviewed this process it can be assigned and a module proposal issue can be created to track progress. ([2.x development process](https://docs.google.com/document/d/1Opak2BgrhXte0DzbKPmziY-aL7jIBj4PCnYhALmiy4w/pub))

**Comment by imawh** [comment]
Child accounts inherit parent tags by default? by definition?  would need function to remove a tag added automatically
Assuming dozens of tags could be applied to a complex accounts structure they need not be pretty labels/badges but rather a list ending with ... when running out of room.
There may be interest in how tags sort if a report presents totals by tag and you want IMA at the top.  That means tags themselves have properties such as sort order.
Indeed the process flow for adding accounts needs to be as optimum as possible facilitating adding 50 accounts in one session.  Hence create another account is the default, and cancel is how you get out of the add account modal.
Specifying account type should be obligatory so the first set of tags would be Cash, Other Asset, Receivable, Payable, Equity, Income, Expense (translated).  I suppose all tags would be translatable.
How do you insert an account in a particular position among siblings?
Totals will appear for each parent in reports and summary screens?

**Comment by jniles** [comment]
@sfount, @imawh  My assumption is that the chart of accounts is ordered on account number by default, correct?

The `+Add Child` sounds like a really good idea for this and other grids.  I'll be interested to see how the UX goes with two buttons for very similar actions, but it sounds nice.

The link you cited for select2 is deprecated, did you mean [ui-select](https://github.com/angular-ui/ui-select) instead?  Or must it be select2?

**Comment by sfount** [comment]
@imawh 
- My current proposal is that you can only tag non-title accounts, this removes many corner cases and leaves the decision up to the accountant (does tagging a parent tag all children, can children be tagged without the parent etc.). Any non-title account that is tagged will still be shown in the report under its title hierarchy (if it's applicable to the report).
- I'm sure there will be a compromise between pretty labels and making sure the UI/UX works for complicated cases. I suggest we start as simple as possible and build on that. 
- :+1: Agreed with create another is set by default; this options could also be cached
- I had not considered translatable tags - this will take a database design! Providing options for each language shouldn't be too difficult but should be carefully considered (it may be adequate to have the tags be in the enterprises base language and reports allow custom headings) 
- Account groups/ child/parent releationships will drive many of the reports and summary screen - implicitly showing a total for parents/ groups.

@imawh @jniles 
- As far as I can tell accounts should by default be ordered by account number with respect to parent groupings, this provides flexibility to group accounts in any way you'd like whilst having predictable ordering 

For example:

```
- 10 Account One 
   -- 101 Child Account One 
   -- 102 Child Account Two 
   -- 120 Child Account Three 

   # There is nothing stopping an accountant from assigining the account '10' as a parent to the account '600' - accounts under '10' will be ordered by account number
   -- 600 Child Account Four    

- 11 Another Root Account 
   -- 110 Another Root Account Child
...
```

edit: (updated link to reference correct repository)

**Comment by jniles** [comment]
@sfount, can this be closed yet?

**Comment by jniles** [comment]
@sfount, what's missing from this issue?

**Comment by sfount** [comment]
Not all ideas here have been implemented but I think this issue has been satisfied. 

In the future it may be interesting to see 'Last Transaction Hit' with a link to the receipt however for now I think the functionality has been merged.
