### ISSUE TITLE
(Proposal) Configuration Page Structure

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#270]
This is a generic proposal for how we structure configuration (management) pages. Currently we use a mixture of UI Grids and HTML tables, using a 2 column structure listing the entity on the left and allowing CRUD operations on the right. 

![Configuration Page](http://i.imgur.com/NFtPNer.jpg)

This proposal aims to improve on this in the following ways: 
- Allow much richer information to be displayed along with each entity. Displaying the entity in a 'card' allows more information than a single line a row of a table - management pages should never contain thousands of entries so this should not become overwhelming. 
- List structure can be sorted by various attributes 
- Pagination allows the page to never become overly large - this is something that hasn't been implemented in any of the current pages
- Makes use of the latest state based routing as introduced https://github.com/IMA-WorldHealth/bhima-2.X/pull/225

![Edit/ Create Page](http://i.imgur.com/Yqgemqu.jpg)
This is the modules create/update state, it provides a link back to the main list and allows the user to change the entities value - it could also provide additional information about the entity (when and where it is being used, how often, etc.)

**Comment by jniles** [comment]
Some quick questions:
1. What does the main page look like without any entities on it?  Is there an image or text informing the user that there are no entities?  This could be a lot of empty whitespace.
2. Is the "Create Another Entity" checked by default?

**Comment by sfount** [comment]
That's a good question - I certainly have not covered that in my design. 
For now I would suggest that an information alert/ panel is shown describing briefly what the entity is and how you can create the first one (clicking the create entity button). In the future we may think about in-lining the create form if there are not yet any entities so that there aren't multiple different states (something that's possible with UI-router). 
1. Basic information about what the entity is and how to add the first one - this can be revised in the future. 
2. This was brought up in https://github.com/IMA-WorldHealth/bhima-2.X/issues/269#issuecomment-205850146 by Wayne. 

> Indeed the process flow for adding accounts needs to be as optimum as possible facilitating adding 50 accounts in one session. Hence create another account is the default, and cancel is how you get out of the add account modal.

I think that this is a reasonable model - it is true that you probably do not need to create 100s of Debtor groups all at once but the meaning of the check box should be very clear and can it can be unchecked for one offs. (It would also be possible to remember the previous state of the check box and use that in following sessions). 

Does that answer your questions? If you have any other ideas or alternatives let me know!

**Comment by jniles** [comment]
Those ideas sound like reasonable defaults.

Inlining the create form would certainly be useful for a "power" user, but we'll have to make sure that it doesn't confuse regular users to have a single corner case (i.e. no entities) drastically change the ui.  Also, if one goes through deleting each entity in succession (no idea why you would do this, but is achievable), it would be a rather big jump to suddenly have a create form where the list of entities used to be!

**Comment by DedrickEnc** [comment]
@sfount  how about theses entities listed as card? there are components? or what?

**Comment by jniles** [comment]
I'd be a fan of making them components.  Easier to test with unit tests!

**Comment by sfount** [comment]
@DedrickEnc I think that is a good idea. In fact the whole sorting/ filtering/ pagination element could be a component that is shared across many pages (depending on how we decide to do configuration pages) 

**Proposal:**
1. The card is templated in using `ng-transclude` - this would allow every configuration module to show different relevant information (Number of debtors/ quick links to reports/ other misc. information). A module would provide this. 
2. The actual data that drives this list would be provided as an array (just like `ui-grid` works) and the component would be responsible for the sorting/ filtering/pagination functionality.

**Comment by DedrickEnc** [comment]
In my mind, it is a worth to know that a component representing a debtor group will be different than a component representing an account for example so, we should build a component for each entity (one for debtor group, one for patient group, account, billing service, ...)

And after an other component to list them, it can be a kind of collection which can be generic and will need just the entity name to list. with very high operation like add to the list, remove from the list ...

What do you think?

**Comment by sfount** [comment]
I agree - I think because each entity would be so different for now it will be sufficient to just use a template, each module will define it's own template for how the card will look which will just be regular Angular markup. 

Do you know of anything the card component would do specifically? If not I would just have each module specify a template for the list component to use when doing  `ng-repeat` on the data.

**Comment by sfount** [comment]
I agree - I think because each entity would be so different for now it will be sufficient to just use a template, each module will define it's own template for how the card will look which will just be regular Angular markup. 

Do you know of anything the card component would do specifically? If not I would just have each module specify a template for the list component to use when doing  `ng-repeat` on the data.

**Comment by jniles** [comment]
This was implemented for debtor groups.  See #364.
