### ISSUE TITLE
feat(stock exit patient): add link between invoice and stock exit to patient

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2700]
This issue concerns the issue #1974 

Adding an optional field for invoice when distributing stock to patient.

![stock exit patient](https://user-images.githubusercontent.com/5445251/38926916-1fd186b4-42fc-11e8-9893-e03f44738551.png)

The challenge here is about the list of invoices to display : 
- Get the list of invoices which are just needed : invoices which contains consumable inventories (inventories that we can be stored in a depot and distribute it to patient)
- These invoices must be relevant to be displayed

**Comment by mbayopanda** [comment]
@jniles

What do you think if we create a component `bhFindInvoice`, 'cause we just need a specific invoice for a patient. we can let the user insert the invoice ID for the selected patient.

In this case we don't have to deal with which invoices to put into the grid.

The component return the invoice object, and for this module we can fill the lot's grid with corresponding inventories (if inventory exists in the depot and quantities are allow).

The component can be have these states : 

![bhfindinvoice](https://user-images.githubusercontent.com/5445251/39422670-431a9f48-4c66-11e8-9dbc-c2b4cdd7e2e3.png)

**Comment by jniles** [comment]
Looks good to me.  Does that mean we won't be able to distribute to multiple invoices?

**Comment by jniles** [comment]
Implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2743.
