### ISSUE TITLE
feat(depot): add reports for patient and service distribution

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2701]
This issue is about to add two reports or registries : 

1. A patient distribution registry : this registry contains : 
   - the reference of the movement,
   - patient information,
   - inventory information,
   - the quantity,
   - the date
   - the reference of the invoice if it is present

2. A service distribution registry : this registry contains : 
   - the reference of the movement,
   - service information,
   - inventory information,
   - the quantity,
   - the date

**Comment by jniles** [comment]
@mbayopanda didn't this get addressed in the regular distribution reports?

**Comment by mbayopanda** [comment]
Already addressed.
