### ISSUE TITLE
fix(enterprise exchange rate): no currency symbol

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2707]
There is no currency symbol for a fresh instance of the application (after running `./sh/build-init-database`).

We create an enterprise with $ as currency with the default project.

![no currency symbol](https://user-images.githubusercontent.com/5445251/38994891-86884b5c-43df-11e8-9ba0-05fdae61b7b5.png)

The currency symbol is not displayed correctly

Also the feature `Exchange Rate` doesn't work if we want to set an exchange rate.

**Comment by jniles** [comment]
This might also have something to do with https://github.com/IMA-WorldHealth/bhima-2.X/issues/2432.
