### ISSUE TITLE
(Design) Debtor Groups

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#271]
This issue describes a module proposal for the debtor groups configuration. This design is driven by and can be used as an example for https://github.com/IMA-WorldHealth/bhima-2.X/issues/270.

![Whiteboard design](http://i.imgur.com/ufcbVGD.jpg)
**Note: The left hand sign of this design is relevant to debtor groups**

**Key points:**
- Each debtor group shows useful contextual information that turn this module into a utility
  - Timestamp of the last transaction hitting this debtor group
  - Created timestamp 
  - ?Current balance on this debtor group
  - Number of debtor in this debtor group

This allows this utility to answer the following questions (subset for example): 
- Are there any inactive old debtor groups? (Sort by 'last transaction' DESC) 
- Which debtor group owes the most money (Sort by 'balance' ASC)
- Which debtor group has them most patients? (Sort by 'total entities' ASC)

This design also leverages state based routing using what would have previously been very complicated routes that can now be implemented using UI-Router. 

Any discussions relevant to the Debtor Group module can be added to this thread! Once we have reviewed this process it can be assigned and a module proposal issue can be created to track progress. ([2.x development process](https://docs.google.com/document/d/1Opak2BgrhXte0DzbKPmziY-aL7jIBj4PCnYhALmiy4w/pub))

**Comment by imawh** [comment]
Debtors and Debtor Groups are eternal once entered into the GL.
Some things you might want to do with Debtor Groups is lock them out from obtaining service until they pay up.  Could color code them by amount owed or by their payment history.
Might want to record when they last paid or when you last sent a payment reminder.
Only debtor groups not present in the GL may be deleted.
Might have an interest in the sort order they appear in reports.
I assume this is a modal that pops up after clicking on a grid listing all debtor groups and some of their statistics.  The modal would have a button that pops up another read only window showing 12 month history of CR/DRs for this particular Debtor group.  Depending on the volume you would consider a debtor group by period total table in addition to a debtor by period total table.

**Comment by jniles** [comment]
Closing this as completed in #364 and #465.
