### ISSUE TITLE
(Bug) Tree component not populated on login

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#272]
**Steps to reproduce:** 
1. start the server `npm run app` 
2. login using `superuser` `superuser`
(The tree is currently in a collapsed state)
3. expand the tree 

**Expected behaviour:**
The tree routes are populated 

**Actual behaviour::** 
The tree is empty

This should be addressed before closing https://github.com/IMA-WorldHealth/bhima-2.X/issues/44 and proves that all of our components **need** unit tests (as introduced https://github.com/IMA-WorldHealth/bhima-2.X/pull/250)

**Comment by jniles** [comment]
The issue is that "login" no longer emits a login event via appstate.   We can either emit the event using $scope.$on/$broadcast, or use a service to listen for login.  Or the SessionService could expose a onLogin() method that calls the tree's loading function whenever the user logs in.

What do you think is the best design?

**Comment by sfount** [comment]
I like the idea of the session service exposing an `onLogin()` method however there may be many smaller components that want to start listening on things like login, logout, session updates etc. If there are enough different cases potentially $broadcast would be the right way to go. 

I suggest this problem is tackled as follows: 
1. A test is written to automatically show that this bug exists
That way if the bug ever surfaces again it will give us a failing test - Unit tests would be ideal for the tree component however it seems to me this is an error would only be presented in the context of the application (E2E test)
2. A solution is proposed to pass the failing tests 
3. Solution is implemented and both tests and improved code are merged into `master`
