### ISSUE TITLE
Need help in project setup

### ISSUE THREAD

**Issue by erdahuja** [third-culture-software/bhima#2729]
Hi, i previously contacted too, i need to setup this project on my local but the documentation is outdated. 

I want to become a regular contributer please revert details at er.d.ahuja@gmail.com

**Comment by erdahuja** [comment]
@jniles https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/sh/build-development-database.sh

it says page not available , i need this script right?

**Comment by jniles** [comment]
@erdahuja, no it should just be https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/sh/build-database.sh.  What documentation is pointing towards that script?  I'll try and change it.

**Comment by erdahuja** [comment]
It says page doesn't exists.

Thank you.



Regards

Deepak Ahuja

Full Stack Developer, Pesto Tech



Official-Email: deepak@ <deepak.ahuja@asaan.com>pesto.tech

skype: dpkahuja

Mobile: +91 8010099223

**Comment by jniles** [comment]
The [build-database.sh](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/sh/build-database.sh) link?  It should be publicly available.

I'm not sure where the link is to the script with "development" in the name.  A more up to date version of the documentation exists [here](https://manual.bhi.ma/for-developers/installing-bhima.html).

**Comment by erdahuja** [comment]
Hi, i installed the project but database doesn't show up.

I followed documentation exactly. and ran 'show databases;' on mysql,
bhima_test doesn't show up after yarn build:db.
Also i guess that's why i am getting access denied on running app on dev.


Thank you.



Regards

Deepak Ahuja

Full Stack Developer, Pesto Tech



Official-Email: deepak@ <deepak.ahuja@asaan.com>pesto.tech

skype: dpkahuja

Mobile: +91 8010099223

**Comment by erdahuja** [comment]
{"status":400,"code":"ERRORS.ER_ACCESS_DENIED_ERROR","description":""}

Thank you.



Regards

Deepak Ahuja

Full Stack Developer, Pesto Tech



Official-Email: deepak@ <deepak.ahuja@asaan.com>pesto.tech

skype: dpkahuja

Mobile: +91 8010099223
