### ISSUE TITLE
(Design) Location Management Redesign

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#273]
This issue proposes a redesign to the location management module, as well as one advanced feature: merging locations.
##### Motivation

The location management module has never had a great UI, mostly because the user interface reflected the backend tables directly.  This leads to a confusing configuration page where a user can create a "country" but cannot ever use it directly, except to create other locations.

Other issues:
1. Locations are a single idea, even though we broke them up for storage reasons into four backend tables.  The user should be presented locations as if they are a single block.
2. There is no facility for eliminating duplicate locations in bhima-1.x.  This has prompted the feature "Merge Locations".
3. Separating "Village" from "Sector" and "Province" makes it very difficult to catch errors in assigning a village to the wrong sector or province.  For example, in our prototype build, we have 21 villages assigned to 'Bas Congo', even though the prototype installation site is nowhere near Bas Congo.  This is because the sector was incorrectly assigned to the 'Bas Congo' province once, and all villages tied to it are now wrongly associated with 'Bas Congo'!  Providing a unified view should help avoid this issue.
##### Designs

The location management should present a single unified grid as shown in Figure 1.  There is a single button on top of the module for creating a new location using the same Location Modal as the `bhLocationSelect` component.  There are also buttons to edit any previously registered location.
![location management 1](https://cloud.githubusercontent.com/assets/896472/14285875/006ae262-fb45-11e5-9471-9b43349d28cc.png)
_Fig. 1: Location Management Grid_
![location management 2](https://cloud.githubusercontent.com/assets/896472/14285876/006d7f90-fb45-11e5-9b5f-c79c8817c576.png)
_Fig. 2: Location Creation Modal_

Updating/Editing a location works similarly to creation in a separate modal. This modal will allow a user to reassign the provinces, sectors, or countries and edit the village text.  If a particular sector does not exist, it will open the creation modal to that exact position by clicking on the "+ New" link.
![location management 3](https://cloud.githubusercontent.com/assets/896472/14285874/003ea24c-fb45-11e5-9b33-6d064fda4280.png)
_Fig 3. Selecting a Location for Update_
![location management 4](https://cloud.githubusercontent.com/assets/896472/14285873/002449c4-fb45-11e5-834f-2a4083137fc5.png)
_Fig 4. Update Location Modal_

The update location modal will also have a "Delete" button, which only works if the location is unused.  Any other case will present the user with an error.

**Location Merge**
![location management 6](https://cloud.githubusercontent.com/assets/896472/14285871/00080336-fb45-11e5-8bcf-813519ee992b.png)
_Fig 5. Selecting Locations to Merge_
![location management 5](https://cloud.githubusercontent.com/assets/896472/14285872/000ef876-fb45-11e5-9842-f680104fe7b6.png)
_Fig 6. Merging Locations_

A needed feature is merging locations, described in Figures 5 and 6.  A user selects two location from the ui-grid and is able to click a "merge" button on the `headercrumb (tm)`.  The merge button will present a comparison of the two locations, including how many times they are used.  (If a location is never used, it can be simply deleted instead of merged).

Once a user clicks "merge", the module will send a PUT request to `/locations/merge` that will search all links the database and rewrite them to be the chosen location `uuid`.  Once that process is finished, the unused location `uuid` is simply deleted.

**Comment by imawh** [comment]
Is the x in top right the only way to get out of merge?  Needs a cancel button that is selected by default.  Need to consider how to select the merge candidates.  In tracker it's two type-ahead drop downs (the second filtering out the first).  Just highlighting rows might be confusing if they are separated by lots of rows/pages of locations.

**Comment by jniles** [comment]
@imawh yes, and the "escape" key.  A cancel button is probably a good suggestion for something of this importance.

_In theory_, you shouldn't have to merge locations that are _too_ far away.  Merging is likely for spelling mistakes in villages, capitalization errors (BIANKY vs Bianky vs bianky).  In fact, I would say that you should only merge locations that are in the same sector....  Good thought though. 

I'll look into creating an issue with the details of the "merge" algorithm so that we can hammer out those details there.  This was more of a broad client module overview.  Thanks for the feedback!

**Comment by lomamech** [comment]
@jniles , I progressed with the work, but I will know is it necessary to have the link +new to add a new location on the form allowing to make the update.

**Comment by lomamech** [comment]
@jniles  @sfount 

I have an observation that with the new design for the unit Location Management, there will be a problem concerning the updating of geographical locations that do not have any village, indeed the main grid displays the villages with their sectors , Provinces and countries.

I believe that the new design of the unit Location management module needs to be modified.

**Comment by jeremielodi** [comment]
@lomamech  proposed to close this issue
