### ISSUE TITLE
Pre-filter all period selection components by Fiscal Year

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2750]
In a few places, we use period selection component without providing the fiscal year.  This results in a very long list of periods.  A better user experience would be to filter the periods by fiscal year and subsequently provide a selection of periods.  It also limits the amount of data we need to download at a time.

**Comment by sfount** [comment]
@jniles It looks like most of these cases have been addressed with the `bh-fiscal-year-select` and `bh-period-selection` components. Unless there's a case I'm missing this can be closed.
