### ISSUE TITLE
refactor(stock exit): use calculated unit_cost for stock exit

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2754]
In the stock exit process, the unit_cost used is not defined by the user but the unit_cost during the entry or the calculated according the (CUMP: Coût Unitaire Moyen Pondéré) method.

So, we have to : 
- set the unit_cost with the correct unit_cost of inventory during an exit
- hide or disable to edit the unit_cost field

![stock exit unit cost](https://user-images.githubusercontent.com/5445251/40050628-e8e22002-582f-11e8-8bee-92d07a60f809.png)

In that way, in the journal there will be correct values for stocks exit.

The principle is : the stock leaves the depot at the purchase cost for the movement of stock accounts

**Comment by jniles** [comment]
I always wondered by we had the cost in the stock entry/exit modules.  It seems to me these values shouldn't be able to be set from the stock modules.  I'm glad to see an issue tackling this.

It seems to me there are several methods for calculating the value of stock.  According to [this resource](https://www.entrepreneur.com/article/55578) they are:
 1. First-in-first-out (FIFO): This means your costs of sales is determined by the cost of the items you purchased the earliest. Inventory is comprised of the cost of the items you purchased the latest.
 2. Last-in-first-out (LIFO): This means your costs of sales is determined by the cost of the items you purchased the latest. It should be noted that depending on your industry, LIFO is not allowed for tax purposes.
 3. Weighted average cost (WAC): Means that your costs of sales is determined by the average cost of the items you purchased determined at the time of sale.  I think this is what you are describing as CUMP.

It would be ideal if BHIMA could support all of them, and an administrator would simply choose which one to use.

**Comment by jniles** [comment]
We've removed the "unit cost" from the stock exit, so this issue is irrelevant.  See https://github.com/IMA-WorldHealth/bhima/pull/3956.
