### ISSUE TITLE
(Proposal) Remove Multiple Enterprise Management

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#277]
BHIMA 2.x currently supports and adding and editing multiple enterprises at `/enterprises`. 

I suggest that we remove this functionality as it is not considered _anywhere_ in BHIMA - every module/report/API assumes that you have one static enterprise (generally enterprise [0] is selected) and the implications of changing this have never been considered.

We could remove this page completely in favour of an enterprise overview page (just like the current home page) that shows all of the enterprise contact details, enterprise exchange rates, links to employee records, daily activity etc. From this page an administrator could edit enterprise settings (through a modal interface or something). 

This would both benefit the landing page (well thought out design and useful day to day features) and reduce the number of pages that we have to maintain (removing the current enterprises page).

@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
I'm okay with this proposal.  We did the same thing for currency configuration, for similar reasons.  No problem here!

**Comment by imawh** [comment]
Actually multiple enterprises is misnamed.  By definition a 'set of books' is for a single 'going concern' or enterprise.  The multiple project capability copied from Tracker would allow HBB to open a project for Garage and Guest House or other peripheral projects and do their accounting separately, only reporting grand totals to the HBB enterprise (mother ship) GL for Balance Reports.  That would require Garage and GH to hire accountants to post their own txns which they probably won't.  Right now I don't see any hospital in DRC rising to that level of complexity.  However,  it is not that great an increase in complexity and works fine in Tracker.  So I'd still make project_id a field in every table with a default 1  (you don't really have a project 0 do you?) for the day HBB lands a $25M USAID grant they want to manage in their system ....  granted adding project functionality adds project_id=CurrentlySelectedProject to the WHERE clause of EVERY query throughout the program.

**Comment by jniles** [comment]
Perhaps it is misleading.  Either way, the idea of multiple going concerns will increase the complexity in the short term for a longer term goal.

Since we do not actually support multiple enterprises in the UI, the pragmatic thing to do is remove the enterprise "create" feature in the short term (while keeping editing), and re-introduce it in the long term.  This avoids a whole class of bugs we haven't considered where users might create enterprises without understanding the implications thereof.

**Comment by jniles** [comment]
Closed via #619.
