### ISSUE TITLE
Reversals/Corrections do not show translated text in transaction description

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2780]
The Credit Note functionality not longer writes the description in the transaction description, leading to a single confusing text "(CORRECTION)".   The modal seems to attempt to translate the key `FORM.INFO.CREDIT_NOTE_INVOICE` [on this line](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/invoices/registry/modalCreditNote.js#L69) which is defined [here](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/i18n/en/form.json#L130), but it never ends up in the database.  It's likely an issue with the interface between Node and MySQL.  Someone should look into this.

**Comment by jeremielodi** [comment]
close #2780
