### ISSUE TITLE
(Design) Fiscal Year

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#279]
This issue proposes a design for the fiscal year module.  It mostly presents a user interface based off the ideas in #270.
##### Changes From 1.x

Our previous 1.x implementation of fiscal years went through many iterations, mostly due to a lack of a formal design.  Here are some things 2.x's fiscal year module will change:
1. We will no longer support variable length periods. In 2.x `period === month`.
2. The previous fiscal year will be automatically calculated via the auto-increment index.  The user will not be able to specify a previous fiscal year - whatever the last fiscal year created was will become the previous fiscal year.
3. No more `transaction_start_number`, `transaction_stop_number`, `start_month`, `start_year`, `fiscal_year_txt` --> `label`
##### Fiscal Year Database Schema

The new database schema for the table `fiscal_year` looks like this:

| Column | Type |
| :-- | :-- |
| id | INT (auto increment) |
| number_of_months | INT |
| label | TEXT |
| start_date | DATETIME |
| previous_fiscal_year_id | INT |
| locked | BOOLEAN |
| created_at | DATETIME |
| updated_at | DATETIME |
##### Mockups

The fiscal year page draws heavy inspiration from #270, but includes only details that make sense to a fiscal year.  Figure 1 shows a list of the fiscal years created on the main fiscal year page.
![fiscal year list](https://cloud.githubusercontent.com/assets/896472/14313846/eb0fccaa-fbeb-11e5-8ec2-c8da55b88032.png)
_Fig 1 Fiscal Year List_

The user is only able to delete a fiscal year if there are no transactions created against it.  This is done in a confirm modal like #150 (not shown here).

Fiscal year creation behaves different between the first year created and any subsequent years created after that.  If the user is creating the very first fiscal year, there is no previous fiscal year, and the user has the option to set the opening balances (stored in period 0 of the `period_total`s).  See Fig 3.

![fiscal year create - first year](https://cloud.githubusercontent.com/assets/896472/14314051/0c2063f4-fbed-11e5-91e2-a3f25b49e66c.png)
_Fig 2 Fiscal Year Creation - First Year_

 ![fiscal year create - opening balances](https://cloud.githubusercontent.com/assets/896472/14313847/eb36686a-fbeb-11e5-9cb6-975f5be86f12.png)
_Fig 3 Fiscal Year Creation - Opening Balances_

If a previous fiscal year exists, it is automatically linked based on the `max(id)` of the fiscal year table.  The user is also presented the option to close the previous year automatically importing the balances from the last year.

![fiscal year create - second year](https://cloud.githubusercontent.com/assets/896472/14314137/80f2a7a0-fbed-11e5-8e9d-ac5e706f1be2.png)
_Fig 4 Fiscal Year Creation - Close Previous Fiscal Year_

Finally, on the edit page, the user is given the opportunity to see the opening balances (uneditable) in a modal, or close the fiscal year (locking it).

![fiscal year edit](https://cloud.githubusercontent.com/assets/896472/14313848/eb39bec0-fbeb-11e5-9ecc-b93cb25e716b.png)
_Fig 5 Edit a Fiscal Year_

**Comment by imawh** [comment]
/# 2 above limits you to one project/enterprise - "The previous fiscal year will be automatically calculated via the auto-increment index. The user will not be able to specify a previous fiscal year - whatever the last fiscal year created was will become the previous fiscal year." 
Need to add 'highest auto-number within currently selected project'

Form above with name, date created, number of months, .... do you want date created or beginning month?  or both.

Opening balances modal needs CR/DR  columns, your balance can be on one side or the other  AND DRs must = CRs or you stay in the modal.

Close the FY needs to be a button on each FY along with X and Edit.  You close a year when ready, often months after beginning a new one.  Rarely, you could go back and fix a closed year (if not audited or reported to the govt) and then recalculate the closing ... which require recalculating the following year's period 0.

**Comment by jniles** [comment]
For point 1, you are right, you would have to explicitly set the enterprise.  The idea would be to do something like:

``` sql
SET @prev = (SELECT MAX(id) FROM fiscal_year WHERE enterprise_id = {{ id }});
INSERT INTO fiscal_year (..., previous_fiscal_year_id) VALUES (...., @prev);
```

I'm hoping we only have to specify a single start date, in the form of a DATETIME.  It would be beginning of the month.  The mockup above uses "Set Date" to emphasize that we will use the same `bhDateEditor` component used in all other modules, but in the "month" mode (not properly shown in the mockup).  Does that make sense?

Alright, will do!  I wondered if DR/CR fields should exist on the view, and ended up not displaying them.  They exist in the backend though.

Perhaps the edit button shouldn't exist if the previous year is closed...  Should you be allowed to reopen a closed year?  We could easily have a series of "close/reopen", "edit", and "X" buttons if needed.  It might be better to put this on the edit form.

@imawh, thanks for the feedback!  I'll adjust the mockups based on this discussion.

After some discussion with @sfount, I'll also add the "Set Beginning Balances" directly in the "Create Form" for the initial fiscal year, in the same location as "Close Previous Fiscal Year" is on the other page.  I'll also remove the "Close Previous Year", and move that functionality onto the list view.

**Comment by jniles** [comment]
This has largely been completed.  For more up to date issues on fiscal years, see https://github.com/IMA-WorldHealth/bhima-2.X/issues/1651, https://github.com/IMA-WorldHealth/bhima-2.X/issues/1646, and https://github.com/IMA-WorldHealth/bhima-2.X/issues/715.
