### ISSUE TITLE
Report for transfers from Cashbox

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2792]
With the work that AG Neron is doing, it is becoming evident that a useful report should show the transfers between cashboxes for auditing purposes.  The following information is being used:
 1. Date
 2. Principal Cashbox Balance
 3. Aux Cashbox Balance
 4. Amount Transferred.

I propose we make a generic report for cash transfers that allows a user to select a cashbox/currency and a period.  The report would then show all the transfers between the first cashbox and other accounts from the general ledger by filtering on Transaction Type = "Transfer" and having the cashbox account.   It would look something like this:

| Date | Balance Before |   | Transfer Amount | Destination | Balance After |
|:----:| --:|:---:| ----:|:---- | ----:|
| 04/06/18 | $10 |  --> | $5 | _Primary Cash_ | $5 |
| 05/06/18 | $5 |  --> | $5 | _Pax Cash_ | $0 |
| 09/06/18 | $0 |  <-- | $15 | _Primary Cash_ | $15 |

**Comment by jniles** [comment]
It might be useful to have the following options:
 1. **Expand Days** - It will show every day in the period, even if the period's days have zero transfers.  This way a user can easily see what days transfers were not made and correct them if needed.

**Comment by Scholldier** [comment]
I'd like to take a shot at this issue! As it's a report, I'm thinking it'll be a good 'first' to tackle. :) Just to be sure -- the table in play for this is primarily the 'cash' table, correct?

**Comment by jniles** [comment]
This actually exists now, thanks @lomamech.  It's called "Analysis of Auxiliary Cashboxes".
