### ISSUE TITLE
Proft & Loss By Month Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2799]
The Profit & Loss report is good for comparing periods between fiscal years.  We also need a Profit and Loss compared to the previous month(s).  This should be a separate report from the Profit and Loss report.

The Profit & Loss By Month report should give the user the following options:
 1. Select a Fiscal Year
 2. Select a Month (within the above Fiscal Year)

The report will produce a report that looks similar to the Profit & Loss Statement.  However, instead of comparing the accounts in the current month to the previous year, it should compare the current month to the previous month, and the month before that.  Logically, it will be:
 1. Current Month
 2. Current Month - 1
 3. Current Month - 2

See the current Profit & Loss Statement below for inspiration:
![proftandlossstatement](https://user-images.githubusercontent.com/896472/40776541-f1c35138-64c2-11e8-8128-95393a2f4707.PNG)
_Fig 1: Profit and Loss Statement_

**Comment by jniles** [comment]
@jeremie, this should be pretty easy.  Since you just completed the analysis of Income and Expense, would you be able to work on this report this week?

**Comment by jeremielodi** [comment]
Yes, let me give it a try.

**Comment by jeremielodi** [comment]
This issue should be closed

**Comment by jniles** [comment]
Closed in #2834.
