### ISSUE TITLE
Cashflow by Service report should filter by cashbox

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2805]
The Cashflow by Service ("Journal De Ventilation") report does not give the user the possibility to filter by cashbox.  In an institution with multiple cashboxes (such as IMCK), this doesn't make any sense.  See below:

![nofilterbycashbox](https://user-images.githubusercontent.com/896472/40830776-2ed69c76-657f-11e8-9ed0-25e2a764a5b4.PNG)
_Fig 1: Current options on Cashflow By Service_

This should be corrected by adding the `<bh-cashbox-select>` component to the page.

**Comment by jniles** [comment]
Note: this report should also present the option of showing values in all currencies supported by the enterprise, at the exchange rate of the day.

**Comment by jniles** [comment]
@mbayopanda, since the team here seems to be really interested in the "Ventillation" report, could you look at making these changes?  That way we can deploy it and test it pretty quickly.

**Comment by jniles** [comment]
I'll grab this since I have more free time.

**Comment by sfount** [comment]
Closed by #2866
