### ISSUE TITLE
Budget vs Balance Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2807]
An important report for managers and financial analysts is the budget versus balance report.  Note that the report depends upon the implementation of #267.

### Budget versus Balance
The budget versus balance report is very similar to the Profit and Loss Statement.  It concerns only income and expense accounts.  The idea is to compare the income and expense accounts against what the budget has for the income and expense accounts.  Importantly, the report should show the variance between what has been budgeted and what was actually received.

**Comment by sfount** [comment]
Looks like this issue was caught in the wrong reference! #2866 submitted work on a different report.
