### ISSUE TITLE
(design) merge algorithm for Location Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#281]
This issue is a proposal for a merge algorithm to power the "merge" feature of Location Management (#273).
##### Procedure
1. The client sends an HTTP `PUT locations/merge` request to the server, containing the body `{ oldUuid : 'some-uuid', newUuid: 'some-uuid' }`.
2. The server passes the body to `locations.merge()`, which runs the `merge` routine (see below).
3. The server returns a `204 No Content`  to the client, indicating a successful merge.
##### Merge Routine
1. The server first confirms that both `oldUuid` and `newUuid` exists in the `village` table.  If it does not exist, the server throws a `404 Not Found` error to the client.
2. The server then scans through a list of all tables with location ids, executing
   
   ``` sql
   UPDATE {{table}} SET {{ column }} = {{ newUuid }};
   ```
   
   wrapped in a transaction.
3. If there are no errors, the transaction is resolved without any data.

**Comment by imawh** [comment]
If you've been consistent naming table columns using locationId you can have mysql schema dbf to dump a list of all tables with that column name to load an array and then cycle the sql update thru all tables .... making sure a minor error doesn't prematurely stop the process .

**Comment by jniles** [comment]
@imawh, interesting idea.  I'll have a look.

**Comment by imawh** [comment]
The advantage being if you add or delete tables with locationid any time in the future the code just works.

**Comment by jniles** [comment]
NOTE: This has been implemented in https://github.com/Vanga-Hospital/bhima-2.X/pull/71.

**Comment by jniles** [comment]
Closed in https://github.com/Vanga-Hospital/bhima-2.X/pull/71.
