### ISSUE TITLE
Add a new toolkit on journal voucher  to enable purchase order payment

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2817]
This toolkit should allow you to select the cashier as well as the purchase order, the employee responsible for the purchase (only confirmed purchase orders will be able to be paid)

**Comment by lomamech** [comment]
I propose to close this issue, the fact that it might perpetuate the error that existed in bhima 1X, indeed when associating an employee to the payment of a purchase order was used the account associated with the group creditor of the employee at when one should use an account relating to advances on purchase, that's why it would not be necessary to have a tooltip for payments of purchase orders, simple use of the JournalVoucher module could be enough to solve this problem

**Comment by jniles** [comment]
Seems logical to me.  :+1:
