### ISSUE TITLE
Proposal: Server Controller Structure

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#282]
Our current server structure is a bit scattered.  We should formalize it as we begin to implement reporting receipts (see #258), reports, and the server-side posting journal core.

I propose that we group common modules into common folders.  Like we are currently doing with `financial`, `hospital`, etc, we can also group related functionality together.  For example, our patient routes could be under `patients/*.js` like this:

``` sh
patients/
  invoices.js        # this is patient invoicing (/sale)
  index.js           # this is the main patient controller
  groups.js          # manages patient groups CRUD
```

This pattern doesn't fit all modules cleanly (what should we do with `projects.js`?), but it would help with linked modules such as `patients`, `inventory`, `stock`, etc.  Partially inspired by [koajs](http://koajs.com/)

\cc @IMA-WorldHealth/local-contributors

**Comment by sfount** [comment]
I agree that the server controllers could be organised more intuitively. 

It seems to me that these two are opposing ideas:
**Organise by abstract category**

> Like we are currently doing with financial, hospital, etc,

**Organise by entity**

> ``` sh
> patients/
>   invoices.js        # this is patient invoicing (/sale)
>   index.js           # this is the main patient controller
>   groups.js          # manages patient groups CRUD
> ```

One would place invoice.js in `financial` and the other would place it in `patients` - is the proposal to favour the latter in place of the former? 

Right now the folder structure was done _very_ quickly whilst re-factoring away from large files containing many controllers - it was not carefully considered.

**Comment by jniles** [comment]
@sfount, good points, I hadn't thought of it in detail. If I come up with a decent proposal I'll make it.  For now, I'll close this issue, since I jumped the gun a bit with it.  I'll reopen it when we have a more solid idea of what the server components are (receipts, posting journal, etc) and we can start to design a nicer folder structure.
