### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by nunojesus** [third-culture-software/bhima#2822]
Hi, first congrats for your project.
I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by jniles** [comment]
Hi @nunojesus, thanks for you offer!  Graphic design is a great way to contribute to OS projects as many of us aren't designs are prefer to command line :).  Our team is currently in the field doing some training and we'll be back online later this month.
