### ISSUE TITLE
Remove `creditor_uuid` from `patient`

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#284]
It seems to me that we never use a patient's `creditor_uuid` field.  Do we even need that link?  Can it be refactored out?

**Comment by sfount** [comment]
I've never written code that considers the patient entity as a creditor.

**Comment by jniles** [comment]
:+1:

**Comment by jniles** [comment]
If that is the case, in my opinion, this can be refactored out as part of any of the patient reviews.

**Comment by jniles** [comment]
@lomamech, peux-tu travailler sur cette issue?

**Comment by jniles** [comment]
Closed via #328.
