### ISSUE TITLE
bug(invoice registry): huge loading time even if there is no data

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2844]
The invoice registry takes a lot of time to load data into the grid even if there is no data the loading indicator still takes a lot of time.

**Comment by jniles** [comment]
It would be good to have a network log for this - otherwise, it's difficult to know if it was the network or application.  Could you snap a network log using the inspector in Chrome?

**Comment by jniles** [comment]
So, @mbayopanda and I investigated this, and it seems to happen on his machine in particular in the database.

@jeremielodi @lomamech do you guys have the same issue?

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2964.
