### ISSUE TITLE
Add new provinces as localisation for DRC 

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2845]
This issue is about to use the actual (new) provinces as localisation for DRC

**Comment by jniles** [comment]
This is a data issue, no?  I don't think we ship with any provinces besides the one for testing.

I propose we work with IMCK to update/clean their locations.

**Comment by jniles** [comment]
I think this got fixed in https://github.com/IMA-WorldHealth/bhima-2.X/commit/02c9f9034076f3613fa7d82a4f49a1fb69951f01.
