### ISSUE TITLE
(Proposal) Use 404 page for invalid routes vs. redirecting to /landing

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#285]
Currently if an invalid URL is entered the client will redirect to `/#/`. Some comments: 
- This is difficult to test - was this redirect as a result of an error or did we actually want to go to the home screen 
- Confusing user experience - I had intended to get somewhere but I've been forced to the home screen 

This was a good first step to handling this problem however I think we should now introduce a 404 pages providing a clear user experience and context. 

(It may also lead to having a good idea of how to implement NOT_AUTHORISED pages and structures) 

@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
A 404 page is a good idea.  The redirect is far too confusing as it is.  I'm behind this proposal.

**Comment by jniles** [comment]
This was closed in #476.
