### ISSUE TITLE
Prevent Billing and Ordering

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2901]
- Prevent billing of items that are missing profit accounts
- Prevent the ordering of items that are missing expense and inventory accounts

**Comment by jniles** [comment]
We handled the first case a long time ago at Lukonga ... I wonder what happened?

**Comment by lomamech** [comment]
There was a case at HBB where an Inventory belonged to an Inventory group that did not have a profit account, we had to go to Accounting to add a Profit Account to this inventory group

**Comment by jniles** [comment]
I'll look into it and try to fix it.
