### ISSUE TITLE
Cashbox Selection displays no cashboxes error even when there are cashboxes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2912]
The cashbox selection modal now shows the "no cashboxes" error, even when there are cashboxes.  See below:

![bugcashboxes](https://user-images.githubusercontent.com/896472/41715104-4bdaf0bc-754a-11e8-92f5-a39329de75ff.PNG)
_Fig 1: This error should be hidden_

We need to fix this since it doesn't make any sense.

**Comment by jeremielodi** [comment]
@mbayopanda can you close this issue. it was solved at #2920

**Comment by jniles** [comment]
Closed in #2920.
