### ISSUE TITLE
Improve Report/ CashReport/ (Add Report Income and Expense Report)

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#2926]
- This two reports makes it possible to know the instantaneous situation of the movements that there was at the level of the boxes, the entries as well as the Outputs, it is report which allow the Audited Accounting the Caisses in particular the Caisse principal

**Comment by jniles** [comment]
How is this different from the Cashflow report?   My understanding is that this is what cashflow was for.

**Comment by lomamech** [comment]
@jniles   at I thought the Cash Report only showed the transactions that are in the general Ledger, reason why I thought we should add a new Income and Expense Report, and when I wanted to start the implementation From this new report, I inspected the server / controllers / finance / reports / cashReport / codes that I realized that this report did indeed look at the PostingJournal and the GeneralLedger after studies I discovered that the search did not include not correctly Date related settings, The PR I'm going to do is going to Correct This Issue, and tomorrow The Main Checkout to now Use this Report without a Problem

**Comment by jniles** [comment]
Aha - glad to hear this.  Good work!

Can we close this issue?
