### ISSUE TITLE
Receipts - 2.x Review

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#295]
This issue tracks progression on the core receipts feature originally introduced https://github.com/IMA-WorldHealth/bhima-2.X/issues/258. 

**Required** 
- [x] HTML renderer to template and return a valid HTML string 
- [x] PDF renderer to template and compile PDF documents to be returned as receipts
- [ ]  (bug) Print style only allows the printing of two pages (this is an overflow-y issue as documented in the print style CSS)
- [x] Loading state for waiting for the receipt request promise to be resolved 
- [x] Handle errors within the receipt modal controller, renderer not shown but error state reported

**Comment by jniles** [comment]
@sfount, can this be closed?

**Comment by jniles** [comment]
Closing this as no longer relevant.  I believe it has been fixed.
