### ISSUE TITLE
Bug(fiscal year): Balances are not displayed correctly

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2969]
This issue is about a bug in the Fiscal year module, the option of seeing the closing balance doesn't display information correctly : 

![image](https://user-images.githubusercontent.com/5445251/42369764-d222f976-8102-11e8-9aea-32e476997128.png)

The module still use a function which have been removed `Fiscal.periodicBalance`, and also there are values in credit and debit column for the opening balance : 

![image](https://user-images.githubusercontent.com/5445251/42369935-4bc1bd4e-8103-11e8-8aea-4e359d11f7a5.png)

**Comment by lomamech** [comment]
@mbayopanda, I have the impression that the PR #2978 closes this issue

**Comment by mbayopanda** [comment]
Already closed by #2978
