### ISSUE TITLE
Add new module : Reference management

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2973]
This issue is about to add a new module `Reference Management` for handling account reference, it is kind of accounts tags management.

The module can be as 2.X administration module with a grid for listing all references, and modal for add or update reference.

For a reference we can have : 
- Abbreviation : ex. CA
- Label : ex. Capital
- Accounts : A list of accounts
- Exception Accounts : A list of accounts to exclude
- Parent : A parent if necessary of the reference 

Here is a bilan with references : 

![bilan-references](https://user-images.githubusercontent.com/5445251/42565283-ed81728c-84fa-11e8-98e7-ed2fe8e5d6c0.jpg)

The goal is to have a mean of having balance of a given group of accounts

**Comment by jeremielodi** [comment]
This issue was already solved by @mbayopanda , I think it can be closed

**Comment by jniles** [comment]
@jeremielodi is right.
