### ISSUE TITLE
Change install documentation to use wkhtmltopdf version 0.12.4

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3038]
The installation documentation for BHIMA does not include a specific version since wkhtmltopdf did not update itself in ~2 years.  But [the released version 0.12.5](https://wkhtmltopdf.org/downloads.html) earlier this summer and it breaks our PDF rendering unit test (since the report renders slightly differently).

In the long run, it would be nice to transition over to the new wkhtmltopdf version, but we would have to ensure that every report continued to behave the same.  In the short run, the most practical thing is to explicitly list 0.12.4 as the required version.

@Scholldier would you be willing to include this in your installation documentation changes?

**Comment by Scholldier** [comment]
You bet! 👍
