### ISSUE TITLE
Changing roles does not reset the user's permissions in real time

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3043]
When a user updates permissions for their own role, nothing happens.  Previously, when we had a mapping of user->unit, it would refresh the list of units in the tree and reset their session on the server.  This made it so they could begin to use the application right away without needing to log out and log back in again.  It would be great to have this functionality again.

This was the original issue from before we had roles:  https://github.com/IMA-WorldHealth/bhima-2.X/issues/1819

**Comment by jeremielodi** [comment]
This issue seems to be very easy to be solved but I'm afraid about the end to end test, the user will be disconnected and the test will restart or some thing like that

**Comment by jniles** [comment]
It shouldn't have any effect - we did the same thing for permissions previously without any issues.

**Comment by jeremielodi** [comment]
I see.
