### ISSUE TITLE
Use bhInlineFilter on Role Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3056]
If you ever have a long list of roles, locating a single one can be a nightmare.  We need to have a `bhInlineFilter` button on these pages.  You can see an example of one in the accounts management module code.

**Comment by Scholldier** [comment]
I see where the code is referenced in /client/src/modules/accounts/accounts.html and accounts.js for the inline filtering. I added the code from the .html file to the roles.html file, and I get the filtering icon. However, making the filter actually occur is elusive. 

Can you point me in the right direction? I tried adding the inline filter toggling code at the bottom of accounts.js to the roles.service.js and roles.ctrl.js files, but that didn't work.

**Comment by jniles** [comment]
Hey @Scholldier,good to have you working on this!

Yes, the line of code in [accounts.html](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/accounts/accounts.html#L61) you are looking for is this one:
```html
      <bh-filter-toggle on-toggle="AccountsCtrl.toggleInlineFilter()">
      </bh-filter-toggle>
```

The `AccountsCtrl.toggleInlineFilter()` is the callback function that tells the [accounts controller](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/accounts/accounts.js#L233) to show or hide the inline filter using this code:
```js
  /**
   * @function toggleInlineFilter
   *
   * @description
   * Switches the inline filter on and off.
   */
  vm.toggleInlineFilter = function toggleInlineFilter() {
    vm.gridOptions.enableFiltering = !vm.gridOptions.enableFiltering;
    vm.api.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
  };
```

The above code is telling the grid to enable inline filtering by setting `gridOptions.enableFiltering` to it's opposite (be default, it is false).  We use [ui-grid](http://ui-grid.info/) as our grid component - [here is the documentation on filtering](http://ui-grid.info/docs/#!/tutorial/Tutorial:%20103%20Filtering) if you are interested.

Basically, we need to do the same thing to role management.  First, we need to get the [roles controller file](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/roles/roles.ctrl.js) and add in code to set the `enabledFiltering` flag on the `gridOptions`.  The variables are mostly named the same, so you couple probably just copy and paste the accounts code in there.  The only change needed is to rename `vm.api` (which is the grid's api set in the `onRegisterApi()` function) to `vm.gridApi` (which is what we called it in [roles.ctrl.js](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/roles/roles.ctrl.js#L100)).  In the end, it should look something like this:
```js
  vm.toggleInlineFilter = function toggleInlineFilter() {
    vm.gridOptions.enableFiltering = !vm.gridOptions.enableFiltering;
    vm.gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
  };
```

Now, you'll need to inject the `uiGridConstants` object into the roles controller.  To do this, you'll need to import it by name, by putting the string 'uiGridConstants' into the end of the [RoleController.$inject](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/roles/roles.ctrl.js#L4) array.  Secondly, you'll need to add the `uiGridConstants` as the last parameter to the [RoleController function](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/roles/roles.ctrl.js#L9).

If you have any more questions, let me know!

**Comment by Scholldier** [comment]
Jonathan, your explanations are seriously amazing. Major props! I'm going to read into the documentation you sent for the filtering, that's much appreciated. I'll also throw in a PR for this as I just tested the code. 👍
