### ISSUE TITLE
Set Stock Accounting optional via the enterprise settings

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3099]
The current state of BHIMA force to write stock operations directly in the posting_journal, so for using stocks we must define all accounts settings for inventory and inventory groups first.

For an instance of bhima which doesn't require to use accounting or for an enterprise which use stock management according the 'Inventaire intermittent' method _(which require to write stocks operations in the journal just a the end of the fiscal year)_, there is no need to configure accounts for inventory or inventory groups.

This issue is about to add an option in the enterprise setting, to choose if stocks operations must write into the posting journal or not.

If the user set that stocks operations must not write directly into the posting journal, stocks modules will skip all operation relates to accounts or accounting.

**Comment by jniles** [comment]
Hey, this is a really great idea.  An enterprise setting is a good way to start - eventually, we'll probably want to build different "flavors" of BHIMA that support a Stock w/o Finance and Finance w/o Stock, etc. 

Great suggestion!

**Comment by mbayopanda** [comment]
@jniles @lomamech @jeremielodi 

What do you think about this issue ?

**Comment by jniles** [comment]
Closed in #3151
