### ISSUE TITLE
Use Winston to configure logging

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#31]
We currently use [morgan](https://github.com/expressjs/morgan) middleware for logging HTTP requests and connections.  Unfortunately, it does not support generic logging (for example, events or thrown errors) and only listens to HTTP connections (not available in libraries).

[Winston](https://github.com/winstonjs/winston) provides a highly configurable logger that gives us the remaining functionality we lack.  It supports the idea of log levels (for example, verbose, production, silent, ...) and outputs seamlessly to files.  I propose we use it to compliment morgan, which seems to do a good job at logging HTTP requests.

**Comment by jniles** [comment]
@IMA-WorldHealth/local-contributors, is there any discussion here?  I'm hoping to introduce a PR this week that supports Winston.

**Comment by sfount** [comment]
LGTM. Worth getting right. Log levels will be useful for debugging + integration/E2E output.

**Comment by DedrickEnc** [comment]
Just try it and we will have the all next week to appreciate it.
