### ISSUE TITLE
Cashbox access permissions - no changes results in Server 500 Error

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#3118]
Submitting the cashbox access permissions modal without making any changes results in the 500 error returned from the server. 

To replicate: 
1. Load the User Management module 
2. Edit the first users cashbox permissions with `Actions` -> `Cashbox Management` 
3. Click Submit

A number of things should be happening here: 
* Ideally - The client recognises no changes are made and makes no GET requests to the server 
* [x] Required - The server handles a no changes state and returns 200 success or 400 bad request depending on this specific API end point 
* [x] Required - A test is written to ensure this is covered, sending no changes should not break the server

The client also does not respond to the 500 error with a user facing notification, this failure is silently logged to the console. 
* [x] Required - Client responds to server error for cashbox permissions submission

Bonus:
- [x] The client side modal 'rejects' even on submission - this needs to be standardised across the client.

**Comment by jniles** [comment]
Yeah, I just ran into this as well.  Good catch.

To round this out:
 1. If no changes occur, we can use the same pattern as on the patient record page and just flash "no changes detected".

I feel that the server should send a 400 if the update API is called without giving a list of cashboxes.  That way, the client can handle it properly with a message.

**Comment by sfount** [comment]
I had code ready to resolve this issue but didn't get around to writing the PR - sorry for confusion.
