### ISSUE TITLE
Proposal: rename user creation fields to match data model

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#3119]
The user creation modal currently has fields for **'username'** and **'login'**. Even as someone who is familiar with the web and computers I am not sure how to differentiate these two fields. 

![screenshot from 2018-09-01 21-30-22](https://user-images.githubusercontent.com/2844572/44949692-9b2dd180-ae2e-11e8-9f84-b260094bceea.png)

These inputs correspond with database values: 
* Login - `username`
* Username - `display_name` 

I propose that everywhere we show user information with a field (this create modal and the users table for example) we use 'Username' and 'Display Name' labels. 

It may even be useful to put a short text description like

Username: 
_This is the user's identifier for the system, it should be short and memorable and will be used every time they log in._ 

Display Name:
_The user's full name, this is displayed on any formal documents or receipts processed by the system._

**Comment by jniles** [comment]
Yeah....  That is kinda silly of us, wasn't it?

I agree with your proposal.  That would clear up a lot of confusion!

**Comment by jniles** [comment]
So, another thing of interest is that the unique validation is on the display_name, not the username.

I'll clean this up.
