### ISSUE TITLE
UI/UX Improvements on Users and Permissions Management module

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#3120]
The 'Users and Permissions Management' module is now out of sync with the latest repository standards, it should be updated so that the same user experience can be expected across modules. 

1. - [ ] Order users first by *deactivated* and second by *display_name*. Deactivated users should be shown last, followed by display names A-Z
2. - [ ] Deactivated users are shown with a line through the username and display_name fields, this was originally a clean implementation however isn't found anywhere in the application. A standard should be researched and implemented here - many tables use a red (disabled) row background to demonstrate a row is reversed or disabled, potentially this could be used. 
3. * (Proposed) Clearly show in the users table which users have no permissions. Users with no permissions will not be able to login to the system and are essentially useless until they have been assigned a role. It should be made very clear to users that something else needs to be done before the profile can be used. Potentially this could be an icon that can be hovered for an explanation. (It could be that a 'Status' Icon column is added that can differentiate between 'Active', 'Deactivated' and 'Needs Roles'. 
4. - [ ] Actions column left aligned with a `max-width`

**Comment by jniles** [comment]
I think this was tackled at the same time as #3122.
