### ISSUE TITLE
UI Improvements on Cashbox Management module

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#3122]
Similar to https://github.com/IMA-WorldHealth/bhima-2.X/issues/3120 there are a number of tweaks to the Cashbox Management module that will make it simpler to use for people that already understand the BHIMA UX. 

1. - [x] Create label should be applied to the Cashbox Management segment of the headercrumb, not in it's own segment
![screenshot from 2018-09-01 23-44-10](https://user-images.githubusercontent.com/2844572/44950504-0b455300-ae41-11e8-8f75-91e4c1ed2f26.png)

(For example)
![screenshot from 2018-09-01 23-45-36](https://user-images.githubusercontent.com/2844572/44950509-2617c780-ae41-11e8-89c5-127860c94ceb.png)

2. - [x] A standard should be proposed for 'danger' actions on management pages and then followed, Cashbox Management here could potentially follow Debtor Group Management (Danger Zone may need to be renamed to something users can clearly understand - this could be researched)
![screenshot from 2018-09-01 23-47-42](https://user-images.githubusercontent.com/2844572/44950526-c5d55580-ae41-11e8-986b-2a622f44bb66.png)
![screenshot from 2018-09-01 23-49-36](https://user-images.githubusercontent.com/2844572/44950527-c5d55580-ae41-11e8-91e9-725a90a6c35b.png)

3. - [x] (See https://github.com/IMA-WorldHealth/bhima-2.X/pull/3121) The 'Edit' button on management pages like this should be changed to 'Manage' or 'Configure' to reflect what you are able to do. For example on cash boxes you can do many things other than edit, for example edit the name, change currency accounts, view users with permissions etc. One suggestion would be 'Manage Cash Box'. 
![screenshot from 2018-09-01 23-52-18](https://user-images.githubusercontent.com/2844572/44950542-50b65000-ae42-11e8-9c7e-b95e7cafa5e9.png)

3.a. 
- [x] This change should also be made on the Debtor Group Management module 
Issue to track https://github.com/IMA-WorldHealth/bhima-2.X/issues/3148

**Comment by jniles** [comment]
There are some good ideas here.  These pages are used so infrequently that it probably isn't worth _too much_ time trying to get right, but we can definitely do better.

I think we might want to do away completely with the current cashbox configuration page - it's very similar to the old 1.x - style of configuration.  It would probably be nicer to have them in a debtor-groups style layout without an extra modal to configure each currency.  What do you think of going down that route?

**Comment by sfount** [comment]
@jniles Completely agree, there's no need to assign a lot of resources to this, I'll assign this to myself and get it out of the way ~~today~~ ASAP. 

I agree that it should fit the more up to date style (debtor groups) for listing entities, the underlying code is actually the same as debtor groups making the most up to date use of `ui-router`. 

Something that is needed across all management pages is a uniform way of implementing the entity lists, right now every module controller implements them in their own different way, this would be an ideal candidate for a component. This could potentially be a good time to fit that in, I'll follow this up with an issue.

EDIT: https://github.com/IMA-WorldHealth/bhima-2.X/issues/3135
