### ISSUE TITLE
Proposal: replace .env.* with .env and add it to .gitignore

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#3146]
In the `master` branch there is currently a `.env.development` file checked into the git repository. I proposed that we restructure our environment infrastructure so that we can remove this and follow the environment file best practices. 

### The problem: 
Our current development tasks rely specifically on `env.development`. Because this file is checked into git this file cannot be updated to your local environment variables without it being tracked as a code change. The purpose of environment files is to seperate the repository code from each environment, this includes development. 

### Proposal: 
* Remove `.env.development` from the version history - dotenv - [Should I commit my .env file?](https://github.com/motdotla/dotenv#should-i-commit-my-env-file)
* Remove any parsing of `.env.${environment}` from the server in favour of a single `.env` file - [dotenv - Should I have multiple .env files?](https://github.com/motdotla/dotenv#should-i-have-multiple-env-files) 
* Check in a `.env.sample` file into the repository demonstrating exactly how a file should be structured and what it should be contained 
* Update the 'Getting Started' and 'Installation' guides to clearly describe how to copy `.env.sample` into `.env` and customise it to fit your setup
* Update continuous integration services to correctly set the `.env` file according to their needs 
* Specify upgrade plan for current production servers using the `.env.production` method, this will most likely just involve copying `.env.production` to `.env`
* Bonus: Make sure the server understands if there's a missing environment file and gives a clear error with instructions on how to resolve this

**Comment by jniles** [comment]
This has actually caused issues in production at least 3 times now.  Considering that we have so many production instances, this probably should be addressed.

**Comment by jniles** [comment]
@kwilu claim
