### ISSUE TITLE
Showing and Hidding columns 

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#316]
In order to make our posting journal UI complete, we have to add showing/Hiding functionnality

My proposal about this functionnality is to have a button which can show a dialog when pressed, the dialog will show a list of columns shown and hidden so the user can change their states.

Once the user apply the change, the system should be able to remember this choice.

bellow, an picture example 
![journal coulmns config](https://cloud.githubusercontent.com/assets/5418919/14528109/d03d1512-0245-11e6-9639-a89992250a4e.png)
FtPNer.jpg)

**Comment by sfount** [comment]
This mock-up and description is very clear! 

I have a few questions: 
1. Is it necessary to include the the help text with the title 'Show or Hide Columns'? From this it is clear to me what this component does.
2. Should there be a cancel/ close button on the modal to allow the the user to cancel the operation?
3. Will there be a system default column settings that can be returned to by pressing a button? 

This suggestion looks excellent to me - implementation on this can begin as soon as possible.

**Comment by jniles** [comment]
Looks good to me.

If we do include the help text, I think it should not be an `.alert` -- it would be better to just either a `<p>` or a `<label>` element.  Alerts are usually used for notification or errors, rather than help text.  We've used this pattern in the past, but it isn't ideal.

Is the selection remembered in appcache?  Or in the database?  Or neither?

**Comment by DedrickEnc** [comment]
@sfount @jniles 

I will add a button to cancel the operation, and will use our appcache service to perform the possiility of remembering.
The only question, I have now is is it a good idea to return back every columns of the table for the first time?

**Comment by jniles** [comment]
Following @sfount's suggestion, I would only use a subset of the columns as "default" columns.  Specifically, these columns:
1. Transaction Number
2. Account ID
3. Debit
4. Credit
5. Description
6. Date
7. Entity (we'll find a way to format this UUID better later)
8. Reference (we'll find a way to format this UUID better later).

All columns would be available, but these I would choose to show by default, until the user changes them.  When the button "reset to default" is pressed, it would reset those basic columns.  What do you think?

**Comment by DedrickEnc** [comment]
I had not this idea of resetting, good idea!
