### ISSUE TITLE
report(stock) : stock lots report

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3179]
Add a configurable report for knowing available lots in each depot and their quantity, and also lifetime, lot lifetime and risk.

Bhima has already a registry for that, but it miss a configurable report in which we can set : 
- A depot
- An inventory
- Custom months of stock for articles
- Custom lifetime for articles

**Comment by jniles** [comment]
I'll tackle this one.

**Comment by jniles** [comment]
@mbayopanda, by "lifetime", do you mean the time before the stock will expire?  So, like "3 years" or something like that?

We might think about adding an "inventory type" selection as well, in case we want to look up things that don't expire, like Telephones.

**Comment by jniles** [comment]
I think this exists with the Stock Quantity Report.
