### ISSUE TITLE
fix(stock file) : display only inventory which can be in stock

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3186]
The stock file report displays also inventory which are not article in stock (not consumable) in the inventory selection list.

![image](https://user-images.githubusercontent.com/5445251/45745214-46dd6c80-bbf8-11e8-92dd-d9b8a6d5a3ec.png)

**Comment by jniles** [comment]
Basically, we just need to filter on `consumable` right?

**Comment by mbayopanda** [comment]
Yes

**Comment by mbayopanda** [comment]
Yes
