### ISSUE TITLE
Stock Features for production

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3199]
The BHIMA software will be deployed for managing assets like phone in multiple areas and depots following the diagram bellow : 

![stock bhima production](https://user-images.githubusercontent.com/5445251/46136000-83cfe180-c23e-11e8-9180-fb03eff2c1e3.png)

For each depot, we must be able to : 
- Perform entry and exit of stocks
- Having an historic of entry/exit movements
- Allow to assign stock lots to person or organization (The assignation is not an exit, it is just for knowing who has what)
- Having an historic of all assignation of lots
- Allow to tag lot (for example : broken, has battery, etc.)

Also, for all entry/exit movement we must have information about the person who receive or the person who send lots.

According the current state of bhima, these features bellow must be implemented : 
- [x] CRUD for person and organization
- [x] CRUD for tags
- [x] Assignation module for assigning lots to person or organization
- [x] Assignation historic for tracking all assignation of lots
- [x] Lot Tagging Feature for tagging lot
- [x] Lot Editing for editing existing lot (for example, update tags or label)

**Comment by jniles** [comment]
Beautiful diagram :+1:

**Comment by jniles** [comment]
@mbayopanda, can you review this and see what we still need it or if it can be closed?

**Comment by mbayopanda** [comment]
These point are not yet done : 
 - [x] Lot Tagging Feature for tagging lot
 - [x] Lot Editing for editing existing lot (for example, update tags or label)
 - [x] Adding Person Sending and Person Receiving input box in the stock entry/exit forms

For the last one, i don't remember its importance. I think we can remove it from the list

**Comment by jniles** [comment]
I think that was when we were trying to assign lots to people.  Let's remove it for now and re-introduce it if we will ever use BHIMA in that capacity.

**Comment by jniles** [comment]
@mbayopanda, what of this is left to be done?

**Comment by mbayopanda** [comment]
We have already a tag management module, but we don't have a lot tagging feature yet. So, we don't have : 
- [ ] Lot Tagging Feature for tagging lot

**Comment by jniles** [comment]
This was implemented in #4762.
