### ISSUE TITLE
CRUD for person and organization

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3200]
This issue is about to add a module for adding person into BHIMA.

We can add a tables `person` and `person_type`, such as : 

The `person` table has as attributes : 
- uuid
- display_name
- sex
- address
- person_type_id

The `person_type` table has as attributes : 
- id
- text

Inside the `person_type` table we can have as record: 
- Physique : a person physique like a human
- Moral : a person moral like an enterprise or organization.

At the end, we must have in bhima for person managment : 
- A module for add, edit and delete person or person_type
- A registry for person and person_type

**Comment by mbayopanda** [comment]
@jniles what do you think instead of `person` having `entity` and `entity_type` tables with the same structure as for person describe above but for entity_type we can have as record : 
- person
- enterprise
- service
- office
- etc.

**Comment by jniles** [comment]
I prefer `entity` to `person`.  That seems like a good change 👍

**Comment by jniles** [comment]
@mbayopanda can this be closed?
