### ISSUE TITLE
CRUD for Stock Tags

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3201]
This issue is about to add a module for create, read, update and delete tags in BHIMA.

Tags can be assigned to many kind of element in bhima for example stock lots.

As tag, we can have : 
- Broken
- Repaired
- Any name we want

At the end, we must have a module for creating, editing or deleting tags; and also a tags registry.

Having a component for selecting tags will be also better.

**Comment by jniles** [comment]
We have a couple of issues about tags.  For example, #1802.

@mbayopanda do you think we should make a single table for tags?  .e.g have a MySQL table `tag` with a route `/tags`, `/tags/:id`, etc?  Or should we make them specific to the type of tag? `stock_tag`, `account_tag`, etc?

**Comment by mbayopanda** [comment]
@jniles having a single table is better because it helps us to do not have duplicated table structure and also we will have just on set of integration tests for this single table.

Certainly we will have other tables for the link to other logic, for example: 
- stock_lot_tags : could contain lots and associated tags
- account_tags : could contain account and associated tags

**Comment by jniles** [comment]
Sounds good.  Let's make it a single table then.
