### ISSUE TITLE
Stock Assignation module for assigning lots to person or organization

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3202]
This issue is about to add a module for assigning stock lots to person so that we can know where is each lots supposed to be in a depot.

- The assignment is based on lot (stock lot), we can have a registry like : 
![assign grid](https://user-images.githubusercontent.com/5445251/48540633-e8143680-e8ba-11e8-95e8-b0c9f8c9c02d.png)

- The modal for adding a new assignment can be : 
![assing modal add](https://user-images.githubusercontent.com/5445251/48540656-fbbf9d00-e8ba-11e8-8bdf-b52676c6508b.png)

- The modal for editing an assignment can be : 
![assign modal edit](https://user-images.githubusercontent.com/5445251/48540672-09752280-e8bb-11e8-8af2-e60f73799f4f.png)

By adding this feature we must update the lot table for having a flag for assignment which will help us to do not consider assigned lots for stock exits.

@jniles what do you think about that ?

**Comment by jniles** [comment]
I think this has already been done.  Is that correct @mbayopanda ?

**Comment by jniles** [comment]
Confirmed offline!
