### ISSUE TITLE
Fast stock lots insert

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3204]
This issue is about to add checkbox in the lot modal for helping the user inserting quickly lot label with a codebar scanner for example

**Comment by jniles** [comment]
Basically, we need to implement an option that the user can turn on or off to change the behavior of the stock entry form.

If the user has "fast insert" on, there will be an `onChange()` event that will add a new line and focus the next serial number/lot number in the stock entry form as soon as an input has been made.  Alternatively, we could do it `onBlur()`.

It is important that the user is able to toggle this option on and off in case it causes problems or if they do not have a barcode scanner.

**Comment by mbayopanda** [comment]
@jniles what do you think about to have in the lot modal an checkbox for enable/disable the fast-insert feature, because the user can have some lots which can be used with fast-insert feature and some other which doesn't need the fast-insert feature.

So, if we put this feature (fast-insert) far away it can be difficult for the user to toggle between to use or not use the fast-insert feature.

Something like : 
![image](https://user-images.githubusercontent.com/5445251/46199601-5e5ada80-c307-11e8-89f3-b21934e3a617.png)

**Comment by jniles** [comment]
Looks good to me @mbayopanda.  I like it.
