### ISSUE TITLE
Fiscal year shows "no fiscal years found" while it is loading

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3207]
On a slow connection, the Fiscal Year page shows "no fiscal years found", even while it is loading.  See below:

![fiscalyearerror](https://user-images.githubusercontent.com/896472/46285734-68cddc00-c574-11e8-92f8-d0478b33befd.PNG)
_Fig 1: Confusing Fiscal Year Message_

This is confusing.  We should only show the message after the module has finished loading and the values are all settled.

**Comment by Scholldier** [comment]
@jniles 
Is this something that just requires a delay? Or more of a recode to place that message only if no data is available (thus, not really putting it on a timeout)? Just curious.

**Comment by jniles** [comment]
Hey @Scholldier, it's more of just a correction of logic.  Three states are possible:
 1. Loading
 2. Loaded w/ Failure
 3. Loaded w/ Success

Basically, we need to show a loading indicator in state 1, show an error in state 2, and show a success message (or the data), in state 3.  In some places, we show an error if there is no data, but the lack of data is because we are in state 1.

For this particular issue, the problem came from [line 59 of the Fiscal Year Controller](https://github.com/IMA-WorldHealth/bhima-2.X/pull/3208/files#diff-8d476a885669447063fd407526e93dceL59), which showed the "no fiscal years available" message if there were no fiscal years, but forgot to check to see that loading had finished first.
