### ISSUE TITLE
Design 2.x Receipt Layout

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#322]
The core technical structure for receipts in 2.x has been proposed and prototyped in https://github.com/IMA-WorldHealth/bhima-2.X/pull/315. 

This proposal includes a very temporary Angular Template that is populated with a `json` renderer. The core financial receipts should be designed and proposed so that they can be integrated into this technology stack and finalise receipts in 2.x. 
- [x] Patient invoice receipt 
- [x] Cash receipt 
- [x] Purchase Order receipt
- [x] Journal Voucher receipt 

**Receipts requiring discussion**
- Simple Transfer receipt 

**Receipt design constraints**
With the current implementation it is very flexible as to if a receipt should be rendered on the client (`json` renderer) or on the server (`pdf`/`html` renderer). My suggestion is that most receipts are rendered using the `html` renderer and returned to the client as valid html. That would imply: 
- Receipts must be designed with classes and styles available to the client - this is what will be displaying the HTML (only using bootstrap/ known structure styles) 
- Receipts should probably assume they are being rendered using `lodash` although this shouldn't have much influence on the design

**Comment by jniles** [comment]
@mbayopanda, could you take a look at some of these this weekend?

**Comment by jniles** [comment]
Most of these are completed.  The Simple Transfer does not produce a receipt, but could easily be made to use the `Journal Voucher` receipt for the present time, with further refinements based on feedback from our users.
