### ISSUE TITLE
Proposal: refactor cashboxes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#324]
I propose we refactor cashboxes in the following way:
1. Remove `is_bank`.  If necessary, banks can be modeled properly in bhima.  However, most bank transactions can be journal vouchers.
2. Rename the following columns:
   1. `is_auxillary` --> `is_auxiliary` (proper spelling)
   2. `text` --> `label` (consistency)
   3. `virement_account_id` --> `transfer_account_id` (English name)

Question: Do we need two separate `gain_exchange_account_id` and `loss_exchange_account_id` ?  Can we make this an enterprise setting and have a single account (`gain_loss_exchange_account_id`)?

**Comment by sfount** [comment]
This sounds like a good proposal, with the additional issue about gain and loss on exchange accounts https://github.com/IMA-WorldHealth/bhima-2.X/issues/327 this should mostly just be a cosmetic change. 

I agree that banks can be modeled completely separately if we need them - I assume they have lots of specific attributes not in common.

**Comment by jniles** [comment]
Sounds good.

In my cash posting journal PR, I'll be adding the `gain_account_id` and `loss_account_id` to the `enterprise` table as requested in #327.   Whoever tackles this issue can simply remove the dangling accounts on the `cash_box_account_currency` table.
