### ISSUE TITLE
Stock Export button needs padding

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3241]
The stock export button is pressed up against the "add items" button in the stock exit module. See below:
![stock - export to csv needs padding](https://user-images.githubusercontent.com/896472/46661071-6260e500-cbb0-11e8-8aa4-ba676bf8f984.PNG)

It would be nice to have some padding to make it look more professional.

**Comment by jeremielodi** [comment]
@jniles, Is this still an issue?

**Comment by jniles** [comment]
I don't think anyone has worked on it, no.

**Comment by jeremielodi** [comment]
I can't reproduce this issue. it seems to be fixed

**Comment by jniles** [comment]
Okay
