### ISSUE TITLE
Implementation of the report profit and loss account

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#3268]
the creation of the Profit and Loss Account report would be equivalent to implementing a report that will be related to that of the OHADA Balance Sheet, all these reports will use the Accounts References module to make the groupings of the accounts.

**Comment by jniles** [comment]
Let's call this "OHADA Proft and Loss" since it is specific to the OHADA accounting system.  We do a similar thing with the OHADA Bilan.

**Comment by lomamech** [comment]
Sorry Google Translate can't translate very well "COMPTE DE RESULTAT"
