### ISSUE TITLE
Cash cancellation interface looks out of date

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3269]
This is the interface to cancel a cash payment:
![better debit note interface](https://user-images.githubusercontent.com/896472/47213948-6b15a000-d394-11e8-852a-75b16b93666c.png)
_Fig 1: Debit Note Interface_

Compare this interface to the Credit Note interface:
![creditnoteinterface](https://user-images.githubusercontent.com/896472/47214047-ab751e00-d394-11e8-8ae5-dae6abc1498c.png)
_Fig 2: Credit Note Interface_

The Credit Note interface is a lot richer, providing details about the invoice that is about to be canceled in a familiar way.  It also clearly explains the history of the invoice.  Finally, it includes the human readable identifiers of the invoice and of the patient.  

We could do a similar thing for canceling cash payments.  It would be nice to see:
 1. The patient's reference
 2. The invoice(s) that was being paid
 3. A warning that this action is permanent and irreversible
 4. A link to the patient.

**Comment by jniles** [comment]
@jeremielodi, can you look into this?

**Comment by jeremielodi** [comment]
okay
