### ISSUE TITLE
Move the gain/loss on rounding accounts to the `enterprise` entity

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#327]
I propose, and will soon be implementing, moving the gain/loss on exchange accounts to the `enterprise` entity, under the columns 
1. `enterprise.gain_account_id`
2. `enterprise.loss_account_id`

Previously, the gain/loss exchange accounts were tied to cashboxes, but in practice, there was never a need to have more than one gain and one loss account (OHADA requires that you separate them).

If anyone comes up with any downsides, please leave a comment.  Otherwise, this issue will be closed when the relevant commit lands closing it.

**Comment by sfount** [comment]
No problem with this. It seems to me having multiple gain/loss on exchange accounts would be overly complex from the accounting perspective, even if we could support it.
