### ISSUE TITLE
Replace WKHTMLTOPDF with Puppeteer

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3274]
It looks like wkhtmltopdf project has stagnated and uses a pretty old rendering engine, preventing us from taking full advantage of the latest CSS technologies.  An alternative to this is [puppeteer](https://github.com/GoogleChrome/puppeteer) which embeds an entire Chromium Browser and uses that for rendering.  It's something we should consider as a replacement.

Pros:
 1. Latest and greatest CSS engine - our HTML versions could be identical to our PDFs.
 2. Potentially easier installations, since we won't need to mess with xvfb and other issues.
 3. Easy update process, first class support.

Cons:
 1. Bloat.  WKHTMLTOPDF is a lean engine, Chrome is a browser.

**Comment by jeremielodi** [comment]
@jniles Let me have a look into this library and see if we can use it in BHIMA

**Comment by jniles** [comment]
@jeremielodi, don't spend too much time on this.  There are more important issues to tackle:
 1. https://github.com/IMA-WorldHealth/bhima-2.X/issues/3210
 2. https://github.com/IMA-WorldHealth/bhima-2.X/issues/3213
 3. https://github.com/IMA-WorldHealth/bhima-2.X/issues/3176
 4. https://github.com/IMA-WorldHealth/bhima-2.X/issues/3258

I'm pretty sure the theory will work since I've used it in a number of other libraries.  For example: https://github.com/IMA-WorldHealth/dhis2-screenshot

**Comment by mbayopanda** [comment]
@jniles I notice that scripts or styles in the html are not processed by Puppeteer, it require to include them globally with `.addStyleTag` or `.addScriptTag` methods.

**Comment by jniles** [comment]
Even with `setContent()`?  Will something like:
```js
page.setContent(`
<html>
   <head>
    <style>body { color : red; }</style>
  </head>
   <body> Hello world! </body>
</html>
`);
```
not render the content as red?
