### ISSUE TITLE
feat(fiscal year): block closing fiscal year if the result account has value

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3294]
Here is a part of the closing fiscal year process : 

1. Before closing a fiscal year look at the result of the year (produits - charges)

2. Look inside the balance sheet if the result account (13xxxxxx) doesn't have value, if this account has value the accountant must move the value into a gain or loss account (12xxxxxxx). The goal here is to have nothing as value inside the result account

3. We sold all profit and loss accounts into the result account (13xxxxxx) which is supposed to contain nothing

The problem here is in the step 2 with bhima we don't take care if the result account (13xxxxxx) has value or not which can be a source of huge problems.

**To avoiding that we could check if the selected result account has value or not, if it has value the system must show a message that the accountant must write transactions to clean the result account before to close the fiscal year, and the closing fiscal year must be blocked at this step.**

**Comment by jniles** [comment]
Partially addressed by https://github.com/IMA-WorldHealth/bhima-2.X/pull/3295.  This implements a message, but not the blocking behavior.

I think we shouldn't block unless we offer the user a configuration setting to turn it off.  This isn't an accounting rule, it's an OHADA creation that might change next time they rewrite OHADA.  Enterprises that don't use OHADA will be confused by this behavior.

**Comment by jniles** [comment]
@mbayopanda, I propose we close this issue.  Are you okay with that?

**Comment by mbayopanda** [comment]
Yes, we can close it
