### ISSUE TITLE
(Design) Journal Advanced Filter

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#330]
This issue proposes the design of the advanced filter in the journal 

**User interface**  

![image](https://cloud.githubusercontent.com/assets/5445251/14607844/4ccfb232-057b-11e6-81a9-fbccab3cc6ca.png)
_Fig. 1: The journal user interface_

![image](https://cloud.githubusercontent.com/assets/5445251/14607906/80437036-057b-11e6-989d-8e4c77593bb8.png)
_Fig. 2: The modal of the advanced filter_

We can have as much input box as columns in journal table for accuracy of the results

**Comment by jniles** [comment]
I'll take this one.

**Comment by jniles** [comment]
I have begun working on this and got a modal up and running.

It seems to me this modal might not be generic enough.  I would imagine that the accountant would want to see the following options for filtering any column (debit for example):
1. `debit > X` (greater than some value)
2. `debit >= X` (greater than or equal some value)
3. `debit == X` (exactly some value)
4. `debit < X` (less than some value)
5. `debit <= X` (less than or equal some value)
6. `X <= debit <= Y` (between some values)

For the text-based columns, you can imagine implementing "`description` contains X", which would be the same as a MySQL "LIKE" statement.

This level of functionality is not achievable with the proposed modal.

I propose modifying this proposal/modal to make the modal show the following:
1. Choose a column
2. Choose a filter type (`greater than`, `less than`, `between`, `contains`, etc ...)
3. `<input>` for the value.  If the user chooses `between` there will be two `<input>`s for each value.

@mbayopanda what do you think?  I can make a quick mockup if that seems like a good idea.

**Comment by sfount** [comment]
Thinking about this it seems that a user would usually work with a filter one at a time, for example 
'First I will search for a transaction containing the text 'x', okay now I would like only transactions from 2012' 

With this process it would favour the suggestion of doing filters one at a time.

**Comment by jniles** [comment]
Since this proposal, we have settled into our current filtering system (without any comparisons besides equals).  I think this proposal still has merit, but should take into account the current structure of ui-grid and FilterService.  Once a new proposal takes these into account, we can work towards an implementation.
