### ISSUE TITLE
Client Service Architecture/ Re-factor

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#333]
Currently we have a flat client service layout - every entity has its own service and that is what is imported into modules. 

For example:
`DebtorService`
`DebtorGroupService`
`PatientGroupService`
`PatientService`
`PatientInvoiceService`

**1.** I suggest we reduce the number of module facing services with a uniform API. This would mean that entities that belong to other entities are exposed through a variable on the parent service. 

For example: 

``` js
function ModuleController(Debtors) {
   // returns details for a specified Debtor  
  Debtors.detail(uuid) //... 
  Debtors.list()

  // returns details for a specified Debtor Group
  Debtors.Groups.detail(uuid) //...
  Debtors.Groups.list()
}

/**
 * In this proposal Debtors and Debtor groups are still split into multiple services
 * however the Debtors Service exposes the Debtor Groups Service
 */
function DebtorService(DebtorGroups) { 
  var service = this;

  // expose groups API 
  service.Groups = DebtorGroups;
}
```

**2.** I suggest we start organising our services like we organise our other controllers and modules into folders as there are now too many for a flat list.

**3.** If a service is only for use in one module I suggest it is saved in the `partials/...module` folder, this will free up the `client/js/services` folder to only contain common and shared services.

**4.** Finally I suggest old services are updated or removed to clear up the bhima.services namespace - many of the older services do not fit the 2.x standards (capital letters etc.)

**Comment by jniles** [comment]
I'm okay with all of these suggestions.

With regards to **4**, we should deprecate + remove old services carefully through issues, as @lomamech has been doing well with #67 and #331.

**Comment by jniles** [comment]
I think that this has been completed for the most part.  It's level of importance is pretty low.  Closing as outdated.
