### ISSUE TITLE
Simple Vouchers needs hamburger menu

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3332]
The simple vouchers menu doesn't have a hamburger menu font icon.  It needs `fa-menu` to be added to it.

![needshamburgermenu](https://user-images.githubusercontent.com/896472/48300669-0ad0d480-e4e2-11e8-8e26-0885d33df2d5.png)

**Comment by flurmbo** [comment]
Hey can I work on this one?

**Comment by jniles** [comment]
Go for it!
