### ISSUE TITLE
(Design) Adding a transfer type for Transfer Slip Module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#334]
This issue is about the possibility of categorizing transferts with some specific prefix description. These prefix are predefined for specific transfer type.

![image](https://cloud.githubusercontent.com/assets/5445251/14639030/31b54694-0632-11e6-8253-06c7b3d46e5c.png)

_Fig. 1: Transfer Slip Module_

The second proposal is about the list of transfers made, the module can have a button `List` which open a modal tool for finding transfert

![image](https://cloud.githubusercontent.com/assets/5445251/14639094/9e512412-0632-11e6-9339-9ab808d6ed63.png)

_Fig. 2: Transfer Slip List_

The modal tool for finding transfers is a tool, it means that it's have more option : filter by date, print the list and display the proof of transfer.

**Comment by jniles** [comment]
For a first implementation, I am happy putting in "Type of Transfers" into the simple voucher to classify transfer types.  It would help us build reports rapidly.  If we discover that the same information is available with an SQL query, all we need to do is remove the option and change our SQL queries a bit!

The list is an excellent mockup, thanks @mbayopanda!  If this gets implemented, it will be extremely powerful.

It is worth noting that we will have a similar "List" for Debtor Invoices, Cash Payments, Purchase Orders, and more.  Perhaps this List modal could be the same template for all of them.  What do you think?

**Comment by jniles** [comment]
This has been addressed.
