### ISSUE TITLE
(Design) Patients Registry

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#336]
This issue describes the patient registry module proposed/ described in https://github.com/IMA-WorldHealth/bhima-2.X/issues/278. 

The patients registry (records) will be the central place in BHIMA to search for a patient, it will be a tool that can be used to check in a returning patient or looking up any patient that has been registered in the past. 

These proposed designs show a complex final state - the core of this module should load patient records and allow filtering on columns. 

Options to search for patients:
- When was the patient registered? - from date, to date 
- When was the patients last bill? - from date, to date
- How old is the patient? - from age, to age
- Gender of the patient? 
- Origin location? 
- Current location? 
- Searches on names

If there are any additional ideas on parameters to search for patients they can be commented and added here.

**Patient Registry Core**
![patient registry](https://cloud.githubusercontent.com/assets/2844572/14669394/9027a754-06e0-11e6-89c3-0d87d85b9f47.png)

I propose that this module uses a UI Grid that allows sorting/ filtering on the current patient records search. On the initial page load the grid will show the most recently registered or visiting patients. 

**Patient Registry Search**
![patient registry search](https://cloud.githubusercontent.com/assets/2844572/14669461/e60f92bc-06e0-11e6-8ae1-8143a9ff98ab.png)

A modal search service will be used to refine the results - this will make a new request to the server for patient records based on the search parameters. It should also provide basic form validation.

**Patient Registry Search View**
![patient registry filtered](https://cloud.githubusercontent.com/assets/2844572/14669504/1c3fed6e-06e1-11e6-89a5-42d91e60d16a.png)

The current search parameters should be shown to the user somehow. This mockup shows a filter bar that could be used across a number of modules like this. How filters/ searches are shown should be discussed.

**Comment by jniles** [comment]
Looks good to me.  

More parameters to search on (in the most complex case):
-  Last Visit - from date, to date
- Hospital Number 
- Reference

For this to work, we need a really well crafted `/patients/search/` API.  Currently, there are at least three routes that exist (`/patients/search/`, `/patients/search/reference/`, `/patients/search/fuzzy/`).  Someone should begin by either removing the unused routes or unifying them into the same route and testing that server API.
