### ISSUE TITLE
Audit spellings/grammar in English i18n files

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3375]
We have a lot of translations at this point in our `client/i18n/*.json` files.  We currently support two languages fully: French and English.  However, we often make mistakes in spelling, grammar, or awkward phrasing.  It would a huge help for someone to go through these files and make sure the phrasing makes sense, correcting those that don't make sense.

[Here is the folder](https://github.com/IMA-WorldHealth/bhima-2.X/tree/master/client/src/i18n/en)

**Comment by joshuahedlund** [comment]
I can work on this

**Comment by joshuahedlund** [comment]
Should all the uses of "dépôt" be translated as "depot" or "deposit"?

**Comment by jniles** [comment]
@joshuahedlund it's all yours!  "dépôt" is used in our app to indicate a depot in English.

**Comment by joshuahedlund** [comment]
Project Update and a question.

I've made it through the letter R. I've come across the occasional fully French string that I've attempted to do my best with context to translate to English. However at the end of report.json there is an uncommonly large collection of French strings in a sub array. Are all these actively used and are they all supposed to be in English? Thought I'd check before attempting that.

**Comment by jniles** [comment]
Hey @joshuahedlund, well done!  That is good to hear.

It's probably easier to take this in smaller bites - anytime we add features to the application, we'll be changing those files so the likelihood that your changes will run into conflicts with other devs' is higher the longer they are out of the main branch.  It also is easier to review smaller pieces at a time.

Could you make a PR with what you have?  We'll walk through the work you've and maybe split off any sections that are 100% French for me to work on.  That way, you tackle your strengths and the project isn't so daunting for a single person :).

Thanks so much for you help on this.  It's really awesome!

**Comment by joshuahedlund** [comment]
Great.

At this point would you like me to skip this portion of report.json...

```
"REF_DESCRIPTION" : {
        "AD" : "Immobilisations incorporelles",
        "AE" : "Frais de développement",
        "AF" : "Brevets, licences, logiciels et droits similaires",
        "AG" : "Fond commercial",
        "AH" : "Autres immobilisations incorporelles",
"AI" : "Immobilisations corporelles",
```

.... and work on S-Z?

**Comment by jniles** [comment]
Yeah, go ahead and do that.  I'll need to make sure I have my translations correct for those as well - I can tackle them.

Thanks so much!
