### ISSUE TITLE
Proposal: Only allow a single subsidy for a bill

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#343]
The Patient Invoicing process allows a bill to be modified by billing services and subsidies.  In bhima-2.X, a `Billing Service` increases the total cost of a bill by a percentage of the bill.  A `Subsidy` will decrease the total cost of the bill by a percentage of the bill.

In the original conception, an invoice could have N billing services and N subsidies applied to it.  I propose we limit the number of subsidies to 1, taking the largest subsidy amount if a bill qualifies for multiple subsidies.

This makes both the invoicing process easier to understand (the accounts do not have to think about combined subsidies), more secure (cannot reach a negative amount in the bill), and simpler to implement (all we have to do is sort in decreasing order of subsidy percentage and take the top element).

@IMA-WorldHealth/local-contributors this will land in my Patient Invoicing posting journal core implementation later this week.  Please use this thread to discuss different implementations, to see if there is another model that makes more sense.

Also interested in @imawh's opinion.

**Comment by imawh** [comment]
What is the experience of 1.x w/ multiple subsidies?  Ever happened?  I'd think dealing w/ one subsidy is about as difficult as dealing with n.  Then there's the hiv meds that are 100% subsidized that should be tracked ...

**Comment by jniles** [comment]
In 1.x, we treated subsidies very differently, but only had one -- a custom hack for IMA.  When trying to formalize it, we run into these questions:
1. What happens when two organizations wish to subsidize HIV patients for 60% of the bill each?  Which one pays more, which pays less?  How do you justify this scenario to an organization that wants to report how much money is spending on patients?
2. What happens if the sum total of all subsidies is over 100% of the bill?  How do you detect this case efficiently in SQL and only deal with as many subsidies as you need to complete out the bill?  Which order do you apply them in?  Which do you exclude?

Those  questions prompted us to this conclusion.  What are your thoughts?

**Comment by jniles** [comment]
Ping @imawh.

**Comment by sfount** [comment]
I think the potential difficulty with applying more than one subsidy is that it makes it impossible for a subsidy provider (IMA for example) to get an accurate reading on what their subsidy is being used for, or what the need for their subsidy is. 

For example if IMA is subsiding 30% on bills that are already being subsidised 90% (resulting in 10% being paid) it will change the reading on the requirements for the subsidy - which completely changes when the higher subsidy either stops or doesn't apply to the majority of patients. 

This may be an over-complication but certainly the base case is that if you meet the requirements to be covered by multiple subsidies on one bill the system can select the best case for the patient (the highest subsidy) and still provide an accurate picture to the subsidiser.

**Comment by DedrickEnc** [comment]
I think in bhima-1.X you can deal with many subsidies (see the sale logic server side), applying one subsidy is not bad however each hospital has is own business logic, so if IMCK let patient to be subscribed to many subsidy bhima-2.X must be flexible to support it.

**Comment by jniles** [comment]
@IMA-WorldHealth/local-contributors Thanks for the feedback!

At the moment, the only thing in the 2.X code preventing multiple subsidies is a single error check that says

``` js
if (subsidies.length > 1) {
  throw new BadRequest('....');
}
```

It would be very easy to comment out this line and support multiple subsidies, but there multiple corner cases to consider.  If a hospital's business logic can account for this (and justify it to the supporting parties as @sfount mentioned), there is no problem supporting it.  We'll likely have to look at a few extra error cases to make sure bills are not over subsidized.

However, unless someone can come up with a proposal for how multiple subsidies should be handled in general, I propose we leave this check.

**Comment by jniles** [comment]
Marking this temporarily resolved.
