### ISSUE TITLE
Deploy BHIMA using Docker

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3439]
We are approaching a point where we will be doing a lot of ops work - maintaining servers, rolling out updates across multiple institutions, so on.  We could benefit from the ease of maintenance of docker, as well as the ease in deploying online.  New contributors could also spin up instances rather easily.

I've never used Docker before, and the initial setup is a bandwidth hog for the Congo context, but these problems are surmountable.  I say we give it a whirl and see what comes of it.

**Comment by lavvy** [comment]
Any updates
