### ISSUE TITLE
(Proposal) Favour client session entity UUID generation

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#345]
In a number of modules that I have developed I rely on the server filling in a UUID for any entities submitted for creation. Whilst this creates a very slick API it does mean that if a client somehow ends up requesting creation many times (due to some error) a valid unique object will be created for every request. 

**Problem**
If an identical form is submitted many times for any reason the server will write a new entity for each request.

If the client generates a UUID for the creation session then once that UUID is used up the client will have to explicitly clear the UUID or create a new one before the entity will be registered again. 

Quick psuedo code example: 

``` js
function CreateEntityController(Uuid, Entity) { 
  var createSessionUuid = Uuid();
  var entity = //...

  // If this is called 100 times only the first will be valid.
  // Following the first call the entity will be 
  // rejected from the database for not being unique
  function submit() { 
    Entity.create(entity, createSessionUuid);
  }
}
```

**Comment by jniles** [comment]
Why not just have `Entity` check if `entity.uuid` is defined instead of adding another API parameter?

**Comment by sfount** [comment]
Excellent question - my initial thought was that this allows the controller to officially get away with doing less. In my example the controller is not responsible for changing any attributes on the entity - **it doesn't actually know that it's a uuid for a database.**

This is mostly semantics but it avoids the controller curating the object through:

``` js
entity.uuid = Uuid();
```

With this way it seems to me it would become a grey area as to what the controller can and should be responsible for.

**Comment by jniles** [comment]
Why are we avoiding this?  Don't we do the same thing all the time with

``` js
entity.date = new Date();
```

It seems to me that if the controller is needing to control whether or not a new UUID is created on the object through an additional function parameter, it should be able to do it through the object's properties as well.  Conceptually they are the same thing.

It doesn't make or break the proposal for me, but just curious for the rational.

**Comment by lomamech** [comment]
@jniles  can we close this issue ??

**Comment by jniles** [comment]
@lomamech, yes.
