### ISSUE TITLE
Goma stock instance suggestions

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3464]
This list of feature are needed at the Goma's instance : 

- [ ] Add a registry which show stock movements between depots where Entries are not corresponding to Exits
- [x] Add a way of editing lot name or expiration date
- [ ] Add a way of editing a purchase order
- [x] Add in the footer of stock entry document : Received by and Approved by
- [x] Add picture of the enterprise and the project in the header of documents or receipts
- [x] Add a user guide as manual for stock management

**Comment by jniles** [comment]
>  Add picture of the enterprise and the project in the header of documents or receipts

We've needed this for a while, especially now that we are getting more use out of the system.

Good suggestions!

**Comment by jniles** [comment]
@mbayopanda do we consider that we have a user guide yet?

**Comment by jniles** [comment]
Note, this is now closed in https://github.com/IMA-WorldHealth/bhima/pull/4027.
