### ISSUE TITLE
Add "reversed" and "posted" labels to the receipt modal

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3473]
If a receipt (cash payment, invoice, voucher) has been posted or reversed, we should add those pieces of information to the receipt modal.  It comes automatically with the record, so why not?

I'm thinking `<span class="label label-primary" translate>FORM.LABELS.POSTED</span>` and `label-danger` for the reversed flag.  They would appear in the top right of the receipt modal pictured below:
![addnewpostedreversedtoreceiptmodal](https://user-images.githubusercontent.com/896472/49926631-45040c00-febc-11e8-8aca-547709d04946.PNG)

**Comment by Gibr** [comment]
In current version i see this:
![b1e47d26ca](https://user-images.githubusercontent.com/19442107/52551273-c4468b00-2dec-11e9-8ac9-8d2497421c36.jpg)
Is it what do you talk about? Already done?

**Comment by jniles** [comment]
Hi @Gibr - well done on getting the app up and running!

This issue is slightly different.  We want to display on the modal header, instead of the embedded PDF, the fact that the document has been posted or reversed.  You can see in the dropdown for vouchers that [we display an "edited" text](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/vouchers/templates/action.cell.html#L10) in a similar way to denote the record as being modified.

So, we will want to put in the top right of the modal in your image the flags for "posted" and "reversed".

Does that help clarify things?

**Comment by Gibr** [comment]
Hi @jniles ! 
Thank you for your compliment and explanation, now issue becomes more clear.
