### ISSUE TITLE
Design: Querying Transaction Balances

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#349]
This issue presents how to compute balances on transactions in bhima-2.X.  This uses the schema defined in #112, updated in #254.

Throughout, we'll use a MySQL `VIEW` to represent the combined `posting_journal` and `general_ledger`, defined as follows:

``` sql
CREATE VIEW ledger AS
    SELECT record_uuid, trans_id, trans_date AS date, account_id, credit_equiv AS credit,
      debit_equiv as debit, reference_uuid, description, entity_uuid
    FROM posting_journal
  UNION ALL
    SELECT record_uuid, trans_id, trans_date AS date, account_id, credit_equiv AS credit,
      debit_equiv as debit, reference_uuid, description, entity_uuid
    FROM general_ledger;
```

This gives us an easy way to factor in both the `posting_journal` and `general_ledger` without explicitly writing that code.

Recall that `record_uuid` will be the `sale.uuid`, `cash.uuid`, `voucher.uuid` as described in #112.  Recall that `reference_uuid` will be previous `record_uuid`s defined in the `ledger`.
#### Balance on an account

Finding the balance on any account is easy.

``` sql
SELECT SUM(credit - debit) AS balance, account_id AS id FROM ledger
WHERE account_id = {{ target_account_id }}
GROUP BY account_id;
```
#### Balance on an entity's account

Finding the balance on an entity's (debtor or creditor) account is easy.  

``` sql
SELECT SUM(credit - debit) AS balance, BUID(entity_uuid) AS id FROM ledger
WHERE entity_uuid = {{ target_entity_uuid }}
GROUP BY entity_uuid;
```

This simply looks as the debits and credits against a patient
#### Balance on any transaction due to an entity

To get the balance due to a debtor or creditor on a particular transaction, we modify the previous query to select for a transaction id (`record_uuid`).

``` sql
SELECT BUID(id) AS id, SUM(credit - debit) AS balance FROM (
  SELECT debit, credit, record_uuid AS id FROM ledger
  WHERE record_uuid = {{ target_record_uuid }} AND reference_uuid IS NULL AND
    entity_uuid = {{ target_entity_uuid }}
  UNION
  SELECT debit, credit, reference_uuid AS id FROM ledger
  WHERE reference_uuid = {{ target_record_uuid }} AND entity_uuid = {{ target_entity_uuid }}
)l
GROUP BY id;
```

Above, `{{ target_record_uuid }}` is the transaction's `record_uuid` that you want to find the balance on.  A balance only makes sense in relationship to a debtor/creditor so `{{ target_entity_uuid }}` is the id of that entity.  This query will give a result like:

| id | balance |
| :-: | --: |
| 7ef68647 | 15.34 |
##### Balance of all cautions on a debtor's account

To get the balance of all cautions on a debtor's account, we first look all cautions from the `cash` table due to a debtor and determine their balances using the `ledger`.

``` sql
SELECT id, SUM(credit - debit) AS balance FROM (
  SELECT debit, credit, record_uuid AS id FROM ledger JOIN cash
    ON cash.uuid = ledger.record_uuid
  WHERE record_uuid = {{ target_record_uuid }} AND reference_uuid IS NULL AND
    entity_uuid = {{ target_entity_uuid }} AND cash.is_caution = 0 
  UNION
  SELECT debit, credit, reference_uuid AS id FROM ledger JOIN cash
    ON cash.uuid = ledger.reference_uuid
  WHERE reference_uuid = {{ target_record_uuid }} AND entity_uuid = {{ target_entity_uuid }}
    AND cash.is_caution = 0 
)l
GROUP BY id
HAVING balance > 0;
```

**Comment by imawh** [comment]
I wouldn't call it Ledger, rather "SortOfLedger" since you're combining unposted w/ GL.  Need to be able to do a pure GL query also.

**Comment by jniles** [comment]
Certainly.  I was mostly just writing it for convenience of showing how the
SQL worked without writing too much boilerplate code!

**Comment by jniles** [comment]
Most of these queries have already been tackled.  Closing this issue.
