### ISSUE TITLE
Patient Financial Report does not refresh the patient identifier

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3493]
We linked the Patient Financial Activity as its own report, but you cannot search for multiple patients - the report page caches the patient identifier and will not search for a second patient.

**Comment by jeremielodi** [comment]
can you please attach a screenshot for this bug, that way it will be more clear

**Comment by jniles** [comment]
Sure!  I didn't have enough internet to do so at the time of the report.  Here is a GIF:

![2019-01-21_10-42-39](https://user-images.githubusercontent.com/896472/51465995-78627200-1d69-11e9-925b-1d5f1bba09cb.gif)
_Fig 1: Patient does not refresh_
