### ISSUE TITLE
Trial Balance should tell which account/debtor group/line of the transation has an error

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3534]
The Trial Balance does not tell me what line in the Posting Journal has an error.  See below:

![incoherenterrormessages](https://user-images.githubusercontent.com/896472/50952759-b7630e80-14b1-11e9-9fd6-404b728f263e.PNG)
_Fig 1: Incomplete error messages on the Trial Balance_

This makes it really hard to figure out what is going wrong.  We should at least tell the user the name of the debtor group, the name of the account, etc, so they can verify it.

**Comment by jniles** [comment]
@jeremielodi, can you look into this?

**Comment by jeremielodi** [comment]
How can I manually create this error and try to solve it

**Comment by jniles** [comment]
Lock an account that is in the posting journal and then try to post it.

**Comment by jeremielodi** [comment]
okay
