### ISSUE TITLE
Feature Proposal: Embedded Documentation

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#355]
This proposal concerns making bhima usage documentation more easily available inside the application.

**UI Mockups**
These mockups use the cash window as an example.
![cash window documentation closed](https://cloud.githubusercontent.com/assets/896472/15989942/8a496b84-307e-11e6-9267-4b402a06750e.png)
_Fig 1: Link to Documentation Modal_

![cash window documentation open](https://cloud.githubusercontent.com/assets/896472/15989941/8a43f258-307e-11e6-9081-7759a650e28c.png)
_Fig 2: Documentation Modal Open_

**Technical Design**
I propose that we create a component, `bhDoc` and a service `DocumentationService` that are responsible for displaying documentation to the user in a modal from any page using a `glyphicon-question-sign` icon next to a label.

The basic `<html>` signature should look like this:

``` html
<label class="control-label">
  {{ "SOME.KEY" | translate }}
  <bh-doc path="/module/some/documentation"></bh-doc>
</label>
```

Which would render a question mark next to the label text.  Clicking this icon would open a modal and embed the file loaded from the path `/module/some/documentation`.

_Edit: Proposal updated with UI mockups._

**Comment by jniles** [comment]
@IMA-WorldHealth/local-contributors I've updated this proposal with UI designs, and would like feedback.  What do you think?

**Comment by sfount** [comment]
I think this is an excellent proposal. Given that our target user may be learning many things at once (both computer interaction and BHIMA) having an easily accessible step by step reminder I'm sure would be useful. 

The technical design looks great to me, the content/ layout of the documentation may have to additionally be designed but I propose we tackle it as we have with a number of other 2.x services. 
- Implement the smallest possible solution on a page this would have an impact
- Iterate on any technical improvements that come up through other work
- Create specific issues for developing and designing the documentation that can then be slot into the infrastructure

The priority on this is hard to judge but for core modules I can see this being essential even for a small initial install.

**Comment by jniles** [comment]
This would be super hard to maintain with a team our size.  We need to get the basics of our documentation up first (https://docs.bhi.ma) and then we'll focus on trying to embed it on the pages.
