### ISSUE TITLE
Make exchange rate conversion automatically adjust currencied accounts

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3554]
We run a multi-currency system, which means that accounts can be in different currencies.  However, the underlying value is always stored in the `period_total` table as the enterprise currency.  There is a trade-off with this method of storing value though: accounts stored in a currency different from the enterprise currency are not accurately represented.

**Scenario**
Suppose you have an enterprise currency in USD, and you also have a cashbox in FC.  Currently, you have 10,000FC in the cashbox, which is represented in your `period_total` table as 6.25$ at 1600FC to the dollar.  Now you change exchange rate of the enterprise to be 1650FC/USD.  What does the balance report say?

In the present version of BHIMA, the balance report will print out 10,312.5FC in your cashbox, even though the _physical cash_ is only 10,000FC.   For the hospital accountant, this is super confusing, since their cash count will be off, and they didn't write any transactions.

We ran into this issue at HEV.

**Proposal**
In order to not confuse people, we should automatically generate a correcting writing to keep the balances of the cash/bank accounts after the exchange rate.  For example, in the above scenario, the system would automatically recognize when you set the exchange rate that the previous balance was 10,000FC and pass a correcting writing that:
 1. Debits the Loss on Exchange account for 312.5FC
 2. Credits the cashbox for 312.5FC.
This way, the underlying amount is kept steady.

In order to do this, BHIMA needs to know that an account is in a currency other than the enterprise currency.  Therefore, we need to assign to accounts a currency.  BHIMA will then automatically attempt to make a writing to retain the balance on exchange rate change.

**Comment by kwilu** [comment]
Hello @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
After some reflection, this isn't a great idea.  A better approach would be to carry forward balances in multiple currencies.  Both @jeremielodi's PR and mine demonstrated that this may not be a great solution since the transactions passed automatically are quite confusing.

I'm closing this now.
