### ISSUE TITLE
Make Travis run unit tests

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#357]
Since we are beginning to get further adoption of unit tests, and have scheduled some more (see #337), it would be very helpful if Travis would run the unit tests using `karma` as part of the test suite.

**Comment by sfount** [comment]
I have had some experience building a docker instance to run the BHIMA production environment - this may be useful when standardising our release as well as help optimising continues integration like Travis. 

It can be found here:
https://hub.docker.com/r/sfount/bhima/

As far as I can remember it bundles everything required to run BHIMA (other than installing npm/ bower dependencies for test reasons) including `xvfs` which can be used to run unit and end to end tests in a virtual buffer. 

We should schedule a few hours for this this week.
