### ISSUE TITLE
Unpaid invoice report is broken

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3575]
The issue is about the unpaid invoice report which doesn't works properly.

When we define entries, we get an error relate to collate : 
![image](https://user-images.githubusercontent.com/5445251/52398035-e1f7b580-2ab7-11e9-8709-622ffeb51295.png)

**Comment by jniles** [comment]
Looks like when there is no data, it errors. :/

**Comment by jniles** [comment]
@kwilu claim
