### ISSUE TITLE
Location API Endpoint 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#36]
API should provide 
- Very detailed view of a specific village 
- Lists of villages/provinces/countries etc. given their dependencies (provinces in countries, villages in provinces etc.)
- Well tested endpoint 

This API will drive the management pages required for administering locations as well as provide data the for the location select directive and any modules that requires locations.

**Comment by jniles** [comment]
I propose the API also provide a way of merging villages in the database.  This will be a complicated UI to handle, but the server-side functionality for merging two villages should be fairly straightforward.
