### ISSUE TITLE
Proposal: use helmet to help secure the server

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#360]
The bhima application has never done security very well.  We could start easily be including [helmet](https://github.com/helmetjs/helmet) as a dependency, immediately adding the benefits of key pinning, protection using proper XSS and CORS headers, and some rate-limiting.  One option that we'll want _off_ by default is `noCache`, which disables caching.

/cc @IMA-WorldHealth/local-contributors

**Comment by sfount** [comment]
I agree, this would be a good first step in starting to think about the servers security. If it can be integrated with passing tests I support this.
