### ISSUE TITLE
Remove dependency on gulp-protractor

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#361]
So far, we have used a wrapper around protractor, `gulp-protractor` to run our end-to-end test automagically.  Since we are using shell + npm scripts extensively to run our tests anyway, we might as well remove this dependency.  The `gulp-protractor` module bundles it's own version of selenium, meaning that we must update both `gulp-protractor` and `protractor` if a new version comes out (a pretty big download!).

For these reasons, I am a fan of removing `gulp-protractor` and using shell scripts such as `sh/test-ends.sh` to take care of starting up the webdriver and associated processes.

**Comment by sfount** [comment]
Relevant to this - we should make sure that our scripts always exit with appropriate and relevant exit codes - if a test has failed this should be reflected in the scripts exit. This would help standardise continues integration services.

**Comment by jniles** [comment]
I'll take this one.
