### ISSUE TITLE
gulp is broken

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3626]
The gulp command throw an error : 

![image](https://user-images.githubusercontent.com/5445251/53835233-401b9980-3f8d-11e9-843a-f77c9ed07d1e.png)

**Comment by jniles** [comment]
It looks like you are using a global gulp.  We recently upgraded BHIMA to gulp version 4 - is your global gulp at version 4?  Otherwise, it will be incompatible.

**Comment by jniles** [comment]
It seems like the gulp-watch might be broken though...

**Comment by jniles** [comment]
@kwilu label "bug"

**Comment by kwilu** [comment]
**ERROR:** Label "bug" does not exist and was thus not added to this issue.

**Comment by jniles** [comment]
@kwilu label "Bug"

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
@mbayopanda can you confirm if this was closed in https://github.com/IMA-WorldHealth/bhima/pull/3649?

**Comment by mbayopanda** [comment]
Fixed by #3649
