### ISSUE TITLE
jsBarcode not imported correctly

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3629]
The barcode doesn't work because it is not correctly imported : 

![image](https://user-images.githubusercontent.com/5445251/53947583-5711d700-40c6-11e9-963d-98c928f9d35c.png)

I got the error below with the visit report : 
![image](https://user-images.githubusercontent.com/5445251/53947647-76106900-40c6-11e9-8b91-2d61e13e0936.png)

**Comment by jniles** [comment]
@kwilu claim
