### ISSUE TITLE
Loading indicators on selects waiting on service HTTP requests. (Proposal)

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#37]
This could be proposed as a requirement for bhima-2.X pages (like form validation etc.)

Anywhere a module elements waits on an asynchronous request it can cause the user interface to 'hang' or wait for the data to be populated - if this is indicated clearly it is very clear what the page is doing. 

This is especially noticeable when loading modals that require additional data to be downloads, for a demonstration of the problem:
1. navigate to [Update Patients/Test Patient](https://localhost:8080/#/patients/edit/274c51ae-efcc-4238-98c6-f402bfb39866)
2. Throttle Chrome connection to GPRS 
3. Select 'Update Group Assignments' 

As the modal downloads the available patient groups, nothing is displayed and the application is allowed to enter a broken or unhandled state.

**Comment by jniles** [comment]
Unfortunately, the only way to accomplish this is hacking on `ui-select` for the `ui-select` directive.  See discussion [here](https://github.com/angular-ui/ui-select/issues/350).  Additionally, [here is one promising PR](https://github.com/angular-ui/ui-select/pull/1779/files) that hasn't been merged or released with `ui-select` yet.

**Comment by jniles** [comment]
@sfount, can we close this?  Or do you still think it would be useful?

**Comment by DedrickEnc** [comment]
This issue seems out of interest, if needed it can be reopened
