### ISSUE TITLE
Add option to hide a service

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3707]
The services module has many uses, but once someone makes a mistake, it is hard to correct.  We should add an option to allow users to "hide" services, so that further mistakes cannot be made.  This would mirror the hidden accounts option (#2808) and the services would be no longer available in the dropdown for invoicing.

![image](https://user-images.githubusercontent.com/896472/57216844-ef560a80-6fe8-11e9-8bb6-d535949c0bfd.png)
_Fig 1: No options besides editing the service name_

**Design**
We need to add an additional boolean column to the service table `hidden`.  This will work exactly the same way the account `hidden` column works.   By default, the value is `0`, but it can be toggled via the web interface. 

The `bhServiceSelect` also needs to be modified to only look for non-hidden services by default (`?hidden=0`).

**Comment by jniles** [comment]
@jeremielodi, can you look into this issue?

**Comment by jeremielodi** [comment]
okay. Let me tackle it
