### ISSUE TITLE
Add balances to the footer of the entry/exit portion of the cash report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3727]
We've received this request from a client:

> Please put the sum of the entries and exits at the bottom of the cash report.

We need to make sure that all the values are in the same currency to be able to sum them.  If all values are in the same currency, we can simply sum the values and display the totals in the grid footer as normal.

If not, we should put a note on the bottom of the report that says something like "mixed currencies are used in this statement so totals are not computed."

![Balances](https://user-images.githubusercontent.com/896472/57768858-68014900-7704-11e9-9e92-7f70e1e513ba.PNG)
_Fig 1: Where the balance totals should go_

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
I also just noticed that the "Transaction ID" and the "date" columns are backwards.  I'll fix that too.

**Comment by jniles** [comment]
@kwilu label "bug"

**Comment by kwilu** [comment]
**ERROR:** Label "bug" does not exist and was thus not added to this issue.

**Comment by jniles** [comment]
@kwilu label "Bug"
