### ISSUE TITLE
The financial situation of a patient is broken

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3738]
Looks like something happened and the financial situation of the patient is broken on the patient record page.  Take a look:
![FinancialSituationBroken](https://user-images.githubusercontent.com/896472/58014227-46cb9e80-7af0-11e9-831d-a43364546ed6.PNG)
_Fig 1: Broken Financial Situation_

This happens with any patient in the system.

**Comment by jniles** [comment]
@mbayopanda would you able to investigate?

**Comment by mbayopanda** [comment]
@jniles no problemo 👍 

I will do it

**Comment by mbayopanda** [comment]
Not noticeable on the master branch
