### ISSUE TITLE
Getting Started in Windows - 'buildVendorForDevelopment' error

### ISSUE THREAD

**Issue by michaeldera** [third-culture-software/bhima#3766]
I am trying to get started with the project and run it on my local environment. I ran `npm install` then ran "build-database.sh" using git bash on my local machine.

I tried the run `npm run dev` and encounter error shown in the image:

![image](https://user-images.githubusercontent.com/12817839/59619039-dbdea900-9129-11e9-8c35-27893c9c5bc6.png).

OS:  Windows 10 (1903)
Node Version: 10.15.3 
npm version: 6.4.1

Not sure if there is anything I am doing wrong.

**Comment by jniles** [comment]
We don't officially support Windows as an install target, so I'll close this issue.  The best way to run BHIMA on Windows is using WSL to get a linux-like environment.
