### ISSUE TITLE
Proposal: Merge weekend create and configuration modals

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3783]
We currently have two modals to configure and create weekends.  I don't see any reason why we should need two modals.  You can see the separate versions below and my proposal following:
**Create Modal**
![image](https://user-images.githubusercontent.com/896472/60670371-5ddc0b00-9e68-11e9-8e7f-06a31918cfe1.png)

**Config Modal**
![image](https://user-images.githubusercontent.com/896472/60670399-6df3ea80-9e68-11e9-83fd-e53fdaaf740f.png)

**Merged Proposal**
![image](https://user-images.githubusercontent.com/896472/60670256-21a8aa80-9e68-11e9-8906-92644b41cd5a.png)

**Comment by jniles** [comment]
@lomamech what do you think?

**Comment by jniles** [comment]
Hmm... This might actually be a lot easier if we merged the two tables `weekend_config` and `config_week_days` into a single table.  I don't imagine these will be used too much - how many configurations could an enterprise desire?

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
I'm still working on this, but it is going slowly.  I'm trying to cleanup the logic of weekends/holidays/offdays a little bit at a time.

https://github.com/IMA-WorldHealth/bhima/pull/3920 is the latest iteration of this improvement.
