### ISSUE TITLE
(Stock Loss) Restrict one lot by line in the grid

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3793]
This issue was tackled with #3189 but the problem is : 
If the user fill the grid with many inventory without specifying lots : 

![image](https://user-images.githubusercontent.com/5445251/60947546-b8ea8380-a2e8-11e9-966d-67b7c6752af9.png)

The user can set the same lot on each line of the inventory

![image](https://user-images.githubusercontent.com/5445251/60947624-e33c4100-a2e8-11e9-9ef2-566b970406ae.png)

We have not to allow movement like that because it a source of many errors, so we have to block the user when he or she try to submit the movement by showing him a message or highlighting concerned rows.

**Comment by jniles** [comment]
@mbayopanda did this get fixed?

**Comment by mbayopanda** [comment]
@jniles yes on the stock exit module, not yet in the stock adjustment module

**Comment by jeremielodi** [comment]
I think this issue can be closed

**Comment by mbayopanda** [comment]
Fixed
