### ISSUE TITLE
Propose 2.X standard for catching client side errors

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#38]
This proposal should be split into two parts: 
- Handling an error in the context of a specific form or form element - this should provide feedback as to why this particular operation failed (I.e cannot submit an integer for a string value) 
- Generic module wide error handling - this should be displayed in the context of the module, every module should handle these errors in a similar way (Server status 500 - contact system administrator etc.)

This proposal can then be implemented across 2.X modules.

**Comment by jniles** [comment]
@sfount, was this not closed by #238?

**Comment by sfount** [comment]
@jniles yes good catch. I closed #228 but not this.
