### ISSUE TITLE
Barcode reader launches multiple HTTP requests

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3839]
The barcode scanner launches a series of HTTP requests to the server.  I thought we had fixed this issue, but it appears to have either reappeared or never been addressed.  Below, you can see the log of a single barcode scan observed in production:
![BarcodeScanForCashResultsinLotsofHTTPRequests](https://user-images.githubusercontent.com/896472/62855401-114ae180-bcea-11e9-91f4-f7a28f6e44b4.PNG)
_Fig 1: Barcode Scan for Cash Payment_

We need to limit these successive requests.  We have the [HTTPCacheService ](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/js/services/HttpCacheService.js) that might help limit subsequent queries.  Otherwise, we need to play with `$timeout`s to make sure we don't send multiple queries on a single `$digest`.

**Comment by jniles** [comment]
@lomamech can you look into this?

**Comment by lomamech** [comment]
@jniles, I did not manage to reproduce the error, it would be envigeasable to reproduce it with the use of a bar code reader.

**Comment by jniles** [comment]
Thanks, I will look into it.

@kwilu claim
