### ISSUE TITLE
Error handling for large text fields

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#387]
At the moment, the application does not limit users on the size of their text fields.  This means that an input that can only take 45 characters will return a generic `BadRequest` error when the form is submitted rather than doing client-side validation and warning the user before submitting it.

For most fields, a better model should be to limit these text fields using `ng-maxlength` on the clientside and add a "Text field is too long" warning message to `ngMessages`.

If this issue doesn't generate discussion, any developer is free to begin working on this issue.

**Comment by sfount** [comment]
I think this is an excellent idea - it is reassuring to see that these bad request errors are propagating through to the client and successfully stopping bad data from being written. This will now address the user experience side of it.

**Comment by jniles** [comment]
Closed in #430.
