### ISSUE TITLE
Analysis of the movements of the auxiliary cashboxes

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#3871]
This issue proposes to add a new report, to allow the monthly follow-up of the movements of the auxiliary cashboxes

**Comment by lomamech** [comment]
@kwilu claim

**Comment by jniles** [comment]
@kwilu label "report"

To follow up on this:

1. The report will group all income and exits by day.  This will allow us to track movements of transfer accounts, cash accounts, and bank accounts.
2. The report will have a balance column as well to show the balance of the account after the movements.
3. The report will be for a period in a fiscal year.
