### ISSUE TITLE
Implement thermal receipts for Stock Exits to patients

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3889]
We have thermal receipts for invoices, cash payments, and even patient registrations.  It would be nice to have them for stock exits to patients.  I can't think of a good reason to implement them for stock entries yet.

The idea of implementing these receipts for stock exits to patients is that they will be used to prove that a patient received the medication they paid for.  An auditor will be able to check the patient's invoices, their payments, and their medications from the printed out receipts.

**Comment by mbayopanda** [comment]
Closed by #3902
