### ISSUE TITLE
Uniformize Units and Reports Ids for all installation with master branch

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3898]
This issue is about : 
- Clean ids of units and reports in the master branch
- Create an update script which update units and reports ids of all installation of bhima with the master branch

**Comment by jniles** [comment]
@mbayopanda did this get closed in https://github.com/IMA-WorldHealth/bhima/pull/3918?

**Comment by mbayopanda** [comment]
Yes
