### ISSUE TITLE
Rename /patients/registry to /patients (Client)

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#391]
Proposal: 
Rename client side route `/patients/registry` to `/patients`. This would then be applied to all similar cases going forward. 

This would provide the following URL structure: 

Provide a searchable list of all patients (Patient Registry) 
`https://bhima.org/patients`

Provide full details on an individual patient (Patient Record) 
`https://bhima.org/patients/:uuid`

Provide tools to edit a patient (Patient Edit) 
`https://bhima.org/patients/:uuid/edit`

Provide a searchable list of all patient groups (Patient Groups)
`https://bhima.org/patients/groups`

**Comment by jniles** [comment]
Sounds good to me.

**Comment by jniles** [comment]
This was closed in #420
