### ISSUE TITLE
Stock Requisition From Depot to Depot

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3939]
This issue describes stock requisitions from one depot to another.  It is #3912 if the service has a depot.

A stock requisition is a way for one depot to request products from another depot.  It is similar to a reverse transfer - instead of depot A initiating a transfer to depot B and depot B accepting the transfer, the process starts with a requisition from Depot B, that Depot A can fill via a transfer.

**User Interface**

Since a requisition isn't a movement of stock, it will not be a button on the stock page.  Instead, it will be in the dropdown menu like this:
![Depot Requisition](https://user-images.githubusercontent.com/896472/66837229-90fb6380-ef5a-11e9-9620-49a5ef2f5e9b.png)

When a user clicks on this, they will have a modal similar to the stock entry modals:
![Depot Requisition (Modal)](https://user-images.githubusercontent.com/896472/66837258-9d7fbc00-ef5a-11e9-8fb8-bf21a06bb27c.png)

The depot administrator will then import then use the modal to specify:
 1. The depot that the stock should come frome
 2. The inventory item
 3. The quantity required

**Schema**
We need to add two tables:
_requisition_

uuid | depot_from_uuid | depot_to_uuid | user_id | filled
-- | -- | -- | -- | --:
XXXX-XXX-XXXX | Depot A | Depot B | jniles | 0

_requisition_item_

uuid | requisition_uuid | inventory_uuid | quantity
-- | -- | -- | --:
YYYY-YYYY-YYY | XXXX-XXX-XXXX | Ampilicin 500mg | 230
ZZZZ-ZZZZ-ZZZ | XXXX-XXX-XXXX | Sutures 1mm thread | 13

-----

**Other Notes**
The "transfer" interface will need to be changed to allow it to import data from requisitions to fill the transfer modal.  Once that is done, the requisition will be marked as "filled" and not show up as an option anymore.

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
@mbayopanda did this get done?

**Comment by jniles** [comment]
I think this has been closed.
