### ISSUE TITLE
Run installation tests on a CI

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3998]
We currently have a few tests for the installation page that aren't run as part of our regular CI builds.  We risk having the installation procedure crash without knowing it.  Let's figure out how to run our installation tests as part of the regular CI checks.  This could be on appveyor or an entirely new CI.

For reference, here is the test file: https://github.com/IMA-WorldHealth/bhima/blob/master/sh/install-tests.sh

**Comment by individual-it** [comment]
@jniles is this issue simply about running that script in CI?

**Comment by jniles** [comment]
@individual-it correct.  It sets up a clean database without any default data to make sure our installation process works correctly for new institutions.

**Comment by individual-it** [comment]
PR in #4453
