### ISSUE TITLE
Break up translation JSONs into multiple files.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#40]
Our translations files have become far to big to work with efficiently.  This leads to repeating the same keys in different contexts, and collisions in our git repository on almost every commit.

The fundamental question is how to break the translation files up.  For a start, we could try splitting on top-level domains, such as `hospital.en.json`, `finance.fr.json`, `shared.fr.json`, etc.  What do @IMA-WorldHealth/local-contributors think?

**Comment by sfount** [comment]
Sounds like a good idea to me - keeping files small should definitely reduce conflicts. Also the core BHIMA keys that are shared across all modules (form labels, actions etc.) should very rarely if ever change, it would be good to have these very clearly listed and simply accessed to reduce duplication.  :+1:

**Comment by mbayopanda** [comment]
Sounds like a good idea... i saw a tutorial on "Gettext" 
(http://blog.pragmasphere.com/2014/08/18/traduire-application-angularjs-angular-gettext/) 
but i think the angular translate library "pascalprecht.translate" is 
simple to use; and we can just find a mean to split the fr.json and 
en.json files correctly.

------ Message d'origine ------
De : "Jonathan Niles" notifications@github.com
À : "IMA-WorldHealth/bhima-2.X" bhima-2.X@noreply.github.com
Cc: "Bruce Mbayo Panda" mbayopanda@gmail.com
Envoyé 26/01/2016 10:54:17
Objet : [bhima-2.X] Break up translation JSONs into multiple files. 
(#40)

**Comment by sfount** [comment]
With this pull request landing https://github.com/IMA-WorldHealth/bhima-2.X/pull/283 and @jniles considering the layout structure on the server https://github.com/IMA-WorldHealth/bhima-2.X/issues/282 this would be a good time to tackle this issue.

**Comment by jniles** [comment]
@sfount, I agree.  Both @lomamech  and @DedrickEnc have done really nice work removing duplicate keys and cleaning up the files!  Now, it shouldn't be difficult to break these into separate files like this:

``` sh
 en/
    - form.json
    - tables.json
    - locations.json
    - modules.json
    - misc.json
fr/
   - form.json
   - tables.json
   - modules.json
   # etc...
```

In the build process, we can simply concatenate the files together and create `en.json` and `fr.json` as usual.  It might also speed up @jmcameron's i18n key comparison algorithm, since we'll be able to compare smaller JSON objects in parallel!

**Comment by jniles** [comment]
@lomamech, could you work on this next?

The idea is to take all of the first-level keys in the `fr.json` file and create smaller files.  For example, if we have:
```js
{
  "FORM" : {
     "LABELS" : {
        "KEY" : "VALUE",
         /* etc ...*/
      },
   "ACCOUNTS" : {
     /* etc ... */
    }
}
```
You would create two files `form.fr.json` and `accounts.fr.json` that contain the following:

**form.fr.json**
```js
{
  "FORM" : {
     "LABELS" : {
          "KEY" : "VALUE"
      }
   }
}
```
**accounts.fr.json**
```js
{
  "ACCOUNTS" : {
     /* etc ... */
   }
}
```

...

Once this is done, we need to write  gulp build script to combine the JSON files into a single JSON.  We can work on that together.
