### ISSUE TITLE
bhDateInterval doesn't set correctly dates

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4017]
This issue is about the fact that : 

- For the week, the bhDateInterval doesn't set correctly the end date (current date is 2019-11-25)
![image](https://user-images.githubusercontent.com/5445251/69541022-728c7d00-0f88-11ea-95c6-fb08429e302e.png)

- For the month, the bhDateInterval doesn't set correctly the end date (current date is 2019-11-25)
![image](https://user-images.githubusercontent.com/5445251/69541042-820bc600-0f88-11ea-8bdf-1d9805ec0228.png)

- For the year, the bhDateInterval doesn't set correctly the end date (current date is 2019-11-25)
![image](https://user-images.githubusercontent.com/5445251/69541062-8df78800-0f88-11ea-8f9a-537003f703ca.png)

**Comment by jniles** [comment]
Should it set the end date to today or to the end of the search period?    What is the expected behavior?

**Comment by mbayopanda** [comment]
@jniles the expected behavior is : 
- When we click on this month for example, we must have the start date set to `2019-11-01` and the end date set to `2019-11-30`, but with the bug we have `2019-12-01` instead of `2019-11-30`

**Comment by jniles** [comment]
Aha, okay, I understand what you are going for.
