### ISSUE TITLE
(Feature) Upload patient documents - Client Module

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#402]
This issue tracks development of the client side patient documents feature. This feature will be integrated as a panel module in the patient overview page described https://github.com/IMA-WorldHealth/bhima-2.X/issues/278 (Intended to be merged into master by 20/05). 

Features required by the client side documents feature: 
- **Ability to upload and assign new documents to a patient** 
- **List of all previous patient documents with a clickable link to view them (download?)** 
  - **If a patient has no documents this should be clearly demonstrated to the user**

This feature has not yet been visually designed however it should consider the smaller panel based design in https://github.com/IMA-WorldHealth/bhima-2.X/issues/278. 

The server side interface has been introduced into master https://github.com/IMA-WorldHealth/bhima-2.X/pull/389 with integration tests demonstrating the `POST` functionality. The list of available patient documents can then be displayed using the database record created during the upload as discussed https://github.com/IMA-WorldHealth/bhima-2.X/issues/63.

**Comment by jniles** [comment]
Closed via #452.
