### ISSUE TITLE
Migrate from glyphicons to font-awesome

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#404]
We currently use glyphicons throughout the application.  However, I have hit some limitations with these icons, and would benefit from a more expansive icon set.  In particular, glyphicons suffers from these defects:
1. No medical icons
2. No chart/graph icons (such as pie charts, line graphs, etc)
3. Limited files system icons (only folders and generic files, no docx icons, no PDF icons, etc).

For the reasons above, I propose we migrate to font-awesome instead of glyphicons.  @IMA-WorldHealth/local-contributors what do you think?

Note: This has previously been recommended by @mbayopanda.

**Comment by sfount** [comment]
This sounds like a good suggestion to me. If Font Awesome can be downloaded through bower without downloading the entire repository (including all source files) this should be fairly seamless. 

We could also use this opportunity to standardise our use of icons across shared components/ ideas used in modules.

**Comment by mbayopanda** [comment]
It's LGTM. "fa fa-search" is better than "glyphicon glyphicon-search" :-)

2016-05-19 4:03 GMT-07:00 Steven Fountain notifications@github.com:

**Comment by sfount** [comment]
Briefly researching it looks like font awesome does not have a bower or an npm install target. 

It looks like this shim https://github.com/components/font-awesome is kept up to date, this could be installed through 
`bower install components-font-awesome`

My suggestion is that we install this along side and begin allowing use of font awesome characters and then create an issue to track the replacement of glyphicons throughout the application.

**Comment by jniles** [comment]
@sfount, thanks for the research and a decent suggestion.  Feel free to either make a PR yourself or assign it to someone.
