### ISSUE TITLE
I can't log in to test the application

### ISSUE THREAD

**Issue by silvesan3** [third-culture-software/bhima#4049]
Good afternoon, I am trying to test the application. At the login with the superuser credentials it shows The Login Succeded but not have perimissions. Does anyone know what is happening?

**Comment by jniles** [comment]
Hi @silvesan3.  How did you initially create the application?

The user logging in will need to have a role assigned to them with permissions to the modules they need access to.  You can see where we do this on the command line in our test/data.sql : https://github.com/IMA-WorldHealth/bhima/blob/master/test/data.sql#L1041

**Comment by silvesan3** [comment]
I have tried to execute build-database.sh but it enters an infinite loop.
Type / build and start over. Sure that is ok? I don't know what I'm doing
wrong.
 I am doing research for a university job, just as you could help me find
the information I need.
- Software Architecture: patterns and anti-patterns
- Software Design: design patterns and anti-patterns

Sorry for my English, and thanks!

**Comment by jniles** [comment]
Hi @silvesan3,

Sorry for the long time in responding. 

The easiest way to build the database is to type "npm run build:db" on the command line.  Note that you will need to change the values in the `.env.development` file in the root of the repository to give your mysql username and password.

There is a more detailed guide available [in the documentation](https://docs.bhi.ma/en/for-developers/installing-bhima.html).

I'm not sure I can help you in software architecture or design as I'm not trained in either.  My background is in biology.
