### ISSUE TITLE
Invoicing on start of a Fiscal Year at 00:00:00 throws an unhandled exception

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#405]
Caught by:
`Patient Invoice`

> `invoices a patient for a single item`

Investigating this bug I noticed that the end to end test framework sets the date on invoices by emulating a user typing into the date select. 

The test types the following date:
`2016-01-01` 

``` js
{"status":400,"code":"ERRORS.BAD_REQUEST","description":""}
```

**This is a valid date in the fiscal year within the test frameworks data.**

Typing this date propagates the correct error:
`2015-12-31`

``` js
{"status":400,"code":"ERRORS.NO_FISCAL_YEAR","description":"No period found in the database for the provided date."}
```

Typing this date correctly registers an invoice:
`2016-01-02`

``` js
{"uuid":"71be3009-e7ff-496d-8dbc-c65b2273429a"}
```

**Date Selection Component Date/Time** 
If you click to select the date of January 1st 2016, this will successfully post an invoice. This seems to be a quirk in the date selection component. 

Submitting a number of test requests into the database shows that if you type into the date select the time will be set automatically to `00:00:00`. However if you click to select a date the time will be set as your current time, for example `10:54:34`. 

This demonstrates that this is not an issue if the time is anything > 0. **However if the time is `00:00:00` it will neither throw an invalid date nor successfully record the invoice, instead throwing the bad request.**

**Database record - date typed**
(Invoice date field is on the left, unrelated timestamp of record is on the right)
![date_typed](https://cloud.githubusercontent.com/assets/2844572/15389841/c346a950-1db0-11e6-9e4d-8c44c5ba3175.png)

**Database record - date selected**
(Invoice date field is on the left, unrelated timestamp of record is on the right)
![date_selected](https://cloud.githubusercontent.com/assets/2844572/15389848/c8fdf83a-1db0-11e6-86c6-9378e1d3a0d2.png)

**Comment by jniles** [comment]
This will probably bite us sooner rather than later, I'll take a look.

**Comment by jniles** [comment]
House keeping!
