### ISSUE TITLE
Use angular translate message format to pluralize messages

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#408]
[Message format](https://messageformat.github.io/guide/) is a way of personalizing messages uniformly between languages.  The angular-translate library has a plugin for message format interpolation, located [here](https://github.com/angular-translate/bower-angular-translate-interpolation-messageformat).  It depends on [MessageFormat.js](https://github.com/SlexAxton/messageformat.js/).

We can add a lot of benefit to user experience if we simply use more personal messages.  For example "You registered 12 patients about five minutes ago" is nicer than "You registered some patient(s)".  Another example is "A record was successfully created" is not as pleasant as "The 'Patients Payant Cash' debtor group was created successfully."

@IMA-WorldHealth/local-contributors this would require a lot of time spent thinking about translations, but I think they are worth it.  What do you think?

**Comment by jniles** [comment]
Alternatively, in the short term, we can use simple variable replacement.  This is available in the application right now.  See [this link](https://angular-translate.github.io/docs/#/guide/06_variable-replacement).

**Comment by DedrickEnc** [comment]
I think that using clears and expressive message is good and I think also keeping our message shorter and significant is better. For some CRUD operations for example, informing the user that his operation was performed successfully is more economic and preferable than a very long and detailed message which will not be read entirely. 
But I agree about some informative message such as a message about the registered entities.

**Comment by jniles** [comment]
Thanks for the feedback.  I agree with you.  I'm just thinking that `Created an account successfully` is nicer than `Create Success`.

**Comment by jniles** [comment]
For reference, PR #763 has a pretty good implementation.

**Comment by jniles** [comment]
This is used in a few places and this issue is no longer useful.
