### ISSUE TITLE
Analyse du module d'administration

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#410]
Administration

1/ Billing Services
 Le module Biling services utilise un ui grid pour la présentation, dans lequel on retrouve deux boutons
 pour la mise à jour ainsi que la suppression 
 Il existe néanmois un bouton au dessus de la grille qui permet d'ajouter un nouveau Billing Service 

2/ Cashbox Management
Le module cashbox management utilise un tableau à gauche et reserve un espace à droite pour le message qui decrit d'une manière sommaire le module ainsi que pour le différent formulaire concernant l'ajout ainsi que la mise à jour des cash box Management 

L'interface de ce module peut être refait en utilisant le ui grid comme pour cashbox Management

3/ Debtor Group
Pour Debitor group il existe à present deux types des présentations la première comme ceux existant dans Bhima 1X et la seconde ne presentant dans un tableau l'essentiel des groupes débiteurs avec plusieur possibilités en ce qui concerne l'affichage, le filtrage de données, le formulaire de création ainsi que celui de mis à jour sont vraiment très explissifs et sont très adaptés à des très long formulaires

La seconde présentation me semble meilleur par rapport à la première #/debtors/groups

4/ Depots
Le module gestion de depots utilise encore l'ancienne presentation de bhima 1X et par le fait qu'il n'existe pas beaucoup des propriétes pour un dépôt le ui grid risquerait d'occupé trop d'espace pour rien et je pense que le présentation de #/debtors/groups pourrai être meilleur pour ce module

5/ Donators
Le module donateur ne possede qu'une seul propriétés celui du nom du donateur
La suggestion à mon avis que le donateur puissent être enregistrer dans le même module 
que le crediteur ( Fournisseur ) parce qu'il peut aussi arriver qu'un fournisseur puissent
devenir aussi donateur et vis versat

6/ Enterprise
Je pense que pour le module entreprise, la présentation avec le ui grid pourrai s'averer ineficace parceque le module gestion de entreprise fait appel au fênetre modale C'est pour cela que je suggère la présentation de #/debtors/groups est meilleur 

7/ Exchange Rate
La présentation du module taux de change pourrai rester comme telle à moins qu'une autre présentation puisse être proposé

8/ Locations Management
Le module location management etant complexe je pense que cette presentation convient le mieux à moins qu'une autre présentation puisse être proposé

9/ Patient Groups
Je suggère que pour le module patient groups puissent être présenter avec le ui grid comme pour le module /#/admin/billing_services  

10/ Price List
Le module price list peut garder sa présentation actuelle 

11/ Projects
Le module project peut être modifier en utilisant  la présentation avec le  ui grid comme pour /#/admin/billing_services

12/ Services  
Le module service peut être modifier en utilisant  la présentation avec le  ui grid comme pour /#/admin/billing_services

13/ Subsidy management
Le module subsidy management peut qu'en à lui être presenter avec le ui grid comme pour /#/admin/billing_services

14/ Supplier
Le module supplier par le fait qu'il possède un long formulaire je suggère la présentation comme celui de #/debtors/groups mais aussi que le supplier et le donateur puissent être gerer dans un même module 

15/ Users and Permissions Management
Ce module pourra rester comme tel

**Comment by jniles** [comment]
@lomamech, merci pour l'analyse!  Nous allons le discuter a demain.

**Comment by jniles** [comment]
Je vais commencer de travailler sur les groupes des debiteurs, suivant les suggestions dans 3/.
