### ISSUE TITLE
Do we need service.uuid and service.id?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4104]
We have both a service uuid and a service ID column.  It isn't clear why this is the case.  Do we really need both columns?  Can we remove one and use the other instead?

**Comment by mbayopanda** [comment]
The `service_uuid` was originally added for being used in the `entity_uuid` column in the `stock_movement` table.

**Comment by jniles** [comment]
So, can we remove one?  Would it be bad to remove the service.id column and consider the primary key to be service.uuid?

**Comment by mbayopanda** [comment]
We can remove service.id the fact is we must explorer the whole application and apply changes :-)

**Comment by jniles** [comment]
@kwilu claim
