### ISSUE TITLE
Break global "reports" folder into separate "reports" subfolders in each module

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4146]
We currently have a global "reports" folder that is getting quite large.  We have a total of 41 reports in the `report` table.  Most of these reports are quite specialized - finance, stock, or medical.

To better manage our reports, we should break them up into separate folders for each component.  For example, we would have
```sh
- Finance
   - Reports
- Medical
   - Reports
- Inventory
   - Reports
```

This would also make it easier to manage permissions to the different reports, since we wouldn't have stock reports visible if there were no stock modules enabled.

**Comment by jniles** [comment]
@lomamech can you look into this?

**Comment by jniles** [comment]
@kwilu claim

**Comment by jmcameron** [comment]
Not sure  what you meant by:
- Finance
   - Reports
- Medical
   - Reports
- Inventory
   - Reports

It seems like these are all under the "Reports" top-level menu item.  Shouldn't this be:

- Reports
    - Finance
         - Rep F1
         - Rep F2
   - Medical
         - Rep M1
         - Rep M2

etc?

**Comment by jmcameron** [comment]
Ok, do you mean to move the Reports for Finance under the top-level menu item "Finance"?  etc?

**Comment by jniles** [comment]
@jmcameron apologies for not responding, I didn't see this.

Yeah, basically there should no longer be a generic "reports" folder, instead there should be many "reports" subfolders in each section.  That way, if we install only stock management, for example, we only need to have "inventory", "purchases" and "stock" as top level folders ... and all of those will contain their respective reports.

It should make it much easier to find reports in the future.
