### ISSUE TITLE
Allow users to set the number of months used to calculate the CMM

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4151]
Currently, the CMM is calculated using [six months of data](https://github.com/IMA-WorldHealth/bhima/blob/master/server/controllers/stock/core.js#L416), however, the algorithm allows us to specify a different base range of months of data.  Our friends in Vanga would like a way to input their own number of months of data for calculating the CMM, since they haven't been running the system for 6 months yet.

**Comment by lomamech** [comment]
@kwilu claim
