### ISSUE TITLE
Remove multiple "id" matches in the end to end tests

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4220]
In our Multiple Payroll (Indice) tests, the following warning occurs:
![image](https://user-images.githubusercontent.com/896472/77530563-d7ea6f00-6e91-11ea-85a0-150feaf5ad96.png)
_Fig 1: Warning multiple id matches_

This is a problem for a couple reasons.
   1. It means that we have multiple equivalent `id` elements on a page.  This isn't supposed to be allowed in HTML.
   2. It means our tests aren't specific enough.  We should always be precise about the element we are selecting.

These tests or components should be rewritten to address the above two points: so that `id`s are unique and that we are sure we are selecting the correct element when we click in a test.

**Comment by individual-it** [comment]
I've fixed the mentioned issue in #4237 but there are more similar ones

**Comment by jniles** [comment]
Closed in #4237.

Thanks so much @individual-it!  If you find other instances, feel free to look into how to fix them :)

**Comment by individual-it** [comment]
please reopen for `Role Management Tests`
![image](https://user-images.githubusercontent.com/2425577/78245948-0dcdca00-7508-11ea-99d1-2660d8d68422.png)

**Comment by jniles** [comment]
@individual-it done!

**Comment by individual-it** [comment]
fix in #4249

**Comment by individual-it** [comment]
more id fixes in #4250

**Comment by individual-it** [comment]
I think this issue can now be closed, there are more non-identical selectors in the UI tests, but I cannot see any where the reason is a not-unique html id

**Comment by jniles** [comment]
Thanks again @individual-it.  Really good clean up work.
