### ISSUE TITLE
Stock Assignment Modal inventory uiSelect should display and search by codes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4256]
The Stock Assignment module allows individual lots to be assigned to entities via the stock assignment modal.  However, in working on #4247, I discovered that you cannot select inventories by their code.  We should add this feature in - both displaying the inventory code and allowing users to filter on it.

[Here is the reference code](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/stock/assign/modals/action.modal.html#L35)

Here is an example:
![image](https://user-images.githubusercontent.com/896472/78472240-2835bc80-772f-11ea-8dcd-29d26c673885.png)

**Comment by lomamech** [comment]
@kwilu claim
