### ISSUE TITLE
Filter purchase order registry on barcode

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4273]
Similar to https://github.com/IMA-WorldHealth/bhima/issues/3396, https://github.com/IMA-WorldHealth/bhima/issues/3005, we should add the ability to rapidly filter the purchase order registry by barcode, just by scanning it.  The design should be identical to the other registries (stock, invoice, patient, cash, etc).  

**Design**
The basic idea would look like this:
  1. In the menu, select menu > Find by Barcode.
  2. The barcode component in a modal comes up to scan a barcode.
  3. The user scans the barcode.
  4. If a record matches the barcode, the modal disappears and the registry is filtered on that particular record.

Note that this issue depends on https://github.com/IMA-WorldHealth/bhima/issues/4272 being implemented first.

**Comment by jniles** [comment]
@jmcameron would you mind taking a look at this?  It will be a lot more involved than your previous work, and will get you more familiar with the client-side code.

Basically, you'll want to re-implement https://github.com/IMA-WorldHealth/bhima/issues/3005, but on the purchase order registry.  You'll likely be touching the following files:

1. https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/purchases/list/list.html - you will add the clickable link in the dropdown menu to this template.
2. https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/purchases/list/list.js - this is the controller that will contain the logic for searching via barcode.

The end result will look like this.  This example is pulled from the voucher registry.
![piUBVYeIc5](https://user-images.githubusercontent.com/896472/86601490-4e226580-bf99-11ea-84eb-2d18fec0c55b.gif)

**Comment by jmcameron** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @jmcameron!

Thanks for your interest in BHIMA! You have attempted to claim an issue without the labels "help wanted", "good first issue". Since you're a new contributor, you can only claim and submit pull requests for issues with the [help wanted](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22) or [good first issue](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22) labels.

If this is your first time here, we recommend reading our [guide for new contributors](https://zulip.readthedocs.io/en/latest/overview/contributing.html) before getting started.

**Comment by jniles** [comment]
@jmcameron I may have fixed the issue with kwilu.  Can you give it another shot?

**Comment by jmcameron** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @jmcameron!

You have attempted to claim an issue without the labels "". It seems like you are new to BHIMA, so we suggest working on an issue with the [help wanted](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22) or [good first issue](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22) label first. We also recommend reading our [guide for new contributors](https://zulip.readthedocs.io/en/latest/overview/contributing.html) before getting started.

To claim this issue anyway, comment on this issue again with the command `@kwilu claim --force`.

**Comment by jmcameron** [comment]
@kwilu claim --force

**Comment by kwilu** [comment]
**ERROR:** `newContributors.permission` wasn't configured.
