### ISSUE TITLE
Inventory Module Design

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#428]
This issue is about the proposal of design for Inventory modules : 

With BHIMA-1.X we had : 
1. Enregistrement des inventaires
2. Mettre à jour les inventaires
3. Configuration des groupes des inventaires
4. Configurer le type des inventaires
5. Voir la liste
6. Imprimer la liste des Inventaires

Our proposal is to have : 
1. A unit for "Inventory" which has : 
    1.1. List : A module of CRUD operations for inventory 
    1.2. Group : A module of CRUD operations for inventory group 
    1.2. Type : A module of CRUD operations for inventory type 

![image](https://cloud.githubusercontent.com/assets/5445251/15507952/74f9444e-2182-11e6-9928-6b2b499eb891.png)
1. Each of List, Group and Type has the same design : 
   2.1. ui-grid
   2.2. buttons for : add, edit and print the list of items 
   2.3. modals for adding and editing items in the module

![image](https://cloud.githubusercontent.com/assets/5445251/15508252/83e783a2-2183-11e6-992f-273ae315ce82.png)

![image](https://cloud.githubusercontent.com/assets/5445251/15508272/9ed6527e-2183-11e6-95e4-a8e9153a8784.png)

**Comment by jniles** [comment]
@mbayopanda, thank you for this analysis and design.  These are very nice mockups!
