### ISSUE TITLE
Make the "Reference" column in Stock Movements link it the PDF receipt

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4297]
The stock movements registry has a reference column that we could use to easily click on and view the document associated with that stock movement.  See below:
![image](https://user-images.githubusercontent.com/896472/79208798-74bd7e00-7e3a-11ea-92e9-831f0e0b3673.png)

This behavior should be similar to the other registries.

**Comment by lomamech** [comment]
@kwilu claim
