### ISSUE TITLE
The "cost" column in stock movements registry should have a sum at the bottom

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4304]
It would be really nice to have the sum in the base of the "cost" column of the stock movement registry.  This will let administrators make really quick analyses on the fly.  See below:

![Test](https://user-images.githubusercontent.com/896472/79266839-24710b00-7e90-11ea-9ad9-593115d0fd9f.png)

**Comment by jniles** [comment]
@lomamech can you work on this?

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/80399674-8169b980-88b1-11ea-90f6-8ab2fb87ef02.png)

@jniles  I do not think that it would be necessary to display the total, just because the movements of stock displays at the same time the entries of stocks as well as the exits, but also this total should have a **significant value in the management of stock**

**Comment by jniles** [comment]
@lomamech, you are right that it doesn't make sense in general - it gives a sort of volume of stock.  But the problem is we have no easy way to figure out the total value of stock for a given search (such as all entries or exists).  If a manager wanted to know this information, where would they look?

**Comment by lomamech** [comment]
> @lomamech, you are right that it doesn't make sense in general - it gives a sort of volume of stock. But the problem is we have no easy way to figure out the total value of stock for a given search (such as all entries or exists). If a manager wanted to know this information, where would they look?

![image](https://user-images.githubusercontent.com/8035588/80401051-9f381e00-88b3-11ea-964a-514adce4a997.png)
This report makes it easy to know the stock value

**Comment by jniles** [comment]
How do we filter stock given to one service?  Or to one patient?  Or to one particular inventory item?  Or assigned to one invoice?

**Comment by lomamech** [comment]
> How do we filter stock given to one service? Or to one patient? Or to one particular inventory item? Or assigned to one invoice?

I think we can add this filter, since we have all the elements

**Comment by lomamech** [comment]
@jniles  What the continuation of this issue, should I add filters to be able to filter by
- Patients
- Service
and others

**Comment by jniles** [comment]
@lomamech, I've been thinking about this for a couple of days.  I think the only case it doesn't make sense to SUM the values, is when you have entry + exit.  Could we just show the total at the bottom of the registry if the registry is filtered on entry or exit?

**Comment by lomamech** [comment]
> @lomamech, I've been thinking about this for a couple of days. I think the only case it doesn't make sense to SUM the values, is when you have entry + exit. Could we just show the total at the bottom of the registry if the registry is filtered on entry or exit?

There will also be another problem, if there are a lot of inter depot movements, imagine that the same item must enter the central depot, then enter the small pharmacy

**Comment by jniles** [comment]
@lomamech good point.

What do you suggest to allow our clients to get this information easily?

**Comment by lomamech** [comment]
> @lomamech good point.
> 
> What do you suggest to allow our clients to get this information easily?

I think we can be content with the report
*This report shows the current stock value for each inventory in a depot*

![image](https://user-images.githubusercontent.com/8035588/81276910-9251c200-904b-11ea-94b1-bffc0a02f6ce.png)

**Comment by jniles** [comment]
This report is currently broken.   See https://github.com/IMA-WorldHealth/bhima/issues/4116.  Would you like to work on it?

**Comment by lomamech** [comment]
> This report is currently broken. See #4116. Would you like to work on it?

I Will do

**Comment by kwilu** [comment]
Hello @lomamech, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!
