### ISSUE TITLE
Link the patient from the "Stock Movement Registry" if the entry is from a patient or the distribution is to a patient

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4309]
It would be useful to link to a patient from the Stock Movement Registry if the flux is to a patient or from a patient. 

It would look like this:
![image](https://user-images.githubusercontent.com/896472/79269218-fee60080-7e93-11ea-8552-19d8c9abefd4.png)

**Comment by lomamech** [comment]
@kwilu claim
