### ISSUE TITLE
Add stock movements to patient financial activity as an optional parameter

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4310]
We have a report for showing patient financial activity in the reports folder.  It is "Situation financière d'un Patient" in French.  See below:
![image](https://user-images.githubusercontent.com/896472/79270036-50db5600-7e95-11ea-8042-fd1e415a7e04.png)

This report prints out all the transactions associated with a patient.  We should add an option to add in the stock movements to the bottom of the report.  This would be in a separate table from the transactions.

**Comment by lomamech** [comment]
@kwilu claim
