### ISSUE TITLE
Link to Articles in Stock from the Stock Movements Registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4318]
It would be really nice if we could check the quantity in stock in a depot by clicking on the movement link in the depot.  We currently do not have that option.  Let's put an option on the dropdown menu to allow us to link to the Articles in Stock.  It should filter on the lot and the depot.

![image](https://user-images.githubusercontent.com/896472/79450497-dcabca00-7fdc-11ea-8e1d-1f421fd6dd5e.png)

**Comment by lomamech** [comment]
@kwilu claim
