### ISSUE TITLE
Purchase Orders do not show unit information at Vanga, but show unit information at IMCK

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4325]
We are starting to get interesting differences between the different deployments.  At IMCK, the purchase orders show unit information, but at Vanga, they do not.  See below.

![image](https://user-images.githubusercontent.com/896472/79547329-a5482680-808b-11ea-81cc-eea244867416.png)
_IMCK's Purchase Order_

![image](https://user-images.githubusercontent.com/896472/79547112-5bf7d700-808b-11ea-8cf8-fce513a4f55f.png)
_Vanga's Purchase Order_

**Comment by lomamech** [comment]
@kwilu claim

**Comment by lomamech** [comment]
@jniles After investigation, I realized that in the VANGA database the abbr column is never completed

![image](https://user-images.githubusercontent.com/8035588/79963553-77932100-8481-11ea-8f1e-72d518e75250.png)

**Comment by lomamech** [comment]
And I also note that on the line 8 and 10 we could have  text: **Flacon** and abbr: **flc**

**Comment by jniles** [comment]
@lomamech thanks for this investigation.  What do you suggest we do?

**Comment by lomamech** [comment]
> @lomamech thanks for this investigation. What do you suggest we do?

Either Vanga must complete and correct the data in this table, or for display we can modify the query by first displaying **abbr or text**

**Comment by jniles** [comment]
Cool, I will work with AG Neron to get them to update this information.

**Comment by jniles** [comment]
@lomamech I am removing you since this task is done.

**Comment by jniles** [comment]
This has been solved.
