### ISSUE TITLE
Improvements to "Optimal Purchase Orders"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4326]
We have an "optimal purchase order" functionality in the purchase orders module that creates a purchase order based on your previous stock consumption.

Currently, all the price information for the optimal purchase order is blank.    We need to implement https://github.com/IMA-WorldHealth/bhima/issues/4119 for this optimal purchase order feature.  The prices should be pulled out of the most recent price information.  This will greatly assist our users who need to fill out multiple purchase orders.

There is also no loading indicator on the "optimal purchase order" button which makes it difficult to know what state the module is in on a slow connection.

**Comment by lomamech** [comment]
@jniles I think that the prices should come from the suppliers, based on the old prices can induce if there is inflation and deflation of the prices

**Comment by jniles** [comment]
@lomamech this is a request from our clients in Vanga.  Apparently the prices don't change very much for them.  You can always change the price during the process, but the default price should be the previous purchase price instead of 0 to save time.

**Comment by jniles** [comment]
@kwilu claim
