### ISSUE TITLE
Add the option to include months without stock exits to the CMM

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4327]
In the current CMM calculation, we do not consider months that do not have any stock movements.  This means if you have the following consumption graph:

jan | feb | mar | apr | may | june | july | aug | sept | oct | nov | dec
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1000 | 0 | 1000 | 0 | 1000 | 0 | 1000 | 0 | 1000 | 0 | 1000 | 0

The CMM will be **1000**, rather than **500**.

It only makes sense to ignore the months with 0 if you believe those months are missing data.   For example, if there was a stock out or you were unable to get stock delivered to patients or unable to record consumption information.  However, if you believe that 0 value is reflective of the reality of the demand, it makes sense to include it since your CMM will not be able to predict the demand of the subsequent month.

I propose that we implement an option to include the months without exits in the CMM.  This will allow users to make an informed decision about their future in both scenarios and they will have the freedom to choose what makes sense to them.

**Comment by lomamech** [comment]
@kwilu claim

**Comment by jniles** [comment]
@lomamech have you begun working on this?  It looks like I was very wrong about this - all procurement manuals I can find warn against doing what I've proposed.

**Comment by lomamech** [comment]
Yes, I have already started 75% but I can stop

**Comment by lomamech** [comment]
@jniles what should i do, finalize or change tasks  :twisted_rightwards_arrows:

**Comment by jniles** [comment]
I say we abandon this initiative to avoid introducing a feature that may be bad practice.

**Comment by jniles** [comment]
I'm basing this on the UNDP's course on [Procurement and Supply Management (PSM) of Pharmaceutical Products](https://procurement-notices.undp.org/view_file.cfm?doc_id=38987).

> It is important to adjust the calculation by taking into account the number of days of supply shortages during the period that is used as a basis for the calculation. When the stock of a product is zero, then the demand for that product cannot be met, and that demand goes unrecorded as far as use of medicines is concerned. Stock and usage records therefore do not reflect that unmet demand, and real demand is therefore underestimated. **Omission of this correction is one of the most frequent Quantification errors**, and causes an under-estimation of needs and subsequently more stock outs.
