### ISSUE TITLE
Create a Stock Movement Dashboard

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4342]
Similar to https://github.com/IMA-WorldHealth/bhima/issues/4340, https://github.com/IMA-WorldHealth/bhima/issues/4339, and https://github.com/IMA-WorldHealth/bhima/issues/4341, we should implement a stock movement dashboard that groups stock movements by date over a period.  This would be accessible from the stock movement registry.  It would look something like this:

![image](https://user-images.githubusercontent.com/896472/79962906-95ac5180-8480-11ea-8227-955a19ad1986.png)
_Fig 1: Stock Movement Dashboard_

To configure this, a user needs to provide:
  1. The Fiscal Year
  2. The Period
  3. The Flux Type
  4. The type of data - # of movements or value of movements.

**Comment by jeremielodi** [comment]
I'm working on this

**Comment by jeremielodi** [comment]
@jniles I need a quick explanation for  ```# of movements``` is it the number of movement per day?
 ```value of movements``` is quantity*unit_cost?

**Comment by jniles** [comment]
@jeremielodi you are correct.
