### ISSUE TITLE
Calculation of the CMM (Average Monthly Consumption)

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4344]
This discussion is more to document how that average monthly consumption (CMM in French) is calculated.

Currently in BHIMA, we only consider medicines dispensed to patients and services as consumed.  This means that we must know that the medicines were given to a patient or service for it to count against the CMM.  Therefore, if stock expires, is stolen, or is lost for some other reason such as damaged, the write-off doesn't count against the stock consumption.

**Prior Art**
Here are some resources from various manuals I have found around the web. 

According to _Chapter 7: Supply Management_ of the WHO's [Operations Manual for Staff at Primary Health Care Centres](https://www.who.int/hiv/pub/imai/om_7_supply_management.pdf):
>  Please note that the units dispensed each month does not include the items returned or issued for disposal or destruction due to bad quality, or those that have been lost, wasted or have expired. If possible, include medicines for emergency use such as for post exposure prophylaxis (PEP)

This definition is in agreement with BHIMA's definition since it only counts consumption by patients.

----

According to _Section 2: Procurement and management of supplies and equipment_ of the WHO's [Medical Supplies for PHC](https://www.who.int/management/resources/procurement/MedicalSuppliesforPHC(2)Procurement%26Management.pdf) (page 14), the algorithm for calculation stock consumption is:
> Step 1: Select the time period for calculating consumption
> Step 2: Calculate the consumption for each item during the time period
>     Recorded consumption = Opening stock balance + Stock received – Closing stock balance 
> Step 3: Adjust consumption figures for wastage or stockouts
>     Real consumption (RC) = Recorded consumption – Wastage (avoidable losses)

This definition includes an explicit adjustment for stock losses.

-----

In MSH's [Inventory Management](https://www.msh.org/sites/msh.org/files/mds3-ch23-inventorymgmt-mar2012.pdf) text, they make allusion to "average monthly consumption, adjusted for stockouts", but do not actually tell you how to calculate it.

-----

According to MSH's [Quantifying Pharmaceutical Requirements](https://www.msh.org/sites/msh.org/files/mds3-ch20-quantifying-mar2012.pdf):
> In  many  instances,  the  most  precise  method  for  quantifying  pharmaceutical  usage  is  the  consumption-based  approach, provided the source data are complete, accurate, and properly adjusted for stockout periods and anticipated changes in demand and use. This method does not normally address the appropriateness of past consumption patterns, which may or may not correspond with public health priorities  and  needs.  Thus,  irrational  medicine  use  may  be  perpetuated by total reliance on the consumption method. If stockouts have been widespread for long periods, applying this method accurately may be impossible, which is why capturing actual demand is the most accurate approach.

Furthermore, they state:
> Inevitably, some medicines will be lost because of damage, spoilage, expiration, and theft. If such losses are not considered in quantification and procurement, stockouts are likely to result. To prevent shortages, a percentage can be added to allow for losses when quantifying requirements. Many systems need to allow at least 10 percent for losses.

This indicates they are including the loss due to theft, but as an additional step afterwars (similar to the WHO's calculation).

---

According to the UNDP's course on [Procurement and Supply Management (PSM) of Pharmaceutical Products](https://procurement-notices.undp.org/view_file.cfm?doc_id=38987) 
> Several issues related to supply management may distort consumption and pose challenges to quantification: supply shortages and expired stocks, loss, thefts and overstocks. Other factors may also influence consumption, including donations of medicines not included in statistics, or the use of standardised kits of medicines where quantities are set beforehand per kit and therefore not reflecting actual consumption

---

**Conclusions**
So it isn't really clear.  On one hand, loss due to theft, expiry, and damage doesn't really reflect the real consumption, but on the other hand, you need to replace that medicine to ensure you don't have a stock out.

Currently BHIMA only considers the real consumption to patients.  Should we be considering losses as well?

**Comment by TimRiceMD** [comment]
At our hospital the CMM is used to gauge the adequacy of stock on hand based on average monthly consumption.  Thus the goal is to be sure there is enough stock on hand.  If an institution has a large amount of theft, expiry, and damage then the institution would need to have a larger stock on hand to cover for these issues.  

There is a value of knowing the "Real Consumption" actual medication use by patients.  So it would be valuable to know that for some medications we have only 80% "Real Consumption" (of the medications going to the patients) and 20% are lost/wastage due to theft, expiry, and damage.  Thus this loss or wastage is a marker of the quality of management of and institution.

**Comment by jniles** [comment]
It sounds like we need two indicators - CMM and "Adjusted" CMM.  The first would be used to report consumption data by patients, and the second would include stock exists due to theft/loss and  be used for forecasting optimum re-order amount.

Basically:
  1. **CMM** - Sum of all exits to patients and services / time period.
  2. **Adjusted CMM** - Sum of all exists / time period.

We wouldn't have to do any updates to (1) as it exists in BHIMA, but we would want to use (2) to calculate the "optimal reorder".

**Comment by jniles** [comment]
We now support multiple algorithms to calculate the CMM, including the MSH one.  The most recent PR making this concrete is https://github.com/IMA-WorldHealth/bhima/pull/4993.
