### ISSUE TITLE
Lots in Stock throws an error if no lots have been added to the database

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4345]
The Lots in Stock registry throws an error if there are no lots found, rather than telling the user that there is no lots in stock found. This was reported by AG Neron.  See below:

![Hlh3FE18WF](https://user-images.githubusercontent.com/896472/79997344-62ce8180-84b1-11ea-9839-6d2855ae0eec.gif)
_GIF 1: Default Broken Lots Registry_

It should behave like the Stock Movements registry which shows "No records found" if there is no information found.

**Comment by lomamech** [comment]
@kwilu claim
