### ISSUE TITLE
Adjusting for Stockouts in the CMM/AMC

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4346]
This issue is related to https://github.com/IMA-WorldHealth/bhima/issues/4344 and https://github.com/IMA-WorldHealth/bhima/issues/4327.

According to my research on Stock Management, the CMM/AMC should be "adjusted for stock outs".  The way BHIMA does this currently is by adjusting for lack of _exits_. In other words, if there is stock in the depot, but no exit occurred during a month, we remove that from the calculation.  That was the main idea because this issue: https://github.com/IMA-WorldHealth/bhima/issues/4327.

However, I think the calculation would be more accurate if we did two things:
  1. We transitioned from counting missing stock consumption as missing data to considering _stock outs_ as missing data.
  2. We started calculating the consumption for a month based on the daily consumption rather than the monthly consumption average.

We actually can't do (1) easily yet - I'm not sure BHIMA tracks the quantity in stock by day.  This would be a rather intense calculation.  We might need a table like `period_total` to hold these values.

Let me give you an example:

Let's assume that we give 50 pills of Amoxy to each patient every day in January.  Let's assume that we give 1 pill on February 1st, and then we run out of stock for the rest of February.  Then we order one pill and give it out on the 1st of March and have stock outs for the rest of March.

In the current calculation of BHIMA, we would have a CMM of: `(50 + 1 + 1) / 3 = 17.34`.

If we calculated this value by day, we would instead have:
  1. 31 days of 50 pills / day.
  2. 1 day of 1 pill / day
  3. 1 day of 1 pill / day.
  4. And the rest we exclude because we had stockouts.

This gives:  `( (50 x 31) + 1 + 1) / (31 + 1 + 1) = 47.03`.  Notice how this is much closer to our actual demand when we have sufficient stock (50 pills / day). 

@mbayopanda @lomamech @jeremielodi what do you think?

**Comment by mbayopanda** [comment]
- For the first point considering stock out as missing data, could you explain it more cause i can't catch the idea here

- The second point will give us an excellent estimation of CMM by considering days of distribution

**Comment by jniles** [comment]
Thanks for your feedback @mbayopanda !

For the first point, we don't consider the quantity in stock when we do our calculation of CMM.  Instead, we look in the `stock_consumption` table.  [Here is the code for the algorithm](https://github.com/IMA-WorldHealth/bhima/blob/6fe35d18197fab1eeb3fc48fc9c8f85bb0a48f27/server/controllers/stock/core.js#L407).

The proposal is to look at the quantity in stock each day and :
  1. Consider the consumption to be 0 if there is stock in the depot, but no movements/consumption.
  2. Do not consider the day if there is no stock in the depot for that item.

For example, imagine the follow scenario:
![image](https://user-images.githubusercontent.com/896472/80091888-c7ddb200-8559-11ea-9fc9-d20c1dde3b16.png)

Currently, we would remove the 4 days in red since there were no stock movements on that day ("consumption = 0").  However, I think what most people do is remove 2 days for when there was a stock out ("quantity in stock = 0"), since the consumption was 0 and there was quantity in stock, meaning there was no demand for stock that day.

**Comment by jniles** [comment]
This assumes that we have accurate data 🤷‍♂️

**Comment by mbayopanda** [comment]
Ah okay... But I seems like the second point of the solution which consider just days for CMM will fit with this first point arguments, since we will just consider days of consumption :
- The stock of those days will not be zero
- The stock consumption of those days will not be zero

**Comment by jniles** [comment]
Yes, but the inverse isn't true - days without consumption may still have stock available.

**Comment by jniles** [comment]
Some work was done in #4477, but we still need to complete the calculation for days where there is quantity in stock and no consumption events.

**Comment by mbayopanda** [comment]
@jniles in this case what will be the CMM, @jmcameron and I would like to work on that but we need more details and explanation for this last remaining case

**Comment by jniles** [comment]
I think the current calculation does not calculate the CMM based on the number of days where we had medicines in stock.  Instead it computes the CMM on the number of days we had consumption of the stock.  It needs to differentiate between the days when we had medicines in stock but no consumption (that is 0 consumption) and the days when we did not have medicine in stock (which should be ignored from the CMM calculation).

**Comment by jmcameron** [comment]
I think we could also complete this in two steps: fix the CMM calculation based on our current understanding to finish this PR. Then add another PR  to add more tests to make sure we're doing the math correctly.  If @mbayopanda can finish up this PR, I can then work with Bruce on the second PR to expand the testing of the CMM.

**Comment by jniles** [comment]
Since we can now choose our own algorithm for the CMM #4993, this has been fixed.
