### ISSUE TITLE
Improvements to the Stock Consumption Graph Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4353]
We just merged a graphical report on stock consumption (https://github.com/IMA-WorldHealth/bhima/pull/4336).  While using it to investigate live data, there are a couple of improvements we can make to make it more user-friendly.

1. Reorder the selection options so that the fiscal year and period are first (they are the only two required).
2. If multiple inventory items are selected, show the bar graphs in different colors.
3. Make the chart dynamically resize to take up 100% of the width of the page.  The PDF print out doesn't look good at all - see the attached PDF report.
4. The clear buttons don't work on the inventory and depot select.
6. Allow a user to choose between the _value_ of the stock or the _quantity_ of the stock.
7. Do not show non-consumable inventory items.
5. Sometimes the numbers stick above the graph - we should make the Y-axis long enough to accommodate the numbers on the graph.  See below:
![image](https://user-images.githubusercontent.com/896472/80193625-1306cc00-8611-11ea-9d33-499bc9394e3e.png)

[Example.pdf](https://github.com/IMA-WorldHealth/bhima/files/4527715/Test.pdf)

**Comment by jeremielodi** [comment]
![muti-enventory](https://user-images.githubusercontent.com/25838121/80480545-c68cfa80-8948-11ea-9aa0-c69313c114df.PNG)
