### ISSUE TITLE
Embedded PDFs are not displayed on mobile browsers 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#437]
We currently use the `iframe` object to display PDFs within BHIMA. Currently there is no fallback for browsers that do not support the `application/pdf` type. 

@mbayopanda has presented [PDF Object](https://pdfobject.com) to the team and this may be a solution. 

This would have to verified to work cleanly with the method currently used for printing PDFs through iframes. 

On mobile we provide a link to either download or open the PDF in a new tab/ supported application.

**Comment by jniles** [comment]
We might be able to do with a simple [<object>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) tag and provide the fallback to download [by putting text inside of the tag](https://stackoverflow.com/a/18432886).  It would be work investigating.  My understanding is that we used an `<iframe>` to isolate styles as well as give the ability to call `frame.print()` on it.  I wonder if that strategy would still work with an `<object>`.

**Comment by jniles** [comment]
This issue is no longer relevant, as PDFs render fine on Firefox on Android.  Presumably the same on Chrome and other rendering engines.
