### ISSUE TITLE
Rapport de Sorties de Stock doesn't sum values correctly when details are not displayed

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4384]
The Rapport de Sorties de Stock doesn't show the correct values if you hide the details.  My guess is that it is summing the unit costs instead of the total costs.  See below:
![uv5XB1I8MP](https://user-images.githubusercontent.com/896472/80488316-0b6b5e00-8956-11ea-8d78-29e9f090385c.gif)
_GIF 1: Different values depending on if details are shown or not_

**Comment by jeremielodi** [comment]
It's complicated to reproduce the issue, everything seems to be well calculated

![st1](https://user-images.githubusercontent.com/25838121/80723183-37bee000-8af8-11ea-92ca-7316581ed6d2.PNG)
![st2](https://user-images.githubusercontent.com/25838121/80723197-3c839400-8af8-11ea-8613-588125873b72.PNG)

**Comment by jniles** [comment]
That is because there is only one movement for each category.  Try adding another one.

**Comment by jeremielodi** [comment]
You're right
