### ISSUE TITLE
Make bhima's Tree Navigation awesome

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#44]
A huge refactor of the CSS + logic powering bhima's Tree Navigation component just landed (#42).  The tree is functional and re-skinned for 2.X standards.  This issue is to track new features we might want to add to the navigation either for bhima 2.X or beyond.  If a PR lands with any of these features, feel free to link them and tick the checkbox.
- [x] Page refresh should preserve the current highlighted tree module.
- [x] The navigation should match the base URL in the cases when $routeParams are present. (e.g. '/patients/:uuid?' should be matched in all the following cases: '/patients', 'patients/', 'patients/1324').
- [ ] [:small_red_triangle_down: Low Priority] Colour coded routes showing category (this will happen one day) - for example:
- Hospital - Blue
- Finance - Orange
- Inventory - Yellow
- Stock - Green
- Reports - Purple
- [ ] End to End tests for all tree functionality
- demonstrate that pages are remembered in the browsers cache.
- demonstrate that the sort order is alphabetical on free nodes
- demonstrate successful logout

**Comment by sfount** [comment]
The second issue can be addressed by simply changing the navigation change watch method - right now it looks for a direct match on a normalised string ('/' removed etc.) [navigation.js:62](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/directives/navigation.js#L62)

This could instead iterate through all paths (index in `unitsIndex`) and do something along the lines of 

``` js
url.indexOf(unit.path) !== -1; // Supported in all JavaScript versions
url.includes(unit.path); // Beautiful - more recent versions of JavaScript
```

**Comment by sfount** [comment]
- [ ] [ :small_red_triangle_down:][Low low priority] Colour coded routes showing category (this will happen one day) - for example:
* Hospital - Blue
* Finance - Orange
* Inventory - Purple
* Stock - Green 
* Reports - Purple

**Comment by jniles** [comment]
Include in "end to end tests":
- demonstrate that the tree remembers the collapsed/opened behavior across page refreshes
- demonstrate the previous tree node is successfully deselected when navigated away to any (even an unknown) link.

**Comment by sfount** [comment]
(Important UX fix) Collapse the tree on successful log out to make the
login page always present a uniform structure.

**Comment by jniles** [comment]
This directive ought to be migrated to a self-contained `angular.component()`.  It's big enough and complex enough to merit the defaults of a component.
