### ISSUE TITLE
Favour moment library over manual date manipulation

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#440]
There are many places that we format dates both on the client and the server using the Javascript date object. This isn't a problem as long as we test/ verify that it is consistent across environments. However it can cause two issues: 
- Manual date manipulation can be very difficult to read https://github.com/IMA-WorldHealth/bhima-2.X/pull/421#discussion_r64591977
- Each developer may come up with a slightly different way of splitting and manipulating date strings that are not always consistent 

I suggest that as we we already have a dependency on the [momentjs](http://momentjs.com/) library we use this to define and format dates both on the server and the client. This might involve setting up a style guide for how dates should be displayed/ created. 

For example: 

``` js
// Explicit - this will always be the same
moment().format('YYYY-MM-DD'); // 2016-05-25

// Much easier to write - changes with locale but that can be researched 
moment().format('L'); // 05/25/2016
```

**Comment by jniles** [comment]
No problem with this.  How will we deal with date formatting if it takes place on the server?

**Comment by jniles** [comment]
Note - `moment` should also be used in place of `DateService`, which can eventually be removed.

**Comment by jniles** [comment]
I think this has mostly been accomplished.  I'll make an issue to remove DateService, which should kill the rest of the instances not using `moment`.
