### ISSUE TITLE
Downloading employee registry as CSV crashes 

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4452]
A GIF is worth a thousand words:
![KpeNc9COd0](https://user-images.githubusercontent.com/896472/81160550-16d80e00-8f82-11ea-8778-9f8ee7b886d8.gif)

To reproduce, all you need to do is download the employee registry as CSV and the SQL query fails with unknown column error.

**Comment by lomamech** [comment]
@kwilu claim

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/81287386-93d6b680-905a-11ea-86cd-3e353ff49f9e.png)

The problem comes from this query, because it refers to several column which does not exist
