### ISSUE TITLE
MySQL 5.6 not supported

### ISSUE THREAD

**Issue by individual-it** [third-culture-software/bhima#4457]
noticed when working on #2090:
the version 5.6 of MySQL is not supported because the `JSON` type was only introduced in 5.7 https://dev.mysql.com/doc/refman/5.7/en/json.html

What to do? Trying to be downward compatible or delete 5.6 out of the documentation?

**Comment by jniles** [comment]
Oh!  How interesting - it looks like the JSON column was introduced [last year](https://github.com/IMA-WorldHealth/bhima/commit/be6494692841a6ba5f91d78929cf70404b3e6af6).  This is why we need better testing... 😄 

Personally, I'd rather dedicate work to migrating up to MySQL 8 than down to 5.6.  Let's just do a documentation update for now.  We'll take a look at patching the password function for MySQL 8 and see if we can get at least 5.7 and 8 playing together first.

**Comment by individual-it** [comment]
PR in #4462
