### ISSUE TITLE
Document all databases that BHIMA works on

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4494]
Thanks to the work of @individual-it and @jeremielodi, we now have a set of database that BHIMA works fairly well on.  In our documentation, we only refer to MySQL 5.7 and MySQL 8.

Let's document the databases that BHIMA actually works and doesn't work on to keep track of what we can install on.  I'm imagining something like this:

  | Working? | Notes
-- | -- | --
MySQL 5.6 | X | Requires JSON column type.  Not   tested
MySQL 5.7 | OK | Tests: integration, end to end
MySQL 8 | OK | Tests: integration
MariaDB 10.3 | ? | Tests: none
MariaDB 10.4 | ? | Tests: none
MariaDB 10.5 | OK | Tests: integration

**Comment by individual-it** [comment]
@jniles after #4473 gets merged MySQL8 would run for integration, e2e and installation tests
MariaDB runs currently e2e and installation tests but no integration tests

**Comment by individual-it** [comment]
this should be addressed in #4473 
I've added a ToDo for myself https://github.com/IMA-WorldHealth/bhima/pull/4473#issuecomment-627778634

**Comment by jniles** [comment]
We officially only support MySQL 8 now.
