### ISSUE TITLE
delete unknown fee_center returns 204

### ISSUE THREAD

**Issue by individual-it** [third-culture-software/bhima#4521]
noticed when working on #4511

this if statement seems not to do anything https://github.com/IMA-WorldHealth/bhima/blob/fcd30509b0d7e04f43a87e6be45bba5c45fdf0f4/server/controllers/finance/feeCenter.js#L222 
because rows is an array
```
{
  "rows": [
    {
      "fieldCount": 0,
      "affectedRows": 0,
      "insertId": 0,
      "serverStatus": 3,
      "warningCount": 0,
      "message": "",
      "protocol41": true,
      "changedRows": 0
    },
    {
      "fieldCount": 0,
      "affectedRows": 0,
      "insertId": 0,
      "serverStatus": 3,
      "warningCount": 0,
      "message": "",
      "protocol41": true,
      "changedRows": 0
    },
    {parts of the 
      "fieldCount": 0,
      "affectedRows": 0,
      "insertId": 0,
      "serverStatus": 3,
      "warningCount": 0,
      "message": "",
      "protocol41": true,
      "changedRows": 0
    }
  ]
}
```

I guess the if should test all 3 `affectedRows`.

I can fix this, but don't want to mangle it into #4511 so this is a note to not forget

**Comment by jniles** [comment]
Hi @individual-it, thanks so much for your continued work on these issues!

Just checking - did this get fixed in https://github.com/IMA-WorldHealth/bhima/pull/4511 ?  Or is it still needing to be fixed?

**Comment by individual-it** [comment]
@jniles no, I left this issue for an other PR, I wanted to have only the MySQL 8 refactoring in #4511

**Comment by jniles** [comment]
Gotcha, that makes sense.

**Comment by jniles** [comment]
@kwilu claim
