### ISSUE TITLE
Deprecation warning in installation tests on Node v14

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4543]
We are getting a deprecation warning on Node 14 in our installation tests.  It would be helpful if someone tracked it down.

![image](https://user-images.githubusercontent.com/896472/82820655-7f881b80-9e9a-11ea-89c3-b60d70ff6ecf.png)

Here is the link: https://travis-ci.com/github/IMA-WorldHealth/bhima/jobs/339689682#L468

**Comment by mbayopanda** [comment]
**Chai-http** use a version of **superagent** which have deprecated methods or functions

https://github.com/chaijs/chai-http/issues/262
