### ISSUE TITLE
Serve Node over HTTP, use nginx for HTTPS.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#455]
_This issue is imported from @sfount's 1.X issue found [here](https://github.com/IMA-WorldHealth/bhima-1.X/issues/707)._

Currently our node server uses the HTTPS protocol to serve BHIMA. I have found that this can be inconvenient whilst developing, it also creates large warnings about how the website is 'untrusted'. 

This is not a problem if the server is configured correctly with the correct SSL certificates installed, however I worry that this is a complicated process for someone who does not fully understand networking. 

My suggestion (for this discussion) is to use a **reverse proxy** to encrypt the network traffic and run our node server through HTTP. 

This would look a bit like this 

`Client` <-> `Reverse proxy (HTTPS server)` <-> `Node BHIMA server (HTTP)`

A very popular and widely used reverse proxy server is called [nginx](http://wiki.nginx.org/Main). We can configure this with one configuration file (nginx.conf) to act as a reverse proxy for the BHIMA server. Here are some pros and cons to using a separate process for HTTPS:

Pros 
- Very quick for development - simply type localhost, no worrying about certificates or trusting any sites
- Requires no additional network experience for hospital installs - if the hospital does not have the experience to set up HTTPS they do not need to and will receive no warnings about the untrusted website 
- If certificates expire or the configuration is broken the Node server can still be accessed through HTTP 
- Reverse proxy allows load balancing across many cores and machines if BHIMA is ever big enough 
- Purely optional - if the hospital is equipped to encrypt their data connection they can add this nginx instance
- Clear separation of networking jobs/ development and BHIMA application development 

Cons 
- It is no longer mandatory to serve the connection over HTTPS - HTTP is **very** vulnerable to hacking 
- If the nginx server breaks (for some reason) that is an additional thing to debug 

This is just a suggestion/ discussion - we can decide on if this is right for BHIMA or not.

**Comment by mbayopanda** [comment]
How about the ease of deployment in Windows or Linux plateform ?

**Comment by jniles** [comment]
The main advantage this proposal has (for development) is that you do not have to use HTTPS during development.  This means that there will be no more certificate errors locally.

For deployment, both Windows and Linux are supported by nginx, though windows support is only beta in Windows ([see here](http://nginx.org/en/docs/windows.html)).  However, you can use any web proxy (apache, HAProxy, etc) and are not limited to nginx.  I recommend we build official support for nginx, since it will be a single configuration file.

Does that answer your question?

**Comment by mbayopanda** [comment]
Yes, thank you very much...

2016-05-30 14:08 GMT-07:00 Jonathan Niles notifications@github.com:
