### ISSUE TITLE
Eliminate Duplicate Selectors found in IPR Tax Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4559]
This somewhat worries me:
![image](https://user-images.githubusercontent.com/896472/83122210-34088400-a0cb-11ea-92a7-0066df5f5e1b.png)

We are finding duplicate selectors somewhere in a dropdown menu, and I'm concerned that it will lead to unpredictable results in our testing.  Someone should look into this and provide further specificity.

**Comment by lomamech** [comment]
Could you detail the problem, I did not understand this Issue

**Comment by jniles** [comment]
In the IPR Tax Configuration management end to end tests, we are using some sort of code like
```js
await $('[uib-dropdown-toggle]').click();
```
but here is more than one `[uib-dropdown-toggle]` on the page.  This is what the warning is in the console.

Instead, we need to tell it which one to click.  For example, it we want to click the dropdown in a modal, we should do:
```js
await $('[uib-modal]').$('[uib-dropdown-toggle]').click();
```
to tell it to click the one in the modal.

I'm not sure exactly what the issue is in those tests - someone should take a look and figure out why it is locating more than one dropdown.

**Comment by lomamech** [comment]
> In the IPR Tax Configuration management end to end tests, we are using some sort of code like
> 
> ```js
> await $('[uib-dropdown-toggle]').click();
> ```
> 
> but here is more than one `[uib-dropdown-toggle]` on the page. This is what the warning is in the console.
> 
> Instead, we need to tell it which one to click. For example, it we want to click the dropdown in a modal, we should do:
> 
> ```js
> await $('[uib-modal]').$('[uib-dropdown-toggle]').click();
> ```
> 
> to tell it to click the one in the modal.
> 
> I'm not sure exactly what the issue is in those tests - someone should take a look and figure out why it is locating more than one dropdown.

Well understood
