### ISSUE TITLE
(Design) Simple voucher UI with panels for details and transaction

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#456]
This issue is about a proposal for redesign the simple voucher ui so that it appear like complex voucher for reasons of harmony.

We propose two panels, one for details and one other for transaction.

![simple_voucher](https://cloud.githubusercontent.com/assets/5445251/15669021/0845d82a-26d3-11e6-8f10-d9f2beb531e6.png)

**Comment by mbayopanda** [comment]
@jniles @sfount @lomamech @DedrickEnc  what do you think about it ?

**Comment by jniles** [comment]
@mbayopanda, I don't think the user experience would be very good.  For me, looking down is easier than looking right.

Also, when we print a receipt, it will have the transaction details under the headers - in this format, the details are on the right.

Does that make sense?

**Comment by jniles** [comment]
Since there has been no more discussion on this topic, I'm closing this issue.
