### ISSUE TITLE
bhYesNo has a buggy behavior in enterprise settings

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4568]
![9YftTe9Hkg](https://user-images.githubusercontent.com/5445251/83546101-163a8500-a4f8-11ea-80bb-39da0e52ee03.gif)

Both options are selected at the same time

**Comment by jniles** [comment]
Can you give me some steps to reproduce?  On the last release, I cannot reproduce on either chrome or Firefox.

![2piWGcCa8E](https://user-images.githubusercontent.com/896472/83605333-a23bc380-a56f-11ea-9a66-73ff1aa17a76.gif)
_Chrome_


![kKYOitDjtC](https://user-images.githubusercontent.com/896472/83605342-a536b400-a56f-11ea-984e-4b127f3c7695.gif)
_FireFox 76_

**Comment by mbayopanda** [comment]
Oh... i am in the master branch, and i just rebuild the database with `yarn build:db`. Also, i have this Chrome version 

![image](https://user-images.githubusercontent.com/5445251/83615493-8a1f7080-a57e-11ea-8122-90dee56ad657.png)

**Comment by jniles** [comment]
I can reproduce on `master`.  This must have been introduced since the last release.

**Comment by lomamech** [comment]
@kwilu claim
