### ISSUE TITLE
is there any installation guide for Mac?

### ISSUE THREAD

**Issue by victorray84** [third-culture-software/bhima#4573]
I check your installation guide, it mentions only Ubuntu. is there any installation guide for Mac?

**Comment by jniles** [comment]
Hi @victorray84, no unfortunately, there is not.  None of the development team have Macs.  You probably could get it up and running in Parallels though.

**Comment by victorray84** [comment]
> Hi @victorray84, no unfortunately, there is not. None of the development team have Macs. You probably could get it up and running in Parallels though.

Ok, Thanks for replying.
