### ISSUE TITLE
Separate our Business Logic Layer (BLL) with our Data Access Layer (DAL)

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#46]
We are writting a new version of BHIMA (V2), some decision must be taken and now is the best moment to take them.
Our system is coupled we have angularjs and nodejs, angular is designed to force programmer using services, controllers and views but it is not the case for nodejs.
We should continue to amend our server side, for now our controllers at the server side contain some data operation which can be isolate to a low level (Data Access Layer).
We should find business rules only in our controller and data access operations in our kind of model or data object.
This proposal, if applied will reduce the number of code line in our `route.js` file and will make the server side code maintainable.
Exposing the controllers interfaces directly instead of exposing each http method one by one is advantageous.

**Comment by DedrickEnc** [comment]
Currently, we have **463 lines of code** in our routes.js and we don't finish to add routes inside yet!

**Comment by jniles** [comment]
It should be noted that we will be removing some routes.  For example, the following:

``` js
  app.get('/available_cost_center/', financeServices.availableCostCenters);                                                                                                                                                                                               
  app.get('/available_profit_center/', financeServices.availableProfitCenters);                                                                                                                                                                                           
  app.get('/cost/:id_project/:cc_id', financeServices.costCenterCost);                                                                                                                                                                                                    
  app.get('/profit/:id_project/:pc_id', financeServices.profitCenterCost);                                                                                                                                                                                                
  app.get('/costCenterAccount/:id_enterprise/:cost_center_id', financeServices.costCenterAccount);                                                                                                                                                                        
  app.get('/profitCenterAccount/:id_enterprise/:profit_center_id', financeServices.profitCenterAccount);                                                                                                                                                                  
  app.get('/removeFromCostCenter/:tab', financeServices.removeFromCostCenter);                                                                                                                                                                                            
  app.get('/removeFromProfitCenter/:tab', financeServices.removeFromProfitCenter);                                                                                                                                                                                        
  app.get('/auxiliairyCenterAccount/:id_enterprise/:auxiliairy_center_id', financeServices.auxCenterAccount);
```

However, I agree that we will have too many routes at the current rate.

**Comment by jniles** [comment]
@dedrickenc, specifically addressing the routes question (not BLL/DAL layers).

We could break up the server architecture along self-contained modules.  ExpressJS allows each module to configure a router which can then be exported and plugged into a main application router.  It looks like this:

``` js
// inside routes.js
var cashboxes = require('./controllers/cashboxes');

/**
* This binds the /cashboxes URL to the methods  defined inside
* the cashboxes controller.  All matching sub-routes will be handled by
* that controller.
*/
app.use('/cashboxes', cashboxes);


/**
* Inside the file server/controllers/cashboxes.js
*/

var express = require('express');
var router = express.Router();

router.get('/', function list(req, res, next) { /* .. code .. */});
router.get('/:uuid', function detail(req, res, next) { /* .. code .. */});
router.post('/', function create(req, res, next) { /* .. code .. */});
// etc ...

// expose the router to the main server
module.exports = router;
```

For documentation on this method, see [ExpressJS Routing](http://expressjs.com/en/guide/routing.html).

In my opinion, the advantages are:
1. Encourages modularity.
2. Cleaner routes.js file
3. Potential for module-level error handling

Disadvantages:
1. Cannot view the entire app functionality in one file (as you an now with routes.js).  We will need to  include very explicit comments in routes.js to describe what each controller does.
2. Where do shared modules (like journal.js) go? 
3. Full route definition not available in each module -- again, this can be fixed with comments.  But we must be explicit that `.get('/')` in the cashboxes controller will actually match a GET request to the route '/cashboxes'.

**Comment by DedrickEnc** [comment]
We must take a decision by tomorrow, it must not be a pending design decision

**Comment by DedrickEnc** [comment]
No opportunity to use it for now, I close it!
