### ISSUE TITLE
Initialize application constants at startup.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#460]
We have several places where we keep application constants.
1. `util`
   1. Contains `minimumDate`, `length*`, `minDOB`, etc.
2. `ModalService`
   1. Contains some modal configuration settings

I propose that we set up global application constants in an [angular.constant()](https://docs.angularjs.org/api/auto/service/$provide#constant) method at the beginning of the application loading that can then be called in from anywhere.

For example:

``` js
angular.constant('bhConstants', {
  dates : {
   minimum : new Date(),
   // etc ...
  },
  modals : {
   // setup modal options
  }
});
```

... then we can use them in controllers/services like this ...

``` js
module.controller('SomeController', function (bhConstants) {
  vm.constants = bhConstants;
});
```

@IMA-WorldHealth/local-contributors what do you think?

**Comment by mbayopanda** [comment]
it's LGTM

2016-06-01 4:27 GMT-07:00 Jonathan Niles notifications@github.com:

**Comment by sfount** [comment]
This should not be closed until it addresses https://github.com/IMA-WorldHealth/bhima-2.X/pull/462#discussion_r65861746

**Comment by jniles** [comment]
Close in #538.
