### ISSUE TITLE
Should stock lot numbers be editable?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4685]
We have received the following feedback from one of our users:

>  Si par omission on ne spécifie pas les différents lot en stock pour un item, est il possible de corriger?

What I believe is happening is that the lot information was incorrect when they registered the data, and now they wish to correct it.  Is there a way to do this safely that we could implement in BHIMA?

**Comment by mbayopanda** [comment]
@jniles actually the stock lot number is editable

![image](https://user-images.githubusercontent.com/5445251/91048083-07550180-e613-11ea-9c38-f4685ec5c558.png)

**Comment by jniles** [comment]
Does this change the `lot_uuid`?  I think we might need a way to merge/separate lots.

**Comment by mbayopanda** [comment]
No, it doesn't change the `lot_uuid`

**Comment by jniles** [comment]
Having used this in production in both HEV and IMCK, this is a necessary tool.  Closing this issue.
