### ISSUE TITLE
Filter Articles in Stock by "Expired"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4687]
We don't have an option to filter the articles in stock by the "expired" status.  This status is for articles that have an expiration date in the past _and_ have quantity in still in stock.  Here is the current list of statuses that we can filter the registry on.

![image](https://user-images.githubusercontent.com/896472/86774776-c0a14d00-c04e-11ea-826e-d35c1b641079.png)

**Comment by jniles** [comment]
@mbayopanda am I missing something?  Where can we find a list of currently expired lots in BHIMA that still have stock in them?

**Comment by mbayopanda** [comment]
Actually we can have expired lots and inventories from : 
- The "Article en stock" registry
![nBkwGFoVCW](https://user-images.githubusercontent.com/5445251/87020212-72658880-c1cb-11ea-91bd-188d2bf7fb06.gif)

- The "Lots en stock" registry 
![TtcLeJTrOu](https://user-images.githubusercontent.com/5445251/87020461-c8d2c700-c1cb-11ea-9e3b-ebf382c819bc.gif)

- The "[Stock] Articles en stock" report
![3bFUqZ4VGs](https://user-images.githubusercontent.com/5445251/87020683-19e2bb00-c1cc-11ea-9663-19f2d9b3d2bf.gif)

**Comment by jniles** [comment]
@mbayopanda, this is very useful!  It looks like you are pointing out the quantity in stock that is 0 (rupture de stock), not the medications that are expired.

We discussed offline that we might not actually have this functionality.  It's really important that we build it.  I'll make this issue into that design.

**Comment by mbayopanda** [comment]
Actually we don't have a report which shows clearly expired lots

**Comment by jniles** [comment]
@kwilu claim
