### ISSUE TITLE
Stock from invoice report has a bug with 404

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4688]
I got this from http://localhost:8080/#!/reports/invoicedReceivedStock

![image](https://user-images.githubusercontent.com/5445251/86807726-07546e80-c072-11ea-9950-ceba53e8738b.png)

And then : 

![image](https://user-images.githubusercontent.com/5445251/86807775-11766d00-c072-11ea-9ca0-d7fb70375f03.png)

Maybe this error is with most of our report

**Comment by jniles** [comment]
@mbayopanda can you check if this is still a problem and in how many production sites?  If it is still a problem, can you propose a fix?

**Comment by jeremielodi** [comment]
There is no bug on IMCK server, was this issue fixed?

**Comment by mbayopanda** [comment]
@jniles Vanga and IMCK don't have this issue, and the local project also is clean

**Comment by mbayopanda** [comment]
This issue no longer exist
