### ISSUE TITLE
Break Even Report needs loading indicator

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4693]
The breakeven report should use the `bhLoadingButton` and disable itself when you click it.  I accidentally clicked it multiple times since it took so long to load.

See below:
![wToTA30Xkh](https://user-images.githubusercontent.com/896472/86903693-9bbce080-c107-11ea-9d03-2c6d69a31f2a.gif)

**Comment by lomamech** [comment]
@kwilu claim

**Comment by lomamech** [comment]
I will extend this issue even for the free center report
