### ISSUE TITLE
Implement Patient Registration PDF report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#470]
In 1.X, we have a comprehensive patient report, that shows patient registrations by time period.  This report is rendered in HTML, and may crash the browser if the data to be rendered is too large.  To avoid this, I propose that we implement a PDF report in 2.X that is rendered on the server.

**Implementation Details**
A print button should be available at the top right of the navigation on the Patient Registry (`/patients`) page.  This button should print whatever is currently matching in the grid.  A modal should pop up with the embedded PDF, allowing the user to download it, open it in a new window, or cancel.

**Comment by sfount** [comment]
This will be the first 'report' that we attempt in 2.X - a lot of the technical pieces exist for receipt reprots but this will be a great additional data point for how we create documents. 

It could also start a discussion about how reports/ documents are presented to users; through a folder in the tree, report modules for each category, direct links from pages etc.

**Comment by jniles** [comment]
I'll take this.
