### ISSUE TITLE
Sort inventory group select in alphabetical order

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4704]
The inventory group select in the inventory creation form isn't sorted in alphabetical order.  See below:

![image](https://user-images.githubusercontent.com/896472/87035708-a0ee5e00-c1e1-11ea-8d46-09f211e54978.png)

For usability, let's make sure these names are sorted in alphabetical order.

**Comment by jniles** [comment]
@jmcameron could you look into this one next?

The code that needs changing is in the `client/src/inventory/list/modals/actions.*` files.  It should be pretty straightforward.  You'll want to use the `orderBy` angular filter.

**Comment by jmcameron** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @jmcameron!

You have attempted to claim an issue without the labels "". It seems like you are new to BHIMA, so we suggest working on an issue with the [help wanted](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22) or [good first issue](https://github.com/IMA-WorldHealth/bhima/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22) label first. We also recommend reading our [guide for new contributors](https://zulip.readthedocs.io/en/latest/overview/contributing.html) before getting started.

To claim this issue anyway, comment on this issue again with the command `@kwilu claim --force`.

**Comment by jmcameron** [comment]
@kwilu claim --force

**Comment by kwilu** [comment]
**ERROR:** `newContributors.permission` wasn't configured.

**Comment by jmcameron** [comment]
Thanks. BTW, that did not fix the dragging issue in the projects Kanban.

**Comment by jniles** [comment]
@jmcameron try again?

**Comment by jmcameron** [comment]
Cool! Now it works!  Thanks.
