### ISSUE TITLE
Implemente invoice registry

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#471]
BHIMA should allow user to retrieve invoices (new or old) and manage them in a centralized way.
So, a module to manage all invoices is important, this module should also provide some functionalities to discard an invoice and to signal a discarded invoice.
This will be a good occasion to walk through the sale table and remove unusefull attribute such as discount (?) ...
The module should give the possibility of advanced research

Any thought?

**Comment by sfount** [comment]
@DedrickEnc This looks good to me! 

I especially like the idea of reviewing what is required in the sale table, I would add to this that sales are now called 'Patient Invoices' so it might be a good time to update the schema to match the server APIs and modules, naming the table something like `invoices`. 

Initially it would be good to simply be able to review patient invoices, maybe with the ability to order/ filter invoices. Following that I agree with your analysis that discarding (credit note) and advanced search would be useful.

**Comment by DedrickEnc** [comment]
That is also my idea, you are right.

**Comment by jniles** [comment]
@sfount, @DedrickEnc, if you are brave enough, you can change the name of the table.  It will be a lot of work though (`sale_subsidy`, `sale_billing_services`, etc, will need to be updated).  It might be better for a separate issue/refactor though.

What's the URL of this module?

**Comment by sfount** [comment]
@jniles you are correct, this would also require updating all throughout server posting procedures etc. I agree that this could be tackled as a seperate issue - this one can focus on the patient invoice records page.

**Comment by DedrickEnc** [comment]
Trivially that should be `invoices/`, `patient_invoices/` or `patient/invoices/` but if there is a better idea this is  a good time to share it.
For now, I am trying to update the schema.

**Comment by sfount** [comment]
`/invoices` sounds fine to me - this could follow a similar design to patients.

`/patients` - patients registry
`/patients/:id` - patient record
etc.

For your information the Patient Invoice page is currently at `/invoices/patient`, this was a temporary path made in isolation though! A good design could easily replace it.

**Comment by jniles** [comment]
This was partially addressed in #478.
