### ISSUE TITLE
Add a "automatic confirmation of purchase orders" feature to Stock Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4725]
Purchase Orders in BHIMA need to be confirmed after creation before they can be put in Stock.  This was developed at IMCK to separate concerns between the accountant and the stock manager.

I propose we add an enterprise setting to automatically confirm the purchase orders.  This makes sense when you don't need the separation between the accountant and stock manager (like the PEPKit project or Ebola drug tracking project).  It's a bit confusing since it isn't immediately obvious that you need to confirm the purchase orders before importing them.

This flag would simply set the purchase status to "confirmed" upon creating of a new purchase order.

**Comment by jmcameron** [comment]
@kwilu claim

**Comment by kwilu** [comment]
**ERROR:** You have already claimed this issue.
