### ISSUE TITLE
In the Enterprise settings, the CMM acronym needs explanation

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4732]
Currently the Enterprise option "Enable CMM calculation based on days of consumption" and its explanation do not explain what CMM is or that it relates to stock.   At a minimum, the term "stock" should be  in there somewhere and the acronym expanded.  The translations for this item should be updated.

Also, change the data type for enable_daily_consumption column in the SQL schemas from SMALLINT(5) to TINYINT(1) using MODIFY COLUMN in migrations.sql.

**Comment by jniles** [comment]
@jmcameron do you feel equipped enough to handle this issue, or would you rather someone with more experience in stock tackle it?
