### ISSUE TITLE
Allow only stock exit for expired lots to loss

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4749]
This issue is about to forbid all distribution of expired lots to patients, services, and depots.

Allow only expired lots to be distributed as a loss.

**Comment by jniles** [comment]
@jmcameron would you consider looking into this?

**Comment by jmcameron** [comment]
Do you think this should be fixed policy, or should we have a Enterprise-level setting that will enforce this?

**Comment by jmcameron** [comment]
> Do you think this should be fixed policy, or should we have a Enterprise-level setting that will enforce this?
From WhatsApp thread:
**Jonathan Niles:** We must apply the rule for everyone.
**Jonathan Cameron:** I wondered if there were some situations where expired medications need to be sent back to some depot for proper handling, etc.
**Jonathan Niles:** Good question - I can't imagine such a scenario.  I think that the point is to "remove" them from stock so they are 1) unavailable to consume and 2) recorded as an expense.   If a scenario occurs where you get a new expiration date, they can always be reintroduced as a new lot.

**Comment by jniles** [comment]
Thanks @jmcameron !

To expand on the above, I think from an institutional perspective, an expired medication is unusable, so may as well remove it from tracking altogether.  I cannot imagine an instance where you would want to track the expired drugs from place to place, and we should definitely not encourage users to dispense expired drugs to patients or service wards.

**Comment by jmcameron** [comment]
What happens if the drugs are only expired by a few days?  High likelihood they are still viable, etc.  Why throw them away?

**Comment by jniles** [comment]
I think legally it's untenable.  I can double check with a pharmacist, but no hospital I've been has ever done such a thing.

**Comment by jmcameron** [comment]
Got the lot filtering working to prevent expired lots to be shown to the user in the Lots drop-down menu once a item has been selected.  

Another question:

- Since we can bring in items via Invoices (Patient) or Requisitions (Service/Depot), how should we handle the items that come in that way that may be expired?

**Comment by jniles** [comment]
In both cases, the items that are selected are actually already in the depot, they are not being "brought in" at all.  It's just presetting the grid so you don't have to.
