### ISSUE TITLE
Display a meaningful message for lots which doesn't expire

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4752]
This issue is about to remove the false expiration date for inventories which doesn't expire 

![image](https://user-images.githubusercontent.com/5445251/88121373-73c88500-cbbd-11ea-9ba5-10a67c910b3f.png)

Information to fix for inventories which don't expire in the lot registry : 
- Expiration
- MSD
- Durée de vie
- Durée par lot
- Risque

**Comment by jniles** [comment]
@kwilu claim
