### ISSUE TITLE
Update migration script to drop all function, triggers, etc

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4766]
The current migration script used the production env but does not use the MYSQL user/password, so additions (such as dropping exiting triggers, etc) that require a mysql call fail and the absence of these drops cause failures when the migration script is used on MySQL 8.0.    Also, functions are not getting dropped now but should be.

Goal: Update the script so that all items that are replaced get DROPped first.

**Comment by jniles** [comment]
@jmcameron thanks for tackling this.  It sounds like a really good and important issue.

I'd be curious to know what it is that is causing the failure in drops when you identify it.

**Comment by jmcameron** [comment]
@jniles Are people using the migration script with 'sudo'?  In the script, the mysql calls do not specify a username/pwd.  My idea is to use the the user/passwd in the .env.production file for the mysql queries (so they can be done without sudo).  AND add the mysql call to add drops for all functions.
