### ISSUE TITLE
Improvement of Analysis of auxiliary cashboxes

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#4767]
It is necessary to define a new column on Analysis of auxiliary cashboxes report make it possible to assess the difference between the fund entries at the levels of the auxiliary funds and their transfers to Principal Cashbox.

**Comment by lomamech** [comment]
@kwilu claim

**Comment by jniles** [comment]
@lomamech pouvez-vous revoir cet issue et nous dire si c'est toujours necessaire?
