### ISSUE TITLE
Stock Lots listing is nearly unmanagable

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4775]
The Stock Lost listing page has grown uncomfortably wide:  It has 19 fields!   Unless you have a really wide monitor, it is not easy to use.   What we can do to reduce the number of columns and make it more usable?  Here are some starting ideas:

- Since we are grouping my by Depot we really need column 1 repeated on each row?
- Could the info in Lifetime and lifetime by lot be combined, eg: 15 / 0 months
- All of these items need to be displayed all the time?  Perhaps we can add an information popup that will either show up via the "Actions" menu on the end of each row?  or have an Info column that shows the info when hovered over?
- Is there any way to collapse columns selectively?   Have some start up hidden/collapsed but able to be expanded as desired.  That way perhaps some columns could be collapsed and others expanded as needed, which still maintaining a reasonable number of columns?

**Comment by jniles** [comment]
Actually, all our registries have a way to toggle the visible columns via the actions menu.  Go to Actions > Columns.  You are right that this is a lot of columns to show by default.

> Since we are grouping my by Depot we really need column 1 repeated on each row?

Unfortunately, our grid library doesn't let us do that.  If you group by it, it needs to exist, be visible, and be on the far left of the grid.

> Could the info in Lifetime and lifetime by lot be combined, eg: 15 / 0 months

I'm open to combing the lifetime and lifetime by lot.  Although I'm actually not sure why we are showing the regular lifetime here.  That seems like it should go in the Articles in Stock registry.   @mbayopanda do you have any thoughts?

**Comment by jniles** [comment]
@jmcameron I think we cleaned this up in the `refactor` branch, right?  Since this is your issue, I don't want to close it without your view.  If you think this has been addressed, please close it.  If not, please highlight the things that need to be done so we can get it fixed.

**Comment by jmcameron** [comment]
I think has been addressed adequately.
