### ISSUE TITLE
Stock Requisition popup cannot cancel

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4776]
When you first launch the Stock Requisition page, it pops up a dialog forcing the selection of a Depot.  That part is fine.  
But it completely disables the [Cancel] button.   I'm sure this is to prevent  proceeding on the page without selecting a Depot.  

What if someone clicks on the [Requisition] button by accident and wants to back out?  The would normally click on the [Cancel] button.  But that is disabled.   

A secondary issue:  If the user only has access to one Depot, that depot will show in the drop-down menu of depots to select and it may be selected (or not).   Again, the [Cancel] button is disabled.  The behavior is a bit puzzling because it is not obvious that it is a Drop-down menu (you cannot select anything else).  Normally a drop-down menu has several options and it obvious what to do.

If we allowed a user to proceed to the page without selecting depot, perhaps the buttons on the top (eg, [New Requisition], etc) could force the pop-up to chose a depot if invoked and no depot is selected.

Also, If the user only has access to one depot, perhaps we should use that automatically without prompting for it?

**Comment by jniles** [comment]
I'm pretty sure this pattern exists for all stock modules - stock exit, stock entry, stock adjustments.

One potential fix would be that we can make the `[cancel]` button map to [`History.back()`](https://developer.mozilla.org/en-US/docs/Web/API/History/back), like we do on the settings page.  That way, we wouldn't have to know where the user was coming from, we could just automatically send them back there on cancel.  This assumes that the depot select is a new history state.  I'll have to check to see if that is indeed the case.

I'll have to investigate the second issue separately.
