### ISSUE TITLE
Merge Finance and Accounting concepts 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#479]
Currently our tree has two categories for `Finance` and `Accounting`. I suggest that both of these are incorperated into `Finance`. The users and permissions set up will still allow us to give accountants access to accounting modules and other employees access to the input modules (invoices etc.). 

This would allow us to standardise the route structure as follows:

``` js
// A list of all of the patients in the hospital (Patient Registry)
'hospital/patients'

// A list of all of accounts for the institution (Account Management) 
'finance/accounts'
```

@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
No problem with this. We have already combined them on the server, as far as I am aware.  I don't think a user would be too confused between `finance/accounts` and `accounting/accounts`, for example.
