### ISSUE TITLE
Name all foreign key constraints

### ISSUE THREAD

**Issue by jeremielodi** [third-culture-software/bhima#4793]
As we have a lot of bhima instance running, having the same database structure facilitate the migration.
Imagine we want to drop a foreign key  from this table bellow 

```sql
CREATE TABLE `table_name` (
  `uuid` BINARY(16),
  `patient_uuid` BINARY(16),
  FOREIGN KEY (`patient_uuid`) REFERENCES `parent` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;

```
In this case you will have to run 
```sql
  SHOW CREATE TABLE `table_name`
```
In order to know the constraint name, but you can see here how it is easy when the constraint name is defined

```sql
CREATE TABLE `table_name` (
  `uuid` BINARY(16),
  `patient_uuid` BINARY(16),
  CONSTRAINT `table_name__parent` FOREIGN KEY (`patient_uuid`) REFERENCES `parent` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;

```
I can drop the FK by running 
```sql
 ALTER TABLE table_name DROP FOREING KEY table_name__parent

```

**Comment by jniles** [comment]
I really like this idea.  If it is practical (.e.g if it takes a reasonable amount of time to run on the production database), I think it will be super helpful into the future.  Great innovation @jeremielodi!
