### ISSUE TITLE
Log in vs Connection button on initial login page

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4806]
On the initial log in form, the button to log in is labeled "Connexion" (fr) or "Connection" (en). 
Shouldn't these be "Log in" (en) and "Connecter"/"Ouvrir la session" in French?

**Comment by mbayopanda** [comment]
@jmcameron you're right `"Log in" (en) and "Connecter"/"Ouvrir la session" in French` is much better and recommended, but we have used `"Connexion" (fr) or "Connection" (en)` by default.

I agree with you, we can enhance this label with your proposal
