### ISSUE TITLE
Missing table in some databases

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4807]
The Bhima_test database has a table: 'rubric_payroll_item'
However, the IMCK (and possibly Karawa) databases do not have this table (as of 2020-08-10).

It seems probable that this is an error of some type:  If the systems at IMCK (and Karawa?) are running fine without this table, then the table is unnecessary.   Is it actually being used in Bhima_test?

**Comment by jniles** [comment]
For context, this table (and others) were added in https://github.com/IMA-WorldHealth/bhima/pull/3749.  The goal was to create a payroll system based on indices for Vanga.  It may help in figuring out why these were missed.

**Comment by jniles** [comment]
I'm going to close this issue as it relates to production and we clearly need to have a deployment plan for upgrading these old sites.  I'm not sure any BHIMA code changes need to be made.

**Comment by jmcameron** [comment]
Ok
