### ISSUE TITLE
Stock Movements Unit has disappeared in the latest upgrade at both IMCK and HEV

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4813]
We are missing the stock movements registry.  It might be worth making a hotfix patch for it.

**Comment by mbayopanda** [comment]
If it is not assigned I can work on that

**Comment by jniles** [comment]
Go for it!

**Comment by jniles** [comment]
I assume this bug affects all sites - the HEV and IMCK are just the ones we checked.
