### ISSUE TITLE
The build:db method builds a database that has title accounts with a balance

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4846]
I ran `yarn build:db` and give a voucher created with the account "601 - ACHATS DE MARCHANDISES".   This is a title account.  We must update this so our test data is consistent with what is actually possible in BHIMA.  It should not be possible for a title account to have a balance.

![image](https://user-images.githubusercontent.com/896472/91039512-973f7f00-e604-11ea-9d51-d062abb2aeec.png)

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/91423056-edecc900-e84f-11ea-992f-8699c757e409.png)
I just detected several title accounts used in the test database

**Comment by jniles** [comment]
@lomamech thanks for taking a look at this.  There is an open pull request about this: https://github.com/IMA-WorldHealth/bhima/pull/4847.  Can you give it a review?

**Comment by lomamech** [comment]
> @lomamech thanks for taking a look at this. There is an open pull request about this: #4847. Can you give it a review?

Thank you I'll do it, but you forgot to assign that you were working on this

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
Note, there also isn't a warning for using title accounts: 
![image](https://user-images.githubusercontent.com/896472/91719791-d7b37580-eb8d-11ea-8f8b-c0d4e99db9d3.png)
