### ISSUE TITLE
Stock Requisition Features To Add

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4849]
This issue is about some feature we can add in the stock requisition registry : 

- Forbid the deletion of stock requisition if the requisition has been implied in any process
- Add a link to depot movement receipt in case of depot movement from requisition
- Add a link to stock movement registry in case of depot movement from requisition
- Add more status:
    - Canceled
    - Movement initialized: in case a stock exit to a depot from requisition is made
    - Movement fully completed: in case all inventories of the requisition have been received by the destination
    - Movement partially completed: in case just some inventories not all of the requisition have been received by the destination

**Comment by jmcameron** [comment]
Do we need a way to indicate that the stock requisition is finalized, even if the delivery was only partially completed?   I presume in some cases, you just have to accept losses during delivery, etc, and declare it it finished anyway (from the point of view of the sending depot).

**Comment by jniles** [comment]
Note: we don't have a way to filter on the requisition's status:

![image](https://user-images.githubusercontent.com/896472/91719606-8acf9f00-eb8d-11ea-84da-621ec64cb796.png)

**Comment by lomamech** [comment]
@mbayopanda A question regarding the statuses of a requisition, using this module I noticed that there are several statuses, but I noticed that the status of a requisition is either **in_progress** or **done**

**Comment by lomamech** [comment]
@mbayopanda @jniles @jmcameron  @jeremielodi  I also think that we will also have to add the date of the creation of the requisition this will allow us to backdated the creation of the requisitions

**Comment by jniles** [comment]
@lomamech no problem.
