### ISSUE TITLE
Add alert about lot expiration in the "Article en stock" registry

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4854]
This issue is about to add : 
- A column with alert icon about lot expiration
- A click on the icon show a popup with more details about lots expirations of the inventory

The popup can contain : 
- Lots with their duration until the expiration (and quantity remaining)

**Comment by jniles** [comment]
Related: https://github.com/IMA-WorldHealth/bhima/pull/4839 and https://github.com/IMA-WorldHealth/bhima/issues/4845
