### ISSUE TITLE
Dashboard for Stock management

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#4856]
The problem is to be able to produce a dashboard of stocks, to allow alerts in real time, 
- on products with risk of peremptions, 
- products at risk of out of stock, expired products, 
- exhausted stocks as well as the deadlines for rupture, 
- purchase orders but also pending requirements
- as well as over-stocked products

It should also make it possible to visualize the reports by deposits but also in the whole

**Comment by lomamech** [comment]
**Feasibility analysis of the dashboard design for Inventory Management**
_1. Expiration and risk of expiration_
Regarding the alerts concerning the risks of expiry, information is available on Lots in stock, it would suffice to apply a filter to obtain the results by deposits and to place them in the dashboard.
_2. Risk of out of stock_
After analysis, of the data, the products at risk of rupture are those:
- Those who have a quantity less than the safety stock, and with a quantity to order.
Take the following example
![image](https://user-images.githubusercontent.com/8035588/91464715-cbc16e00-e884-11ea-9521-a32ee6389473.png)

With this example, we see that all of these products are below their safety stocks, but I think we can categorize them by calculating the percentage of the quantity in stock compared to the value of the safety stock

Here is the small table that I propose to categorize the products below the security threshold by color
![image](https://user-images.githubusercontent.com/8035588/91464958-15aa5400-e885-11ea-9846-840159f10590.png)

_3. Pending purchase orders_
For purchase order statuses, there is no problem as the purchase order records provide all of its information.

**Comment by lomamech** [comment]
@mbayopanda , I would like to know if there is a small user guide on the management of requisitions

**Comment by jniles** [comment]
@lomamech I like this idea.  We could probably define this by using the [HSL color function](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#HSL_colors) in CSS to make it darker and darker in the same range.

The real question is  ... where does this go?  It is in an extra column on the Items in Stock dashboard?  Or in the "Risk" column?

**Comment by jmcameron** [comment]
Perhaps coloring the quantity field since the warning is about quantity, not expiration, etc?

**Comment by jmcameron** [comment]
> The real question is ... where does this go? It is in an extra column on the Items in Stock dashboard? Or in the "Risk" column?

J'en ai, mais avec la probabilité d'être seule, et la certitude du silence qui y règne, j'opte pour le bureau, pour aller vite

**Comment by jmcameron** [comment]
> The real question is ... where does this go? It is in an extra column on the Items in Stock dashboard? Or in the "Risk" column?

Perhaps color the 'Quantity' field since it is primarily about the quantity being low.
