### ISSUE TITLE
Add ability to set the "safety stock" per depot, rather than per medication

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4860]
Our safety stock is currently calculated based on a hard-coded variable:
https://github.com/IMA-WorldHealth/bhima/blob/1bf6400fd99f7997aca0f221635a6f218becb1c9/server/controllers/stock/core.js#L412-L416

However, to account for differences between the health centers (which need a single month of stock on hand) and the health zone offices (which need four), we'll want to set the minimum number of months of stock by depot.

**Comment by jmcameron** [comment]
Should we have a default value for this in the Enterprise settings as well?  When a new depot is created, this can be the default value which can be changed when the depot is created or edited later.

**Comment by jniles** [comment]
Yes, I agree, it would need to appear in both places.
