### ISSUE TITLE
Move "Include Exhausted Lots" to the "Default Filters" Category

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4862]
The current default for "Include Exhausted Lots" is "No".  We treat it like a default filter.   Let's move it to the default filters category.

![image](https://user-images.githubusercontent.com/896472/91439816-8e011d00-e865-11ea-9257-9b6fb8cc8126.png)

**Comment by jmcameron** [comment]
There is something odd about the "Show expired lots" option shown here.   In practice there are three options implied by this option:
   Cleared - Display all lots
   Yes - Display only expired lots
   No - Display all lots EXCEPT expired lots

When I read "Show expired lots", what I first think is:
   Yes - Display all lots including expired lots
   No - Display all lots EXCEPT expired lots
   Cleared - ???

I'm not sure how to fix this.  One idea is to change the option label and Yes/No labels to read:

- Limit display of expired lots  (was: Show expired lots)
   - Show only expired lots  (was: yes)
   - Do not show expired lots (was: no)

**Comment by jniles** [comment]
We've encountered something similar before and we basically ended up with a radio button that said

"Expired Lots" 
  - include only the expired lots
  - exclude all expired lots

Then the "cleared" state is basically "don't do any operations (excluding or including) based on expired lots.

**Comment by jniles** [comment]
@jmcameron would you be willing to look into this?
