### ISSUE TITLE
Fix Stock Lots expired warning block to display all expired lots

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4863]
The current implementation of the expired warning block is a bit odd.   If I have two lots of an inventory item that are expired and one that still has stock, the expired warning block does not catch that.  It only lists one expired lot.  However, when you click on "See all" you see both expired lots. 

Since this warning block is for Stock Exits, it seems like we should be warning about expired "Lots", not expired "products".   And for each inventory item, we can show a list of the expired lots (in the single "Lot" cell on the right) instead of the current 1.  Also the count of expired "Lots" should be computed based on the total number of lots expired in the whole warning block.

_Originally posted by @jmcameron in https://github.com/IMA-WorldHealth/bhima/pull/4857#issuecomment-681037824_

**Comment by jniles** [comment]
@jmcameron is this still relevant?

**Comment by jmcameron** [comment]
Just looked at this again.  I've decided that it does not make sense to do.  The current interface is okay.
