### ISSUE TITLE
(Proposal) Implement a xlsx renderer

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#488]
The 2.x ecosystem currently supports rendering reports as JSON, HTML, or PDF.  A highly useful feature for accounting would be an "export to Excel".  Javascript already has a pretty mature [xlsx writer/parser](https://github.com/SheetJS/js-xlsx) that we could leverage.

The behavior would be the same as all other reports/renderers.

@IMA-WorldHealth/local-contributors what do you think?

**Comment by jniles** [comment]
This should be similar to the [csv renderer](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/lib/renderers/csv.js) implemented in https://github.com/Vanga-Hospital/bhima-2.X/pull/89.

**Comment by jeremielodi** [comment]
fixed in #2106
