### ISSUE TITLE
Update to expiration alert in stock registry

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4886]
I suggest a small update to the recent stock registry expiration alert in PR https://github.com/IMA-WorldHealth/bhima/pull/4865.

When you enable the display of exhausted lots, the current implementation puts a check mark in the alert column of the exhausted item.  I suggest not including any icon in that field for exhausted stock.

![image](https://user-images.githubusercontent.com/62145/92183029-0cc7fe00-ee02-11ea-8abc-e0fdd362511a.png)

**Comment by jniles** [comment]
@jmcameron , how is this different from https://github.com/IMA-WorldHealth/bhima/issues/4943 which was closed in https://github.com/IMA-WorldHealth/bhima/pull/4951?  Is it a duplicate or was this substantially different?

**Comment by jmcameron** [comment]
It is a duplicate. I'll close this issue.

**Comment by jmcameron** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/4951
