### ISSUE TITLE
Do not show "view articles in stock" if articles haven't been received in stock

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4903]
In our purchase registry, we have an option to "view the article in stock".  However, this doesn't make any sense for those that haven't been received in stock.  See below:

![image](https://user-images.githubusercontent.com/896472/92727070-7b5b0d80-f366-11ea-83fa-8c4cec3867f5.png)

We should switch this to only show this option if the items have been received in stock.

**Comment by jniles** [comment]
@jmcameron would you mind looking into this one?

**Comment by jmcameron** [comment]
Ok.
