### ISSUE TITLE
Feature - Account Deletion 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#491]
After the Account management core (https://github.com/IMA-WorldHealth/bhima-2.X/issues/489) has landed we should consider the Account deletion case. This feature should be carefully thought through before being implemented on top of the original core. 

**Initial states that should be considered**
- Accounts that have been used anywhere in the posting jounral or general ledger 
- Accounts that have not been used
- Accounts that are referenced by any configuration entity (Debtor Groups) etc.

This design thread is to discuss the implications of Account deletion on the accounting/ technical implementation.

**Comment by jniles** [comment]
@sfount, can this be closed?  I think the final work was done already.
