### ISSUE TITLE
Improvement of the depot management interface

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#4922]
With the option of being able to manage multiple depots, the interfaces that are currently in BHIMA were easy to use in this context.

Since we should manage several hyarachized repositories by province (CDR), BCZs and structures, this issue proposes to add a hierarchy of repositories, by adding the parent attribute to repositories, this will facilitate the display and management especially in the hypothesis or we will have more than 50 deposits to create

This advantage will also be necessary in the interface for assigning deposits to users, with this way of doing things, it will now be very easy to assign to a user, all the deposits of a health zone, of a province. unlike the way we do it now

**Comment by jniles** [comment]
@lomamech this is an interesting proposal.

I'm wondering, though, if a hierarchy makes sense.  Do you think the ability to group depots might make more sense?  For example, you can imagine the following groups:
  1. HGRs
  2. CSs
  3. CDRs
  4. Depots in the Kasai
  5. Depots in Nord Ubangi
... etc ...

That would accomplish the same thing (allowing a user to have access to multiple depots) without enforcing a hierarchy.  What do you think?

**Comment by lomamech** [comment]
> @lomamech this is an interesting proposal.
> 
> I'm wondering, though, if a hierarchy makes sense. Do you think the ability to group depots might make more sense? For example, you can imagine the following groups:
> 
> 1. HGRs
> 2. CSs
> 3. CDRs
> 4. Depots in the Kasai
> 5. Depots in Nord Ubangi
>    ... etc ...
> 
> That would accomplish the same thing (allowing a user to have access to multiple depots) without enforcing a hierarchy. What do you think?

I referred to the pyramid of health
-- DPS Nord Ubangi
----- **Depots nu Karawa Zone de Santé**
---------- nu Karawa Hôpital Général de Référence
---------- nu Bobadi Mc Centre de Santé
---------- nu Bodambule Centre de Santé
-- DPS Kasai Centrale
----- **Depots Kr Tshikaji Zone de Santé**
---------- kr Tshikaji Hôpital Général de Référence
---------- kr Kalemba Mulumba Centre de Santé
---------- kr Njila Muimpe Poste de Santé
---------- kr Tudimuena Poste de Santé
---------- kr Kabasubabu Poste de Santé

**Comment by jniles** [comment]
I understand.  But this forces on particular model of how to structure depots.  Imagine that we want to give the pharamcy team access to all "structures SONU".  This tree wouldn't help.  A grouping might though.

**Comment by lomamech** [comment]
I think it will really facilitate the management of the deposits but also the administration

**Comment by jniles** [comment]
@mbayopanda @jeremielodi what do you think?

**Comment by lomamech** [comment]
> I understand. But this forces on particular model of how to structure depots. Imagine that we want to give the pharamcy team access to all "structures SONU". This tree wouldn't help. A grouping might though.

In this case, it will be necessary to hierarchize the deposits by categories (Sonu), or to maintain the pyramid of the Ministry of Health by adding tags to the deposits
