### ISSUE TITLE
Add permission for destination depots

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4928]
This issue is about :

1. Add in the user depots permissions: options for selecting authorized destination depots

2. Add enterprise setting to enable or not authorized destination depots feature: if enabled, the user must have the authorization to send products into the destination depot.

The goal is to only shows authorized depots in : 
- `bhDepotSelect `component
- `bhDepotSelectSearch `component

**Comment by jniles** [comment]
@mbayopanda what is your progress on this?

**Comment by mbayopanda** [comment]
I have already finished the enterprise settings and destination depot settings, but since @lomamech create #4944 I am waiting that its work be merge to combine both feature

**Comment by jniles** [comment]
I understand.  Thanks for the update!

**Comment by jniles** [comment]
@mbayopanda can this be closed now...?
