### ISSUE TITLE
Proposal of elements to exist in Invoices and Bills

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#493]
- The logo of the enteprise (Optional)
- Name of hospital
- Hospital address
- No phone
- Web Mail (Optional)
- Website (Optional)
- Title of the invoice
- The date
- Number of invoice
- Patient Name
- Patient Code
- Medical service
- Company name which supports the Patient
- Zone reserved for signatures

**Comment by jniles** [comment]
LGTM.  Thanks!

**Comment by jniles** [comment]
This issue was closed by #600.
