### ISSUE TITLE
(Proposal) Split up client side application routing

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#494]
The `app.js` client configuration (routing) currently has many responsabilites and is ~1100 lines long. 
I suggest that we split this up into smaller pieces; the simplest way I can think of doing this is delegating the routing responsability to each module (partial) individually. 

The proposal structure is as follows
(from a sketch on the whiteboard by @jniles)

``` js
// all services that are shared across many modules
'services/'
- 'Exchange.js'
- 'Receipts.js'
- 'Currencies.js'
'modules/'
- 'cash/'

// templates specific to a module
- - 'cash.html'

// controllers specific to a module
- - 'cash.js'

// set up module routes 
- - 'cash.routes.js' 

// services specific to routes 
- - 'cash.services.js' 
- - 'AnotherCashSpecificService.js'

// module code specific to a module
- - 'modals/'
- - - 'transfer.modal.js'
- - - 'transfer.modal.html'

- 'accounts/'
- - 'accounts.html'
- - 'account.js'
//...
```

This proposal would reduce `app.js` to focus on bhima application configuration.
@IMA-WorldHealth/local-contributors

**Comment by jniles** [comment]
LGTM.

I think renaming the `partials/` directory `modules/` makes a lot more sense from the 2.x standards we have been adopting.  It will encourage us to write more modular code.

**Comment by jniles** [comment]
I think this overlaps and supersedes #333.

**Comment by DedrickEnc** [comment]
I notice that @mbayopanda is working on fetching data from the database to fill the posting journal grid, so I will take this one and I can do the trial balance after Bruce's pull request.

**Comment by sfount** [comment]
@DedrickEnc it's worth noting that that I have experimented with how this could be implemented with my work on https://github.com/IMA-WorldHealth/bhima-2.X/issues/489. 

My test was to create an angular module `bhima.routes` and then import that into bhima. After that any configuration that is done on `bhima.routes` will be imported into the main app in `app.js`. 

An example of this configuration can be found on my branch here [accounts.route.js](https://github.com/sfount/bhima-2.X/blob/feature-accounts/client/src/partials/accounts/accounts.routes.js) with the required module definition here [define.js](https://github.com/sfount/bhima-2.X/blob/feature-accounts/client/src/js/define.js)

There should only be a conflict in the `define.js` file if you continue to do this re-factor - unless you decide to take it in another direction. Otherwise these changes will land with the account management core.

**Comment by DedrickEnc** [comment]
To avoid collision I dicided to wait for your pull request, so that I will understand very well the logic, I am working on testing location (unit test).
Thanks

**Comment by jniles** [comment]
I'm going to work a bit more on this and see if we can close this issue.  It should help us better reason about the repository from a build standpoint.

**Comment by jniles** [comment]
This was closed in https://github.com/IMA-WorldHealth/bhima-2.X/commit/7120ef3dbc42f3eff38e999477c3740b8ce168d5
