### ISSUE TITLE
Stock Lots warning column should not show check mark for exhausted lots

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#4943]
On the Stock > Items in Stock, the new warning column (to the left of the "Status" column) shows a warning icon for nearly exhausted items, etc.   However, if the item is completely exhausted (quantity=0), a check mark is shown with a tooltip that is somewhat confusing ("No lots with expiration risk").  See below.  The check mark should be suppressed for exhausted items or converted to a warning icon.  We already have the red "Stock Out" label pill in this case, so perhaps a warning icon is not necessary (see the second image below).

![image](https://user-images.githubusercontent.com/62145/93903562-a79f5400-fcad-11ea-9191-27fb211e36f4.png)

![image](https://user-images.githubusercontent.com/62145/93903946-1ed4e800-fcae-11ea-8aca-afb921e43884.png)

**Comment by jniles** [comment]
I agree.  This is a good proposition.

**Comment by jniles** [comment]
@kwilu claim
