### ISSUE TITLE
Clean up 2.x routes 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#495]
The `client/app.js` file currently contains many routes directly ported from 1.x that no longer point to updated modules. 

In order to make sure that all 2.x code and modules are correctly integrated we should remove all outdated references - these can be added back in as they are developed/ upgraded to 2.x. 

This refactor has two steps: 
- Remove all references to 1.x modules that are not yet upgraded to 2.x
- Remove all '/routes/ in state name - these should be completely seperate from the `url`
  (@todo add example of this)

This base `app.js` will allow us to split up application routing into individual modules creating a much more modular routing structure that should not conflict as much during development. (Proposed https://github.com/IMA-WorldHealth/bhima-2.X/issues/494)

**Comment by jniles** [comment]
As an initial step, I will be removing many of the client-side templates, services, and filters that are unused in 2.x.  This refactor will not touch `app.js`, but another developer can follow and remove the routes from `app.js` easily.

**Comment by jniles** [comment]
@lomamech, once #529 lands, could you begin working on this?  Thanks!
