### ISSUE TITLE
Remove "add tag" from the lots search modal

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4953]
Our search modals so far haven't had functionality to add/modify data.  I don't think it makes much sense to add that now.  We should remove the "add tag" option from the search modal for lots in stock.  See below:

![image](https://user-images.githubusercontent.com/896472/94255389-17b51080-ff20-11ea-8a3f-9270656f7aaa.png)

**Comment by jniles** [comment]
@jmcameron want to take a look at this?

**Comment by jmcameron** [comment]
> @jmcameron want to take a look at this?

Yes.
