### ISSUE TITLE
Do not refresh requisitions grid if the modal for new requisition has been canceled

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4974]
I noticed this while reviewing https://github.com/IMA-WorldHealth/bhima/pull/4921, but it didn't have to do with that PR.

When you click the "new requisition" button, a modal appears to create a new requisition.  If you click "cancel", the entire grid refreshes!  We don't need to redraw the grid - we just need to get rid of the modal.  This is likely because of an instruction in the $state reference to refresh the $state on transition via the cancel button.  We don't need this and it should be removed on cancel.  On submit, it makes sense, but on cancel, it does not.

Specifically, you'll be looking for something like this:
```js
         $state.go('requisition.list', null, { reload : true }); 
```
and you'll need to remove the `reload` property.

**Comment by jniles** [comment]
@jmcameron can you take a look into this?

**Comment by jmcameron** [comment]
Ok.
