### ISSUE TITLE
(Design) Print direct to PDF 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#498]
@jniles recently introduced the first report using the new 2.x structure in https://github.com/IMA-WorldHealth/bhima-2.X/pull/481. 

This report has a similar design to Receipts using the following process:
1. Click 'Print' button
2. Report PDF is downloaded and saved as blob
3. Open 'Reports' modal that references the blob through an `<embed>` tag
4. Click 'Print' button to bring up the chrome print dialog (this is done through `$window.frames.frameName.print();`)

I propose that for reports/ printing that are entirely driven by the pages content (in this case the patients registration report) we remove the middle step for the user: 
1. Click 'Print' button 
2. Report PDF is downloaded, saved as blob and embedded in a hidden `<iframe><embed></iframe>`
3. Print is automatically invoked with `$window.frames.frameName.print();` - user sees chrome print dialog with document for the first time

This proposal would require some clear guidelines about when to use which method, the two categories of proposed printing can split into two:

**Preview in Modal before invoking print**
- The document is used as a 'success state' - (invoice receipts, patient registration)
- Requires configuration/ confirmation
- Report can be exported to many types and requires a uniform interface (PDF/CSV/XLSX etc.)

**Directly print document**
- Report is just a document intended to be printed 
- Report is configuration is entirely driven from the page 
- No other action is available or gained (for example confirmation or success state) during the modal step

The advantages of this are:
- Improved user experience - only press print once 
- If the options are the same it should be simple to use the previous PDF without going to the server again

I have not designed the tehcnical implementation however it would probably be enapsulated in a component: 

``` html
<bh-print-report 
  url='/reports/invoices?renderer=pdf'
  options='options'>
</bh-print-report>
```

Options could include the URL simplifying the process.

In the future we have to consider how he handle reports/ documents that require configuration - in this case an additional Modal service may be required.

**Comment by jniles** [comment]
This was closed in #541.
