### ISSUE TITLE
Allow any depot to have children, not just warehouses

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5005]
The depot tree described in https://github.com/IMA-WorldHealth/bhima/issues/4922 and implemented in https://github.com/IMA-WorldHealth/bhima/pull/4944 is about creating a permissions hierarchy.  However, the implementation requires depots to be warehouses to have children.

I propose we remove this logic.  It is complicated and isn't related to permissions, which is why we originally wrote this code.  Furthermore, you can make a child, then edit the parent to not longer be a warehouse, so there are logic bugs.

Let's just remove this restriction.

**Comment by jniles** [comment]
@jmcameron want to tackle this one?

**Comment by jmcameron** [comment]
> @jmcameron want to tackle this one?

I'll take a look at it... maybe next week.
