### ISSUE TITLE
Problem unfolding all rows in Grid

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5006]
When you run the page:  Fee Center Management > Distribution Keys Managment,
it is supposed to start with all rows unfolded (un-collapsed).  However it does not always work -- although opening and closing the centers in the browser works.  This causes occasional problems for the end2end tests.

The problem seems to be in the  GridGrouping.js file:

  function unfoldAllGroups(api = this.gridApi) {
    $timeout(api.treeBase.expandAllRows, 0, false);
  }

https://github.com/IMA-WorldHealth/bhima/blob/9e85213a55075b2e64e4086b4f735303d26ed8a8/client/src/js/services/grid/GridGrouping.js#L115

It appears that this treeBase.expandAllRows function is not working correctly.

UPDATE 2020-11-11: This issue was resolved for the Distribution Keys issue in PR https://github.com/IMA-WorldHealth/bhima/pull/5093.  The problem was that the grid was not being started in a consistent state (in terms of folded/unfolded children).  After some debugging, we added a call 

    vm.grouping.unfoldAllGroups();

in the main loading function for the page.   This resolved the problem for Distribution Keys and is how some of the other pages with grids operate.   There may be a bug in the Grid 'expand' functionality that should be addressed eventually.

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
@kwilu abandon

**Comment by jniles** [comment]
@jmcameron we could probably change this text to reflect a general issue with GridGrouping rather than a specific issue on Distribution Keys.

**Comment by jmcameron** [comment]
Resolved in PR https://github.com/IMA-WorldHealth/bhima/pull/5093
