### ISSUE TITLE
Add a description to the depot table

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5025]
We should add a `TEXT` description to the depot table.  The main motivation is to stick DHIS2's `uid` in it for that structure.  This will make it easy for us to link the two in the bespoke implimentation of medicine tracking across the country.  It also makes sense to use a description for some depots in a hospital setting.

**Comment by jniles** [comment]
@jmcameron if you have some spare time, this would be a decent thing to work on.  It will give us some flexibility to link up data in the future.

**Comment by jmcameron** [comment]
It seems like we should add two items:  DHIS2's `uid` and a description field.   Using the same field for both seems like it could cause problems later.

**Comment by jniles** [comment]
@jmcameron sure - let's add both the `uid` and the `description` columns.  Neither should be required.
