### ISSUE TITLE
Remove the stock_consumption table and associated procedures

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5073]
We don't have many references to the stock consumption table, and we don't really use it.  It has been deprecated in favor of stock_movement_status.  Let's remove it and all associated procedures.

**Comment by jniles** [comment]
@mbayopanda can you verify that we actually don't need this before @jmcameron does too much work on it?

**Comment by jmcameron** [comment]
@jniles @mbayopanda :  I looked at this yesterday and two reports currently use the stock_consumption table:
       - Monthly consumption report
       - Consumption report graph report

So my guess is that we cannot remove this table yet.   Or we need to delete those reports too.

**Comment by jniles** [comment]
Thanks for following up!  It sounds like we have additional work to do before we can remove the `stock_consumption` tables.

I propose we tackle this one thing at a time:
  1. Remove the Monthly Consumption Report's dependency on the stock_consumption table.  It should either query the stock_movement table directly or use the stock_movement_status table.
  2. Remove the Consumption Graph Report's dependency on the stock_consumption table.  It should definitely use the stock_movement_status table.
  3. Remove the stock_consumption table.
