### ISSUE TITLE
Need color legend for Stock Lots page

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5099]
We need a color legend for the colors of the rows in the Stock Lots page. 
This includes:

- No color - Normal stock status
- Yellow - A risk (of stock out)
- Red - At risk of expiration
- Purple - Out of Stock
- Blue - Over maximum (perhaps?)

Note that we should also re-examine the color scheme here and the color of the stock status labels on the Items in Stock page to see if they can be made consistent.

**Comment by jniles** [comment]
This will probably play into @lomamech's PR on a stock dashboard.  Those alerts will need to be in the same colorscheme as whatever we decide here.

I'm for Blue - Over Maximum.

**Comment by jniles** [comment]
Also, this is somewhat related to https://github.com/IMA-WorldHealth/bhima/issues/4845
