### ISSUE TITLE
Write documentation on stock settings and their impact

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5114]
We've _largely_ got our stock settings sorted out.  We still have four algorithms, two of which probably shouldn't be used.  However, the interface is stable, we've removed the nonsensical options and will likely not add them back in.

Let's add detailed documentation on these options to https://docs.bhi.ma.  We need to create a page under "Stock Management" that details the different Stock Settings and what impact they will have on the application.

We also need to add a page describing how we calculate the Average Monthly Consumption.  This should include an overview of how the CMM is calculated by each algorithm, and what impact the AMC has on the min stock, security stock, and max stock.

**Comment by jniles** [comment]
@jmcameron would you be willing to tackle this?

**Comment by jmcameron** [comment]
@kwilu claim
