### ISSUE TITLE
Fix bug in the translation comparison utility

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5140]
Most of the time, the `utilities/translation/tfcomp.js` utility works fine.  However it does have a bug in one corner case:

There is a bug when you have a token which is single item in one language but is has a subtree under it in the other language.  In that case `tfcomp.js` does not detect a difference and the items in the sub-tree that are missing in one language are not reported.

**Comment by jniles** [comment]
@jmcameron, do you want to take a crack at this?
