### ISSUE TITLE
Make the posting journal load data from the database

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#518]
The current implementation of the posting journal fakes data to facilitate client-side development.  We have some working implementations of grouping and filtering worked out for the Patient Registry (#336) and the accounts management module (#489).

A good improvement would be to remove the locally created data and begin using the database to load Posting Journal transactions.  This would allow us to begin writing utilities for the trial balance and other necessary implementations.

**Objectives**
1. The Posting Journal should load data from the backed database.
2. During no data, loading or error states, there should be a notification to show those states using the `bhGridLoadingIndicator` component.

**Comment by jniles** [comment]
@mbayopanda, can you work on this while waiting for a review for #517?

**Comment by mbayopanda** [comment]
@jniles no problemo

**Comment by jniles** [comment]
This was closed in #524.
