### ISSUE TITLE
Allow depots to have 0 as min months security stock

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5193]
At IMCK, we discovered they have a few "passthrough" depots.  These are constantly in stock out.  Instead of warning of constant stock outs, let's make it clear that these depots are "passthrough" depots by simply saying 0 months of stock is their minimum.  Here is what happens when I try to do that:

![image](https://user-images.githubusercontent.com/896472/101001088-f6475500-355e-11eb-93fe-c4f74470691b.png)

**Comment by jniles** [comment]
@jmcameron @mbayopanda what are your thoughts on this idea?

**Comment by jmcameron** [comment]
We could also have an option for the Depot (like the Stock Entry or Stock Exit options) that allows min months to be zero (skips that check both in the edit form and in related calculations).  What impact does min months == 0 have on calculations, etc.  And if min months == 0, what does that imply about stock ordering decisions?

**Comment by jniles** [comment]
This issue is outdated.
