### ISSUE TITLE
Resolve negative stock quantites problems

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5205]
The problem is that we are encountering negative quantities in some production sites.  We have implemented a work-around for now that lets us operate with the negative values but it would be good to try

- Resolve exactly how they happen
- How negative stock quantities can be avoided in the future
- How current negative stock quantities can be repaired.

Note that negative stock quantities have the potential of causing errors in the computation of CMM, etc.

---

**Extracted from comments in PR https://github.com/IMA-WorldHealth/bhima/pull/5151**

**Jonathan Cameron:**
Before allowing negative quantities, I'd like to know why this is necessary. Specifically:
   - What does a negative quantity mean?
   - How does a negative quantity occur in the BHIMA software?
It seems to me that this could introduce more problems than it solves. It may be better to address why these negatives occur and fix it so they cannot happen!

**Jonathan Niles**
@jmcameron we were surprised by this as well. It's actually quite easy to get negative values and nearly unavoidable. Here is how:

   - Start with a balance of 100 pills at the beginning of this month.
   - Distribution 80 pills today.
   - Back date a distribution of 50 pills to be made yesterday.
   - We are now -30 in the hole today, even through you did have 80 pills today, and you did have 50 pills yesterday.

To avoid this, we would need to some check that says "would making this distribution put the database in an invalid/undefined state"? And then we would further need to figure out how to communicate that to the user such that they can avoid the issue.

Does that make sense? Maybe you can help us think of a way to work around this issue.... currently, it's escaping me.

**Jonathan Cameron**
I have two ideas about how to deal with this problem:

   - If an update will produce negative values, do not accept it; print out a very specific and detailed error message, something to the effect of: This update will produce a illegal negative quantity for stock item XYZ. Update the quantity in the form before submitting the form.
   - Automatically update negative values to zero when the form is submitted. Perhaps print an info/warning message that it got zeroed out.

We could also include a suggestion that it may be necessary to go back and correct previous updates. It seems obvious that there is an error in a previous update or this update.

It also seems like we need a utility to scan the database to see if there are any negative values and deal with them.

If it is not obvious, I still do like the idea of allowing negative quantities!!

**Jonathan Niles**
So, I worry about the calculation that backs this "if .. will produce negative values". This seems like a whole stock_movements table scan, recomputing balances all along. Unless we have a more efficient way to store balances, this could get really computationally intensive. I suppose we could cache the balances in a table that contains (lot_uuid, depot_uuid, current_balance) and decrement that on each exit, and if current_balance goes negative we know something is wrong?

**Jonathan Cameron**
Here are couple more thoughts on this:

   - In the stock exit form, prevent selecting a date before the current date. I realize this may not be practical, given delays in updating data, etc. But if we did this, fixes to historical quantities could be done via the Stock Adjustment page.
   - The Stock Adjustment page should accept the total at a certain date. I'm not sure if the Increase/Decrease options really make sense in typical operations (it seems like they have use the total to compute the increase/decrease anyway). If the Stock Adjustment form was used to correct historical data, it would be for one stock item at a time and it would not really matter if the computations are involved. Should anyone expect Stock Adjustment (an unusual operation to my mind) to be fast? Stock Exits on the other hand should be speedy since they will be done a lot.
   - Back to the concern about computations involved to see if a changes produces any negative values: We are only doing one stock item at a time in the stock exit. And the involved computations only need to be done if the date is back-dated -- and I think we can just put up a "Checking totals..." notification while the computations are being done.. If it is the current date, we can just make sure that we do not exit more than the existing quantity available (which I assume we already do).

**Jonathan Niles**
The problem with using Stock Adjustments is that it breaks the calculation for CMM since adjustments are not considered consumption. It has been kind of nice to have all CMM calculations flow from a single source (stock exists), so we can optimize that to death.

For (3), you are right - we only need to do the computation for back dating totals, and I think that is entirely reasonable. It seems like the best proposal yet. That way, we don't delay the distribution of stock to "regular" patients, in real time.

I think our CMM calculation also needs to be reviewed to make sure this logic is put in place. I believe we make an attempt, but am not sure the success of it.

**Comment by jniles** [comment]
So... I want to revisit this.  With https://github.com/IMA-WorldHealth/bhima/pull/5372, we basically force the re-computation of this "had 0 values" check just to record the CMM information.  So it should be really easy to institute the rule to block negatives quantities as long as we can figure out a suitable UI for it.

**Comment by jniles** [comment]
We are running into negative quantities in stock in the online database.  @lomamech has volunteered to look at this issue.

Here is how I propose we tackle this:
1. Implement a function that checks, after each stock movement, the stock_movement_status table for negative `sum_quantity`.  If the quantity is negative, throw an error.

The error message should be detailed as @jmcameron suggests:
> Print out a very specific and detailed error message, something to the effect of: This update will produce a illegal negative quantity for stock item XYZ. Update the quantity in the form before submitting the form.

I would add that the `date` to this error message.  Something like "On DD/MM/YYYY, stock XYZ will become negative with this movement."
