### ISSUE TITLE
Merge patients missing database updates

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5217]
The Merge Patient function does many of the correct database updates for merging patients but is missing a few items:

- stock_movement (entity_uuid)
- medical_sheet (patient_uuid)
- entity_group_entity (entity_uuid)
- voucher_item (entity_uuid)
- stock_assignment (entity_uuid)
- entity (uuid)  (row needs to be deleted)

NOTE: The schema.sql file should be updated to indicate what each occurance of 'entity_uuid' can refer to (for example, see 'entity_uuid' in the 'stock_movement' table).

**Comment by jniles** [comment]
This is a bug.  We'll need to update this function as soon as possible.
