### ISSUE TITLE
Add "Shipping and Handling Costs" to Purchase Order

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5225]
We need a way to add shipping and handling to the purchase order.  Shipping & Handling is important because it increases the value of the inventory (e.g. the cost of the inventory).  We can either calculate this as a percentage of the order value (i.e. 5% of total value) or a fixed cost (it costs $20 to deliver this inventory).

We'll need to add a section to the purchase order where the user can put in either a percentage or a fixed cost to the order.  This would not change the prices of the inventory items displayed, but would add a final section to the order "shipping and handling".  We would then divide this across the entire order.

This feature was requested by our friends at IMCK.

**Comment by jmcameron** [comment]
I propose adding a fixed cost + a percentage rate.  In most cases, it would be one or the other, but I can imagine that in some cases it might include both.

Also: I think these should be filled in with default values from the supplier.  So I plan to add default values for both in the supplier table, editor, etc.  In the Purchase Req, they could be edited by the user, if needed.

**Comment by jniles** [comment]
I am happy with this suggestion.

**Comment by jmcameron** [comment]
@jniles Here is what I'm planning to do for the adjusted unit price for PO items for stock entry with shipping and handling.  Hopefully the formulas a  straight-forward.    I've also attached the spreadsheet in case you want to look at the formulas, as implemented.  Note that the box on the left is the PO, the three boxes to its right are 3 separate partial deliveries.  
![image](https://user-images.githubusercontent.com/62145/123659989-291ea680-d82b-11eb-886a-a0533719a8c9.png)

I wanted to work this out carefully to make sure the computations work correctly with partial orders.  I presume that most orders will be full, but it definitely should work with partial orders too.

[po_costs.xlsx](https://github.com/IMA-WorldHealth/bhima/files/6727342/po_costs.xlsx)

**Comment by jmcameron** [comment]
> @jniles Here is what I'm planning to do for the adjusted unit price for PO items for stock entry with shipping and handling. 

In the entry by PO receipt report, I plan to add 2 columns:  one for S+H per item, and one for the adjusted unit price.   The extra columns will not be shown if the S+H costs are zero.
