### ISSUE TITLE
(component) bhInfo for showing popover information

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#525]
In several places we have begun using popovers to show additional information that would be hidden from the user normally.  Some examples of this are debtor groups, patient invoicing, and purchase orders.

**Observation**
Every single popover looks like this:

``` html
<span
   class="text-info fa fa-info-circle"
   uib-popover-template="'typePopover.tmpl.html'"
   popover-placement="right"
   popover-append-to-body="true"
   popover-trigger="mouseenter">
</span>
```

This is mostly repeated code.

**Proposal**
I propose we make a new component called `bhInfo` with the following signature:

``` html
<bh-info template="some/url" direction="right"></bh-info>
```

That would embed the icon and popover automatically into the page.  This would speed up development of modules by a bit and encourage use of popovers.

**Comment by mbayopanda** [comment]
:+1:
