### ISSUE TITLE
A few remarks on the developers installation documentation

### ISSUE THREAD

**Issue by diderikvw** [third-culture-software/bhima#5253]
Hi!
I just took the effort of doing a developer installation of Bhima on my laptop. The process and documentation is quite straightforward and a lot better than that of many others I have seen. A few minor remarks:

1. The developer installation documentation is a bit fragmented now between the main README, the home page of the Manual and the Installing Bhima page in the Manual. All the necessary documentation is there, but cross links are not complete and I needed to go through each to understand the 'complete picture' of what I needed to install and how to log in to look around.
2. I was a bit confused about installing MySQL locally or running MySQL in a Docker container. The documentation goes for local install, but then suddenly mentions Docker. It is not clear that this is OR OR and it does not explain the pros/cons of each option.
3. I ran into an "ERRORS.ER_NOT_SUPPORTED_AUTH_MODE" exception after opening the app locally for the first time. Only after solving this by myself, I found the "Troubleshooting" section at the end of the installation page, with the solution I needed to do (although the error is different). It would be convenient to be pointed towards this section earlier on.

But all in all I was able to install and run Bhima locally without too many bumps in the road.

**Comment by jniles** [comment]
@diderikvw, thank you for sharing your experience.  If you have suggestions for how to improve the documentation, please make a pull request.  The documentation is found under the `docs/` folder.
