### ISSUE TITLE
Make lot numbers unique per inventory item

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5257]
Our friends at HEV have requested that we make lot number unique per inventory item.  Currently, lot numbers do not need to be unique at all.

Basically, during lot creation, we would need to look up the lot_uuid based on the lot number, and substitute that lot number if it exists.  From a user interface perspective, it might be useful to have a way to auto-populate the expiration date if they have put in the lot already.

This functionality would ~~replace~~ render obsolete https://github.com/IMA-WorldHealth/bhima/issues/5165.  Instead of merging lots, just put the same lot number and they will be merged.

**Comment by jmcameron** [comment]
It seems like we would still need the merge lot functionality to deal with old lots.

**Comment by jniles** [comment]
You are right.  It might make sense to implement that first, actually.

**Comment by jmcameron** [comment]
Closed with https://github.com/IMA-WorldHealth/bhima/pull/5387
