### ISSUE TITLE
Add column to Stock Adjustments to show difference between the old stock and new stock

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5259]
Our friends in Vanga have requested that we add a column to the stock adjustments grid to automatically show the difference between the old stock and the new stock.  The module is https://hev.bhi.ma/#!/stock/inventory-adjustment.

Basically, we need to add an extra column here:

![image](https://user-images.githubusercontent.com/896472/103400589-f464b780-4b45-11eb-999f-92d80e4002f1.png)

That will show the difference between the old quantity and the quantity the user enters.

**Comment by Buzunda** [comment]
Hi, I would like to work on this. What would be the column name and where (as in order) should that column be added?

**Comment by jniles** [comment]
Hi @buzunda, great to have you interested!

The column name would be "difference"  and it would be to the right of the "new quantity" column.  The code you are looking for is here: https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/stock/inventory-adjustment/inventory-adjustment.js


Let me know if you have any further questions!

**Comment by Buzunda** [comment]
Ok. would you please assign issue this to me?

**Comment by jniles** [comment]
Done!
