### ISSUE TITLE
(report) Implement Cashflow Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#526]
Once #334 lands, we will be ready for an initial implementation of the cash flow report.  It is important to get as many reports into 2.x as early as possible so we can begin to ensure that 2.x is doing proper accounting according to the standards of reports designed in 1.x.

@mbayopanda has the most experience with the cashflow report, so I will leave it to him to design the cashflow report for 2.x.

**Comment by mbayopanda** [comment]
:+1: LGTM

**Comment by jniles** [comment]
Closed in #696.
