### ISSUE TITLE
Show sum of medicines distributed to different services in Sorties de Stocks

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5261]
In our report of Sorties de Stocks, it would be nice to see the quantity of stock consumed by service, grouped by stock item.  Currently, they are grouped by stock movement.  See below:

![image](https://user-images.githubusercontent.com/896472/103406720-ff2a4700-4b5b-11eb-8f34-b584dc4cf9a3.png)

In this image, the service "Dispensaire" has consumed 6000 capsuls of medicines.  I obtained this by counting.  We should provide a nicer user interface see this grouped by inventory item with sums.

**Comment by mbayopanda** [comment]
@jniles in the `Sorties de stocks` report we have two options for distribution to services: `Distributions aux services par produits` and `Distributions aux services par services`

![image](https://user-images.githubusercontent.com/5445251/103754515-bfa4a480-500c-11eb-8ee9-1d49f9010e8c.png)

And the other option by services 

![image](https://user-images.githubusercontent.com/5445251/103754654-ec58bc00-500c-11eb-8024-960ad8439498.png)

So the question is the `Distributions aux services par produits` does not answer the issue or do we need to implement another option?

**Comment by jniles** [comment]
No, this doesn't quite answer the issue.  We need a combination of the two: how much quinine did that maternity consume?  We don't have this information easily available.
