### ISSUE TITLE
Feature - Editing Accounts

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#528]
To be contributed following https://github.com/IMA-WorldHealth/bhima-2.X/issues/489

**Business logic that should be considered**
- The degree that an account can be altered once it has been used in a transaction should be managed by well defined rules
- An account that has had no transactions can be deleted and created again if a mistake is made during creation 
- The following attributes can be freely updated 
  - Account Label 
  - Account Parent 
- The client should only be able to send updated attributes for columns that can be changed, this does not stop hacking but will help mitigate mistakes 
- The server should have a white list of columns that can be changed, this will stop any post requests that are made by different clients 

The logic dictating how, when and what on an account be edited should be very well documented.

**Comment by jniles** [comment]
@sfount, can this be closed?

**Comment by jniles** [comment]
Closing this as implemented for Lukonga.
