### ISSUE TITLE
Transition BHIMA to using custom SMTP server with NodeMailer

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5290]
We currently request mailgun credentials that we do not use since MailGun quit their free tier.  Here they are in our `.env.sample` file:
https://github.com/IMA-WorldHealth/bhima/blob/d3583f63ecc01905d323354a0f9d8df8d4e505fe/.env.sample#L39-L43

Additionally, their node module is unmaintained.

Instead of tying ourselves to mailgun, let's move towards a more flexible solution by just using [nodemailer](https://www.npmjs.com/package/nodemailer) for delivery.  A good point of reference is our [Sunfish project](https://github.com/IMA-WorldHealth/sunfish) where I have already set it up:
https://github.com/IMA-WorldHealth/sunfish/blob/70965671491ea71dbd2884843f7c52eb1397284b/lib/mail.js#L47-L70

To complete this issue:
   1. Remove mailgun-js
   2. Add in nodemailer.
   3. Change `.env.sample` to use SMTP credentials as is found in Sunfish.
   4. Add in the nodemailer transport.
   
Eventually we could create a user interface to set the SMTP variables in a database, but it isn't necessary now.

**Comment by jmcameron** [comment]
Please send out an email with what this should look like in our .env files.
