### ISSUE TITLE
Add "View Consumption Schedule" modal to the "Articles in Stock" registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5292]
This feature depends on https://github.com/IMA-WorldHealth/bhima/pull/5226.

We currently have a "Consumption Schedule" where we assume that a depot will consume the lots in order of expiration date from soonest expiration date to the longest.  It would be nice to display this to the user in a graphical format - something like a [Gantt chart](https://www.wincalendar.com/Gantt-Chart).  This would allow the user to see which lot (on the Y axis) will be used during which time (on the X axis).  We could include cutoffs for their expiration dates so the user can see why they are unable to use all the quantity they think they have in stock, even if they have a large quantity in stock.

This would be linked from the Articles in Stock registry.

Here is a good example of how it should look:

https://cdpn.io/tutsplus/fullembedgrid/ZEzerNB?animations=run&type=embed

**Comment by jniles** [comment]
![image](https://user-images.githubusercontent.com/896472/121370062-4fd87400-c934-11eb-8320-9e29d41d3b50.png)

A better image to inspire what the form might look like.

**Comment by jmcameron** [comment]
@jniles Where is the "Consumption Schedule" you mentioned in the issue description?

**Comment by jniles** [comment]
The diagram looks kind of like a scheduling diagram of when you would consume different stock lots.  That's what I meant by the "consumption schedule".  Arguably, we could pick a better term.

**Comment by jmcameron** [comment]
> The diagram looks kind of like a scheduling diagram of when you would consume different stock lots. That's what I meant by the "consumption schedule". Arguably, we could pick a better term.

I thought you meant that there is something that computed the dates for the lots but was not graphical.  So I wanted to see that to use it as a starting point.
