### ISSUE TITLE
Improve multi-depot Stock Sheets

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5293]
After contacting the pharmacists, they approved the idea of being able to consult the stock card for several depots, but --I would like to suggest
- that we can activate the filter of depots to which the user has the right of access
- but also that the option of selection of deposits can be multichoice, for example we could know the quantity of a product of the deposits of a health zone

_Originally posted by @lomamech in https://github.com/IMA-WorldHealth/bhima/issues/5283#issuecomment-760131489_

---

Also, @jmcameron suggested:   I also think that we should show the table sorted by Depot then date (perhaps as an option). And Adding subtotals for each depot could also be useful.  We should think about how to do that cleanly (in terms of the UI).

We should probably discuss this further and decide what to implement and what the UI should look like.

**Comment by jniles** [comment]
This got closed at some point.
