### ISSUE TITLE
Proposal: usage of services and code layout

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#53]
In order to facilitate easily reading and reviewing the code (as well as nice JSDoc layouts), I propose we adopt the following guidelines for creating services within the application.
1. Always use services over factories, unless a specific use case is desired.
2. Always use the suffix 'Service' at the end of the service name.
3. Always alias `var service = this` at the top of the service function.
4. Always bind service methods at the top of the service function declaration.  The method definitions should be declared later.
5. Always write JSDoc documentation comments at the function definition.
6. Always return `service` at the bottom of the service function declaration.

Here is an example:

``` js
angular.module('bhima.services')           // note: we are creating a 'service' instead of a 'factory'
.service('SomeService', SomeService);  // note: this name contains the suffix Service

SomeService.$inject = [ '$http', 'util' /*, other injects ... */];

function SomeService($http, util) {
  var service = this;  // note: we are aliasing the `this` reference.

  /** @method detail */
  service.detail = detail;

  /** @method someOtherMethod */
  service.someOtherMethod = someOtherMethod;

  // .... 

  /**
  * @desc The detail methods returns detailed records from the database
  * @param {Number} id A numerical id found in the database
  * @example
  * SomeService.detail(id)
  * .then(function (record) {
  *   vm.record = record;
  * });
  * @returns {Object} promise A promise object with the response.body inside.
  */
  function detail(id) {
    return $http.get('/some/endpoint' + id)
       .then(util.unwrapHttpResponse);
  }

  /**
  * @desc blah, blah, blah
  *  .... more JSDoc documentation
  */
  function someOtherMethod() {
    // ... code ... 
  }

  return service;  // Note: returning service at the bottom of the service.
}
```

**Comment by DedrickEnc** [comment]
This is now a decision, we should all follow this pattern to create services.

**Comment by jniles** [comment]
This is now a wiki for future reference.  [link](https://github.com/IMA-WorldHealth/bhima-2.X/wiki/HOWTO-structure-client-services)

**Comment by jniles** [comment]
This is now a wiki for future reference.  [link](https://github.com/IMA-WorldHealth/bhima-2.X/wiki/HOWTO-structure-client-services).
