### ISSUE TITLE
Make Stock dashboard "no inventory found" messages positive

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5319]
Here is what the dashboard "no inventory found" message looks like when it doesn't find any expired products:

![image](https://user-images.githubusercontent.com/896472/106318247-ebaff000-626f-11eb-9973-bb96b35bf3a1.png)

This should be _much_ more positive!  We should make this into a green "success" message, potentially with a thumbs up icon.  This will give users a clear visual indicator that they are doing well.

**Comment by jmcameron** [comment]
Done in PR https://github.com/IMA-WorldHealth/bhima/pull/5335
