### ISSUE TITLE
The "articles in stock" report should say "include items with no stock" rather than "lots"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5322]
The Articles in Stock report shows items in stock, their CMM, and relevant information.  However, one of the options reads "Include Empty Lots" which is misleading, since the report does not show lots!  We should rename this option to "Include items not in stock".

![image](https://user-images.githubusercontent.com/896472/106321262-5105e000-6274-11eb-819d-30ee1d164129.png)

**Comment by jmcameron** [comment]
Done in PR https://github.com/IMA-WorldHealth/bhima/pull/5335
