### ISSUE TITLE
Add a new label/flag of "unused stock" to the stock registry

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5323]
We currently have multiple labels for different stock items including "out of stock", "low stock", etc.  As suggested in https://github.com/IMA-WorldHealth/bhima/issues/5321, let's make a label for "unused stock."  The definition of "unused stock" is any inventory item that has not had any consumption from a depot (CMM = 0).

Why make a new label?  These are actually interesting stock items - why would they never have a consumption event?  We could use this label to track down stock that either (1) should not be consumable or (2) users are not properly tracking.  It also gives us an easy way to account for the issue described in #5321 and remove unused stock from the "risk of expiration" calculation.

@jmcameron what do you think of this proposal?

**Comment by jmcameron** [comment]
It sounds like a good suggestion.  
Step 1: Add the Unused Stock (per this issue)
Step 2: Update CMM calculations (in another issue/PR)

**Comment by jniles** [comment]
@jmcameron would you mind looking into this on your list of TODOs?
