### ISSUE TITLE
Unify the names of "Articles in Stock" and "Items in Stock"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5326]
In the English translation, we use "articles in stock" and "items in stock" interchangeably to mean any kind of inventory item that has stock.  We should choose one as it is confusing to have both.  I prefer "Articles in Stock" since "items" is pretty generic.  However, my opinion could be swayed.

@jmcameron what do you think?  Which would you pick?

**Comment by jmcameron** [comment]
I do not have a strong opinion.  So I'm fine with going to 'Articles', since you prefer that.

**Comment by jmcameron** [comment]
Done in PR https://github.com/IMA-WorldHealth/bhima/pull/5335
