### ISSUE TITLE
Translation items missing in Edit Employee page

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5353]
Several translation items seem to be missing or hardcoded in the Edit Employee page (English and French).  See below:
![image](https://user-images.githubusercontent.com/62145/106770789-25c41d80-65f3-11eb-8f66-47f34ffee1e2.png)

**Comment by jniles** [comment]
This isn't actually a bug.  These are custom fields defined by users as different rubrics an employee should be paid for.  I believe they are defined in the `rubric_payroll` table:
https://github.com/IMA-WorldHealth/bhima/blob/66968a10581b569ebdd5bd0cb51c8108a8962a5e/test/data.sql#L3058-L3073

The idea is that an institution should be able to set custom payment options if they cover things like transport for workers, different pay levels for "responsibility", etc.

**Comment by jmcameron** [comment]
Ok. Just figured out where this can be edited in Bhima.   I'll close this issue, but note that we have an issue on translation for these types of things.   This reminds me of the issue of Patient Exit Types where we have made the decision to hardcode the labels in the translation files but reference them in a database table.
