### ISSUE TITLE
Remove 'quantity' and 'initial_quantity' from lot table

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5366]
The '**quantity**' field in the 'lot' table should be removed.  The quantity in a lot should be tracked by stock movements (see queries in server/controllers/stock/core.js).   Note that several queries in server/controllers/stock/lots.js will need to refactored since they include the 'quantity' field in the 'lot' table rather than computing it on the fly.   It is also likely, that some integration tests will need to be fixed for changes.

We also need to remove the '**initial_quantity**' and **unit_price** fields since the same issues apply to them.  

Other lot table columns that need to be reconsidered 

- delay?
- entry_date (applies to parts of a lot received, not the entire manufacturer's lot)
- is_assign?

- **description** (since it does not seem to be used anywhere.  Although it is possible that there more be information for this in the future if we connect into online manufacturer lot databases (eg, which plan produced it, etc).

**ALSO:** We may need to remove the 'quantity' from the lots registry page -- or make sure it is computed correctly.

**NOTE:** The stock entry page should still have entries for initial_quantity and entry_date.  These should be stored somewhere, but not in the 'lot' table.

**QUESTION:** How is initial_quantity related to the "Global Quantity" in the Stock Entry lot modal page? What is "Global Quantity" and where does it come from?  Is this the total number of items in the manufacturer's lot?  If so, how could possibly know that?  Perhaps it should be purged from the Stock Entry pages?

**Comment by jniles** [comment]
I agree.  It's confusing to have the quantity in the table as we never use it.

**Comment by jniles** [comment]
> QUESTION: How is initial_quantity related to the "Global Quantity" in the Stock Entry lot modal page? What is "Global Quantity" and where does it come from? Is this the total number of items in the manufacturer's lot? If so, how could possibly know that? Perhaps it should be purged from the Stock Entry pages?

@jmcameron piping in about this question.  Global Quantity is somewhat confusing, I agree.  It is a sanity check way to make sure users are entering in all the stock necessary in an entry.  It doesn't get stored anywhere.  It's just on that form to make sure you don't do something silly, like forget to put in stock.

For example, say that I give you 15,000 pills in a variety of lots and containers, but we both know for a fact I've given you that much.  We would put in 15,000 into the global quantity, then start putting in each lot.  At the end, we submit.  If we haven't actually gotten the sum of each lot's total to 15,000 the system will refuse.  This is annoying for small amounts but very useful in practice for large deliveries.   We can then go back and see where we made a mistake.

The UI could be improved, but that is the gist of it.

**Comment by jmcameron** [comment]
> At the end, we submit. If we haven't actually gotten the sum of each lot's total to 15,000 the system will refuse. 

I think we should verify this behavior.  It seems to me that I've entered a bigger "global quantity" than the lots during integration and not gotten any complaints.

**Comment by jniles** [comment]
Okay, concretely, we could probably remove the following columns:

1. `delay` - I can't find where it is used.  I looked as part of https://github.com/IMA-WorldHealth/bhima/pull/5473 and couldn't find anything.
2. `quantity`
3. `initial_quantity`
4. `entry_date`

The `is_assign` field is used for "unique" lots - e.g. things like computers that have serial numbers as their lot number.  Since all our instances of inventory articles are lots, we kind of overloaded that table.

**Comment by jmcameron** [comment]
@jniles  I was able to do #1 (remove delay) without any issue.  I have not submitted a PR for it yet.

But I'd like to talk with you about to handle the others (quantity, initial_quantity, and entry_date).  I want to clarify whether they should be available in the database lot queries via joins with the stock_movement table.  If so, that would mean some DB query code needs to be added/updated rather than just deleting all occurrences of the three.

**Comment by jniles** [comment]
@jmcameron are you still awaiting a conversation with me about this?  Or have we gotten clarity since then?
