### ISSUE TITLE
Implement function to automatically merge lots which can be merged without user decisions

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5370]
In the production databases, we have many duplicate lots.   Some of these will require knowledgeable uses to determine which lots are the and merge them as appropriate.   However, there probably are some duplicate lots that could be merged automatically.   Taking care of these would reduce the work for users how need to make decisions about how to handle the other lot merges. 

Lots have these intrinsic characteristics:

- Same UUID
- Same lot label
- Same inventory_uuid
- Same expiration date

There are other fields in the 'lot' table, but some of them are problem the result of muddled thinking about lots.

If lots have the same values for all the intrinsic fields above, they can probably be merged automatically.

Once we clarify what constitutes identical lots, we should be able to write a function that will identify identical lots, we can create function to do that and put it in the main drop-down [Menu] in the 'Find Duplicate Lots' page.

@JNiles, please review this issue and let me know what you think about how to identify identical duplicate lots that can be merged automatically without user decisions.

**Comment by jniles** [comment]
The UUID is generated, so we don't need to use that as a matching criteria.  The rest are good.

Yes, in theory, the "lot label" should be unique and match to one and only one expiration date for each inventory item.  I think that if the label, inventory, and expiration date are the same, we can just merge these without user consent.  However, if the expiration dates disagree by a large margin (taking into account that I believe we store TIMESTAMPs and not DATEs, which doesn't make sense for expirations), we'll need to leave those and ask the user to clarify.

I agree this is an urgent task.
