### ISSUE TITLE
Add the expiration date in dropdown of lots in the stock exit module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5375]
This issue is about to add the lot's expiration date next to the lot name in the dropdown of selecting lot

![image](https://user-images.githubusercontent.com/5445251/107579352-44c73e80-6bf5-11eb-9735-099091ce8142.png)

**Comment by jmcameron** [comment]
I'm currently working on this.  See Issue https://github.com/IMA-WorldHealth/bhima/issues/5257

**Comment by jmcameron** [comment]
Actually, this may be a different (but related) issue. What page is this?

**Comment by jniles** [comment]
@mbayopanda, do you need this urgently?  If so, we may have to figure out how to either merge our `refactor-stock-management` branch earlier, or we may want to do this directly against master.

**Comment by jniles** [comment]
@jmcameron, you are referring to stock entry, not exit.  This is a separate issue.
