### ISSUE TITLE
Rename stock `Items` functions in stock to `Articles`

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5400]
As mention in https://github.com/IMA-WorldHealth/bhima/issues/5326 and https://github.com/IMA-WorldHealth/bhima/pull/5372#discussion_r578763825. we should continue our internal name refactoring to avoid confusion so that all references to inventory "items" in stock are referred to as "articles".  This will help us have clarity in our language when we discuss these things.

**Comment by jmcameron** [comment]
We should also be consistent in our use of the term "product" (for instance on the Stock Dashboard.   In that case, perhaps the term should be "Inventory" or "Articles" rather than "product"?

**Comment by jniles** [comment]
@jmcameron has this advanced far enough that we can consider closing this issue?

**Comment by jmcameron** [comment]
> @jmcameron has this advanced far enough that we can consider closing this issue?

I think we still have places "items" is used, so I would suggest we should not close this issue yet.
