### ISSUE TITLE
Implemented Weighted Average Cost (WAC) / Cout Moyenne Pondere (CMP) algorithm for stock exits

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5401]
Actually, the unit cost of lots during a stock exit is related to the lot unit cost which causes a mismatch with the accounting value of the stock when there is multiple unit cost for a unique lot.

The proposal is to have an average unit cost for lots with multiple values during the stock exit.

the goal is to have the same value in the stock value report and the account report each time

**Comment by jniles** [comment]
I think this means we'll need a function that returns the weighted average cost (WAC) for an inventory item.  I'm imagining a function call `getWeightedAverageCost(inventoryUuid BINARY(16))` that returns the current value given an inventory item. 

Note, we already have some prior art in our stock value report:
https://github.com/IMA-WorldHealth/bhima/blob/1819d8f7380f16590fce3fbbe3c900513d001c56/server/controllers/stock/reports/stock/value.js#L85-L90

Here is how the algorithm would work with the refactored `stock_movement_status` table structure.
  1. Look up the most recent stock out in the `stock_movement_status` table (`sum_quantity` = 0).  If no such record exists, take the first entry date.  Get that date as `start_date`:
  2. Get all stock movements from the `start_date` on that are entries into stock.  NOTE: we may have to filter out movements between depots.
  3. Compute the WAC by summing the `quantity` * `unit_cost` of each entry, divided by the total `quantity` entered.  In SQL, I believe this should be something like
  ```sql
SELECT SUM(unit_cost * quantity) / SUM(quantity) FROM stock_movement WHERE date >= $start_date and is_exit = 0 AND inventory_uuid = $inventory_uuid;
```
  4. Return this value as the `unit_cost` of the item for exit.

Note: we may wish to support providing an end date as well, so we can ask what the value of stock was at a given time period.

The source for this algorithm is found [here](https://corporatefinanceinstitute.com/resources/knowledge/accounting/weighted-average-cost-method/) and [here](https://www.investopedia.com/terms/a/averagecostmethod.asp).

If we had such a function, we could use this for:
  1. Stock Value Report
  2. Stock Expiration Report
  3. Each stock exit (as noted here)

**Comment by jmcameron** [comment]
Besides the avergate weighted cost, it might be useful to have the min and max prices for audit purposes.

**Comment by jmcameron** [comment]
https://smallbusiness.chron.com/kinds-companies-choose-weighted-average-costing-37851.html 
(Search for: Pharmaceuticals) 
This brief article mentions 3 approaches:  
1. Weighted average costing
2. LIFO - last-in, first-out  (more common)
3. FIFO - first-in, first-out

Another nice article with more details is:  
https://www.investopedia.com/ask/answers/09/weighted-average-fifo-lilo-accounting.asp

**Comment by jmcameron** [comment]
I was able to get the SQL query working for AWC for a single stock item and to convince myself that it actually is doing the right thing.  I'll attach the script here.  Note that the first query shows all entry stock movements and running sums for quantity, $ total exits, and $ total entries.   The second query does the calculation in one step without the stock movement details.  Both are for a single inventory item.

Use the IMCK database.

[testawc.sql.txt](https://github.com/IMA-WorldHealth/bhima/files/6231586/testawc.sql.txt)

**Comment by jniles** [comment]
@jmcameron nice work!  Note that this will require #5364 to be closed.  This next release is the last release we'll officially support MySQL 5.7.

**Comment by jniles** [comment]
The WAC is more complicated than I previously stated.  Here is an XLSX attachment that should show how it all works:

[WAC Validation.xlsx](https://github.com/IMA-WorldHealth/bhima/files/6962410/WAC.Validation.xlsx)

![image](https://user-images.githubusercontent.com/896472/128884173-0d4d6f3b-fdd4-45dc-babd-26da312228b0.png)


What you'll notice is that the WAC only changes when we purchase items, and it doesn't depend on where the items are stored.  So, we don't need to consider the concept of depots. 

The WAC will always be `WAC = ${running_value_total} / ${running_total_stock}`.  We already have `${running_total_stock}` in the column `sum_quantity` in the `stock_movement_status` table.  All we need to do is find (or store) the `${running_value_total}`.
