### ISSUE TITLE
Problems with Stock Import

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5426]
When stock is imported successfully, the Stock Lots page is displayed with a filter for the depot that received the import.  Unfortunately, the UUID is shown for the depot in the filter label, not the depot name (in 'master').
![image](https://user-images.githubusercontent.com/62145/109038752-eaac8b80-7680-11eb-91bd-3c3ee6d9d96c.png)
Note that this filter label works correctly in the stock lots registry when selected by the [Search] filter there.

Also the example import file is broken (includes double-quotes within double-quotes, quoted numbers, etc.  These issues will be addressed by one of the fixes in the refactor-stock-management branch.

**Comment by jmcameron** [comment]
Here is an example import file I adapted from the template that works with the IMCK database (rename to *.csv).

[test.csv.txt](https://github.com/IMA-WorldHealth/bhima/files/6037890/test.csv.txt)

**Comment by jniles** [comment]
This would be because of a broken filter label somewhere.  I wonder if we changed it in a SQL query.  Certainly that is what happened in https://github.com/IMA-WorldHealth/bhima/issues/5430
