### ISSUE TITLE
Lot Registry : Edit lot doesn't show the inventory name

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5430]
When we click on Edit lot in the registry we don't see the inventory name in the modal 

![image](https://user-images.githubusercontent.com/5445251/109124643-712d9f80-774b-11eb-9dd8-a3f38119172e.png)

**Comment by jniles** [comment]
This is probably due to a name change with the `inventory_text` that we worked on during the merging/editing lots refactor.  It should be simple to fix if we can just figure out with the inventory is now called.
