### ISSUE TITLE
Stock : avg_consumption is still used in most of stock modules and registries

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5431]
The `avg_consumption` column in the inventory table has been removed in the `refactor-stock` branch but in `master`, there are modules and registries which still use this column.

**Comment by jniles** [comment]
I thought I had removed all references to this column in the `refactor-stock-management` branch.  I also just did a quick search in the code to see where it is used and I couldn't find it.  Can you point me to an example?

**Comment by jniles** [comment]
@mbayopanda did you find anywhere?  If not, I don't this this issue is still valid - you might have been looking at the `master` branch.  They should be removed in the `refactor-stock-management`.

**Comment by mbayopanda** [comment]
No it was fixed in the `refactor-stock-management`
