### ISSUE TITLE
Translation of handlebars template in user session language

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#544]
This PR is about the possibility to translate the handlebars templates to the language that the user has chose. 

The reason is that we can chose the french language in the application and have English in the generated report : 

![french voucher](https://cloud.githubusercontent.com/assets/5445251/16418459/c2eaa160-3cfe-11e6-94cf-04523e5d12d6.png)

And the report is in English

![english report](https://cloud.githubusercontent.com/assets/5445251/16418475/d7019578-3cfe-11e6-9b2a-98e81807b5c7.png)

**Comment by jniles** [comment]
This was closed in #569.
