### ISSUE TITLE
Contexte d'ajustement de stock dans BHIMA

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5457]
# Stock Adjustment Issue

## Ajustement de stock normal lors de l'inventaire à la fin de l'année

1. La quantité physique est supérieure à la quantité théorique

| Physique | Théorique | Différence |
| ---      | ---       | ---        |
| 10       | 5         | 5          |

Le stock théorique doit correspondre au stock physique, dans la comptabilité on passe les écritures en débitant le compte de classe 3 (stock) et on crédite le compte de classe 603 (variation de stock) car le stock théorique doit être augementé.

Voici les deux écritures à passer :

| Compte 31     ||
| ---   | ---    |
| Débit | Crédit |
| 5     | 0      |

Et pour la variation de stock, on aura : 

| Compte 603     ||
| ---   | ---    |
| Débit | Crédit |
| 0     | 5      |

2. La quantité théorique est supérieure à la quantité physique

| Physique | Théorique | Différence |
| ---      | ---       | ---        |
| 10       | 20        | 10         |

La quantité théorique doit être diminuer de 10 unité afin qu'elle corresponde à la quantité physique.

Voici les écritures à passer :

| Compte 31     ||
| ---   | ---    |
| Débit | Crédit |
| 0     | 10     |

Et pour la variation de stock, on aura : 

| Compte 603     ||
| ---   | ---    |
| Débit | Crédit |
| 10    | 0      |

## Ajustement de stock dans le contexte de BHIMA

Dans BHIMA lorsque la comptabilité du stock est activée, il y a deux parties pour touts mouvements de stock, à savoir : 

- L'opération de stock (avec les quantités)
- L'opération comptable (avec les valeurs monétaires)

Les quantités de stock dans BHIMA ne sont pas gardées dans une table comme des valeurs uniques mais plutôt ce sont des valeurs calculées des différents mouvements d'entrées et de sorties de stock.

Prénons notre example avec le stock physique supérieur au stock théorique

| Physique | Théorique | Différence |
| ---      | ---       | ---        |
| 10       | 5         | 5          |

Voici les opérations dans BHIMA

1. L'opération de stock

1.1. Créer des mouvements qui vont remettre à zero le stock théorique

1.2. Créer des mouvements qui vont insérer la nouvelle quantité théorique qui doit correspondre avec la quantité physique.

2. L'opération comptable

2.1. Pour la remise à zero, des écritures comptables sont passées :

Théoriquement nous avons 5 unités dans notre stock, pour la remise à zero nous devons reduire ces 5 unités en créditant le compte de stock (31) par le débit du compte de variation de stock (603)

| Compte 31     ||
| ---   | ---    |
| Débit | Crédit |
| 0     | 5      |

Et 

| Compte 603    ||
| ---   | ---    |
| Débit | Crédit |
| 5     | 0      |

Ces écritures auront pour conséquences de rendre la valeur du compte 30 à 0

2.2. Pour la nouvelle quantité théorique

Maintenant que la valeur de notre stock est à 0, nous n'avons juste qu'à ajouter la nouvelle quantité théorique afin qu'elle soit conforme avec la quantité physique.

| Compte 31     ||
| ---   | ---    |
| Débit | Crédit |
| 10    | 0      |

Et 

| Compte 603    ||
| ---   | ---    |
| Débit | Crédit |
| 0     | 10     |

Maintenant notre stock théorique (dans BHIMA) vaut 10 unités, ce qui correspond au stock physique.

QUESTION ? Pourquoi ne pas insérer directement la différence afin que le stock théorique corresponde avec le stock physique, au lieu de passer par les deux étapes (Remise à zero et insertion des nouvelles valeurs) ?

REPONSE : 
1. Sur le plan de la comptabilité : Il n'y a pas de problème

2. Sur le plan du module ajustement de stock et de la structure du logiciel BHIMA

Passer un mouvement de stock avec la différence entre stock physique et théorique est la solution.

CONCLUSION :

- Le fait d'avoir deux opérations de stock à savoir : la remise à zero et l'insertion, impliquent :
  - il y a des quantités mouvementées que l'on aurait pu éviter pour les types de flux (`INVENTORY_RESET` et `INVENTORY_ADJUSTEMENT`) si on avait seulement un seul mouvement
  - le debit et le credit des comptes (3 et 603) sont gonflées par des mouvements que l'on aurait pu éviter

- La difficulté d'implémentation d'un seul mouvement reside principalement sur le fait que dans BHIMA nous utilisons la procédure `PostStockMovement` qui reçoit en paramètre :
    - Le `uuid` du document
    - Le `is_exit` pour savoir s'il s'agit d'une entrée ou d'une sortie
    - Le `project_id` l'indentifiant du projet

L'utilisation du `uuid` du document et du `is_exit` dans notre procédure `PostStockMovement` nous permet de passer un seul mouvement seulement dans le cas où nous avons soit seulement des entrées ou seulement des sorties. Dans le cas où les entrées et les sorties sont melangées dans un seul document nous ne pouvons pas utiliser notre procédure `PostStockMovement`. See #5458

**Comment by jniles** [comment]
Merci @mbayopanda pour cette explication très claire!  

Si nous prenons l'exemple suivant:

| Physique | Théorique | Différence |
| ---      | ---       | ---        |
| 10       | 5         | 5          |


Il semble que nous pouvons le faire dans une seule mouvement - une sortie de 5 unités.  Donc, on pourra avoir juste une seule écriture avec le même valeur d'un ajustement comme si nous avons utilisé le module d'ajustement avec une "diminution".  Voici un écriture exemplaire que j'ai fait avec le module "ajustement" qui a produit une seule écriture:
![image](https://user-images.githubusercontent.com/896472/110023667-b7779580-7d2d-11eb-856a-6e9db3cd7049.png)
 

Du même manière, nous pouvons avoir ce cas:

| Physique | Théorique | Différence |
| ---      | ---       | ---        |
| 10       | 15         | 5          |

Encore, nous pouvons le faire dans une seule écriture qui augment le valeur a 15.

La seule complication c'est les exemples "mixed":

| Produit | Physique | Théorique | Différence |
| --- | ---      | ---       | ---        |
| X | 10       | 15         | 5          |
| Y | 10 | 8 | 2 |

Dan ce cas, nous ne pouvons que utiliser deux écritures.  Mais ce n'est pas nécessaire que nous passons par une quantité 0.  On va juste faire augmenter pour tous qui sont bas, et diminuer pour tous qui sont haut.

Il semble que l’opération "remis a zéro" est aussi dangereux.  Voici les écritures négatif qui ont été crée automatiquement par le système a cause de ce logique:

![image](https://user-images.githubusercontent.com/896472/110024630-a54a2700-7d2e-11eb-9037-ee4d44942811.png)
_Amoxy 250MG a IMCK_

![image](https://user-images.githubusercontent.com/896472/110024851-e80bff00-7d2e-11eb-8df4-2c049f922e22.png)
_prednisone 5 mg a IMCK_

Est-ce que nous pouvons juste enlever la logique de "remise a 0"?

**Comment by mbayopanda** [comment]
Oui, nous pouvons le faire

**Comment by mbayopanda** [comment]
La difficulté est seulement sur le fait que si on veut un mouvement unique, pour un ajustement de stock qui fait des augmentations et des diminutions, nous allons avoir du mal pour dire si ce mouvement unique doit être une entrée ou une sortie

**Comment by mbayopanda** [comment]
Nous pouvons supprimer l'étape de remise à zero et faire l'ajustement

**Comment by jniles** [comment]
Oui, je ne suis pas trop chaud pour le mouvement unique, mais je pense que l’étape de remise a zéro est vraiment important a enlevé.   C'est claire que si on fait une ajustement, et après, on ajoute un autre mouvement avant, le solde risque d’être négatif.

**Comment by jniles** [comment]
@mbayopanda can we close this?

**Comment by jniles** [comment]
This was addressed a while ago.  We now do adjustments by going from the current value to the new value without going through 0.
