### ISSUE TITLE
Duplicate lot flags in expiration report?

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5460]
In the process of fixing the Stock Expiration Report in PR https://github.com/IMA-WorldHealth/bhima/pull/5438, I noticed that the expiration, at_risk, etc, flags in the lot appear both at the top level of each lot object as well as in its 'flags' sub-object.   

To see this,  edit server/controllers/stock/reports/stock/expiration_report.js and insert console.log(lot) inside the rows.forEach loop (about line 70) and observe the results when you execute the Stock Expiration Report.

This duplication should be cleaned up.

**Comment by jniles** [comment]
This is true.  We do duplicate these flags.  I agree we should clean it up.
