### ISSUE TITLE
Edit patient "Prenom" is broken

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#547]
This issue is about the patient prenom edit which doesn't work

**Comment by jniles** [comment]
@mbayopanda, could you take a look at fixing this today?

**Comment by jniles** [comment]
Here is the proper way to submit a fix for this bug:
1. Write an end-to-end test that tries to update a patient's name.  This test should fail.
2. Write code that fixes the bug.  This will likely be changing the `ngModel`, or the `service.update()` call.
3. Show that the code fixes the end-to-end test.
4. Submit a pull request with your changes.
