### ISSUE TITLE
Articles in Stock status tags

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5478]
In the articles in stock, the status tags (Over Maximum, Critical Stock, Stock Out, etc) are cut on the right in the narrow column for Status.  One way to address this (without changing column widths) is to add a tooltip on them so when you hover over them, you see the full text

Also, I notice that the grid filtering option does not allow filtering on the Status column.   If that is not too difficult to fix, it might be useful.

**Comment by jniles** [comment]
I would also propose that "critical stock" be red.  It means that you are below your security stock - you will have a stock out, no matter even if you order today.  "Low stock" should be yellow.

> Also, I notice that the grid filtering option does not allow filtering on the Status column. If that is not too difficult to fix, it might be useful.

This isn't difficult, but it is tricky.  That is, you have to know the trick.  It's something like filtering after the angularjs $translate filter is applied to the cell.  The ui-grid documentation would be of use here.

**Comment by jniles** [comment]
Note - the medical director of Vanga just asked me for the ability to sort this column.  Bumping this up to a higher priority.

**Comment by jmcameron** [comment]
Notes on the current status label colors:
- 'out of stock' is red (label-danger)
- 'critical stock' is orange (label-warning)
- 'low stock' is light blue (label-info)
- 'in stock' is green (label-success)
- 'over-maximum' is blue (label-primary)

Based on chats with @jniles, it makes sense to change the 'low stock' labek to yellow to indicate a problem. That way the three problem cases (out, cricial, low) form a natural range of colors (red, orange, yellow).

**Comment by jmcameron** [comment]
PR https://github.com/IMA-WorldHealth/bhima/pull/5497 resolved the status filtering and status tag coloring issues, but did not add the tool tips.  That still needs to be done in a different PR.
