### ISSUE TITLE
Is our calculation of minimum stock correct?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5481]
For the resolution of this, see https://github.com/IMA-WorldHealth/bhima/issues/5481#issuecomment-802825729.  This discussion is kept for historical purposes.

----

I've been writing down how the stock flags are calculated and I think the minimum stock is not actually correct, or, at least, it doesn't make sense.

Here is how we calculate security stock and minumum stock:
https://github.com/IMA-WorldHealth/bhima/blob/6e5077e5fb9771532af326ad10aabbbb0ca085ad/server/controllers/stock/core.js#L520-L531

I don't think this definition of minimum stock makes sense.  Shouldn't it be some amount of stock + the security stock?  I can imagine it being better expressed as:

```js
    inventory.S_MIN = inventory.S_SEC + (CMM * inventory.min_months_stock);
 ```
 
 I rewrote this code for clarity in the last year.  Did I make a mistake, is this a bug, or does our definition actually make sense?  The more I think about it, the more I feel like it should be the method I propose above, rather the our current method.

**Comment by jmcameron** [comment]
Just from reading the code comment above, it seems like the max() function should be involved:

`
  inventory.S_MIN = CMM*max(delay,  inventory.min_months_security_stock)
`

Where I am assuming 'delay' is in months so the units are all compatible.

Something like this should give the 'floor' mentioned in the comment.

**Comment by jniles** [comment]
The delay is the purchase lead time - the number of months the stock is in transit.

You bring up a good point about units.  The current implementation doesn't make sense:
```js
// quantity of stock = quantity of stock * duration in months 
 inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
 ```
 
 That is why something like this makes more sense:
 ```js
// quantity of stock = quantity of stock + (monthly rate * duration in monthsn)
inventory.S_MIN = inventory.S_SEC + (CMM * inventory.min_months_stock);
```
I do think that the security stock should always be strictly less than the months of stock.  So I like the + offset.

**Comment by jniles** [comment]
@mbayopanda @lomamech do you guys have any opinion on this?

**Comment by mbayopanda** [comment]
This definition :
```js
// quantity of stock = quantity of stock + (monthly rate * duration in monthsn)
inventory.S_MIN = inventory.S_SEC + (CMM * inventory.min_months_stock);
```
If the `delay = inventory.min_months_stock` then
```js
inventory.S_MIN = 2 * inventory.S_SEC;
```
Which was the first implementation of S_MIN in BHIMA.

**Comment by jniles** [comment]
So, is our implementation correct or not?  Or are you suggesting we go with 
```js
inventory.S_MIN = inventory.S_SEC + (CMM * inventory.min_months_stock);
```
?

**Comment by mbayopanda** [comment]
Since by definition : 
`Stock minimum : niveau du stock correspondant au délai normal de livraison.`

Our implementation is not correct according to [stock minimal](http://public.iutenligne.net/gestion/gestion-previsionnelle/antraigue_januario/partie6_control_gest_841-S4/sansmenu/GEST-P06-R04/CHAPITRE-02/Section-2-1.html)

This will make more sense : 
```js
inventory.S_MIN = CMM * inventory.min_months_stock;
inventory.S_SEC = 2 * inventory.S_MIN;
```

**Comment by mbayopanda** [comment]
In other documentation S_MIN and S_SEC : 
```js
inventory.S_SEC = CMM * inventory.min_months_stock;
inventory.S_MIN = 2 * inventory.S_SEC ;
```
![image](https://user-images.githubusercontent.com/5445251/111590341-4670bd00-87c6-11eb-872f-3f836643d2e8.png)

Our implementation : 
```js
inventory.S_SEC = CMM * inventory.min_months_security_stock;
inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
```
Is not correct for S_MIN

**Comment by lomamech** [comment]
I don't think there was an error in the way we calculated the safety stock calculation, this is exactly what came from the formula, the delivery time is actually (the average delivery time) for a product.

**Comment by lomamech** [comment]
For the minimum stock, I think that the number of months of stock is an agreement from one institution to another by our Ministry of Health they have fixed in advance this value

**Comment by lomamech** [comment]
![IMG_20210318_090901_463 1](https://user-images.githubusercontent.com/8035588/111593044-d2d0af00-87c9-11eb-9e7a-c1511f4aaf10.jpg)
@jniles  The implementation we have done correspond exactly to the formulas in this document

**Comment by lomamech** [comment]
> Since by definition :
> `Stock minimum : niveau du stock correspondant au délai normal de livraison.`
> 
> Our implementation is not correct according to [stock minimal](http://public.iutenligne.net/gestion/gestion-previsionnelle/antraigue_januario/partie6_control_gest_841-S4/sansmenu/GEST-P06-R04/CHAPITRE-02/Section-2-1.html)
> 
> This will make more sense :
> 
> ```js
> inventory.S_MIN = CMM * inventory.min_months_stock;
> inventory.S_SEC = 2 * inventory.S_MIN;
> ```
Explain a little this form, how to calculate S_SEC the stock from the minimum stock
inventory.S_SEC = 2 * inventory.S_MIN ???

**Comment by mbayopanda** [comment]
1. Our implementation : 

```js
inventory.S_SEC = CMM * inventory.min_months_security_stock;
inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
```
If the CMM = 100, We will have : 

|Delay | SEC | MIN |
| --- | --- | --- |
|0|0|0|
|1|100|100|
|2|200|400|
|3|300|900|
|4|400|1600|
|5|500|2500|

The MIN increases exponentially.

With MIN = 2 * SEC;

|Delay | SEC | MIN |
| --- | --- | --- |
|0|0|0|
|1|100|200|
|2|200|400|
|3|300|600|
|4|400|800|
|5|500|1000|

The MIN doesn't increase exponentially which is enough good than the exponential version.

And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say : 

```js
MIN = SEC + C
```
With `C = A constante value chosen by convention`.

And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.

**Comment by jniles** [comment]
Thanks for the feedback @lomamech and @mbayopanda !

So, I think the `min_months_security_stock` variable was meant to replace the `2` value since the amount of stock a health center needs is different from the health zone (the health zone needs at least 3 months of stock on hand).

As @lomamech noted, this means our `S_SEC` is correct:
```js
inventory.S_SEC = CMM * delay;
```

and if we consider `min_months_security_stock` to replace "2", our `S_MIN` calculation should be :
```js
inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock;
```
which is what we have. 

This problem is that I think we allow `inventory.min_months_security_stock` to be less than 1, so `S_MIN` would be less than `S_SEC`.  From the documentation @mbayopanda linked:

> Stock de sécurité : supplément au stock minimum nécessaire en cas de retard de livraison ou d'accroissement de la demande.

This doesn't imply that `S_SEC` is necessary greater or less `S_MIN`, but it doesn't give formulas for either.  I think what it considers `Stock d'alerte` is what BHIMA considers `S_MIN`.

 I see two solutions to this problem.  Either we:

1. Do not allow smaller values than `1` for the `min_months_security_stock`.
2. Make this an offset - `S_MIN = S_SEC + (inventory.S_SEC * inventory.min_months_security_stock)`

**Comment by mbayopanda** [comment]
> > Since by definition :
> > `Stock minimum : niveau du stock correspondant au délai normal de livraison.`
> > Our implementation is not correct according to [stock minimal](http://public.iutenligne.net/gestion/gestion-previsionnelle/antraigue_januario/partie6_control_gest_841-S4/sansmenu/GEST-P06-R04/CHAPITRE-02/Section-2-1.html)
> > This will make more sense :
> > ```js
> > inventory.S_MIN = CMM * inventory.min_months_stock;
> > inventory.S_SEC = 2 * inventory.S_MIN;
> > ```
> 
> Explain a little this form, how to calculate S_SEC the stock from the minimum stock
> inventory.S_SEC = 2 * inventory.S_MIN ???

These definitions are based on [Gestion de stock](http://public.iutenligne.net/gestion/gestion-previsionnelle/antraigue_januario/partie6_control_gest_841-S4/sansmenu/GEST-P06-R04/CHAPITRE-02/Section-2-1.html)

But in BHIMA, 
S_SEC => Stock minimum of this link
S_MIN => Stock de securité of this link

This is not bad because some schools agreed with the BHIMA's way [Stock](https://www.mecalux.fr/blog/stock-minimum-definition)

**Comment by lomamech** [comment]
> 1. Our implementation :
> 
> ```js
> inventory.S_SEC = CMM * inventory.min_months_security_stock;
> inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> ```
> 
> If the CMM = 100, We will have :
> 
> Delay	SEC	MIN
> 0	0	0
> 1	100	100
> 2	200	400
> 3	300	900
> 4	400	1600
> 5	500	2500
> The MIN increases exponentially.
> 
> With MIN = 2 * SEC;
> 
> Delay	SEC	MIN
> 0	0	0
> 1	100	200
> 2	200	400
> 3	300	600
> 4	400	800
> 5	500	1000
> The MIN doesn't increase exponentially which is enough good than the exponential version.
> 
> And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> 
> ```js
> MIN = SEC + C
> ```
> 
> With `C = A constante value chosen by convention`.
> 
> And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.

In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock

**Comment by jniles** [comment]
@mbayopanda, the `min_months_security_stock` is a constant, so your formula shouldn't increase exponentially.

If the CMM = 100, and `min_months_security_stock` = 0.5,  We will have : 

|Delay | SEC | MIN |
| --- | --- | --- |
|0|0|0|
|1|100|50|
|2|200|100|
|3|300|150|
|4|400|200|
|5|500|250|

Or if the CMM = 100, and `min_months_security_stock` = 2,  We will have : 

|Delay | SEC | MIN |
| --- | --- | --- |
|0|0|0|
|1|100|200|
|2|200|400|
|3|300|650|
|4|400|800|
|5|500|1000|

So I don't think it is exponential.

**Comment by jniles** [comment]
Alternatively, using the links that @mbayopanda provided, we can create a new definition of `S_ALERT` that is `S_MIN + S_SEC`.  Then if one of them is 0, I won't be bothered 😄

**Comment by mbayopanda** [comment]
> @mbayopanda, the `min_months_security_stock` is a constant, so your formula shouldn't increase exponentially.
> 
> If the CMM = 100, and `min_months_security_stock` = 0.5, We will have :
> 
> Delay	SEC	MIN
> 0	0	0
> 1	100	50
> 2	200	100
> 3	300	150
> 4	400	200
> 5	500	250
> Or if the CMM = 100, and `min_months_security_stock` = 2, We will have :
> 
> Delay	SEC	MIN
> 0	0	0
> 1	100	200
> 2	200	400
> 3	300	650
> 4	400	800
> 5	500	1000
> So I don't think it is exponential.

Yes, in this case, it is not exponential but values are weird and have no sense

**Comment by jniles** [comment]
When you say they make no sense, I assume you don't like that `S_MIN` can be less than `S_SEC`?  That was also my concern in creating this issue.

**Comment by mbayopanda** [comment]
> > 1. Our implementation :
> > 
> > ```js
> > inventory.S_SEC = CMM * inventory.min_months_security_stock;
> > inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> > ```
> > 
> > 
> > If the CMM = 100, We will have :
> > Delay	SEC	MIN
> > 0	0	0
> > 1	100	100
> > 2	200	400
> > 3	300	900
> > 4	400	1600
> > 5	500	2500
> > The MIN increases exponentially.
> > With MIN = 2 * SEC;
> > Delay	SEC	MIN
> > 0	0	0
> > 1	100	200
> > 2	200	400
> > 3	300	600
> > 4	400	800
> > 5	500	1000
> > The MIN doesn't increase exponentially which is enough good than the exponential version.
> > And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> > ```js
> > MIN = SEC + C
> > ```
> > 
> > 
> > With `C = A constante value chosen by convention`.
> > And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.
> 
> In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock

If the delivery time is 1 => MIN = 100 and SEC = 100. In other word, MIN = SEC if the delivery time is 1 according our implementation.

**Comment by mbayopanda** [comment]
> When you say they make no sense, I assume you don't like that `S_MIN` can be less than `S_SEC`? That was also my concern in creating this issue.

Exactly, because by definition MIN is the SEC + a given quantity

**Comment by jniles** [comment]
> 
> 
> > When you say they make no sense, I assume you don't like that `S_MIN` can be less than `S_SEC`? That was also my concern in creating this issue.
> 
> Exactly, because by definition MIN is the SEC + a given quantity



So, that is what I thought to, but your link doesn't explicitly mention that.  It says:

>  Stock de sécurité : supplément au stock minimum nécessaire en cas de retard de livraison ou d'accroissement de la demande.

So... it's just a suppliment, but it doesn't have to be more or less than the minimum stock.  But I think that is because they are using "stock d'alerte" which BHIMA doesn't implement.

I'm fine with your proposal of  
```
MIN = SEC + C
```

but I think C should be a computed value based on either the CMM or the delay or both.  So, something like :
```js
C = CMM * 2 // this means "two months of stock"
// OR
C = delay * CMM // this means "the amount of stock consumed while waiting for an order"
// OR
C = CMM * min_months_of_stock_for_depot
```

What do you think?

**Comment by mbayopanda** [comment]
> > 1. Our implementation :
> > 
> > ```js
> > inventory.S_SEC = CMM * inventory.min_months_security_stock;
> > inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> > ```
> > 
> > 
> > If the CMM = 100, We will have :
> > Delay	SEC	MIN
> > 0	0	0
> > 1	100	100
> > 2	200	400
> > 3	300	900
> > 4	400	1600
> > 5	500	2500
> > The MIN increases exponentially.
> > With MIN = 2 * SEC;
> > Delay	SEC	MIN
> > 0	0	0
> > 1	100	200
> > 2	200	400
> > 3	300	600
> > 4	400	800
> > 5	500	1000
> > The MIN doesn't increase exponentially which is enough good than the exponential version.
> > And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> > ```js
> > MIN = SEC + C
> > ```
> > 
> > 
> > With `C = A constante value chosen by convention`.
> > And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.
> 
> In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock

Maybe we need  a way to set this `C` constant configurable for each depot

**Comment by jniles** [comment]
We are clearly on the same wavelength 👋 📏

**Comment by lomamech** [comment]
> > > 1. Our implementation :
> > > 
> > > ```js
> > > inventory.S_SEC = CMM * inventory.min_months_security_stock;
> > > inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> > > ```
> > > 
> > > 
> > > If the CMM = 100, We will have :
> > > Delay	SEC	MIN
> > > 0	0	0
> > > 1	100	100
> > > 2	200	400
> > > 3	300	900
> > > 4	400	1600
> > > 5	500	2500
> > > The MIN increases exponentially.
> > > With MIN = 2 * SEC;
> > > Delay	SEC	MIN
> > > 0	0	0
> > > 1	100	200
> > > 2	200	400
> > > 3	300	600
> > > 4	400	800
> > > 5	500	1000
> > > The MIN doesn't increase exponentially which is enough good than the exponential version.
> > > And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> > > ```js
> > > MIN = SEC + C
> > > ```
> > > 
> > > 
> > > With `C = A constante value chosen by convention`.
> > > And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.
> > 
> > 
> > In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock
> 
> Maybe we need a way to set this `C` constant configurable for each depot

Sorry we must multply and not add
```` MIN = SEC + C or MIN = SEC * C ````

**Comment by mbayopanda** [comment]
> > > > 1. Our implementation :
> > > > 
> > > > ```js
> > > > inventory.S_SEC = CMM * inventory.min_months_security_stock;
> > > > inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> > > > ```
> > > > 
> > > > 
> > > > If the CMM = 100, We will have :
> > > > Delay	SEC	MIN
> > > > 0	0	0
> > > > 1	100	100
> > > > 2	200	400
> > > > 3	300	900
> > > > 4	400	1600
> > > > 5	500	2500
> > > > The MIN increases exponentially.
> > > > With MIN = 2 * SEC;
> > > > Delay	SEC	MIN
> > > > 0	0	0
> > > > 1	100	200
> > > > 2	200	400
> > > > 3	300	600
> > > > 4	400	800
> > > > 5	500	1000
> > > > The MIN doesn't increase exponentially which is enough good than the exponential version.
> > > > And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> > > > ```js
> > > > MIN = SEC + C
> > > > ```
> > > > 
> > > > 
> > > > With `C = A constante value chosen by convention`.
> > > > And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.
> > > 
> > > 
> > > In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock
> > 
> > 
> > Maybe we need a way to set this `C` constant configurable for each depot
> 
> Sorry we must multply and not add
> `MIN = SEC + C or MIN = SEC * C`

**Comment by lomamech** [comment]
````
 Maybe we need a way to set this C constant configurable for each depot
````
@mbayopanda  In Bhima we had already defined the number of months of security by default but also by depot

**Comment by lomamech** [comment]
So far I don't think there is a problem with the way we calculated the safety stock as well as the minimum stock in BHIMA (compared to the documentation that we had used as a reference) with the implementation in the BCZ database we had initialized the delivery time to 1 which will have for consequence that the CMM will always be equal to the safety stock, for the calculation of the Minimum Stock we multiply S.MIN = S. SEC by the number of months of security in the old implementation we had fixed the value by 2 but now in BHIMA we have the possibility to set the value by deposit, for the deposit of BCZ Tshikaji this value is equal to 3 months

**Comment by mbayopanda** [comment]
> > > > 1. Our implementation :
> > > > 
> > > > ```js
> > > > inventory.S_SEC = CMM * inventory.min_months_security_stock;
> > > > inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock; 
> > > > ```
> > > > 
> > > > 
> > > > If the CMM = 100, We will have :
> > > > Delay	SEC	MIN
> > > > 0	0	0
> > > > 1	100	100
> > > > 2	200	400
> > > > 3	300	900
> > > > 4	400	1600
> > > > 5	500	2500
> > > > The MIN increases exponentially.
> > > > With MIN = 2 * SEC;
> > > > Delay	SEC	MIN
> > > > 0	0	0
> > > > 1	100	200
> > > > 2	200	400
> > > > 3	300	600
> > > > 4	400	800
> > > > 5	500	1000
> > > > The MIN doesn't increase exponentially which is enough good than the exponential version.
> > > > And by definition, the MIN is a value that we agreed to add to the SEC for preventing late delivery. And we can say :
> > > > ```js
> > > > MIN = SEC + C
> > > > ```
> > > > 
> > > > 
> > > > With `C = A constante value chosen by convention`.
> > > > And I think having this `C` as a variable that changes exponentially will give us a MIN with quantity over than what the enterprise need since the SEC is already based on the consumption and the delay.
> > > 
> > > 
> > > In our implementation the delivery time is equal to 1 for BCZ data so that In our implementation the delivery time is equal to one which will make the CMM always equal to the Secure Stock
> > 
> > 
> > Maybe we need a way to set this `C` constant configurable for each depot
> 
> Sorry we must multply and not add
> `MIN = SEC + C or MIN = SEC * C`

In BHIMA, MIN = Supplément au stock securité nécessaire en cas de retard de livraison ou d'accroissement de la demande.

```js
inventory.S_SEC = CMM * delay;
inventory.S_MIN = inventory.S_SEC * inventory.min_months_security_stock;
```
How the `delay` is computed for having SEC for BCZ ?

**Comment by lomamech** [comment]
````
How the delay is computed for having SEC for BCZ ?
````
It is fixed at 1 by Health Ministry

**Comment by lomamech** [comment]
> ```
> How the delay is computed for having SEC for BCZ ?
> ```
> 
> It is fixed at 1 by Health Ministry

But with BHIMA if we use the Purchase Order module and proceed to the stock entry coming from this purchase order, the waiting time value will be reset

**Comment by jniles** [comment]
@lomamech is right - delay is either the computed value or a user-provided value.  It's actually `Math.max()` of those two.  The reason for this is that the delay at Vanga was 0.0003 for some inventory items, which wasn't appropriate.

**Comment by lomamech** [comment]
> @lomamech is right - delay is either the computed value or a user-provided value. It's actually `Math.max()` of those two. The reason for this is that the delay at Vanga was 0.0003 for some inventory items, which wasn't appropriate.

![Uploading image.png…]()

**Comment by jniles** [comment]
@lomamech can you try to send that again?  It didn't upload.

So, it sounds like we are okay with the `S_SEC` calculation.  It also sounds like we agree that we should do something like:
```
MIN = SEC + C
```

But we still need to determine what `C` is.  My proposal is:
```js
C = (CMM * depot.min_months_stock)
```

Where `min_months_stock` is a DECIMAL that can be configured by a user.  

@mbayopanda @lomamech what do you think?

**Comment by mbayopanda** [comment]
With this definition `C` sounds like SEC, because : 
```js
SEC = CMM * delay;
```
And I agree with that because it will give us as in the documentation if we have a correct `delay` and `delay` = `depot.min_months_stock` : 
```js
MIN = SEC + C =  SEC + SEC = 2 * SEC;
```

**Comment by mbayopanda** [comment]
With this use of `depot.min_months_stock` we must be sure that all inventories of the depot have the same `min_months_stock`.

I would like to know the real difference between our `delay` which is computed and `depot.min_months_stock`

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
Here is the difference in value between the two formulas for calculating the Minimum Stock

**Comment by mbayopanda** [comment]
> ![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
> Here is the difference in value between the two formulas for calculating the Minimum Stock

What is the difference between `Delay` and `min_months_stock` in real?

**Comment by lomamech** [comment]
> ![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
> Here is the difference in value between the two formulas for calculating the Minimum Stock

The question I ask myself is what is the formula that our Ministry of Health uses for the calculation of safety stock

**Comment by lomamech** [comment]
> ![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
> Here is the difference in value between the two formulas for calculating the Minimum Stock

The question I ask myself is what is the formula that our Ministry of Health uses for the calculation of SEC

**Comment by mbayopanda** [comment]
> > ![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
> > Here is the difference in value between the two formulas for calculating the Minimum Stock
> 
> The question I ask myself is what is the formula that our Ministry of Health uses for the calculation of safety stock

I don't think that our Ministry has `min_months_stock`, but we `Delay` and calculation are based on that.

So do we have a delay configurable?

**Comment by jniles** [comment]
@mbayopanda `delay` is related to how long it takes to procure the stock.  `min_months_stock` is related to how how it takes to consume it.

Both are configurable, although if our computed `delay` is longer than the configured value, we use the computed value.

**Comment by jniles** [comment]
It's two different variables.  If it takes you a long time to procure the stock, you need to have a long reserve in security.  That is `delay`'s role.

However, in the BCZ's case, no matter how long it takes to procure they want to have at least 3 months of stock on hand.  This is related to the CMM.  So, the `min_months_stock` would be related to how many months of stock on hand above and beyond their security stock they would like to maintain.

**Comment by mbayopanda** [comment]
So could we say that the SEC of the BCZ is
```js
SEC = CMM * min_months_stock
```

**Comment by jniles** [comment]
But why?  We don't calculate `min_months_stock`.  It's a user-provided value.  If the user provides `1` and it takes 4 months to order stock, they will be in stock out for a long time 😕

**Comment by mbayopanda** [comment]
> But why? We don't calculate `min_months_stock`. It's a user-provided value. If the user provides `1` and it takes 4 months to order stock, they will be in stock out for a long time 😕

You're right, we must calculate the SEC with 4 months which is good because BHIMA computed that automatically

**Comment by jniles** [comment]
So, bringing this back to the main point.  It sounds like we are happy with our security stock calculation.

How do we calculate `S_MIN`?  Does anyone have an alternative proposal to:
```js
MIN = SEC + C
```
where 
```js
SEC = delay * CMM;

C = (CMM * depot.min_months_stock)
```
?

This allows us to have `SEC` be the time it takes to procure stock and `MIN` be the number of months of stock on hand that make sense for the depot.  So, `1` for a health center and `3` for the health zone office and whatever the hospital feels it needs to set it at for them to function correctly.

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/111615166-b5f3a600-87e0-11eb-95ce-b3af59ba2f45.png)
The question I ask myself is what is the formula that our Ministry of Health uses for the calculation of safety stock

**Comment by lomamech** [comment]
> > > ![image](https://user-images.githubusercontent.com/8035588/111607418-82ad1900-87d8-11eb-8b49-d6975473b826.png)
> > > Here is the difference in value between the two formulas for calculating the Minimum Stock
> > 
> > 
> > The question I ask myself is what is the formula that our Ministry of Health uses for the calculation of safety stock
> 
> I don't think that our Ministry has `min_months_stock`, but we `Delay` and calculation are based on that.
> 
> So do we have a delay configurable?

Sorry I had a disturbance with the internet connection

**Comment by lomamech** [comment]
> I don't think that our Ministry has `min_months_stock`, but we `Delay` and calculation are based on that.
> 
> So do we have a delay configurable?

@mbayopanda  They have some and I think this is exactly what we had configured in BHIMA 3 months for the central office and two months for the structures

**Comment by mbayopanda** [comment]
I am ok with the min formula 
```js
MIN = SEC + C
```
With `C` as mentionned, our concern will be if our SEC is correct in any level : 
- Independant depot
- BCZ
- CS
Because delay is calculated differently, since BCZ and CS don't do purchase, and for requisition, we must think about and ask BCZ to use effectively that

**Comment by lomamech** [comment]
> I am ok with the min formula
> 
> ```js
> MIN = SEC + C
> ```
> 
> With `C` as mentionned, our concern will be if our SEC is correct in any level :
> 
> * Independant depot
> * BCZ
> * CS
>   Because delay is calculated differently, since BCZ and CS don't do purchase, and for requisition, we must think about and ask BCZ to use effectively that

![image](https://user-images.githubusercontent.com/8035588/111622419-73829700-87e9-11eb-8d76-17a28adba67e.png)
I stay for this formula and with BHIMA we have replaced 2 by min_months_stock

**Comment by jniles** [comment]
@lomamech the problem is the `min_months_stock` can be `<1`.  So, if it is, `S_MIN < S_SEC` and that doesn't seem right.  We can restrict this value to be at least one, if we want.

I prefer the 
```
MIN = SEC + C
```
construction because it will never have this problem.  `C` should always be a positive number.

Can both of you come to the office tomorrow?  It will be easier to discuss this with a whiteboard :)

**Comment by lomamech** [comment]
> @lomamech the problem is the `min_months_stock` can be `<1`. So, if it is, `S_MIN < S_SEC` and that doesn't seem right. We can restrict this value to be at least one, if we want.
> 
> I prefer the
> 
> ```
> MIN = SEC + C
> ```
> 
> construction because it will never have this problem. `C` should always be a positive number.
> 
> Can both of you come to the office tomorrow? It will be easier to discuss this with a whiteboard :)

The **min_months_stock** in the standard formula was fixed at 2 months, if in BHIMA we have it flexible it is just because our BCZs need 3 months (1 Quarter) for their security stocks. It may be up to us in the form to prohibit values less than 1 for example

**Comment by jniles** [comment]
Okay, after much whiteboard work, discussion with our pharmacy team, and so on, here is what we've arrived at:

```js
// Security Stock is the Average Monthly Consumption multiplied by the Delivery delay.
S_SEC = CMM * delay; // 

// We need to make sure `min_months_security_stock` always > 1
// Minimum stock should always be bigger than security stock, but there isn't a 
// strict formula for it.  We'll just put it as a ratio of the security stock.  By default, this is 1.
S_MIN = S_SEC * depot.min_months_security_stock;


// Max Stock is the minimum, plus the amount of stock you want to keep in the depot at
// any given time.  This is related to how often you want to purchase stock - the purchase interval.
S_MAX = S_MIN + (CMM * depot.purchase_interval)
```

Given the above, we just need to change the explanation of the `min_months_security_stock` to say that it is simply a factor to "alert" when you need to purchase stock.

Additionally, we need to tie the `purchase_interval` to the `depot` not the inventory item.  Currently we have it tied to the inventory.
