### ISSUE TITLE
Allow users to delete unconfirmed purchase orders

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5490]
Similar to https://github.com/IMA-WorldHealth/bhima/issues/5489, we should allow users to delete unconfirmed purchase orders.  This would help us clean up the junk that users create and never get executed.  It's important that this only applies to unconfirmed purchase orders - confirmed purchase orders are considered contracts that should be executed.

**Comment by jniles** [comment]
@jmcameron would you be willing to tackle this?

**Comment by jniles** [comment]
After discussion w/ @jmcameron, I'm going to tackle this.

**Comment by jmcameron** [comment]
I cannot figure out how to delete unconfirmed OR cancelled PRs.   Did this PR address this and did it get stomped later, somehow?
