### ISSUE TITLE
CMM Algorithm names

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5498]
Since we have not deleted algorithms 2 & 3, I think we need to rename Algorithm 1 and just use 'MSH Algorithm' instead of Algorithm 4.    People will wonder what are algorithms 2 & 3!

**Comment by jniles** [comment]
Yeah... I wonder what we can call the other CMM algorithm.  Maybe Algo IMA?

**Comment by jmcameron** [comment]
> Yeah... I wonder what we can call the other CMM algorithm. Maybe Algo IMA?

Where did the idea come from?   I presume it has some history or reference for it?

**Comment by jmcameron** [comment]
I suggest we just call it "Default Algorithm"
