### ISSUE TITLE
Report on inventory (purchase) prices

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5519]
Inspired by https://github.com/IMA-WorldHealth/bhima/issues/5401#issuecomment-783668386, it would be nice to have a report that shows the historical purchase price for medication.  For example, for Quinine 500mg, it would be nice to show each instance in which is was "purchased" or entered into the inventory from either a donation, a purchase, or an integration.

The following information would be interesting to know:
  1. What date was it entered?
  2. Who entered it?
  2. What was the reason? (purchase, integration, donation)
  3. How many items?
  4. What was the unit cost?
  4. How did this affect the average cost? (https://github.com/IMA-WorldHealth/bhima/issues/5401)
  5. What was the total value of the movement?

Finally, in summary: what was the min price and what was the max price?

This would give a lot more transparency to the purchasing process and the value of stock.

**Comment by jmcameron** [comment]
It seems like this type of report would be useful for stock exits as well!
