### ISSUE TITLE
Add barcode scanning for stock exits

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5576]
We should add the ability to scan barcodes to set up the stock exit form.  Basically, instead of going from "inventory -> lot", you should be able to simply click a button that says "scan an item" and scan the lot number to look up the inventory item and lot number.  There would be an option to "scan another", like we do for cash payments.

This would mean we would need to generate lot barcodes like we do for other records.  I propose we prefix them with "LT".  We would allow users to print out the lot barcodes from someplace, such as a report (lots in the depot) or the lot registry.

This would change the burden of correctness from the stock exit to the stock entry.  The only thing you would need to get right during the exit is the quantity, the destination, and the date.

**Comment by jmcameron** [comment]
Closed in PR https://github.com/IMA-WorldHealth/bhima/pull/6070
