### ISSUE TITLE
Add ability to delete purchase orders

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5584]
We should have the ability to delete unconfirmed and cancelled purchase orders.

**Comment by jniles** [comment]
We have this ability - I just worked on it in https://github.com/IMA-WorldHealth/bhima/pull/5513.  Or were you thinking of something different?

**Comment by jmcameron** [comment]
This does not seem to work for me on master.  I create a PO and do not see the delete option in the action menu:

![image](https://user-images.githubusercontent.com/62145/116146361-43090500-a693-11eb-9f4d-fafd1ea45bf8.png)

**Comment by jniles** [comment]
This is a bug.  I probably forgot to add the `bhConstants` import to the registry.
