### ISSUE TITLE
Patient Registry problem sorting by name

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5612]
In Hospital > Patient Registry, sorting by the name field does not seem to work correctly.

**Comment by jniles** [comment]
What exactly was the issue?  I just checked the latest release and couldn't reproduce anything strange.

**Comment by jmcameron** [comment]
> What exactly was the issue? I just checked the latest release and couldn't reproduce anything strange.

That is strange.  I works fine with Vanga.   But I definitely saw some sorting issues with IMCK.  Some of the names were completely out of order (after clicking on the "Name" header to sort on it).  And it was not just a upper/lower case issue.

**Comment by jmcameron** [comment]
> 
> 
> > What exactly was the issue? I just checked the latest release and couldn't reproduce anything strange.
> 
> That is strange. I works fine with Vanga. But I definitely saw some sorting issues with IMCK. Some of the names were completely out of order (after clicking on the "Name" header to sort on it). And it was not just a upper/lower case issue.

I just tried it again with IMCK and it seems to work fine. I don't know what happened before.  I'm closing this issue.
