### ISSUE TITLE
Use of 'origin_id' in Voucher table as a reference to the voucher type

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#562]
For purposes of categorizing slips, we have the concept of voucher type. Do this for each transaction made with the voucher Module we must select the type of voucher (in accordance with the main body modules 1.X).

Since we do not have a table to store all types of vouchers, we use an array in Javascript. But still, how to keep the reference the type of voucher in the database.

In this issue, we propose adding the column 'origin_id' in table 'Voucher', this column will contain the reference to the type of voucher selected.

**Comment by jniles** [comment]
Aha, now I understand what `origin_id` is.  Since it's a voucher type, why not call the column `type` or `type_id`, depending on if it will store `TEXT` or an `INT`?

Otherwise, I am fine with this proposal and would like to see it implemented.

**Comment by jniles** [comment]
Closed in #561.
