### ISSUE TITLE
Design a state-driven form submit button

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#57]
One major difficulty that bhima has faced is users double-clicking the submit button.  This results in multiple form submissions.  This proposal is for a submit button that has state so that it is disabled and shows a loading indication when submitting when submitting, and behaves like a regular button at all other times.  The idea would be something like this:
**Ready State**
![buttonreadystate](https://cloud.githubusercontent.com/assets/896472/12714536/ab31b68c-c8d5-11e5-82ef-94611a1af01a.png)
**Loading State**
![buttonloadingstate](https://cloud.githubusercontent.com/assets/896472/12714537/ab3876b6-c8d5-11e5-9d1f-83eab868ecb5.png)

When loading, the button shows a loading indicator and disables itself.  When not loading it is a regular button.  This button in the HTML might look like this:

``` html
<button submit-button="Ctrl.loadingState" class="btn btn-primary" ng-click="Ctrl.submit()" type="submit"></button>
```

**Comment by DedrickEnc** [comment]
This is the good time to start with this style because we are rewriting the application.
