### ISSUE TITLE
If a medicine has only expired stock, we should consider it as "stock out"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5706]
@lomamech and I had an interesting discussion this morning.  If a medicine is expired, and we have no lots in stock, we should consider that as "out of stock" of that medicine.  Since the medicine cannot be used, it is effectively that in practice.  It seems certain health centers are masking their out-of-stock status by keeping expired medicine on the books, which it should really be removed.

@mbayopanda @jmcameron what do you think?

**Comment by jmcameron** [comment]
This sounds good to me.   But what will actually cause them to remove the expired stock from the shelves and is this a potential source of abuse (using/selling expired stock)?

**Comment by jniles** [comment]
Hopefully, their hierarchy.  People seem to treat out-of-stock much more strictly than stock expiry.  So, if we just make it painfully obvious that the expired medication doesn't count, they will hopefully be encouraged to get in-date medications to give to their patients.

**Comment by lomamech** [comment]
I am thinking, how to resolve this issue, I have the following idea
- Have a usable quantity column, and that we can use this value as the quantity in stock
- The other idea is that the PV of stock loss, be automatically created by BHIMA and that we have a register similar to the movement of stock which will keep all of the automatic stock losses.

![image](https://user-images.githubusercontent.com/8035588/123394242-d2993a00-d596-11eb-90be-99d8f24f4f2c.png)

**Comment by lomamech** [comment]
@jniles @mbayopanda  @jmcameron  How do you find these ideas

**Comment by jniles** [comment]
I don't like the idea of having a automatic PVs generated by BHIMA.  There is a good chance that the date on the medicine is wrong, and the users can just correct it.

I'm okay with doing a new column with "usable quantity" in it.  I think that should be the first approach, and we can make it better with more PRs.

**Comment by lomamech** [comment]
In this case I will start with the first proposal, but we will invite the stock manager to remove the stock by loss and to archive the documents
