### ISSUE TITLE
Editing purchase orders does not save the modifed price

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5716]
When we modify a purchase order, the old unit price that we modified does not get restored.

**Comment by mbayopanda** [comment]
@jniles how can I reproduce the issue? because with the `master` branch I do know how to reproduce the issue

**Comment by jniles** [comment]
Yeah, I also have been unable to reproduce it, but I haven't yet tried everything.  It may have been my imagination.  I am going to keep this open a little while longer until I can systematically test all the different cases.

**Comment by jniles** [comment]
So, the issue was a race condition.  You can observe it by:

- create a purchase order with a new unit_cost
- putting the network in slow motion mode (2G/3G)
- the inventory will take a lot longer to load and observing that when it loads, the unit_price will be reverted to the inventory unit_price.

I've fixed the issue by simply waiting to apply the edits after the inventory has already loaded.
