### ISSUE TITLE
Modifying a purchase order doesn't create new purchase_item

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5736]
Our feature to edit purchase orders doesn't seem to create new purchase_items.  The vanga team attempted to add purchase items later to the order and this operation did not work.  We should also ensure that deleting purchase order items works as expected and removes the individual line items.

**Comment by jmcameron** [comment]
While we are doing this, we should modify the purhcase order create/edit form to not display a [Clear] button when editing, but instead show a [Cancel] button.

**Comment by jniles** [comment]
Good suggestion @jmcameron
