### ISSUE TITLE
Bug in stock exit

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5786]
Try this:
- Use IMCK db
- Do stock exit to Patient [PA.PAX.8989] Anasthasie Ntumba Ndaye
- Add stock 110010 - multivitamine sirop 100 ml
- Select only available lot:  MUT166
- Notice it is expired and yet we could select it AND that it is accepted as a valid stock item (green check mark on the left).  This should be prevented!
- See:

![image](https://user-images.githubusercontent.com/62145/125063683-ae198380-e0a7-11eb-8bcf-daf86dfb5354.png)

**Comment by jniles** [comment]
Did this get closed in #5790?

**Comment by jniles** [comment]
Can no longer reproduce on master.
