### ISSUE TITLE
Display inventory label in the stock exit typeahead

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5789]
This issue is about to set back the inventory label in the typeahead when defining stock to exit in the code column.

Actually we have the lot number which is displayed 

![image](https://user-images.githubusercontent.com/5445251/125460769-6dcd24d6-f915-4f2c-9f59-2031ee6730c9.png)

![image](https://user-images.githubusercontent.com/5445251/125460844-5a8b5650-53f3-4e0a-924a-0421563d0f79.png)

For a an intuitive user experience we can set back the inventory label.

**Comment by jniles** [comment]
@mbayopanda did this get fixed?

**Comment by jniles** [comment]
It looks like this did get fixed:


![image](https://user-images.githubusercontent.com/896472/128691443-fc71f16e-6897-4244-9957-2c51d84bd2f6.png)
