### ISSUE TITLE
Edit date component

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#58]
Directive to display a read only date that can enter a discrete manual update state to allow the date to be changed only if required. 

This pattern has been used in a number of places and it would be good to standardise/ test it. 
- Aux Cash 
- Patient Registration 
- Patient Invoices 

The component would have to states 
- Set - Date is read-only; pressing the 'Edit' button will allow the date to be changed
- Update - It should be possible for the date to accept minimum and maximum values and report errors accordingly - A submit button should be pressed to return to the 'Set' state (required for submitting forms)

![Patient Edit Component](http://i.imgur.com/Pnw3tzf.png)

Along with this issue https://github.com/IMA-WorldHealth/bhima-2.X/issues/57 there are a number of components we used in many places in BHIMA that should be well researched, proposed and implemented.

**Comment by jniles** [comment]
This would be very useful.  I'd be willing to implement a prototype candidate in the next couple of days, unless someone else is interested.

**Comment by jniles** [comment]
Proposed feature: warn the user if the date in the future.  It might look like this:
![warndateinfuture](https://cloud.githubusercontent.com/assets/896472/12749237/94f1a082-c9af-11e5-8701-731fc9174a1e.png)

**Comment by jniles** [comment]
The component signature (what we write in the HTML) should like something like this:

``` html
<bh-edit-date date="Ctrl.model" on-change="callback()"></bh-edit-date>
```

The date should be two-way bound to the parent controller, so that "Ctrl.model" changes when the date changes.  It should also support an "on-change" callback that fires when the user presses "set" to set the date.
