### ISSUE TITLE
Sorting by expiration date in Duplicate Lots Registry doesn't work

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5807]
The date sort in the duplicate lots registry ui-grid doesn't work.  As an example:

![image](https://user-images.githubusercontent.com/896472/127358073-a56e1567-83d2-437c-b74a-d32876fd50c1.png)

**Comment by jniles** [comment]
@lomamech can you work on this?

**Comment by lomamech** [comment]
@jniles I cannot reproduce the error
![image](https://user-images.githubusercontent.com/8035588/128163738-24a05ee4-72e1-460f-a6c4-f6c67ca67d9a.png)

![image](https://user-images.githubusercontent.com/8035588/128163876-5d153393-ead4-4de2-bb82-1b8b24724b90.png)

**Comment by jniles** [comment]
Duplicate lots registry, not the lots in stock registry.  :+1:
