### ISSUE TITLE
Bug in the purchase order analysis report

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5817]
This issue is about a bug in the purchase order analysis report (Analyse de commande d'achat):

![image](https://user-images.githubusercontent.com/5445251/128016951-7346d4d0-c259-4f2f-8ab4-fd9b8c2868ae.png)

**Comment by jniles** [comment]
Is this different from  https://github.com/IMA-WorldHealth/bhima/issues/5429 ?

**Comment by mbayopanda** [comment]
Oh... No, it's not different.

**Comment by jniles** [comment]
Closing in favor of #5429.
