### ISSUE TITLE
Not null constraint for VARCHAR allows empty string

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5842]
This issue is about the fact that with MySQL8 our NOT NULL constraint on VARCHAR columns allows empty string.

There is an integration test for depot, which passes instead of failing on master.

`test\integration\depots.js` on line 90.

**Comment by jniles** [comment]
Sounds like we have a test that isn't strict enough - the tests seem to pass on master!

https://ima-worldhealth.semaphoreci.com/workflows/4bdce495-5971-49e8-a2ae-949fca9697ff

**Comment by mbayopanda** [comment]
In local with MySQL8 : 
![image](https://user-images.githubusercontent.com/5445251/128839170-eded6c70-b326-4d72-9d81-ce1c689e8274.png)

**Comment by jniles** [comment]
Are you sure your SQL mode is set correctly?

```
 sql-mode = "STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION"
```

**Comment by mbayopanda** [comment]
Thanks @jniles
