### ISSUE TITLE
Improvements to the System Usage Statistics Report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5848]
Inspired by https://github.com/IMA-WorldHealth/bhima/pull/5846, we could make the following improvements to the System Usage Statistics report:

1. Include a column number of stock movements
2. Include a column for the number of active users
3. Add totals at the foot of the report

![image](https://user-images.githubusercontent.com/896472/129200546-6b1225ff-de04-48bd-8cf5-a35d7a07d945.png)

**Comment by jmcameron** [comment]
I think we could go even further by including some other high-level statistics such as:
- Total $ paid by patients
- Value of stock used in the day
- Number of admissions, surgeries, births, deaths, discharge, etc.

Also, this report is for a single day.  I think there could be value in letting the user specify a date range (like the date range choice in many stock "Search" menus.   I would think this report would be useful for a week or a month, or even for arbitrary date ranges.

**Comment by jniles** [comment]
@jmcameron I think you may be looking for a different report.  The goal of this report was to let a hospital administrator see if people were showing up to work on time, and if there was a time period where no one was working.
