### ISSUE TITLE
(recommendation) Do not paginate the Posting Journal for 2.x

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#586]
Our current posting journal implementation has a Posting Journal that is paginated so that records can appear on multiple pages to try and keep page sizes and rendering small.  This introduces UI and programmatic complications when considering other features like printing, filtering, and sorting.

I propose we remove this functionality until it can be properly designed with all other features in mind.  Ideally, we should complete the following features:
1. Printing
2. Filtering
3. Sorting
4. Trial Balance
5. Editing Transactions

Afterwards, we can reintroduce the pagination feature, taking care to make sure it interacts properly with each implemented feature.

@IMA-WorldHealth/local-contributors What do you think?

**Comment by sfount** [comment]
I agree that pagination should come last :+1:. I think that unless we know the scope of the other features we will not be able to anticipate the requirements for pagination (filtering/ totaling on transactions etc.)
