### ISSUE TITLE
Proposal: Potentially rename English "Fee Centers" to something more standard

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5861]
As discussed in https://github.com/IMA-WorldHealth/bhima/pull/5860#issuecomment-900271911 and https://github.com/IMA-WorldHealth/bhima/pull/5860#issuecomment-900282193, the name "Fee Centers" doesn't appear in any of the documentation Larry has provided.  Since he is the ultimate client, we should find terminology that he is familiar with and that is standard across the industry, particularly if his goal is to sell the BHIMA product.

**Comment by jmcameron** [comment]
I see the (English) terminology "Profit Center".   I think we should consider renaming these to "Revenue Center".   You don't really know if there is a profit until you do a larger-scale analysis, so "profit" may not be the best term to use in this context.

**Comment by jniles** [comment]
I agree with renaming profit -> revenue.  That is a much more appropriate term.
