### ISSUE TITLE
Use step-down to allocate costs from one cost center onto all others

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5882]
This issue follows https://github.com/IMA-WorldHealth/bhima/issues/5879 and https://github.com/IMA-WorldHealth/bhima/issues/5881 logically.

Assuming we have a series of cost centers classified as "principal" or "revenue-generating", and assuming that we have the `cost_center_aggregate` table, we can use the step-down method to allocate costs from auxiliary cost centers onto revenue generating centers.  The goal is to end up with every cost allocated to a revenue generating center.

To do this, each cost center must have an allocation method configured for it (https://github.com/IMA-WorldHealth/bhima/issues/5879).  This means that a cost center must be assigned to a cost allocation method.   For example:

Cost  Center | Allocation Method
-- | --
Taxes | Equality
Electricity | Working Hours
Payroll | Number of Employees
Cleaning | Square Footage
Maintenance | Working Hours
Security | Working Hours

These allocation methods could be done permanently or configured per analysis.  If we allow users to change them while during the analysis, we will need to print what the allocation methods were on the report for each cost center.

We also need the costs associated with each cost center.  Using https://github.com/IMA-WorldHealth/bhima/issues/5881, this is easy.  All we need to do is directly pull from this table.

The user will choose the order in which to "step down" allocating costs.  Only the auxiliary centers (not principal) will be allocated, and _every center's cost will be allocated to every other cost center_.  Once the cost is allocated, we remove that center from the analysis.  We repeat the same step down until we are left with only the principal centers.

**Comment by jmcameron** [comment]
Partially completed in PRs https://github.com/IMA-WorldHealth/bhima/pull/5894 and https://github.com/IMA-WorldHealth/bhima/pull/5905.

**Comment by jniles** [comment]
Can we say this is largely completed?

**Comment by jmcameron** [comment]
That may be a bit optimistic at this point...

**Comment by jmcameron** [comment]
Mostly done, but still parts in work.

**Comment by jniles** [comment]
I'm marking this as completed.
