### ISSUE TITLE
Create a default "lost medicine" cost center for automatically allocating costs

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5883]
The vision of BHIMA is automate as much of cost center analysis as possible.  If an account is directly assigned to a cost center, then we can just slot in the cost center into the correct column of the general_ledger/posting_journal (#5880).

There are three other locations we can really automate the tagging of cost centers: invoicing, stock consumption, and payroll.  In all three, BHIMA puts an interface on top of the raw transactions, allowing us to automatically tag the associated centers _directly_ as we create the transactions, when they otherwise would be considered _indirect costs_.  This is the power of using BHIMA.

For invoicing, the user must select a service.  The service will map to a cost center, so we have automated the tagging of cost centers for invoicing.  So, if there is an account being billed that is not tied to a particular cost center - such as `hospitalisation` or `Profit Divers` or another generic income account - we can directly associate the costs onto the service in the invoice.  So, this automation is simple.

For stock consumption, we can find the associated cost center in three ways:

1. The stock consumption must be tied to a patient who must be invoiced and the invoice will provide us the service.  The service has the cost center in it.
2. The stock consumption will be directly tied to a service.  The service will have the cost center in it.
3. The stock consumption is a loss due to expiry or theft.  _What is the cost center here?_

For payroll, workers that worked in a particular service which will contain the cost center.  Each employee is assigned a service, so this is straightforward.

------

Given this, I propose we create a generic "lost medicine" cost center that can be hit/tagged when we exit stock due to loss.  We can build this into every default BHIMA database to make sure that we are properly accounting for it.

**Comment by jmcameron** [comment]
I think Issue https://github.com/IMA-WorldHealth/bhima/issues/5856 should be done first (Ensure automatic cost allocation happens during stock consumption).

**Comment by jniles** [comment]
It's likely a chicken and egg problem.  What cost center will you automatically assign on lost medicines?

It can be done first, just ignoring the "lost" stock exits.  Then we'll need to create a default cost center, and then go back and create the automatically assigned "lost" center.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/5941.
