### ISSUE TITLE
Ensure models/test/data is up to date with latest standards

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#589]
Our test dataset was created before a lot of the functionality was specified or possible in 2.x. 

At the moment there are many cases where the data does not line up, for example there are two invoices but only one recorded in the posting journal. The patient who has been invoiced is subscribed to billing services and subsidies but there are not factored into the test dataset. 

This behaviour can be very confusing when testing additional functionality. 

`test/data.sql` should be updated to make sure that it could have been created by the system itself. This should be easier now with a lot of the functionality implemented.

**Comment by jniles** [comment]
Good point.  We can do this analysis and finish this up pretty quickly.
