### ISSUE TITLE
Stock Consumption Schedule rendering can sometimes get out of whack

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5897]
Here is an example at Vanga:
![image](https://user-images.githubusercontent.com/896472/131669444-c00b91f3-c17b-4ffd-a6ab-7e750609f0d3.png)

There are two issues here:

1. The top table off the modal to the right.
2. The bottom calendar doesn't reflect that actual expiry date.

**Comment by jmcameron** [comment]
I think this is because the red part has wrapped to the next line.  So something is off on the CSS rules and/or the width calculations.

**Comment by jmcameron** [comment]
is the modal 'medium' size different here for some reason?

**Comment by jniles** [comment]
I do not believe so.  I've seen something similar before - it could be that the screen resized and that through the calculations off?  Not sure.
