### ISSUE TITLE
"Fee Centers" registry should be ordered alphabetically

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5899]
The default ordering seems to be the order in which the database was written:

![image](https://user-images.githubusercontent.com/896472/131836756-3bb4befd-97af-4143-bd1e-25cf00d35939.png)

**Comment by jmcameron** [comment]
I'm working on a release and I'll include fix for this as part of it.

**Comment by jmcameron** [comment]
@jniles I think this has been done.  The current ordering in the Cost Center registry is 

     ORDER BY f.is_principal DESC, f.label ASC

This produces a list like this:
![image](https://user-images.githubusercontent.com/62145/133746261-482221ab-9eb3-4b73-9aea-c0d97da415df.png)

The principal centers are listed first (in alphabetical order) and then the auxiliary centers are listed afterwards (in alphabetical order)

Note that the user can click on the top of the label column to override the default ordering and sort alphabetically (ignoring the distinction between principal and auxiliary cost centers.

**Comment by jniles** [comment]
Alright, closing this until we can reproduce.
