### ISSUE TITLE
Report on stock lost during transit

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#5915]
In a meeting with Dr. Susan, she asked me:

> Who is looking at the difference in the BL & PV de reception in the health zone dataset?  Is it flagged?

I don't think we have a comprehensive report on this, and we really need one.  It would make BHIMA much more marketable to use on a health zone level if we had this level of reporting.

**Comment by jmcameron** [comment]
@jniles Could you describe the desired report in a little more detail?

**Comment by jniles** [comment]
Yes.  Below is the image of a completed stock transfer - what was sent out, what was received, and the difference:

![image](https://user-images.githubusercontent.com/896472/133760639-af62f910-654e-4989-bfba-da59265a5300.png)

It's all zeros here, which is good.  That is what we expect.  But if it wasn't 0, we wouldn't have a good way to find out about it.  We need this surfaced in a report somewhere so that we can know when stock leaves the warehouse but never arrives at the destination.

**Comment by jmcameron** [comment]
> Yes. Below is the image of a completed stock transfer - what was sent out, what was received, and the difference:

@jniles How was this table generated?

**Comment by jniles** [comment]
Here is the handlebars: https://github.com/IMA-WorldHealth/bhima/blob/502e8c9ecc00428f35c99b90a2097c9baa69f06f/server/controllers/stock/reports/stock_entry_depot.receipt.handlebars

And here is the javascript controller: https://github.com/IMA-WorldHealth/bhima/blob/502e8c9ecc00428f35c99b90a2097c9baa69f06f/server/controllers/stock/reports/stock/entry_depot_receipt.js

**Comment by jmcameron** [comment]
> Here is the handlebars: https://github.com/IMA-WorldHealth/bhima/blob/502e8c9ecc00428f35c99b90a2097c9baa69f06f/server/controllers/stock/reports/stock_entry_depot.receipt.handlebars
> 
> And here is the javascript controller: https://github.com/IMA-WorldHealth/bhima/blob/502e8c9ecc00428f35c99b90a2097c9baa69f06f/server/controllers/stock/reports/stock/entry_depot_receipt.js

Excellent, thanks!  I did find those but I could not figure out how to invoke them from the Bhima menus.

**Comment by jniles** [comment]
Yeah, these are stock entry receipts.  Just exit stock to a depot and then enter it into the depot.

**Comment by jmcameron** [comment]
Right!  Got it working; thanks.  With Bhima_test, I actually need to do these inter-depot transfers to see the report.

**Comment by jmcameron** [comment]
I've worked out the appropriate SQL query for this:

    SELECT
      dest.uuid, 
      dest.date,
      dest.description,
      dest.period_id,
      dd.text AS destDepot,
      od.text AS srcDepot,
      dest.quantity AS RecdQuantity,
      ex.quantity AS sentQuantity,
      IFNULL((ex.quantity - dest.quantity), 0) AS quantity_difference,
      dest.document_uuid,
      i.text AS inv_name,
      l.label AS lot_label,
      dest.unit_cost,
      (dest.quantity * dest.unit_cost) AS total_cost
    FROM stock_movement dest
    JOIN depot dd ON dd.uuid = dest.depot_uuid
    JOIN depot od ON od.uuid = dest.entity_uuid
    JOIN lot l ON l.uuid = dest.lot_uuid
    JOIN inventory i ON i.uuid = l.inventory_uuid
    JOIN (
      SELECT m.document_uuid, m.lot_uuid, m.quantity, m.unit_cost
      FROM stock_movement m
      WHERE m.is_exit = 1 AND m.flux_id = 8
    ) ex ON ex.document_uuid = dest.document_uuid AND ex.lot_uuid = dest.lot_uuid
    WHERE dest.flux_id = 2
    ORDER BY dest.date, destDepot

Where the flux_id values of 2 and 8 correspond to FROM_OTHER_DEPOT and TO_OTHER_DEPOT respectively.  Note that I'm ignoring is_exit since flux_id = 2 is always entry (is_exit = 0) and flux_id = 8 is always exit (is_exit = 1).

For bhima_test, after doing a  few stock transfers between depots, this is the result of the query:

    +------------------------------------+---------------------+-----------------+-----------+------------------+-----------------+--------------+--------------+---------------------+------------+-----------+------------+
    | uuid                               | date                | description     | period_id | destDepot        | srcDepot        | RecdQuantity | sentQuantity | quantity_difference | lot_label  | unit_cost | total_cost |
    +------------------------------------+---------------------+-----------------+-----------+------------------+-----------------+--------------+--------------+---------------------+------------+-----------+------------+
    | 0xD903A292AAB0475981A37377CB89A4CA | 2021-09-21 09:38:45 | Stock Reception |    202109 | Depot Secondaire | Depot Principal |          198 |          200 |                   2 | New-lot    |    0.0500 |     9.9000 |
    | 0x764AE9760EB54B79BAFF3C57FC560DAC | 2021-09-21 10:10:38 | Stock Reception |    202109 | Depot Secondaire | Depot Principal |          499 |          500 |                   1 | New-lot    |    0.0500 |    24.9500 |
    | 0xA9598E7A70F94BE1894A52F3F94E5063 | 2021-09-21 10:10:38 | Stock Reception |    202109 | Depot Secondaire | Depot Principal |            3 |            3 |                   0 | QUININE-C  |    2.0000 |     6.0000 |
    | 0x9E6BE705472D4CACA19F395D11814ABC | 2021-09-21 10:11:34 | Stock Reception |    202109 | Depot Secondaire | Depot Principal |           75 |           75 |                   0 | VITAMINE-A |    1.2000 |    90.0000 |
    +------------------------------------+---------------------+-----------------+-----------+------------------+-----------------+--------------+--------------+---------------------+------------+-----------+------------+
    4 rows in set (0.00 sec)
