### ISSUE TITLE
(design) Single Page Enterprise/Project Configuration

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#592]
This proposal creates a unified design for the enterprise and project management pages.  It complements #277.

**Proposal**
1. Create one page to manage enterprises and projects instead of two
2. Remove unused/confusing options from the project configuration:
   1. `locked` should be redesigned if it is ever used.
   2. `health zone` should be introduced when needed.
3. Do not allow any user to delete an enterprise if it is used.
4. Remove option to create multiple enterprises.

**User Interface**
See the below mockups that take inspiration from the Patient Edit page.
![enterprise configuration](https://cloud.githubusercontent.com/assets/896472/16980503/30b84d8a-4e5e-11e6-8506-f79526d1af72.png)
_Fig 1: Unified page for Enterprise Configuration_

![enterprise configuration edit project](https://cloud.githubusercontent.com/assets/896472/16980502/2f05a8a2-4e5e-11e6-8108-543f6fa989d9.png)
_Fig 2: Editing a Project in a Modal_

**Other Considerations**
1. This page should be available to super users at `/#/enterprises`.
2. The enterprise currency is **not editable**.  A user will have to create a new enterprise to have a different set of books.
3. The page should switch between multiple enterprises if they exist via a dropdown, but not allow creating a new one.

**Comment by sfount** [comment]
This design looks good to me. It will reduce the code from a lot of configuration modules. 
- Should we allow you to edit the abbreviation as shown here? This might have implications on the transactions in the posting journal that I haven't thought through. If anything it might be confusing. 
- Are exchange rate settings part of working with an enterprise? Should they be included when this module is implemented?

**Comment by jniles** [comment]
@sfount, thanks for the feedback!
1. Hmm... I had not thought through the implications of changing the abbreviation.  So far, the abbreviation has made the UI pretty - human readable identifiers are constructed on the fly from the abbreviation + id.  Changing the abbreviation shouldn't affect bhima's working at all, but may be confusing to have a patient card suddenly begin reading "TPB" instead of "TPA", if someone makes that edit.  I think we can allow it for now and if we discover any issues in testing, we make the input `readonly`.
2. Yes, I think we could easily attach exchange rates here.  Do you think we should put a panel in (below projects?) that will deal with the exchange rate?

**Comment by mbayopanda** [comment]
Hi @jniles and @sfount 

This design is good also to me, and i have some change to propose to you : 
- Put a delete enterprise button in the enterprise panel, and remove the `Danger Zone`, the deletion will be made by confirm text box (#348 issue)

![enterprise](https://cloud.githubusercontent.com/assets/5445251/17268781/eb4b667c-55e9-11e6-9f88-96b9e33a25f4.png)

Sorry, I dont use balsamiq for mockup but i can always update the UI according our decision

For the exchange rate, if we choose to put it here how can we deal with users who has only permission for exchange rate and not for enterprise data or project data.

**Comment by jniles** [comment]
@mbayopanda, thank you for the feedback!

After thinking about it, we are not supporting creating an enterprise - why should we support deleting one?  Let's just remove the delete button altogether.

Concerning Exchange Rate, @sfount and I have talked about this a little bit.  On this page, we could put "set an exchange rate", as well as the last three rates set (like the patient checkin page).  The exchange rate could be set from a modal that can be called from anywhere.

The home page could also let you set an exchange rate.  This was a user does not have to be a super user to set the exchange rate.  If necessary, we can also put links on the cash window or journal voucher pages.

What do you think?
