### ISSUE TITLE
Treat units for predefined cost center allocation basis items as translation tokens

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#5951]
Currently, the value of units of allocation basis items (table cost_center_allocation_basis) is not translated.  However with predefined basis items, there is no reason not to provide translations for items that have appropriate units.

So the item stored in the database for 'units' for the predefined items should be treated as a translation token for predefined bases and taken literally for non-predfined tokens (like the `name` field is treated.

**Comment by jniles** [comment]
@jmcameron did this get taken care of?

**Comment by jmcameron** [comment]
Yes!
