### ISSUE TITLE
Add ability to change the order of step-down cost allocation steps

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#5953]
Provide a way to edit the order of the steps for auxiliary cost centers.
Ideally this would be some type of drag-and-drop interface, but could be some type of direct editing of the step order numbers.

**Comment by jniles** [comment]
@jmcameron, did this get done?

**Comment by jmcameron** [comment]
Yes, this was completed in PR https://github.com/IMA-WorldHealth/bhima/pull/6003.
