### ISSUE TITLE
Bug: Role management add button is broken

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#5958]
The "add role" button is permanently broken due to a bug found by @jeremielodi .

The `has-permission` property is incorrectly set.  It needs to be map to something in the current scope, but refers to the ui-grid's scope which it doesn't actually have access to.  See below:

https://github.com/IMA-WorldHealth/bhima/blob/3b3c4d0a55a273dba06d4119aed8200a233b9781/client/src/modules/roles/roles.html#L8

**Comment by jeremielodi** [comment]
It's seems that I don't have permission to push to this repository. To solve this issue, just replace the line you highlighted by 
```<div class="toolbar" bh-has-permission="RolesCtrl.bhConstants.actions.CAN_EDIT_ROLES">```

**Comment by jniles** [comment]
You can definitely open a PR ;)

**Comment by jeremielodi** [comment]
I don't think it possible yet. It still reject.
![git_access_bhima](https://user-images.githubusercontent.com/25838121/135467243-7d6c8c47-7794-40a3-910b-6e10ed06fa59.PNG)

**Comment by jniles** [comment]
Yeah, you'd have to fork it first, and then do a PR from your fork.  Otherwise, anyone could push code to this repository.
