### ISSUE TITLE
Add is_editable flag to cost_center_allocation_basis table

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#5964]
Since some of the cost center bases are calculated by the system (direct cost, number of employees), etc, it should not be possible to edit them.  

This is not the same as is_predefined.  'is_predefined' bases could be either computed by the system (not editable) or entered manually (editable),.

**Comment by jniles** [comment]
@jmcameron, I assume that because we don't want users to edit them, it also means that a user will not be able to create an uneditable cost center basis, right?  These are all system bases?

**Comment by jmcameron** [comment]
> @jmcameron, I assume that because we don't want users to edit them, it also means that a user will not be able to create an uneditable cost center basis, right? These are all system bases?

Actually, I'm not sure I want to do this yet.  In my current not-quite-PR-yet, I added a flag 'is_computable' to signal that the system knows how to compute the values.  However, I still (for now) leave it editable.   We need to think about whether editing system-general basis quantities makes sense.

**Comment by jniles** [comment]
Alrighty then.
