### ISSUE TITLE
Cost center aggregate table needs to distinguish costs and profits

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6023]
This issue is related to the fact that our `cost_center_aggregate` table aggregates all data from the general_ledger based on their `cost_center_id` and `principal_center_id` without considering if these data are for expenses or incomes.

Assume that we have a cost_center : Administration which have values for expense (Class 6) and incomes (Class 7), in the `cost_center_aggregate` table we put just together all these data.

The proposal is to have a way to distinguish expenses and incomes in the `cost_center_aggregate` table by adding maybe a new column for that.

**Comment by jniles** [comment]
Yeah, I noticed this as well.  I hope we can have as elegant a solution as just an extra column in the cost_center_aggregates table.  We'll need to then update the procedure that creates this table.

**Comment by jniles** [comment]
Closed in #6026.
