### ISSUE TITLE
Possible problem with the Bhima test data or journal registry display

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6038]
Try this: 

- Run Bhima with bhima_test
- Go to the journal registry (Finances > Journal)
- In the Search options, select the new "Account Type" and select "Income".  Note that you get the first display below
- Go back into the Search Options > Defaults > Show Full Transactions.  You should see the second display below

![image](https://user-images.githubusercontent.com/62145/137717516-6c5222b8-2bf3-4f62-b22c-edf3a02b4e88.png)

With full transaction details, everything seems okay, assuming "Income" means something different for the different accounts.
![image](https://user-images.githubusercontent.com/62145/137718013-72cec21f-3c52-4d95-abf4-d0f0941ecdc8.png)

It seems strange to me that the non-full-transactions view displays differently for TPA2 than the others.   Perhaps something different about the 57110011 account.    

And perhaps nothing is wrong at all.

**Comment by jniles** [comment]
@jmcameron I don't really understand this issue.  Do you remember what the concern was?

The screen captures look to me to be doing what it is supposed to.

**Comment by jmcameron** [comment]
Thx
