### ISSUE TITLE
Transpose the table of allocation bases in Cost Center Step Down Report

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6039]
In the cost center step down report, we have a table of allocation bases at the bottom.  It looks like this:
![image](https://user-images.githubusercontent.com/896472/137724799-3bd8237c-c6fb-4c5d-97ab-5435fb9db86b.png)

I propose we transpose the columns/rows here.  We will probably always have more cost centers than we do bases, and it is better to have this go vertically than horizontally.

We may also want to have that final table as an optional inclusion.  On the report configuration page, we can say "Include values of allocation bases" or something with a yes/no selection so that users can hide it if they don't need it.

**Comment by jmcameron** [comment]
👍

**Comment by jniles** [comment]
@jmcameron mind tackling this?

**Comment by jmcameron** [comment]
> @jmcameron mind tackling this?

Ok!
