### ISSUE TITLE
Add created_at to registry exports

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6061]
We had a request from the MD of Vanga who was trying to figure out what time people started work.  I pointed him to the record date, but these records are set by the computer - and some of the workers had computers that were in different timezones, so this made it hard.  I propose we export the `created_at` field in our Excel exports as well as the regular date to account for this.

**Comment by jmcameron** [comment]
What report needs to be updated for this?

**Comment by jniles** [comment]
The following registries:

1. Patient Registry
2. Invoice Registry
3. Cash Payments Registry
4. Stock Movements Registry
5. Voucher Registry
6. Purchase Order Registry
7. Requisitions Regsitry
5. Journal

**Comment by jniles** [comment]
I'll tackle this.

**Comment by jniles** [comment]
I'll tackle this.
