### ISSUE TITLE
Stock exit using barcode scanner

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6066]
This issue is about to add a way to fill the stock exit grid by reading barcodes.

The proposal is to have a modal in which you scan barcodes when you finish with the modal by submitting, the stock exit grid will be filled and you will have just to click submit.

The need is for fast entering data.

**Comment by jmcameron** [comment]
Based on discussions with @jniles 

- The barcodes will be unique IDs.   
- Each barcode will be pasted on a box
- During stock entry, the barcode will be used as the lot ID.  Every lot scanned in by barcode will be a new lot.  Minor adjustments will be necessary to the stock entry form to streamline entering expiration dates.
- During stock exit, the barcode will be used to look up the lot quickly

**Comment by mbayopanda** [comment]
> 
> 
> Based on discussions with @jniles
> 
>     * The barcodes will be unique IDs.
> 
>     * Each barcode will be pasted on a box
> 
>     * During stock entry, the barcode will be used as the lot ID.  Every lot scanned in by barcode will be a new lot.  Minor adjustments will be necessary to the stock entry form to streamline entering expiration dates.
> 
>     * During stock exit, the barcode will be used to look up the lot quickly

I comply with that
