### ISSUE TITLE
Implement Monthly Clients Report

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#6103]
It is a question of implementing a report which displays all the groups of debtors, their account balances at the beginning of the month, the debits and credits of their accounts and their balances at the end of the month.

**Comment by jniles** [comment]
I think this exists already for debtor groups.  Is that what you are looking for?

**Comment by jniles** [comment]
I believe this report already exists in either the Annual Clients Report or the Aged Debtors Report, so I have closed this issue.
