### ISSUE TITLE
Updates for the Aged Creditor Report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6167]
Finance > Report > Aged Creditor Report

**Suggestions**
- The font for the date range should be a little larger
- Add multi-currency support
-  The date range subtitle "Until The Period August 2021" should be reworded to something like: "FY 2021 through August 2021". Note that the titles on the report does not make it clear that the report is restricted to the selected fiscal year. Some reworking of the report title seems needed.

**Comment by jniles** [comment]
For your third point, if the previous fiscal year has been closed, it should include the previous year's balance as well, so it would truly be through the current date.  Perhaps a better idea might be to include a warning stating that if the previous fiscal year has _not_ been closed, you need to close it for the current balances to be correct?
