### ISSUE TITLE
Updates for the Aged Debtors Report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6168]
Finance > Report > Aged Debtors Report

Suggestions
- The currency should default to the enterprise currency
- The font for the date range should be a little larger on the report
- The date range subtitle "Until The Period August 2021" should be reworded to something like: "FY 2021 through August 2021". Note that the titles on the report does not make it clear that the report is restricted to the selected fiscal year. Some reworking of the report title seems needed.

**Comment by jniles** [comment]
This is the same comment about the aged creditors report.
