### ISSUE TITLE
(proposal) Replace `user.first` and `user.last` with user.display_name

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#617]
I propose that we replace the `user.first` and `user.last` names with `user.display_name` that will appear on reports.  This is much less confusing and gives the user control over the way the name is displayed (first, middle, last OR last, first, middle).

@IMA-WorldHealth/local-contributors what do you think?

**Comment by sfount** [comment]
I agree - this should also be uniform across all tables that we record a name (potentially with patients as an exception). 

For example, some different naming schemes we have currently: 

Employees - `employee.prenom` `employee.name` `employee.postnom`
Users - `user.first` `user.last` 
Suppliers - `supplier.name`
Patients - `patient.first_name` `patient.middle_name` `patient.last_name`

**Comment by jniles** [comment]
@sfount, thanks for the feedback.  Those are good observations - I think we could update most of these tables with `display_name` to lower confusion.  We can schedule this as a refactor due sometime.

**Comment by jniles** [comment]
@lomamech, could you work on this issue while waiting for a review on #669?

**Comment by jniles** [comment]
Closed in #676.
