### ISSUE TITLE
Updates for the Balance of Accounts report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6171]
Finance > Report > Balance of Accounts

**Suggestions**
- It seems to me that the "Include Closing Balances" option should have a default.
- What does the last row, marked "Total", represent?  If it is the closing balance, it should probably say that or at least have a label that is more descriptive than "Total"
- Add multi-currency support

**Comment by jmcameron** [comment]
@jniles Regarding the "Total" line.  Can you suggest a better term than "Total", eg, "Final Total" or "Total for Interval", etc?

And does multi-currency support still seem desirable?

**Comment by jniles** [comment]
@jmcameron, yes multicurrency is desirable for this report.
