### ISSUE TITLE
Updates for the Cashflow by Service report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6174]
Finance > Report > Cashflow by Service

**Suggestions**
- Make the font for the Cashbox on the report a little bigger
- Add multi-currency support
- In the examples I tried (with Vanga data), I only saw positive numbers.   For this report is "cashflow" only one direction?  If so, fine.  But if not, where are the negative values?
- The labeling of the last row (last 2 rows) of the report could be improved.

**Comment by jmcameron** [comment]
@jniles Should we add multi-currency support to this report since the cashboxes are for different currencies?  How should we handle that?

**Comment by jniles** [comment]
Yes and no.

No, we should stick to the currency of the cashbox.  So,  we should render the currency and it could be any currency, but we 
should never show anything other than the true transaction currency.

However... if we have a "summary" total part of the report, we could show that in different currencies though, with the exchange rate prominently displayed.

**Comment by jmcameron** [comment]
I took another look at this report and it already only shows the currency for the cashbox, so no fix is needed for that.

There is no separate summary section, just the last row (which is in the currency of the cashbox).  Until someone asks for it, I say do not add an additional summary in any other currency.

**Comment by jniles** [comment]
Sounds good.
