### ISSUE TITLE
Unify Profit and Loss Statement reports

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6181]
We currently have 3 Profit and Loss Statements reports under Finances > Report.  They seem to function the same other than different fiscal year/period selections.  These should be unified into one report where the selection of the fiscal year/periods/months is handled cleanly from one client-side interface.

**Comment by jniles** [comment]
I agree with this.

**Comment by jniles** [comment]
Closed by https://github.com/IMA-WorldHealth/bhima/pull/6653
