### ISSUE TITLE
Updates for the Recovery Capacity Report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6182]
Finance > Report > Recovery Capacity Report

**Suggestions**
- Increase the font size of the date range on the report
- Add multi-currency support
- If "Include Unposted Values" is set to "Yes", add a column indicating whether items are posted or not
- A summary would be useful at the bottom indicating % of interval where recover was above 70% (green), 60-70% (yellow), and less than 70% (red).
- A possible low-priority enhancement:  It is possible there is correlation between the days that have poor recovery capacity and the days of the week.   A possible formatting idea is show the day of the week for each row in the report too and possibly marking the rows that begin each week.  Obviously this should be investigated to see if there really is such a correlation before doing this!

**Comment by jniles** [comment]
@lomamech can you take a look at this one?

**Comment by lomamech** [comment]
@jniles  **If "Include Unposted Values" is set to "Yes", add a column indicating whether items are posted or not**  About this proposal, it will be necessary to discordally discharged the data posted by those who are not by date

**Comment by jmcameron** [comment]
> @jniles **If "Include Unposted Values" is set to "Yes", add a column indicating whether items are posted or not** About this proposal, it will be necessary to discordally discharged the data posted by those who are not by date

@lomamech I looked at this a bit last week.  It looks a bit complicated to figure out whether items are posted or not.  At a minimum, it would probably require a new query.  So I suggest skipping this for now.  But if you think it is a reasonable thing to do,. add a new issue for it.

**Comment by lomamech** [comment]
I dont very well understood this comment _A summary would be useful at the bottom indicating % of interval where recover was above 70% (green), 60-70% (yellow), and less than 70% (red)._

![image](https://user-images.githubusercontent.com/8035588/150999843-ad8ebc46-cf92-499e-8641-ce2b79dae2bb.png)

**Comment by jmcameron** [comment]
> I dont very well understood this comment _A summary would be useful at the bottom indicating % of interval where recover was above 70% (green), 60-70% (yellow), and less than 70% (red)._

The idea is to count the number of months that are in each category (red, yellow, green) and present a summary below the table.   This would be useful to a manager to see that the recovery capacity was 100% for 80% of the months, and (red) below 60% for 15% of the months.  This would help a manager evaluate the overall state of the recovery capacity during the time interval.

**Comment by lomamech** [comment]
> > I dont very well understood this comment _A summary would be useful at the bottom indicating % of interval where recover was above 70% (green), 60-70% (yellow), and less than 70% (red)._
> 
> The idea is to count the number of months that are in each category (red, yellow, green) and present a summary below the table. This would be useful to a manager to see that the recovery capacity was 100% for 80% of the months, and (red) below 60% for 15% of the months. This would help a manager evaluate the overall state of the recovery capacity during the time interval.

We either want to add an option to be able to see a collection summary report in for a fiscal year, with the interface it is possible to see the collection just by defining the date range

**Comment by jmcameron** [comment]
> > > I dont very well understood this comment _A summary would be useful at the bottom indicating % of interval where recover was above 70% (green), 60-70% (yellow), and less than 70% (red)._
> > 
> > 
> > The idea is to count the number of months that are in each category (red, yellow, green) and present a summary below the table. This would be useful to a manager to see that the recovery capacity was 100% for 80% of the months, and (red) below 60% for 15% of the months. This would help a manager evaluate the overall state of the recovery capacity during the time interval.
> 
> We either want to add an option to be able to see a collection summary report in for a fiscal year, with the interface it is possible to see the collection just by defining the date range

I'm not sure this is necessary.  It seems like seeing the overall statistics would be useful regardless of what the interval is.  Regarding an option to do a fiscal year, that is fine, but I think you still want the capability to select an arbitrary interval.  So the "Select FY" option could fill in the start and end periods.   Also being able to select an interval that starts in one FY and ends in another FY should be possible.

**Comment by lomamech** [comment]
> I'm not sure this is necessary. It seems like seeing the overall statistics would be useful regardless of what the interval is. Regarding an option to do a fiscal year, that is fine, but I think you still want the capability to select an arbitrary interval. So the "Select FY" option could fill in the start and end periods. Also being able to select an interval that starts in one FY and ends in another FY should be possible.

If for example I chose the interval of one week, what should we find in the summary

**Comment by jmcameron** [comment]
Ok. Make it optional, but default to true?
