### ISSUE TITLE
Bug in Cash Report getCashboxByAccountId function

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6191]
The getCashboxByAccountId function in server/controllers/finance/reports/cashReport/index.js has a bug.

If two cashboxes refer to the same account, the query in this function returns two values but db.one() is used, expecting only one.  THis should be fixed or handled more gracefully.   This is not an issue of Cashbox permissions.

To reproduce this error
- Use the Vanga dataset
- Go to the Finance > Report > Cash Report page
- Set the date interval, select either Petite Casse
- Try the preview and see the error.  
- If you try this with one of the Caisse Principal, it works

Looking the SQL database, I see:
```
mysql> select * from cash_box_account_currency;
+----+-------------+-------------+------------+---------------------+
| id | currency_id | cash_box_id | account_id | transfer_account_id |
+----+-------------+-------------+------------+---------------------+
|  1 |           1 |           1 |       3734 |                3735 |
|  2 |           2 |           1 |       3734 |                3735 |
|  3 |           1 |           2 |       3733 |                3749 |
|  4 |           2 |           2 |       3899 |                3749 |
+----+-------------+-------------+------------+---------------------+
4 rows in set (0.00 sec)

mysql> select * from cash_box;
+----+-------------------+------------+--------------+
| id | label             | project_id | is_auxiliary |
+----+-------------------+------------+--------------+
|  1 | Petite Caisse     |          1 |            1 |
|  2 | Caisse Principale |          1 |            0 |
+----+-------------------+------------+--------------+
2 rows in set (0.00 sec)
```
Clearly both Petite caisses refer to the same account so the LEFT join returns more than one row.  

Even if this is a configuration error in the Vanga cashbox setup, it should be handled gracefully by this function and useful error message produced.

**Comment by jniles** [comment]
This is a configuration issue at Vanga.  I wonder if we can reproduce it from a clean install - two cashboxes having the same account.  If so, I agree with the proposed fix.  If not, I propose we fix Vanga's database.
