### ISSUE TITLE
Patient standing component link to view stock movements no longer working

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6203]
We have received a report from the field that the link to view stock movements in the Patient Standing Component is no longer working.  Specifically, this one:

![image](https://user-images.githubusercontent.com/896472/146499244-f0008c8d-9a6b-45c1-990d-c8ff0f1565b1.png)

**Comment by jmcameron** [comment]
To reproduce this error
- Use a recent Vanga dataset
- In the patient registry, find patient PA.HEV.48787
- In their action menu, select "Patient Record" to see the display above.

**Comment by jmcameron** [comment]
I tried this with the current master (2021-12-20) and could not reproduce the error.

**Comment by jniles** [comment]
I'll try to reproduce when I get a look at it in production.  Thanks for the follow-up @jmcameron !

**Comment by jniles** [comment]
On the live Vanga server, I could not reproduce this.  Must have been a network issue or something at the time.
