### ISSUE TITLE
Create bhShowExchangeRate component to use in various reports

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6248]
This component would display the specified exchange rate in a smart way to make it easy to display in various reports when the enterprise currency is not used.   For an example of how this might work, see:
- [server/controllers/finance/reports/debtors/openDebtors.js](https://github.com/IMA-WorldHealth/bhima/blob/c6b605c8fc42c032be83174a44f5123b4c610bc5/server/controllers/finance/reports/debtors/openDebtors.js)
- [server/controllers/finance/reports/debtors/openDebtors.handlebars](https://github.com/IMA-WorldHealth/bhima/blob/c6b605c8fc42c032be83174a44f5123b4c610bc5/server/controllers/finance/reports/debtors/openDebtors.handlebars#L15)

This could also be extended to automatically display the WARN_CURRENCY message.

Ideally this would only require the currency ID (and an optional date) as inputs.

**Comment by jniles** [comment]
This would be a handlebars component, I assume?

**Comment by jmcameron** [comment]
> 

Uh... Right!?    Or perhaps a javascript function that returns an html blob which could be included in handlebars via a variable.

**Comment by jniles** [comment]
Gotcha!  I was confused at first.  This seems like a really good idea :+1:

**Comment by jmcameron** [comment]
> Uh... Right!? Or perhaps a javascript function that returns an html blob which could be included in handlebars via a variable.

We could also wrap it in an Angular component...
