### ISSUE TITLE
Display exchange rate in a user friendly format

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6250]
Actually the exchange rates in the home dashboard is display like this : 
![image](https://user-images.githubusercontent.com/5445251/148348906-842b76bd-09e0-4faa-b932-5319add88111.png)

This format is not user friendly, it can be better to have : 
1$ = 2000 Fc
1$ = 0.88 Euro

**Comment by mbayopanda** [comment]
@jeremielodi Could you take this.

**Comment by jeremielodi** [comment]
Yes I can.
