### ISSUE TITLE
Hack: Assets as Lots

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6287]
Let's do an experimental hack where we treat lots as assets.  This needs to be done ASAP to demo for a client.  To do this, we'll need to:

1. Set an `is_asset` flag on a `lot` table.
2. Add extra columns in a `lot_asset` table that we need for the demo.  It should have a `lot_uuid` as a column and be one-to-one.  This includes:

Manufacturer's   Serial # | Date Acquired (Delivery Date) | Origin | PO | Vendor | Quantity (# Units) | Local Currecny | USD Cost | Province | Localisation | Condition
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

3. Add a tag to the lot registry where we can filter on `is_asset`.
4. Add the ability to print out the barcode from the Lot Registry.

**Comment by lomamech** [comment]
I think is_asset should be linked to inventory and not to lot
