### ISSUE TITLE
Translate all XLSX headers in the stock registries

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6295]
We need to translate all the column headers of our XLSX exports.  The key registries to focus on are:

- [x] Stock Lots
- [ ] Stock Movements
- [ ] Articles in Stock
- [ ] Inventory

Here is how to get the XLSX export, for example:

![firefox_E8BUZfud4r](https://user-images.githubusercontent.com/896472/150082103-c2c1c691-2b18-453d-b221-19ceb84d3f6b.gif)

As you can see, things like `mvt_quantity` are not translated.  We should have these translated for the presentation.

**Comment by jniles** [comment]
@jmcameron could you tackle this?

**Comment by jmcameron** [comment]
Right!  I only did the Lots Registry.   I'll re-open the issue so I don't forget to do them.  If I have time, I'll work on them today.
