### ISSUE TITLE
Updating a depot destroys its location information

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6318]
As reported by @lomamech, when you update a depot, the location information is removed.  If the location information hasn't been touched, it should remain.

**Comment by jniles** [comment]
@lomamech, did this get fixed?

**Comment by jmcameron** [comment]
I was not able to duplicate this problem (bhima_test).   
@lomamech Please describe to how to reproduce this error.

**Comment by jniles** [comment]
Looks like it did get closed: https://github.com/IMA-WorldHealth/bhima/pull/6331
