### ISSUE TITLE
Asset Management - Inventory Changes

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6348]
Our goal is to use the current stock lots as assets.  In order to do this, we need to add some data to the 'inventory' table and add some related functionality.

### Database Changes
- add: ‘is_asset’ to inventory table (boolean, default to false)
- add: ‘external_reference_number’ to inventory table (TEXT, defaults to NULL).  
- To be used to refer to an external reference such as PROSANI inventory ID.
- add: ‘manufacturer_brand’ to inventory table (marque) field (TEXT, defaults to NULL)
- add: ‘manufacturer_model’ field to inventory table (TEXT, defaults to NULL)
- add: ‘equipment_type_id’ to inventory table (reference into an equipment type table)

**Create ‘equipment_type’ table including these fields:**
- id
- label (TEXT, raw string or i18n token)
- description (TEXT)
- is_predefined (if label is i18n token)

**Notes**
- ‘inventory group’ is not quite suitable for equipment types.
- The equipment_type ‘label’ field will be the i18n token for predefined entries but raw text in case entered manually at a site.  Note that something like this is done in the cost_center_allocation_basis table and related code.

### Interface changes
- In the Inventory registry, add the new fields to the grid.  They should be hidden by default.
- The form to edit inventory items should allow editing these new fields.
- Add a simple editor for the equipment_type table entries.  It should not be possible to edit the label for equipment_types with predefined tokens.
- Add the ability to export the inventory registry as XLSX.

**Comment by jniles** [comment]
I propose we rename `model` to `manufacturer_model` for clarity.  Otherwise, this proposal looks good to me.

I also advise that we do not limit the number of characters in some of these description tables.  Let's just keep them as TEXT.

**Comment by jmcameron** [comment]
> I propose we rename `model` to `manufacturer_model` for clarity. Otherwise, this proposal looks good to me.
> 
> I also advise that we do not limit the number of characters in some of these description tables. Let's just keep them as TEXT.

Done

**Comment by lomamech** [comment]
@jmcameron, there are already exists  **inventory_type** table  which can contain the necessary information found in the **equipment_type** table
````
DROP TABLE IF EXISTS `inventory_type`;
CREATE TABLE `inventory_type` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `inventory_type_1` (`text`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;
````
I propose to add the two new properties
- **_description_** (TEXT)
- **_is_predefined_** (if label is i18n token)

**Comment by jmcameron** [comment]
> @jmcameron, there are already exists **inventory_type** table which can contain the necessary information found in the **equipment_type** table
> 
> ```
> DROP TABLE IF EXISTS `inventory_type`;
> CREATE TABLE `inventory_type` (
>   `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
>   `text` VARCHAR(30) NOT NULL,
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `inventory_type_1` (`text`)
> ) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;
> ```
> 
> I propose to add the two new properties
> 
>     * **_description_** (TEXT)
> 
>     * **_is_predefined_** (if label is i18n token)

I am okay with this.  See my comments in https://github.com/IMA-WorldHealth/bhima/pull/6390#pullrequestreview-879015654.
