### ISSUE TITLE
Asset Management - New Asset Management scan support

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6350]
### Database Changes
- Create new ‘asset_scans’ table
  - uuid
  - asset_uuid (this is the **uuid** in lot table)
  - scanned by (person/name)
  - date (of scan)
  - location (depot)
  - condition_id (id in ‘equipment_condition’ table, similar sql, editing functions as the equipment_type table)
  - Purpose (defined in separate table: initial receipt, packing, in-transit, relocation, delivery, inventory)  Table should work like equipment_type table.
  - created_at (date)

**Question:** If we want the ability to have part of assets inventoried on one schedule and part on another schedule, we may need to add 'inventory_scan_due_date' to the lots table.   I was initially picturing a global "Asset inventory scan" deadline, but now I wonder it this does not need to be specific to each asset (lot).    I can picture an Assets Registry "Set next asset inventory scan date" function which updates only the assets displayed (using existing filters) which would then update the 'inventory_scan_due_date' for those assets.  We could add filters to the Assets Registry that shows assets needing scanning for a specified period -- or sorted by 'inventory_scan_due_date'.

### Interface Changes
- Add new “Asset Inventory Scans” registry menu item
    - Show grid of asset scans
      - Menu: Search options to limit time frame, type of asset, etc
      - Asset action menu: Edit scan entry (which fields should we allow editing?)
      - Asset action menu: Edit scan entry, eg: conditions (edit equipment_condition table)
  - Main [Menu] item to set the default location for scans.  Ideally, this location should be able to be entered via a barcode.
  - Big [Scan Asset] button to create new asset scans
    - Brings up a barcode scan interface
    - Once the barcode is scanned, a pop-up modal allows editing Purpose, condition, etc.  id, asset_id, scanned_by, location.  Note that the exact inventory item and asset (lot) will be identified by this scan.
- In the Assets registry, and an action menu item to show the scan history for the asset

**Comment by mbayopanda** [comment]
@jmcameron correct me if I am wrong, it seems like this module it is for a periodic check of assets (Assets Cycle Count) in that case :
- Are we supposed to scan all assets in one day ?
- In case we scan assets for more than one days, how to know the end of assets scan to know the real status of assets.

**Comment by jniles** [comment]
@mbayopanda @jmcameron, my two cents:

- I don't think we should be required to scan assets all in one day.  I think we need to timestamp the date of the scan, and that way we will know the current state.  `created_at` may be enough, but we may also (for some reason) need to put in a way to back-date it.  I cannot imagine the use-case right now, so I am comfortable moving ahead with `created_at`.

**Comment by jmcameron** [comment]
>     * Are we supposed to scan all assets in one day ?

The way that asset scanning worked in the company I used to work for is like this:

- "Inventorying" (scanning all assets) was required once a year
- A deadline was given for all assets to be scanned each year
- In the month (or more) before the deadline, everyone was instructed to scan their assets (using special devices or smart phones).  In some cases administrative staff or IT folks would do a lot of the scanning.
- The administrative staff monitored what percent of items were scanned (since last year's inventory).  
- In the last week or two before the deadline, the administrative staff would work directly with people or departments who had not completed their scanning to get it done ASAP.
- In the last week, the department head would warn people who had not completed their scans that it would count against them on their next review if their scans were not completed before the deadline.
- Occasionally, items could not be found or were known to be lost.  There was a procedure to handle these cases but usually require manager approvals.
- Failures of departments to get all their assets scanned was a black mark against the department that was reported up to higher levels in the organization.  And the reviews of these upper-level managers were probably impacted negatively in such cases.  So each department was eager to get their scans completed early.  My department required all assets to be scanned a month before the deadline!

We do not have to do this this way, but we do need a way to say that an inventory process has started and will end at a specific deadline.  And then we need to be able to list all assets that have not been scanned during that date interval.
