### ISSUE TITLE
Asset Management - Asset Shipping support

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6351]
### NOTE:  For BHIMA, a "Shipment" is defined a **_SINGLE CONTAINER_**.

Therefore several "shipments" may be necessary to send a set of assets to a destination corresponding to a specific requisition.

Note that it is not clear yet if any changes will be needed for requisitions.  It seems likely changes will be necessary.  As you implement the shipping features, please make notes in this Issue (or a new issue) about this.

### Database Changes
- Create a new Shipper (transport) table
  - SQL/functions like Supplier table
- Create new ‘shipment’ table
  - uuid
  - name
  - description
  - shipper_id
  - requistion_id
  - notes
  - current location (depot)
  - destination (depot)
  - anticipated_delivery_date (date)
  - date_sent (ie, date it left a depot for transport elsewhere)
  - date_delivered (ie date it arrived at a depot)
  - receiver at final depot (simple text field to include in printed shipment label)
  - Status (defined in separate table: empty, partial, complete, in-transit, at-depot, delivered, lost)
  - created_at (date)
- Create new ‘shipment_item’ table
  - shipment_uuid
  - asset_uuid (this is the **uuid** in lot table)
  - date_packed
  - notes?
 
### Interface Changes
- Add a new entry “Asset Shipping” under the top-level Assets Management menu group
- Under the “Asset Shipping” menu item add these pages:
    - Shipping Registry
      - Shows grid of shipments, include total value of shipment in a summary.  User can select the display currency.
      - Big button on top:  [New Shipment] or [Add]
        - Brings up a shipment create modal
      - Menu:
        - Search options
      - shipment action menu
        - Edit
        - Scan barcode to change location, status, etc.
        - Print shipping label
        - Print barcode

**Comment by jniles** [comment]
Here is a nifty image of something shipped that might help us.

![image](https://user-images.githubusercontent.com/896472/151545522-e8dbd6bd-ca22-4bf8-adb9-d9b06f42aec2.png)
