### ISSUE TITLE
Asset Management - Add Assests Registry page

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6353]
## WARNING:  Issues https://github.com/IMA-WorldHealth/bhima/issues/6348, and https://github.com/IMA-WorldHealth/bhima/issues/6349, and https://github.com/IMA-WorldHealth/bhima/issues/6352 should be done before this issue!

- Add “Assets Registry” page under the "Assets Management" top-level menu item
  - Brings up the Stock Lot registry with flags to show asset-related fields by default.  We might change the Title to “Assets” vs “Lots” in this case.

**Comment by jniles** [comment]
We discussed this as a team.  I think that if we decide that _only assets can be assigned to entities_ (currently under Stock Assignment), that the Asset Registry can be both an Asset Registry and an Asset Assignment registry.

**Comment by jmcameron** [comment]
Based on chat with @jniles:
- Q: Should we make the asset registry a clone of the lot registry or actually re-use the lot registry with a flag that hides some fields and displays asset-related fields?

- A: Make a new one, but blend it with the "stock assignment" registry.  So, it would double as the registry responsible for viewing who is assigned each asset. That way it plays the dual role of being an asset registry and showing who is assigned what.
