### ISSUE TITLE
Tag number (barcode) generator for assets

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6361]
Adds a tool for generating barcode of tag number to be used in case we want to print out tags to affixes on assets before entering them in the warehouse.

Position in unit : 
- Stock
  - Stock Entry : In the menu option adds a new item `Generate Tag Numbers`

When you click on the menu item `Generate Tag Numbers` a modal will be displayed in which you have to specify number of tag number to generate, a submission will give you a `csv` file with tag numbers.

The csv file can be imported in a printer software such as Dymo to generate barcodes from these tag numbers.

These printed barcodes will be affixed on assets before entering them in stock.

**Comment by jniles** [comment]
Will we need to create any new database tables to store IDs?  Or are the IDs just to give you the ability to create barcodes on the fly?

**Comment by mbayopanda** [comment]
We don't need any database table, we create barcodes (tag numbers) on the fly

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/6368.
