### ISSUE TITLE
Implement transit depot for stock movements between depots

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6373]
Actually when we do a stock exit to a depot, while the receiver didn't enter the stock, we do not know where this stock is.

With the transit depot we must track information about stock exit while there is not a corresponding stock entry; and we have to inform the user about the location of this stock.

**Comment by jniles** [comment]
Before you get too far on this, can you describe how you intend to implement this?  Is it one transit depot for the entire institution?
Or will there be a separate transit depot between each depot?

**Comment by mbayopanda** [comment]
I was thinking about having a new table `depot_transit` with these fields: 
- From: the sender 
- To: the destination
- Exit date: the date of the exit
- Exit quantity: the quantity sent
- Entry date: the date of a corresponding entry for an exit
- Entry quantity: the quantity received
- Lot uuid: the unique lot identifier
- Status: 
   - In progress
   - Done
   - Cancelled
- Document uuid: the document uuid of the exit movement
- Label: not required, but can be an information about the transportation during a shipment.

The idea is to update this table during a stock exit or a stock entry, in that way we have more information about stock `In-Transit` and we can enhance `Article en stock` or `Lot en stock` queries to display this information in the group of each depots.

We have this `status` field which must help us to filter only `in-progress` records that will be displayed as in `In-Transit`.

Challenges are: 
- How to correctly display these `In-Transit` stock in the `Articles en stock` and `Lot en stock` registries.
- How to optimize our `Articles en stock` and `Lot en stock` SQL queries with this `In-Transit` information to not have performance issues since these SQL queries already big and can have performance issues.

**Comment by jniles** [comment]
Is this different from shipping linked here https://github.com/IMA-WorldHealth/bhima/issues/6351?

A lot of the fields look the same.  How does it relate to shipping?

**Comment by mbayopanda** [comment]
You're right it is like the shipping proposal however the shipping is related to assets only.

Here the idea was track stock exit (any lots, not only assets)

**Comment by jniles** [comment]
I propose we implement both at once.  All inter-depot movements would be shipments, but we would create two different kinds of interfaces (like we do for assets) to ensure that we capture the correct information for shipments while allowing users to quickly move stock between two depots via the regular stock exit interface.
