### ISSUE TITLE
How to add the employee's name on the voucher

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#6377]
![image](https://user-images.githubusercontent.com/8035588/152535846-63c9eee3-e0fc-41cd-8c48-dd1ba94c38fa.png)

It is important to be able to put the employee's name on the documents instead of using their code

**Comment by jniles** [comment]
Hmm... this has certain privacy implications.  A printed document like this could be given to someone who doesn't have the right to access this information.  Was this requested by a production site?  If not, we should check if them to see if they agree or not.

**Comment by lomamech** [comment]
![image](https://user-images.githubusercontent.com/8035588/158363084-389a37de-c013-4260-810a-daef8f09a4d3.png)
at IMCK for example, he had asked for it a very long time ago and for Vanga with the document generated during salary advances it will be very difficult to detect in the event of an error whether the data entry operator had chosen the best person

**Comment by jniles** [comment]
I would actually add this to the text of the description as well.  Can we make this from "Avance Salaire" repeated to "Avance Salaire Jonathan" for example?  It would help us find text later.
