### ISSUE TITLE
Stock entry from a transfer allow multiple bad entries

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6391]
In the stock entry from a transfer, when we select a movement already entered we still have the original lots (all lots concerned by the movement) instead of have only not entered lots with remaining quantities

![chrome_7j7GBFBhTn](https://user-images.githubusercontent.com/5445251/153370298-82c43953-b244-415f-9b8e-0669ca377abe.gif)

**Comment by jmcameron** [comment]
I was not able to duplicate this error.  Please describe the steps needed to reproduce this problem.

**Comment by mbayopanda** [comment]
> I was not able to duplicate this error. Please describe the steps needed to reproduce this problem.

To reproduce the bad behavior: 
1. Perform a stock exit to a depot, for instance this:

![image](https://user-images.githubusercontent.com/5445251/153491501-807c39d2-b749-46cc-b61b-729a38424fde.png)

2. Do a stock entry from the transfer, we select our movement:

![image](https://user-images.githubusercontent.com/5445251/153492251-dfad0b2e-3a27-4322-850b-5b48b7505c2f.png)

Which give us 3 lots with quantities:
- Quinine: 5
- Quinine: 5
- Vitamin: 3

![image](https://user-images.githubusercontent.com/5445251/153492469-2b5836d4-da30-4992-b91a-6b49925790f6.png)

We decide to not entering all lots just a part, like this:
- Quinine: 1
- Quinine: 5
- Vitamin: 0

![image](https://user-images.githubusercontent.com/5445251/153492726-47f1e2f6-de56-4164-9357-42199474fc37.png)

All things are okay until now. But we decide to re-entering the other remaining part like this:

3. Do again a stock entry from the transfer (which is possible by enabling the button "Reçu")

![image](https://user-images.githubusercontent.com/5445251/153490744-48598e7d-0fab-4cc5-8de5-6c321fccb10c.png)

![image](https://user-images.githubusercontent.com/5445251/153490960-d8cbed1a-16af-4a71-8768-06300e6052bd.png)

![image](https://user-images.githubusercontent.com/5445251/153493128-c02d6ca5-b161-41fe-b1d8-04d87c027461.png)

And you will see, we still have all the initial lots, instead of having the remaining part which must be:
- Quinine: 4
- Vitamin: 3
