### ISSUE TITLE
Move reference_number field from inventory table to lot table

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6433]
We initially put 'reference_number' in the 'inventory' table.   The idea was that 'reference_number' would be used as an "External Reference Number" to associate assets with specific orders by external entities.   However, an inventory item is actually more general.   For instance, different specific assets (lots) of the exact same inventory item could be ordered and processed by two different external entities or separate orders by the same external entity.  Therefore it does not make sense that this number should be in 'inventory'.  Instead it should be in the 'lot' table.

**Comment by jniles** [comment]
Makes sense to me!
