### ISSUE TITLE
Add support for required asset inventory scans

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6466]
We would like the ability to require an inventory scan of a set of assets.  These could be ALL assets, or all the assets at a particular destination or depot, or all assets assigned to a particular entity.  Each required inventory scan would have a due date as well as information about the requestor, purpose, etc.   These inventory scans may be required on a  periodic basis or an arbitrary date.   Also, it seems possible that a specific asset may be need scanning for two different inventory scans at the same time.  Based on all that, it seems clear that we need the ability to define an "Asset Inventory Scan" with the following data:

Inventory Scan (SQL table)
 - Created date
 - Due date
 - Brief description
 - Depot (optional)
 - Inventory (optional)
 - Inventory Group (optional)
 - is_asset (1, 0, NULL)
 - Assigned to (optional)
 - Reference number (optional, this is the 'reference_number' used to refer to lots/assets being tracked by an organization providing them.

The goal of the "depot", "assigned_to", "inventory", "inventory_group", "is_asset", etc fields above is to allow a search all applicable assets (lots) to list the relevant lots (work like filters).  In conjunction with the asset_scans table, it should be straightforward to list all unscanned assets, etc, for more detailed reports.

Also need to add a page under "Assets Management" to support "Required Asset Inventory Scans".  Include creating new, editing old, and action menu items for getting status of scanned vs unscanned data, etc.  Also need regression tests.

**Comment by lomamech** [comment]
I just read the content of the issue, I think the content is very clear, my concern is that assets that will not be scanned will _its will be considered lost?_

**Comment by jmcameron** [comment]
> I just read the content of the issue, I think the content is very clear, my concern is that assets that will not be scanned will _its will be considered lost?_

Good question!   This is a policy question that we may need to address eventually.   I think what will happen is if items are not scanned, the managing agency will ask the center/Depot responsible what happened to the items that are missing scans.   The have a choice: (1) Find the items and scan them so an updated report shows the as scanned, or (2) declare the items lost and do stock exits (to loss) for them.
