### ISSUE TITLE
Creating shipments allows expired stock to be selected

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6471]
When creating shipments, doing [add] and selecting an inventory code allows lots/assets to be selected that are expired.  Only assets OR unexpired lots should be allowed in the "available lots" so that expired lots cannot be selected.

Reference notes in merged PR https://github.com/IMA-WorldHealth/bhima/pull/6394

**Comment by mbayopanda** [comment]
@jmcameron I was trying to fix that but I can't reproduce that, could you help us with the steps to reproduce this issue. Thanks

**Comment by jmcameron** [comment]
To reproduce this problem:
- Use bhima_test
- Shipment > Create new shipment (select Main depot)
- Click [Add] to add a new line for an inventory/lot item
- Type 'quin' into the inventory code area until it gives you one option for quinine.  Select it.
- Note that it automatically selects lot QUININE-A.  However it is expired.

**Comment by mbayopanda** [comment]
@jmcameron it select the Quinine but you cannot submit it because it is expired, and there is a red highlight on the concerned row

**Comment by jmcameron** [comment]
> @jmcameron it select the Quinine but you cannot submit it because it is expired, and there is a red highlight on the concerned row

Why would we want the user to figure that out, when we can eliminate the expired stock before the display happens?

**Comment by jmcameron** [comment]
@mbayopanda As we discussed yesterday, I'll see if I can fix this.
