### ISSUE TITLE
Are conditions for items necessary in the Shipments?

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6497]
As noted in [PR 6496](https://github.com/IMA-WorldHealth/bhima/pull/6496), when creating shipments, selecting a condition for each item is required before submitting. If it is not set, the form can be submitted, but the condition for the item is null for the resulting shipment. We should think about this. And it is not clear that the condition is needed as part of the shipment itself since that could be tracked with asset scans.

I suggest that we remove these from the shipment (item) table and shipment forms and rely on tracking asset conditions from by asset scans.   The current plan is to scan each item as it is placed in a shipment, so that should provide this information.

**Comment by jniles** [comment]
I agree, the condition is not needed for a shipment. The condition should be a property of the asset, and likely only updated in/during the asset scan registry.
