### ISSUE TITLE
Do not enforce daily exchange rates

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#65]
This proposal concerns conceptually changing the exchange rate.  We currently treat exchange rates as only valid the day they are defined.  I propose change the exchange rate handling to be valid from the time of definition to the next time of change.

Proposed Database Changes:
1. Drop the column `enterprise_currency_id` and replace with `enterprise_id`.
2. The `date` column's data type  will be DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP.
3. Rename `foreign_currency_id` to simply `currency_id`.

Proposed API changes:
1. `GET /exchange` lists all the exchange rates in the database
2. `POST /exchange` will create an exchange rate.  If no date is provided, use the current timestamp.
3. `PUT /exchange/:id` update an exchange rate in the database.
4. `DELETE /exchange/:id` will delete an exchange rate from the database.

Proposed algorithm changes:
1. The `ExchangeService` will get exchange rates based on the current time.  The exchange rates will be kept in an ordered list.  Given a date, the algorithm will walk down the list of exchange rates, setting the most recent rate prior to the given date as a valid rate.  If no valid rate exists, the service should throw an error.  [This part of the proposal has already been implemented in ExchangeRateService](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/ExchangeRateService.js).

Additionally, we should support both editing and deleting exchange records.  This would allow the enterprise to correct previous records by editing a faulty exchange rate and recalculating the rates for the data in the posting journal.

**Comment by DedrickEnc** [comment]
Since our exchange rate service, considers that we will not set a new exchange rate every day, this issue can be closed

**Comment by jniles** [comment]
I would feel better about closing it when @lomamech's exchange rate changes land in master.  In the current build, daily exchange rates are still enforced, but that will soon be changed.
