### ISSUE TITLE
Improvements to the Inventory Adjustment page

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6506]
Since we removed the "Stock > Adjustment" page in [PR 6502](https://github.com/IMA-WorldHealth/bhima/pull/6502), the "Stock > Inventory Adjustment" page is the primary page to make inventory adjustments.     

The old "Stock > Adjustments" had one nice feature: you could select inventory items to adjust.  The current "Stock > Inventory Adjustments" lists all the inventory.  

I propose adding a [Search] feature, including optional depot selection, searching for specific inventory codes, etc, to make this interface friendlier for sites with a lot of different types of inventory.

**Comment by jniles** [comment]
I am not sure we need this.  The page is geared on a single depot, like all our other stock pages, so I'm not sure it makes sense to search in other depots.

We also have the ability to filter with the inline filter.  What does this issue add that we can't do with the existing module?

**Comment by jmcameron** [comment]
Ok.
