### ISSUE TITLE
Add Shipment Registry action item menu entries

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6529]
Add new entries in the action menu for shipments in the Shipment Registry.
- Stock Exit --> Jump to Stock Exit page and automatically set Origin Depot and Shipment 
- Stock Entry -->  Jump to Stock Entry page and automatically set Destination Depot and Shipment

**Comment by jniles** [comment]
Note that these should be conditional - only the stock entry should be allowed if the item is shipped and only exit if the shipment is ready, etc.

**Comment by jmcameron** [comment]
Definitely.  Already figured that out.
