### ISSUE TITLE
Confusing column lables in Stock entry (from shipment) receipt document

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6531]
What is the meaning of the "Quantity Received" and "total received" columns (after doing a stock Entry of a shipment)?

![image](https://user-images.githubusercontent.com/62145/162761212-985c8d6c-fe06-4896-9d84-e76eb976d627.png)

Notice that if the purchase/transfer is complete and all differences are 0, the "Total Received" and "Difference" columns can be omitted to make the report clearer.

Also see #6565

**Comment by jniles** [comment]
I believe this is because the stock entry is generic and you can enter stock from one exit in several different entries.  For shipping, this doesn't make any sense and we should probably have a different receipt for entry from shipping with more details.
