### ISSUE TITLE
Create Transfer Type Module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#654]
Add a transfer type table and module for adding, update or delete type dynamically. The reason is we must have a mean to group transactions correctly for cashflow report.

![tt](https://cloud.githubusercontent.com/assets/5445251/17780868/cfe0e492-6521-11e6-9c04-9e4561cc4936.png)

Above we have a fixed list of transaction type which represent groups for cashflow report, we must add, update or delete items of the list above in the application and not in the source code.

This issue is about : 
- Creating a table `transaction_type` in the database 
- Add a module in the application for managing crud operations for the transaction type
- Update the `VoucherService` to considere data which came from the database

**Comment by mbayopanda** [comment]
@jniles i can start with this issue in waiting your review of the #666 PR

**Comment by jniles** [comment]
@mbayopanda, sounds good.  Thanks!
