### ISSUE TITLE
When editing a shipment, it should not be possible to change the origin depot

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6571]
Some of the complicated logic when editing shipments is to accommodate the possibility of changing the origin depot while editing the shipment.   We should prevent that possibility by disabling the "Change Depot" option under the [Menu] button while editing shipments.  We can also clean up the related code in create-shipments.js.   This would also be an opportunity to rename create-shipments.js to something more appropriate (for both creating and editing).

**Comment by jniles** [comment]
@jmcameron did this get addressed?  I feel like it did, but I cannot rightly remember.

**Comment by jmcameron** [comment]
> @jmcameron did this get addressed? I feel like it did, but I cannot rightly remember

Just tested this.  It is partially done: If you edit a shipment ("Update packing list") and you change the origin depot (via the menu), the contents of the order get deleted (because who knows if the items in the previous packing list even exist in the new origin depot).  What does not get done and should be done are:
- Delete the Label, destination depot, anticiapated delivery date, notes, and any underlying UUIDs, etc and 
- Put up an info message that says "Creating new shipment"

**Comment by jniles** [comment]
Aha, I hear you.  

I prefer we just ... don't let you do that.  If you do, you need to delete the shipment and restart.  That seems cleaner to me.

What do you think?

**Comment by jmcameron** [comment]
One confusing thing here is the origin Depot is a cached system var.   When you do a stock out and you change the origin depot, the next stock out will use the new origin depot until you change it via the Menu > Change Depot modal.

I think disabling the Menu > Change Depot option when editing a Shipment might make sense.

**Comment by jniles** [comment]
Yes, I agree.
