### ISSUE TITLE
(design) General Design for Reversing Transactions

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#659]
This design concerns reversing user-created transactions: journal vouchers, invoices (as a credit note), and cash payments (as a debit note).

**Background**
In double-entry accounting, reversing a transaction is extremely easy: simply create a new transaction with the debit and credit fields swapped.  This could also be done with negative values as explored in #468.  (One can even imagine having a setting for switching between proper double-entry reversals and OHADA-specific negative numbers.)

**Design**
Each implementation of a reversal route should go like this:
1. `POST /{{entity}}/:uuid/reverse` where `{{entity}}` is `cash`, `invoices`, or `vouchers`
2. The `POST` body should have a description associated with the request.
3. The endpoint `/{{entity}}/:uuid/reverse` will be responsible for initiating a MySQL stored procedure `ReverseTransaction(uuid, description, user_id)`.  The `user_id` can be obtained from `req.session.user.id`, the description from `req.body.description` and `uuid` from `req.params.uuid`.
4. As described in #112, #254, and #349, the `posting_journal.record_uuid` or `general_ledger.record_uuid` will be the same as `cash.uuid`, `invoice.uuid` or `voucher.uuid`.  the `ReverseTransaction()` stored procedure will look up the record in the `posting_journal` or `general_ledger` and reverse the record (swapping debits and credits).
   1. Note: if the record is referenced (i.e. has a `reference_uuid` pointing to it) it should not be reversed, and `ReverseTransaction()` should error out.  For example, if an invoice has a cash payment against it, you should not be able to credit note it.
5. All reversals will create a new record in the `voucher` table and post it to the `posting_journal`.

**Closing Thoughts**
In this strategy, there will be no "Credit Noted" invoices - there will be only balanced invoices.  There will also be no "discarded cash payments" - only payments that have not contributed anything to the overall balance because they have been reversed.

**Comment by DedrickEnc** [comment]
@jniles

Here are some concerns : 
1. Why the point 5?
2. There is already a route to the journal for reversing a transaction is it different than this issue?
3. I am not understanding well your closing thoughts

**Comment by jniles** [comment]
@dedrickenc, thanks for the feedback.

Point 5 allows us to use the `voucher` table's posting procedure.  It also gives us a receipt to refer to later if we need to.

This is the same idea.  The current implementation in `master` was based off #534, which was short-sighted and specific to Credit Notes.  This issue proposes a more general design.

With this strategy, it will **not** be possible to distinguish between a balanced invoice by a credit note, and a balanced invoice with a payment, since there is no specific credit note table.  We will lose that power, but we will have a more general way to reverse transactions.  Does that make sense?

**Comment by DedrickEnc** [comment]
Not really, sorry.
How can we distinguish a balanced invoice by credit note and a balanced invoice by cash payment since there is no credit_note table?

**Comment by jniles** [comment]
That's because I am terrible at typing :(.  We will **NOT** be able to distinguish between a regular payment and a reversal (credit note).  It will simply balance the payment.
