### ISSUE TITLE
Migrate from bootstrap-less to bootstrap-sass

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#66]
Apparently [Bootstrap 4 will be written in SASS, not LESS](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/).  Since we are in a period of change, we might as well make the migration before the Bootstrap 4 community, in order to remain compatible for the future.  Bootstrap maintains an official Bootstrap 3 SASS port, available via bower as `bootstrap-sass`.

**Comment by DedrickEnc** [comment]
@jniles is this issue valid yet?

**Comment by jniles** [comment]
It has not been fixed if that's what you mean.
