### ISSUE TITLE
Improvements to Enterprise Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#661]
The enterprise management module was heavily refactored in #619.  The new interface is much improved.  This issue tracks refinements to the new module.

**Refinements**
- [ ] ~~Deep link the projects states using `ui-router`.  Specifically:~~
  1. ~~`/enterprises/:id/projects/create` should open the create form to create a new project for the enterprise with id `:id`.~~
  2. ~~`/enterprises/:id/projects/:projectId/update` should open the update form to update the project with id `:projectId`.~~
  3. ~~`/enterprise/:id/projects/:projectId/delete` should open the delete modal to delete the project with id `:projectId`.~~
- [x] The `locked` project option should not be available in the `create` state.
- [ ] The second "update" button on the optional form should be a link like in patient edit.
- [x] The accounts should use `ui-select` (discussed in #539, introduced in #637)
- [ ] Do not send a PUT request if nothing changed in the form (similar to patient edit)

**Comment by DedrickEnc** [comment]
The question is how the UI will look like? will we continue to keep enterprise management and project management as two different units in our tree?

**Comment by jniles** [comment]
They are currently only one unit in the 2.x tree in `master`.  See the issue https://github.com/IMA-WorldHealth/bhima-2.X/issues/592 for the UI design.  Note that we are not able to change enterprise or delete the enterprise.
