### ISSUE TITLE
(bug) Upload Patient Image button takes a long time to show dialog

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#662]
On the Patient Overview page, the "Upload Patient Image" button takes a very long time to bring up the dialog.  It takes anywhere from instantly to several seconds to bring up the dialog to select the patient image on a reasonably performant machine.

For comparison, check the Patient Documents file button, which instantly opens the dialog.

**Steps to Reproduce**
1. Navigate to the Patient Records page.
2. Click the "Upload Patient Image" button.

**Expected Result**: The file selection dialog should immediately pop up.
**Actual Result**: The file selection dialog pops up after several hundred milliseconds.

**Comment by mbayopanda** [comment]
LGTM

2016-08-25 6:38 GMT-07:00 Jonathan Niles notifications@github.com:

**Comment by jniles** [comment]
Seems like this is specific to my setup (linux + i3 window manager).  Closing issue.  If anyone experiences this, please comment and we can track it down.
