### ISSUE TITLE
Report issues

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6621]
Once [PR 6606](https://github.com/IMA-WorldHealth/bhima/pull/6606) lands, there are few a reports that should be checked.

These reports may be obsolete (or I could not figure out how to see these reports in BHIMA)
   - [x] finance/reports/break_even/report.handlebars
   - [x] finance/reports/break_even/report_project.handlebars
   - [x] finance/reports/break_even_cost_center/report.handlebars
   - [x] finance/reports/break_even_cost_center/report_project.handlebars
   - [x] finance/reports/cost_center/report.handlebars
   - [x] inventory/reports/items.handlebars
   - [x] stock/reports/stock/assignment/stock_assign.registry.handlebars
   - [x] stock/reports/stock_assign.receipt.handlebars

I could not figure out how to check these reports.    I tried to fix the formatting in them, but it is possible further tweaks may be needed:
   - [x] finance/reports/cash/receipt.pos.handlebars
   - [x] finance/reports/vouchers/report.pos.handlebars
   - [x] stock/reports/stock_adjustment.receipt.handlebars
   - [x] stock/reports/stock_aggregate_consumption.receipt.handlebars
   - [x] stock/reports/stock_movements.report.handlebars

**Comment by jniles** [comment]
Some of these might be registries.  And anything with "pos" in their names is a thermal receipt and you must enable "POS Receipt" in bhima's SETTINGS.

**Comment by jmcameron** [comment]
> Some of these might be registries. And anything with "pos" in their names is a thermal receipt and you must enable "POS Receipt" in bhima's SETTINGS.

Some these I looked for a while and gave up when I was spending too much time on them.  Then I just fixed them based on the other fixes but could not verify the fixes.  And thanks for the info on the .pos. ones.

**Comment by jmcameron** [comment]
> enable "POS Receipt" in bhima's SETTINGS.

How do I do this?  I do not see that in the BHIMA Enterprise settings...

**Comment by jniles** [comment]
In the settings, not enterprise settings.  It's the bottom left corner gear icon.

**Comment by jmcameron** [comment]
> In the settings, not enterprise settings. It's the bottom left corner gear icon.

Thanks.  I checked all the .pos.handebars reports and none of them are affected by these changes.

**Comment by jniles** [comment]
I'll tackle removing some of the break even reports and cost center reports.

**Comment by jniles** [comment]
I've tackled the break_even and cost_center reports in #6660.

I'll take a look at the stock assignment ones once that PR gets merged.

**Comment by jmcameron** [comment]
We currently do not have Stock Assignment Report working.  You may want to leave the existing reports in place so we can set up connections to them somewhere: Under "Assets Management > Reports" or "Stock Lot" - not sure which is best.
