### ISSUE TITLE
(refactor) Better Error Messages

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#663]
One significant weakness of 1.x was poor error messages.  With 2.x, we have good alerts of errors, but poor indication of what the error is.  For example, if you register a patient with the same name, the following error occurs:
![genericerror](https://cloud.githubusercontent.com/assets/896472/17935129/21520c4e-6a12-11e6-8d5b-f492c73c9fb2.png)
_Fig 1: Generic Error Message for Patient Registration_

We can do better.  In fact, the console does better:
![betterconsoleerror](https://cloud.githubusercontent.com/assets/896472/17935624/f2f09558-6a13-11e6-848c-98fb05768559.png)
_Fig 2: Better Console Error Messages_

This error was due to `ER_DUP_ENTRY` error, thrown by a constraint that a debtor cannot have the name as another debtor (UNIQUE KEY).

I propose that we ensure that our `BadRequest` errors show more information to the user.  Some ideas:
1. `Your request was missing some fields.  Verify that the form was correctly filled in and try again.`
2. `There is already a patient with the name ${patientName}.  Please ensure this patient's name is unique`.
3. `This record is referenced in the Posting Journal or General Ledger and cannot be removed.`

With these changes, the application will become much more usable by our end users.

**Comment by DedrickEnc** [comment]
@jniles 
You are right however some solution (the second and the third) can be expensive to implement depending on how mysql report error to nodejs.

My be it will be good the says to the user some thing like :

>  The operation failed make sure that :  
>  a list of eventual causes which can be happen at once

Because by analyzing the database structure we can define the error cause for every table, we can see this way of reporting error in windows (troubleshooting network issues).

Note that this solution is valid if only a CRUD operation fails.

**Comment by jniles** [comment]
@DedrickEnc, I think defining each error for every table is a bit exhaustive.  We can simply capture all errors and translate the ones we find are important.  Then all we need to do is translate all tables names, plus a subset of MySQL errors.

For this issue, here is how I propose we implement our error handling.

MySQL defines a strict syntax for all it's errors.  We can find the whole list [here](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html).

We can choose a subset of these error codes that occur frequently.  Here are some that I've notice happen quite often:
1. [Duplicate Key Error](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_dup_key) for records that have been submitted more than once.
2. [Duplicate Unique Index](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_dup_unique) for tables with UNIQUE constraints across columns.
3. [Row is Referenced](http://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_row_is_referenced) for deleting rows that posted or used in elsewhere in the application.

`node-mysql` will return the error via `error.code`.  [Here is the relevant documentation](https://github.com/mysqljs/mysql#error-handling).

Since we have the MySQL syntax, it is easy to obtain the table name and associated value from the error by parsing the error string.  Then, we can translate the error, substitute an ID if necessary, and substitute a translated table name.

**Comment by jniles** [comment]
I think most of these have actually been taken care of in our `interceptors.js` file.  Closing.
