### ISSUE TITLE
Next Generation of BHIMA End to End Testing

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6669]
We've written BHIMA into some pretty large scale projects.  We should get our E2E testing back up and running.

We have a couple of options:

1. Playwright - https://playwright.dev/docs/protractor
2. Cypress - https://www.cypress.io/
3. Nightwatch - https://nightwatchjs.org/

My preference would be for playwright.  We could also move our PDF rendering to playwright and have a more unified dev/production environment.

----

Protractor is clearly not coming back.  Due to https://github.com/angular/protractor/issues/5521, browsers have updated causing AngularJS to no longer bootstrap.  This means that we will need to migrate no matter what to a different E2E framework.

**Comment by jmcameron** [comment]
See Issue https://github.com/IMA-WorldHealth/bhima/issues/6976 to convert the end-to-end tests to Playwright.

**Comment by jniles** [comment]
We have migrated to playwright!
