### ISSUE TITLE
Add an xlsForm for "Consumption" in FOSA

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6672]
Assume that we are in the context of a FOSA (Formation Sanitaire) and we have ODK Collect to collect data of consumption of medicines. 

This form will allow us to collect data of consumption of medicines in the FOSA, these data will be sent to ODK Central and then synchronized with BHIMA to populate the stock movement table for the FOSA with the goal of having the CMM of the FOSA in real time.

**Comment by jniles** [comment]
So, I'm seeing this design as:

1. The data in the BHIMA for the FOSA depot is assumed to be accurate.  So, we can just sync to the device the current stock in the depot as of a timestamp.
2. The first question will ask for the current date.  It will default to today.
3. The next page will contain a list of every lot in stock in alphabetical order of the inventory, and an input for the quantity consumed on that day.  A calculation will ensure that the quantity consumed does not exceed the initial quantity in stock.
4. On a technical note, the submission UUID will map to the document_uuid of the stock movement to ensure that we can detect repeats.
5. When the IT returns with their telephone, the data is synced, and a new form is downloaded.

Note that, if a FOSA bought and consumed other stock between the time of synchronization, that will have to be recorded in the system by the pharmacist of the zone.

**Comment by jniles** [comment]
We could also imagine a daily synchronization for health centers that have access to 3G, where they upload their stock daily to the system.   Should we try to implement both or just implement a single version?

**Comment by mbayopanda** [comment]
> So, I'm seeing this design as:
> 
> 1. The data in the BHIMA for the FOSA depot is assumed to be accurate.  So, we can just sync to the device the current stock in the depot as of a timestamp.
> 2. The first question will ask for the current date.  It will default to today.
> 3. The next page will contain a list of every lot in stock in alphabetical order of the inventory, and an input for the quantity consumed on that day.  A calculation will ensure that the quantity consumed does not exceed the initial quantity in stock.
> 4. On a technical note, the submission UUID will map to the document_uuid of the stock movement to ensure that we can detect repeats.
> 5. When the IT returns with their telephone, the data is synced, and a new form is downloaded.
> 
> Note that, if a FOSA bought and consumed other stock between the time of synchronization, that will have to be recorded in the system by the pharmacist of the zone.

@jniles what about the selection of the depot (the FOSA depot)? 
And do you think the stock movement will be a stock exit to patient or  service? because this value must help us with the CMM calculation

**Comment by jniles** [comment]
I would do a form per depot.  That way, there is less data to sort through in ODK.  Do you think we'll need to be able to select the depots?

Aha, that is a good point.  I would only do consumption for the first part.  Then I would later ask about if they had any losses, and include the reason for the loss.

**Comment by jniles** [comment]
@mbayopanda is this issue still relevant?  Are we using the ODK connections to BHIMA?
