### ISSUE TITLE
Stock entry of assets limited with quantity 1

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6709]
This issue is about the fact that during a stock entry of assets, when we click on the "Lots" link, the default and fixed quantity is set to one.

In case we want to enter 3 DELL XPS with serial number "S1", "S2" and "S3"; the normal process is: 

- Go to *Stock Entry* Module
  - Click on *Integration*
  - Set the date
  - Set the description
  - Click on the "Add" button for adding lines for inventories
    - Select an asset by typing its name or code
    - Click on the "Lots" link for adding different lots of the inventory in the line

In the modal for inventories which are assets, we have a fixed quantity of 1, in our example, we would like to set quantity to 3 for our three serial numbers of DELL XPS.

**Comment by jmcameron** [comment]
What this means is that you need to create 3 separate "Adds" in the list of items to be integrated, one for each lot number.  Assets are restricted to being completely unique (different from drugs) and therefore the quantity for assets is always 1.

**Comment by jmcameron** [comment]
I understand.  Using the top-level add does work, so you can do that for now.  But I'll fix the lot-selection modal Add so it will work too.
