### ISSUE TITLE
Added new information for asset management

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#6783]
**Added new information for asset management**
After analyzing a registry of assets,
We realized that there was missing information, but necessary for the managers,

Reasons why it is necessary to add the following properties
- Year or Date of acquisition (This could be obtained automatically for the cases where one proceeds by the entry of stock by purchase order)
- The possibility of displaying the number of years of life based on the data of the date or the year of acquisition.
- The depreciation rate
- The value depreciated by depreciation (Purchase cost * Depreciation rate)
- Residual Accounting value (Cost of purchase - Depreciated value)

![image](https://user-images.githubusercontent.com/8035588/184849938-7cf1b245-4f1e-4201-bdfd-85fdfa1e8ea0.png)

**Comment by jmcameron** [comment]
These suggestions make sense.
 - Date of acquisition --> Can we get this from stock movements based on first entry?  Otherwise we will need to add it to the 'lot' table
 - Expected lifetime --> Add to 'inventory' table?
 - The depreciation rate --> Add to 'inventory' table?
 - The value depreciated by depreciation (Purchase cost * Depreciation rate) --> computed
 - Residual Accounting value (Cost of purchase - Depreciated value) --> computed

**Comment by lomamech** [comment]
> These suggestions make sense.
> 
> * Date of acquisition --> Can we get this from stock movements based on first entry?  Otherwise we will need to add it to the 'lot' table
> * Expected lifetime --> Add to 'inventory' table?
> * The depreciation rate --> Add to 'inventory' table?
> * The value depreciated by depreciation (Purchase cost * Depreciation rate) --> computed
> * Residual Accounting value (Cost of purchase - Depreciated value) --> computed

After analyzing the documentation regarding depreciation by assest category, I think it will be better to define the depreciation rate **by inventory group**

**Comment by jmcameron** [comment]
> After analyzing the documentation regarding depreciation by assest category, I think it will be better to define the depreciation rate **by inventory group**

I'm not sure I agree.  I think our inventory groups are too broad (currently).  I suppose we could create new groups for this.  But I think two different types of vehicles could have different expected lives even though they might be in one inventory group.

**Comment by lomamech** [comment]
> > After analyzing the documentation regarding depreciation by assest category, I think it will be better to define the depreciation rate **by inventory group**
> 
> I'm not sure I agree. I think our inventory groups are too broad (currently). I suppose we could create new groups for this. But I think two different types of vehicles could have different expected lives even though they might be in one inventory group.

Exactly, I was thinking of new groups of inventories where we will only find inventories that will have the same depreciation rate

![image](https://user-images.githubusercontent.com/8035588/185427958-f85cc142-090d-47e8-9af2-7aac7cceaea6.png)

**Comment by jmcameron** [comment]
> Exactly, I was thinking of new groups of inventories where we will only find inventories that will have the same depreciation rate

That seems reasonable.  Here are couple of questions:
- How the data is going to be entered in BHIMA.  If it is manual process (create the group, create one asset after another).  If it is going to be imported via CSV files, it might be simpler to add another field to the inventories importer.
- If we do this approach, we have to add additional fields to inventory_group.  Are 'exepcted_life' and 'depreciation' applicable to all types of inventory?   On the other hand, if add them to the inventory definition, we have the same question.

**Comment by lomamech** [comment]
> That seems reasonable. Here are couple of questions:
> 
> * How the data is going to be entered in BHIMA.  If it is manual process (create the group, create one asset after another).  If it is going to be imported via CSV files, it might be simpler to add another field to the inventories importer.
> * If we do this approach, we have to add additional fields to inventory_group.  Are 'exepcted_life' and 'depreciation' applicable to all types of inventory?   On the other hand, if add them to the inventory definition, we have the same question.

I think we can add another field to the inventory importer or create group inventories before importing inventories
