### ISSUE TITLE
Stock exit with shipment reference broken

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6793]
In the stock exit to the depot, when we choose "We have a shipment ready" and select the shipment, the submit button becomes disabled

![image](https://user-images.githubusercontent.com/5445251/186891106-dfef3459-f273-4e1c-a0e6-c0eeae9d0ee9.png)

**Comment by jmcameron** [comment]
I just tried this (with the current 'master') and had no problem with it.  Please describe the exact sequence of actions to produce this problem.

**Comment by jmcameron** [comment]
To fix this, see https://github.com/IMA-WorldHealth/bhima/issues/6800
