### ISSUE TITLE
Convention Module need a loading indicator

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#68]
The convention module need a loading indicator for notify the user about the debitor receipts are being loaded when we select a debitor. 

The process take too long time for loading debitor receipts and also when we click on "submit" for a payment.

**Comment by sfount** [comment]
This is relevant to https://github.com/IMA-WorldHealth/bhima-2.X/issues/37

**Comment by mbayopanda** [comment]
@jniles, @sfount, @DedrickEnc and @lomamech : We have also to define a loading indocator for when we click on the submit button for a payment because it takes too long time before to display the receipt...

**Comment by jniles** [comment]
Sounds like a good use case for #57.  :)

**Comment by jniles** [comment]
@mbayopanda, to signal all those same contributors in the future, you can use @IMA-WorldHealth/local-contributors.

@sfount and I have linked two issues that might help solve this issue.  If you would like to add to either of those issues (or start working on one of them), feel free to coordinate with @DedrickEnc.  I'd be grateful to have both complete.

**Comment by jniles** [comment]
@mbayopanda, the loading indicator for the form landed in #194, if you would like to update the form in the convention module.

**Comment by jniles** [comment]
Closing this as outdated.  Please comment if it is still relevant.
