### ISSUE TITLE
Add additional information to the purchase order

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6813]
This issue is about adding additional information to the purchase order : 

- Nº Commande
- PRF Number
- Nom du fournisseur
- Adresse du fournisseur
- Téléphone du fournisseur
- Email du fournisseur
- Personne de contact
- Titre du contact
- Lieu de livraison
- Date de livraison
- Conditions de livraison
- Instructions spéciales
- Conditions de paiement
- Les signatures : 
-   Demandé par (nom, titre et date en caractères d'imprimerie) et signature
-   Approuvé par (nom, titre et date en caractères d'imprimerie) et signature
-   Deuxième approbation (nom, titre et date en caractères d'imprimerie) et signature
-   Signature du fournisseur (nom, titre et date en caractères d'imprimerie) et signature
- Conditions générales d'achat

**Comment by jmcameron** [comment]
Some of these items could be handled by using a "Contact" for the Fournisseur, delivery contact, etc.  The "Contacts" already support Name, Phone, address, etc.   "Contacts" could be updated to include a title.
