### ISSUE TITLE
Refine find-patient directive

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#69]
The find-patient directive has been updated to BHIMA 2.X standards and is now a very solid base. 

There are a few additional features that could be added to improve user experience and simplify use - as this directive is used in so many different modules it can be tackled by any developer that would like to address an issue. 
## Proposed Features 
- [x] Use standard form components for success and failure states (maintain similar message but deprecate alert element) 
- [x] Support binding the `required` hook for form validation
- [x] [Improvement] The "Patient Name" button should have tabindex = -1 in the HTML
- [ ] ~~Searching by patient name should be done in two steps to make the experience the same~~ 
  - ~~A name is entered and results displayed~~
  - ~~A result is clicked to select a patient~~
  - ~~'Submit' is pressed to confirm this patients selection~~
- [x] OR
  - The 'Submit' button is removed allowing the typeahead to confirm the search
- [x] Improvement: Add the following HTML tags to the underlying <input> to prevent confusing browser rendering:
  - autocomplete="off"
  - autocorrect="off"
  - autocapitalize="off"

**I will add any comments that are made below into this list of proposed features for the find-patient directive**

**Comment by jniles** [comment]
(Included in features)
~~The find-patient directive should support binding the `required` hook for form validation.~~

**Comment by jniles** [comment]
(Included in features) 
~~Improvement: The "Patient Name" button should have tabindex = -1 in the HTML....~~

Not sure if this is related, but the "enter" key in the input should search (in "Search By ID" mode).

**Comment by jniles** [comment]
Improvement: the patient find directive should only download the patient's name and ID (plus display metadata such as sex/birthday).  Upon "submit", the directive should return only the ID of the selected patient and nothing else.  It currently provides a large object of information which is sometimes useful, sometimes wasteful.

**Comment by jniles** [comment]
Improvement: Add the following HTML tags to the underlying `<input>` to prevent confusing browser rendering:
- autocomplete="off"
- autocorrect="off"
- autocapitalize="off" 

After a few searches, my browser got smart and hid the first element with its own suggestion.  These improvements solve that problem.  See below:
![smartbrowserinput](https://cloud.githubusercontent.com/assets/896472/12844840/3e39f384-cc02-11e5-9cb3-8ef96b92b259.png)

**Comment by jniles** [comment]
Test improvement: build test hooks so that the find patient component can easily be used in e2e tests for modules.  Proposed API:
1. `components.findPatient.findByName()`
2. `components.findPatient.findById()`
