### ISSUE TITLE
Add validation of requisition feature

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#6911]
In the context of Health Zones, orders have to be validated by the drugs committee and there is an important indicator based on that: the validated order satisfaction rate (Taux de satisfaction des commanded validées)

Since not all structures can have this feature, it must be activated on the stock settings page.

The feature will add a new page named "Order Validation" (Validation des requisitions), in this page the user has to: 
- Select the requisition through a typeahead select box
-   A grid with items of the order is shown up with a new column "valid quantity"
- Fill the grid of items in the order with the valid quantity

Once the order is validated then it can be delivered to other structures (only in case this feature is activated in the stock setting page)

**Comment by jniles** [comment]
Closed in #7040.
