### ISSUE TITLE
Problem on the management of product packaging

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#6956]
We have noticed that at the warehouse level some products are ordered in terms of packages but are consumed in terms of units. This issue proposes to modify the appearance of purchase orders, to display data related to packages in terms of packages and maintain stock entries in terms of units

**Comment by jmcameron** [comment]
I thought we already addressed this.  See  https://github.com/IMA-WorldHealth/bhima/issues/6811 and related PRs.

**Comment by lomamech** [comment]
> I thought we already addressed this. See #6811 and related PRs.

There is a little difference
- In the first issue which is already implemented, solved the problems that the Pharmacists had mentioned with the possibility of filling in the data by packaging
- When we have 4 Quinine boxes of 100 (total 400 boxes) and 5 Quinine boxes of 1000 (total 5,000 boxes) in stock, the overall quantity in stock is 5,400 boxes.

But the current problem concerns the ordering of products such as pens, the suppliers make the delivery in terms of packages
But at the level of the depot, we take out the stock in terms of unit, when the procurer orders 10 packets, the depot receives 500 pens.
The current issue will only change the display on the order form to only display quantities in terms of packages

**Comment by lomamech** [comment]
> > I thought we already addressed this. See #6811 and related PRs.
> 
> There is a little difference
> 
> * In the first issue which is already implemented, solved the problems that the Pharmacists had mentioned with the possibility of filling in the data by packaging
> * When we have 4 Quinine boxes of 100 (total 400 boxes) and 5 Quinine boxes of 1000 (total 5,000 boxes) in stock, the overall quantity in stock is 5,400 boxes.
> 
> But the current problem concerns the ordering of products such as pens, the suppliers make the delivery in terms of packages But at the level of the depot, we take out the stock in terms of unit, when the procurer orders 10 packets, the depot receives 500 pens. The current issue will only change the display on the order form to only display quantities in terms of packages

@jmcameron I used google translate did you understand my explanation
