### ISSUE TITLE
Satisfaction rate report

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7000]
The analysis of the satisfaction rate of the drugs, is a report making it possible to evaluate the quantity ordered by the structures, the validated quantity and the quantity delivered

Modules to add
- It will be necessary to add the activation in the stock parameter of the requisition validation step
- It will be necessary to add a module allowing to proceed to the validation of the orders
- The delivery should now take into account the validated quantities

The report should display:
- Satisfaction rate by quantity granted
- Satisfaction rate by number of item granted

**Comment by jniles** [comment]
What is the definition of "satisfaction rate"?  Is there a formula for it?
