### ISSUE TITLE
Improvements to Users and Permissions

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#706]
The Users and Permissions was the first 2.x module, written almost a year ago.  It needs to catch up with best practices.
- [ ] Submit buttons should be `bhLoadingButton`.
- [ ] New users do not refresh the `ui-grid`.
- [ ] The create button should be in the top right corner.
- [ ] The controller should use `$state`-based routes.
  1. `users/` should display all users.
  2. `users/:id` should highlight a single user
  3. `users/:id/update` should update details of a single user.
  4. `/users/create` should route to a form to create a user.
  5. `/users/:id/permissions` should route to a form with permissions controls for the user.
- [ ] The module should use `Notify` for success/danger/error states.
- [ ] If a ui-grid is used, it should extend all the way to the bottom of the page.

**Comment by DedrickEnc** [comment]
I will take this one
