### ISSUE TITLE
Strange NaN error during multiple payroll indice configuration

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7080]
I got a strange NaN error during multiple payroll by indice, with Vanga's database.

<img width="1142" alt="Screenshot 2023-05-18 at 11 58 55 AM" src="https://github.com/IMA-WorldHealth/bhima/assets/896472/38a8af2f-c0e8-4d9e-bd4f-271f330ea561">

We should try to catch these errors and let the user know what is wrong.  At the moment, the only error states that a field could not be stored in the database.

**Comment by lomamech** [comment]
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/5dff5cc8-7943-4c8f-b9b6-0016ea1f4b08)
I just did an investigation into this issue, by searching the Vanga database, and I searched for the pay period with ID = 22, and I found that this pay period corresponds to a period of test payroll for which there is no configuration

![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/b72939ed-55da-49fd-84cd-88bef87f7eec)

I don't think there is a bug

**Comment by jniles** [comment]
Closed based on @lomamech's feedback.
