### ISSUE TITLE
wkhtmltopdf does not reproducibly render content sizes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#709]
The PDF rendering library wkhtmltopdf exists to give us better control over our reports, rendering reliably across different devices.  However, it seems that different versions, or perhaps with different environments, interpret and render content differently.  Here are the wkhtmltopdf renderings of the same report on an ubuntu machine installed three days ago and the local development one installed in march:

![localwkhtmltopdf](https://cloud.githubusercontent.com/assets/896472/18438980/6e8958ee-78fb-11e6-8f19-345349701964.png)
_Fig 1: Development WKHTMLTOPDF_

![latestwkhtmltopdf](https://cloud.githubusercontent.com/assets/896472/18438934/47458e60-78fb-11e6-88f4-a1af02099f4f.png)
_Fig 2: Latest WKHTMLTOPDF_

This issue needs to be investigated so that our reports are reliably reproduced.  Potentially, we can force the font size at runtime, or in a CSS file.

**Comment by sfount** [comment]
I have also noticed that different versions of `wkhtmltopdf` have varying levels of support for page breaking and various other features that we rely on. 

There is also a difference between versions that rely on a display server and those that don't. We should encourage the use of those that don't (a relatively new feature). 

I agree that having a standard 'normalise' CSS file would help with cross platform/ version development. I also suggest we specify a version of `wkhtmltopdf` that BHIMA officially supports that can be upgraded and tested if new features are required or if our version is no longer supported.

**Comment by jniles** [comment]
I believe this is probably a combination of several issues:
 1. The version of `wkhtmltopdf` as @sfount mentioned.
 2. The fonts installed and available on the server.
 3. The screen resolution and default page sizes used.  This is particularly important when using a virtual frame buffer on headless servers.

None of these is _necessarily_ tied to the software, but more specifically to the production environment.  For this reason, I think we can close this issue and address it on a case-by-case basis with each installation.
