### ISSUE TITLE
Implementation of Payroll for General Hospitals of Reference

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7158]
After completing a mission in the 3 HGR of Tshikapa city, we noticed that the Payroll system differs slightly from the one implemented for the Baptist community hospitals. To address this, we considered using the BHIMA system, which can be configured to accommodate the necessary changes. However, implementing this would require performing certain tasks manually to ensure accuracy and prevent errors. Our proposal is to integrate these additional functionalities into the BHIMA system.

After conducting a thorough analysis of the current situation, we have identified that the BHIMA system currently only handles grades and functions, without consolidating functions and professions together. This poses a potential challenge and may lead to confusion. To address this, we propose enhancing the system by incorporating the management of professions. This will help avoid any potential confusion and ensure a more streamlined and efficient process.

**Comment by jniles** [comment]
Is there anywhere that the differences are documented between HGRs in Kasai, IMCK, and the Baptist system?  I am curious to know what the impact of a job title is on the index system, for example.
