### ISSUE TITLE
Handle all uiGrid window resizes manually

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#716]
Many of our `ui-grid`s use the [uiGridAutoResize](http://ui-grid.info/docs/#/tutorial/213_auto_resizing) directive without consideration of the performance implications.  In theory, we should not have any unknown window resizes - the `bhNavigation` component fires an event when its state changes (see [application.js#L47](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/partials/application/application.js#L47)), allowing all grids to hook into this and call [handleWindowResize()](https://github.com/angular-ui/ui-grid/blob/1c01e74/src/js/core/factories/Grid.js#L268) at their leisure.

If the `ui-grid` docs are correct, this should speed up the application's performance.

**Comment by DedrickEnc** [comment]
So for you every ui-grid should handle manual resizing?

**Comment by jniles** [comment]
Yup.  We could even have a generic service for registering grid instances that would listen for `nav:toggle` and call `grid.core.handleWindowResize()`.  That way, instead of calling `handleWindowResize()` every 250 milliseconds like we currently do, we only call it when we need it.

**Comment by jniles** [comment]
Alternatively, we could write a directive called `bh-grid-auto-resize` that listens for the `nav:toggle` call and calls `grid.core.handleWindowResize()`.  That's probably a more AngularJS way of doing it.

**Comment by DedrickEnc** [comment]
Can you share a link where it is discussed to make things more clear for the developer who is going to take this issue?

**Comment by jniles** [comment]
A link to what?  Unfortunately, the `ui-grid` documentation is pretty poor.

The clearest place to see what is meant is the [ui-grid-auto-resize directive](https://github.com/angular-ui/ui-grid/blob/1c01e74/src/features/auto-resize-grid/js/auto-resize.js#L15).

We could copy exactly this, but instead of `setTimeout()` use

``` js
$scope.on('nav:toggle', grid.core.handleWindowResize);
```

This avoids a `setTimeout()` loop running continuously in the browser.
