### ISSUE TITLE
Move `is_medical` property from employee to title

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7170]
Based on  https://github.com/IMA-WorldHealth/bhima/pull/7159#discussion_r1271467056

> Can we move the is_medical to the title_employee table? It seems like is_medical has to do with the employee's job title, not the employee themselves, right?

This issue to be closed by removing the property from the employee table and putting it on the profession, title, or some other table where it is appropriate.

**Comment by lomamech** [comment]
Hello @jniles  what do you think? Should Pull Request #7159  be merged first just because the creation of the title_employee management module has been fully implemented in this PR? or reimplemented title_employee handling in this new Issue?

**Comment by jniles** [comment]
Hi @lomamech, I don't think this issue should block any code mergers.  It is mostly related to code cleanliness.
