### ISSUE TITLE
(design) Saving Reports for Later

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#718]
In the current version of 2.x, the reports generated by any of the `render/*.js` are shipped back to the client and never stored on disk.  This is a great default behavior, but it would be nice to save the exact generated report for later.

I propose that we add that any reports that can be saved should add the flag `?saved=1` to the URL.  The [ReportManager](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/server/lib/ReportManager.js) can then write the PDF to a file for future lookups.  This would allow the Report Pages (see #694) to create a URL to past reports.

**Comment by mbayopanda** [comment]
@jniles 
It is interesting, but my worry is about the disk space storage and reports which are configurable (Ex. cashflow: we have to set the cashbox and dates).

**Comment by jniles** [comment]
@mbayopanda thanks for the feedback.

Only the report PDF document would be saved, not the report parameters.  On my machine, the voucher registry with minimal information is 18Kb.  I expect our larger reports won't exceed 1Mb.  That means, on a machine with 20Gb of free space, we can store ~20,000 PDF reports comfortably.

Not every report will be saved - only those saved via the Report Page.  By default the PDF will simply be sent to the client and never written to disk.

**Comment by DedrickEnc** [comment]
And do we have already a Technic for looking up reports?

**Comment by jniles** [comment]
Nope - we generate a new report every single time we look one up.

**Comment by jniles** [comment]
This was closed in #832.
