### ISSUE TITLE
Fiscal year opening

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#721]
This issue is about a proposal for the fiscal year opening / fiscal year creation : 

This is current state of creation of fiscal year 

![new fiscal year](https://cloud.githubusercontent.com/assets/5445251/18507645/1083d28e-7a26-11e6-9ea5-29f75ba08dc4.jpg)

My proposal is : 
1. Add the previous fiscal year in the fiscal year creation form 
2. Check if the previous fiscal year is set or not to launch the `opening balance configuration` modal : 
- If the previous fiscal year is not set, we can define the opening balance or not

![opening-balance](https://cloud.githubusercontent.com/assets/5445251/18507752/86aee714-7a26-11e6-8ecf-10cf5391c3d8.png)
- If the previous fiscal year is set, launch the `opening balance configuration` modal with default values which cannot be modified, these values come from the previous fiscal year balance (period `0` if adopted)

![opening-balance-disabled](https://cloud.githubusercontent.com/assets/5445251/18508089/a66e3496-7a27-11e6-8574-ddbbcfe631c0.png)

**Comment by mbayopanda** [comment]
@jniles @DedrickEnc could you look this issue

**Comment by jniles** [comment]
@mbayopanda, the procedure seems fine to me.

I think a modal limits the amount of space for information. Why not put it in the page?

**Comment by mbayopanda** [comment]
@jniles you're right, with some account label we must have enough width space

**Comment by DedrickEnc** [comment]
@mbayopanda 
Seems good to me, Patrick should have a look and We should also have a definitive decision about period 0.

**Comment by jniles** [comment]
@mbayopanda, I think this issue was closed with #737, correct?

**Comment by jniles** [comment]
Closed in #737.
