### ISSUE TITLE
Clean up ODK residue and refactor ODKSettingsService

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#7214]
There are still some left-over ODK-related files in BHIMA after the recent [PR 7199](https://github.com/IMA-WorldHealth/bhima/pull/7199) to remove them.  For instance, the `odk.json` translation files are still there.

Also the ODKSettingsService module needs to re refactored.  It is currently only needed by the Admin/Users and Permissions Management page to generate QR codes for the users.  That should be refactored into a new service (or extend some other service) to create QR codes.   The current wording indicates that the QR code is for ODK purposes.  If it is only for ODK, the perhaps this QR code funcationaly can be removed entirely and the ODKSettingsService can simply be deleted.

To duplicate the current error:
   - use bhima_test
   - go to the `Administration / Users and Permissions Management` page
   - enable the browser dev tools console display
   - For one of the users, use the action menu "Generate ODK QR Code" and note the error.

**Comment by jniles** [comment]
The QR codes for users are actually logins for the ODK central server.  So my fix for this will be to remove that functionality entirely.
