### ISSUE TITLE
(refactor) Remove all Stock Management code/tables

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#722]
In preparation for more work on the stock and inventory management modules, it would be helpful to remove all 1.x code related to these modules.  In this way, we can start design fresh with the freedom to expand beyond 1.x.

**Comment by DedrickEnc** [comment]
Got it and new landed modules should configure their routes in a separate file if possible.

**Comment by jniles** [comment]
@mbayopanda, you've done the most work with Stock Management... has this been addressed satisfactorily?

**Comment by jniles** [comment]
Ping @mbayopanda.

**Comment by jniles** [comment]
Closing as out of date.
