### ISSUE TITLE
Link stock movements to user project

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#7234]
This issue is about linking stock movements to user projects

How: 
- Add the project ID in the stock movement table
- Add filter in stock registries for project

**Comment by jniles** [comment]
What is the use-case for this?   I remember we originally created projects to deal with symmetricDS and the Tshikaji-PAX asynchronous connection, but we haven't really used them since.  Why do they need to be attached to stock movements?

**Comment by jniles** [comment]
Closing this for the moment.  If we can think of a good use case, we'll reopen and propose a design.
