### ISSUE TITLE
Auto insert the base grade salary for employee when "Grade" is selected

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#7236]
When registering or editing an employee, when the grade is selected, the base salary for that grade should be inserted into the "Salary" field (unless it already has data).  In this screen shot, when a grade is selected, the Base Salary from that grade should be inserted in the "Basic Salary" field on the right.   Note that Grade Management shows a "Base Salary" for each grade, so this seems like the correct amount to insert into the "Basic Salary" field for new employees.    If the adminstrator has already added a basic salary, it should not be overridden.   And of course the Administrator can edit the field and change it as desired.  But it seems like the basic salary for that grade is the correct value to insert as a default.

![image](https://github.com/IMA-WorldHealth/bhima/assets/62145/bcdb9603-db65-4beb-85d8-7c7fd61e91af)

Obviously, this could be edited before saving/updating the employee.

**Comment by jniles** [comment]
Do you know the relationship between the "salary" referred to here and the base salary?  Does this replace the base salary in computations?

**Comment by lomamech** [comment]
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/e99a17a4-eee6-40f2-bc8b-b43b94e8d7c8)
With the Payroll system, if when registering an employee 0 is mentioned as *Individual Basic Salary* the system will automatically assign to this employee the salary corresponding to this grade.

**Comment by jmcameron** [comment]
My suggestion is:  When selecting a grade for the employee, if there is already a base salary set, do not change it.  If not, insert the base salary for the grade.  They can always edit it later.   This would simplify adding an employee since you would not need to abort creating an employee to look up the base salary for their grade before starting creating the employee a second time.
