### ISSUE TITLE
(refactor) Report Routes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#724]
So far, 2.x has lacked a standard style of implementing reports.  In particular, we do not have a defined URL structure

**Proposal**
We group reports by their type (Finance, Inventory, Medical, etc).  The Chart of Accounts report already uses this syntax, as well as cashflow.  See #684 and #696.

| Current Route | Proposed Route |
| :-- | :-- |
| `/reports/patient/registrations` | `/reports/medical/patients` |
| `/reports/patient/:uuid` | `/reports/medical/patients/:uuid` |
| `/reports/purchases/:uuid` | `/reports/inventory/purchases/:uuid` |
| `/reports/finance/aged_debtors` | `/reports/finance/debtors/aged` |
| `/vouchers/reports` | `/reports/finance/vouchers` |
| `/vouchers/receipts/:uuid` | `/reports/finance/vouchers/:uuid` |
| `/invoices/patient/report` | `/reports/finance/invoices` |
| `/inventory/reports/metadata` | `/reports/inventory/items` |

All added reports would expect to abide by the same conventions.

The Report Page (#694) would just as `/saved/` to the URL route for performing CRUD on saved reports.

@DedrickEnc @mbayopanda Comments?

**Comment by DedrickEnc** [comment]
I think grouping entity in a kind of name space is not bad.
 What will be the route for seeing the list of invoices of a particular debtor?

**Comment by jniles** [comment]
Hmm..  I would think something like `/reports/finance/debtors/:uuid/invoices` or `/reports/finance/patients/:uuid/invoices`, unless there is a better name for that kind of report.  Do you mind making an issue for that report?

**Comment by DedrickEnc** [comment]
I think for the finance context debtor is a better name.

**Comment by jniles** [comment]
That makes sense to me.  The `:uuid` should be a debtor uuid anyway!

**Comment by jniles** [comment]
I'll take this one.
