### ISSUE TITLE
(bug) Purchase Orders broken

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#726]
For some reason, the `ui-grid-cellNav` on the Purchase Orders page has made the grid uneditable.  I propose we remove the `ui-grid-cellNav` feature - it doesn't really have a use anyway.

**Steps to Reproduce**
1. Go to `/purchase/create`
2. Enter any supplier
3. Attempt to fill in the first inventory item.

**Expected Result** 
Inventory items should show up in a typeahead.

**Actual Result**
The input cannot be selected since the `cellNav` captures all the inputs.

**Comment by DedrickEnc** [comment]
You suggestion works for me.
Why our end to end test did not prevent bugs?

**Comment by jniles** [comment]
I'm not sure...  I'll investigate after #694 is in.
