### ISSUE TITLE
(refactor) Change all account typeaheads to uiSelects

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#727]
The `ui-select` bridges a nice gap between typeahead and a dropdown select.  I propose that we refactor all our account `uib-typeahead`s to use `ui-select`s.  The testing hooks already exist, so this is purely a UI change.

@DedrickEnc @mbayopanda what do you think?

**Comment by DedrickEnc** [comment]
I agree, it is natural to use a right component for a right purpose.

**Comment by jniles** [comment]
I'll take this.
