### ISSUE TITLE
The "releve de compte" report has required fields marked "optional"

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7288]
In the Releve de Compte report, we have required fields (default filters) marked at "optional".  They should not be optional, as they are required.  See below:

<img width="996" alt="image" src="https://github.com/IMA-WorldHealth/bhima/assets/896472/7280df42-6d0e-4177-a22d-64ec5cb55b5b">

**Comment by Ebed-meleck** [comment]
Go to Finance > Report > Account Statement.  Nothing will show.   Click on [Search] and then the [Defaults] tab.  Choose All Time, submit. Now see a variety of accounts listed.  If no account is selected in the search dialog, the search is not limited.  So I think it should be optional (not required).

@jniles can reopen it if you think we are wrong.

**Comment by jniles** [comment]
Hi Ebed,

Thanks for tackling this issue!  I am pretty sure a "Releve de Compte" is only supposed to be for a single account in accounting, so showing multiple accounts is also incorrect.  Instead, it should show posted transactions for a single account.  You can check with @mbayopanda if I am wrong - he is the project lead and I will respect his decision.

If we do allow multiple accounts, I would propose that we should remove this module entirely.  It will not add any value over the posting journal.

**Comment by jmcameron** [comment]
> Hi Ebed,
> 
> Thanks for tackling this issue! I am pretty sure a "Releve de Compte" is only supposed to be for a single account in accounting, so showing multiple accounts is also incorrect. Instead, it should show posted transactions for a single account. You can check with @mbayopanda if I am wrong - he is the project lead and I will respect his decision.
> 
> If we do allow multiple accounts, I would propose that we should remove this module entirely. It will not add any value over the posting journal.

Thanks for this info.  I was the one that didn't understand this and suggested this approach to Ebed.  Looking forward to what Bruce says!
