### ISSUE TITLE
Improve the documentation for running in production

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7315]
The BHIMA documentation for installation is pretty good and has seen several revisions.  It is found at https://docs.bhi.ma/en/for-developers/installing-bhima.html.

This documentation is mostly meant for getting developers up and running, and isn't ideal for running in production.  We should add a separate set of instructions for running in production that covers:
  1. Using `nginx` as a proxy so that users don't have to type the :`$PORT` after the url in the web browser.
  2. Setting a strong `SESS_SECRET` variable in the `.env`
  3. Setting up backups using `cron`.

Some optional stuff we might consider adding:
 1. Setting up `.my.cnf` so that system administration is easier.
 2. Encouraging `systemd` over `pm2`.

**Comment by jmcameron** [comment]
@jniles Shouldn't this have been closed by your recent Debian set up PR?

**Comment by jniles** [comment]
I suppose it could be.  I would like to keep working on these issues though.  It probably won't be as relevant if I can get the server to build with docker-compose.

**Comment by jniles** [comment]
I did get the application working with docker-compose, so I'm closing this issue.
