### ISSUE TITLE
Complex Vouchers should create a receipt

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#733]
At the moment, only the Simple Vouchers generate a receipt.  The Complex Vouchers do not present the possibility to present a receipt.  For most transactions, it will be important to see a receipt after the transaction is created.

**Comment by jniles** [comment]
@mbayopanda, was this fixed?

**Comment by jniles** [comment]
@mbayopanda, was this fixed?

**Comment by mbayopanda** [comment]
@jniles yes, it was

**Comment by jniles** [comment]
:+1:
