### ISSUE TITLE
(feature request) Allow webcam to take patient picture

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#742]
On the Patient Record page, we are able to upload patient images.  Since images will likely be taken with a webcam, it would be very nice to upload a patient image directly from the webcam.  This functionality used to exist, but we removed it as we had no way of storing images.  [See this tutorial for inspiration](https://www.jonathan-petitcolas.com/2016/08/24/taking-picture-from-webcam-using-canvas.html).

**Comment by jeremielodi** [comment]
@jniles, this issue should be closed, I have already worked on it.

**Comment by jniles** [comment]
Sounds good!
