### ISSUE TITLE
Finance Dashboards not working

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#7430]
If you go to the Finances dashboard under 'Dashboards', it does not show any data.
After a bit of digging, apparently the database queries in `server/controllers/finance/indicators/dashboard/collect.js` are not producing any results.   

Examining the SQL code, it looks like some of these SQL queries rely in the tables 'hospitalization_indicator', 'finance_indicator' etc.  Further work needs to be done to track down why these tables are not being regenerated.

**Comment by jniles** [comment]
@jmcameron these tables are never generated, they are manually input.  So, I do not believe this is a bug, it is intended functionality.

**Comment by jniles** [comment]
I'm going to close this issue in favor of a proper design for finance dashboards.
