### ISSUE TITLE
Error message when trying to lock a user

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7446]
It is noted that it is no longer possible to lock a user, this issue proposes to resolve this problem.

**Comment by lomamech** [comment]
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/9386bc1c-cbfb-4fea-b613-4f2d04a63866)

**Comment by jniles** [comment]
Also reported here: https://github.com/IMA-WorldHealth/bhima/issues/7422
