### ISSUE TITLE
Users report 5% pay code increase does not work

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7454]
At Vanga, they recently paid their employees this year.  Several potentially relevant pieces of information:

  1. It is a new fiscal year
  2. They added ~8 employees to the organisation
  3. They had two employees that were absent the entire month, and attempted to model this by putting in negative "jours supplementaire" instead of just putting 0 days worked.

The last point caused havoc, as you might imagine (https://github.com/IMA-WorldHealth/bhima/issues/7452). 

However, we also received this feedback from the Vanga team:

> The other problem was the 5% pay code increase did not show up on the calculation.  I recommended we just pay today and work with the BHIMA team to see if this can be corrected prior to payday in February.

I believe that the 5% yearly increase is supposed to happen automatically.  We should investigate why it is not being applied and ensure that it isn't a bug in BHIMA.  We can probably improve our user interface so that users know if it is being applied or not as well.

**Comment by jniles** [comment]
This may or may not be related, but we might consider refreshing the session parameters from the database when a user makes payroll calculations.  For example:

https://github.com/IMA-WorldHealth/bhima/blob/2580145f3632f536e3c4a14e80c406cb1805611a/server/controllers/payroll/multiplePayrollIndice/paramter.config.js#L33-L35

In the above, the percentages are read from the `req.session.enterprise` object.  This might get stale if the user has not logged in for a long time.  Instead, let's use the `enterprise_id` to read out the new parameters to make sure we are always up to date.

**Comment by lomamech** [comment]
![image](https://github.com/IMA-WorldHealth/bhima/assets/8035588/b647b675-0500-4f53-93ff-cb24e91c4933)
I have just redone the payroll simulation with Index by configuring the increment percentage of the base index, and I did not find any errors, the calculations are correct,
