### ISSUE TITLE
Unable to display the item in stock and batch in stock register due to the error ER_DIVISION_BY_ZERO  

### ISSUE THREAD

**Issue by Ebed-meleck** [Third-Culture-Software/bhima#7461]
This error was produced during training, say after users added the batches. Once we go to the item in stock and lot in stock register. This error message appears.This error is due to the fact that a division by zero is reproduced when calling the GetAMC procedure. As shown in the console image
<img width="932" alt="Screen Shot 2024-02-02 at 19 03 10" src="https://github.com/IMA-WorldHealth/bhima/assets/63899331/4a5f870b-2ccc-4ed7-8b96-ab4f2b41e538">

This crashed both registers

**Comment by jniles** [comment]
Just a note - https://github.com/IMA-WorldHealth/bhima/issues/6876 already reported some problems related to CMM - it might be worth looking more deeply at issues around calculating the CMM while you are doing your installation and making sure it works according to the design.

The design was proposed in https://github.com/IMA-WorldHealth/bhima/issues/4864.  More details related to stock outs were discussed in https://github.com/IMA-WorldHealth/bhima/issues/4346.

**Comment by Ebed-meleck** [comment]
Closed via #7462
