### ISSUE TITLE
Use multer instead of connect-mutliparty for uploads.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#75]
The [connect-multiparty README](https://github.com/andrewrk/connect-multiparty) recommends using the multiparty API directly.  However, the [multiparty README](https://github.com/andrewrk/node-multiparty/) recommends that implementers look into [busboy](https://github.com/mscdex/busboy) as a faster alternative.  It seems that none of these projects are very stable.

I have experience using [multer](https://github.com/expressjs/multer) in a separate app, and it is part of the official ExpressJS ecosystem.  I suggest we migrate to using it for future uploads and migrate our existing code to use that module instead.

**Comment by DedrickEnc** [comment]
@jniles  assign a label for your issue please!
