### ISSUE TITLE
Generic Confirm Dialog Modal

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#759]
We have a confirm deletion modal #348 

![confirm deletion](https://cloud.githubusercontent.com/assets/5445251/18947884/afc5f51a-85e9-11e6-9310-550f34e7ae50.png)

this one is only for deletion but if we want to confirm an important action in the same way, we can have a generic confirm dialog modal. 

My proposal is : 
1. Extend the Confirm Deletion Modal by updating the message displayed according the context.
2. Create a new module

**Comment by jniles** [comment]
Seems like a good idea.
