### ISSUE TITLE
Allow builds to be either HTTP or HTTPS

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#76]
This proposal concerns the bhima build system.

I propose that we allow optional SSL.  In production, you should _always_ use HTTPS to protect your data; however, many virtualization and testing frameworks do not support SSL.  It would certainly make our integration and end to end tests more clear.

To accomplish this, we will include the following flag in the `.env` environmental variables:
- `BHIMA_USE_TLS` = { 0 || 1 }

We should also rename the previous `TLS_CERT` and `TLS_KEY` flags to use the `BHIMA` prefix.

An application built with TLS will continue to function as the current build.  An app built without TLS enabled will import `http` instead of `https` and not require the certificate or keys to be imported.

Finally, if the application is not built with TLS, there should be prominent console warnings on boot up, telling the user that running data over an unencrypted network is dangerous.

**Comment by sfount** [comment]
Agreed. I made an issue on this on the previous repository - serving node
over HTTP (with a reverse proxy to serve HTTPS). I think this flag is a
reasonable compromise as it is crucial the production builds use HTTPS.

**Comment by jniles** [comment]
Awesome, I'll have a PR in tomorrow with this change.  I'm running into bizarre errors in #74, and this would reduce one variable.
