### ISSUE TITLE
Add a Receipt for Transfer operation in the payment module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#760]
The transfer operation is : 

![virement et transfer](https://cloud.githubusercontent.com/assets/5445251/18949015/45acff02-85ee-11e6-87b4-11a8da58c880.png)
1. Virement : Made with the transfer operation in the payment module, this step produce a `Document` that the accountant use for making a transfer voucher in the principal cashbox if necessary
2. Transfer Voucher : Made with the voucher module, the accountant made a transfer voucher based on the `Document` generated in `1. Virement` step.

This issue is about the generation of this `Document` and update the transfer module by displaying the balance in the `Virement account` which can help to see money which are not yet transfered.

**Comment by jniles** [comment]
It seems to me that if the `transfer` uses a simple journal voucher, we can just use the Journal Voucher receipt for this.  @mbayopanda would that work?

**Comment by jniles** [comment]
@mbayopanda, @sfount, what is the state of this issue?  Do we have receipts for transfers yet?  If so, can someone make one?
