### ISSUE TITLE
Need a way to post into the general ledger data for period `0` and `N+1`

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#761]
In the need of working with balance which are in the period `0` and period `N+1` of a fiscal year we have to find a way to post in the general ledger this data which are correctly written in the journal.

The problem is : 
- We cannot post transactions which are in a bad period (based on the period_id and data), in our case data in the journal for the period `N+1` has date = last date of the fiscal year and period_id = the Id of the period `N+1` of the fiscal year, so the posting manager consider these transactions like bad transactions because they have bad period (the date is not in the period given).

Solution : 
- Found a way to add an exception for period `0` and `N+1` when posting to the general ledger

**Comment by jniles** [comment]
Why exactly does the Trial Balance reject transactions made on the last day or first day?  It seems to me that it should be inclusive.

Jan 01, 20xx 00:00:01 should be a perfectly valid transaction date for a fiscal year that starts on Jan 01, 20xx.  Is this not the case?

**Comment by mbayopanda** [comment]
The date of transaction is not a problem but the `period` is the problem, when transactions are written in the journal they have a `date` and a `period (0 or N+1 in our case)`. for the `period 0 or N+1` the date range is not defined `(start_date= null and end_date = null)`. So, the transaction is considerate as invalid because the date of the transaction is not in the period date range  `(start_date= null and end_date = null)`.

**Comment by jniles** [comment]
Ah, I understand.  Okay, I'll think about it.

**Comment by jniles** [comment]
@mbayopanda, did this ever get solved?

**Comment by mbayopanda** [comment]
@jniles not yet

**Comment by jniles** [comment]
I believe this is superseded by #1651.
