### ISSUE TITLE
Categorize Debtor Group: Distinguishing Insolvent and Solvent Entities

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7674]
To enhance our financial management system, we propose categorizing the debtor group into two distinct categories: Insolvent and Solvent. This categorization will allow for more precise tracking, reporting, and decision-making regarding outstanding debts.

**Comment by jniles** [comment]
@lomamech can we introduce other business rules around this flag besides reporting?  For example, an insolvent debtor group probably should not accept new patients or have new invoices generated against it.  Would the hospital requesting this flag agree?

**Comment by lomamech** [comment]
> can we introduce other business rules around this flag besides reporting? For example, an insolvent debtor group probably should not accept new patients or have new invoices generated against it. Would the hospital requesting this flag agree?

The Bhima system blocks admission and billing for patients belonging to locked debtor groups, so it may be necessary to simply lock the debtor group,
