### ISSUE TITLE
Add Feature: Group Accounts into Categories for a Synthetic Cash Flow Report

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7675]
To enhance our financial management system, we propose categorizing the debtor group into two distinct categories: Insolvent and Solvent. This categorization will allow for more precise tracking, reporting, and decision-making regarding outstanding debts.
- Improved Risk Management: Differentiating between insolvent and solvent debtors will help the team assess financial risks more effectively, enabling more strategic planning and interventions.
- Optimized Collection Strategies: By identifying which debtors are insolvent, we can tailor our collection strategies to focus efforts on recovering debts from solvent entities, improving overall efficiency.
- Enhanced Reporting Accuracy: Categorizing debtors allows for clearer and more accurate financial reporting, which is crucial for internal audits and external stakeholder communication.
- Legal Compliance: Proper categorization ensures compliance with relevant financial regulations and standards, reducing the risk of legal complications.

**Comment by jniles** [comment]
Could we just lock the debtor group and visually display that in the report?  For example, I think we have the ability to filter out locked accounts in some reports.  In this case, we could just filter out locked debtor groups.
