### ISSUE TITLE
Bug: Report renderer uses fixed substring for logopath, breaking custom logo paths.

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7679]
The current report manager uses a fixed number (`7`) to parse the logo string.  IMCK uses a custom path for its logo, so it caused intermittent crashing when the reports could not load the logo into the reports.  Here is the code in question:

https://github.com/IMA-WorldHealth/bhima/blob/fd3b7e2d397a3e22546778a8e05038bed4795bc5/server/lib/ReportManager.js#L160-L165

And here is the error caused:
![image](https://github.com/user-attachments/assets/39ef0cd3-9b30-4b47-b6d7-9b13dfa79b3e)

This file path should be `bhima-uploads/pics/...` but is truncated by the `substring()` call.  We should figure out a better solution for this code.

I can see two alternatives:
 1. We treat the logo path as absolute (e.g. it must start with `/home/bhima/example/pics/` or `C:\Users\bhima\example\pics`) and simply inject the logo directly into the HTML file.  This might require updating the `uploader` code.
 2. We treat the logo path as relative and merge with the application's current path. 

In both cases, we should probably check that the logo path is well defined using [`fs.access()`](https://nodejs.org/api/fs.html#fspromisesaccesspath-mode`).  For example:

```js
const { access, constants } = require('fs/promises');

try {
  await access(metadata.enterprise.logo, constants.R_OK)
  // logo is readable, proceed to render as normal.
} except (e) {
  // logo is not readable, use a fallback
  metadata.enterprise.logo = '/some/default/logo/that/ships/with/bhima'
  // OR
  // delete metadata.enterprise.logo
} 

await render(template, options);
```

**Comment by lomamech** [comment]
I have also noticed for some time, when launching the test database, the icon images no longer appear
![image](https://github.com/user-attachments/assets/d49d908a-f739-486a-8671-3ec65607ab5b)

And when I look at the images in bhima-2.X\client\src\assets 
![image](https://github.com/user-attachments/assets/8d6ff1b2-2a16-4613-bd6d-f1dc08163fd5)

and after execution the images that appear are corrupted and different from the original
bhima-2.X\bin\client\assets
![image](https://github.com/user-attachments/assets/552284b2-0ec9-48b4-b9a2-0a05be41f86a)

**Comment by lomamech** [comment]
I don't know if all these problems are related because in my local version even without the image, I still have the problem with puppetter

![image](https://github.com/user-attachments/assets/fcfcd44e-598b-410b-b16d-cef64f6fc370)

**Comment by jniles** [comment]
I'm not sure if the puppeteer error is related.  It looks like chrome isn't starting.  Here are some things to try:

 1. Make sure all your node modules are up to date using `npm`.
 2. Make sure you have chromium or google chrome installed and accessible on the command line.  I'm not sure what kind of environment you are running, but one way to check in linux is `which chromium` or `which google-chrome`.  This will give you the path to the browser.
 3. Once you have identified the browser, set the `PUPPETEER_EXECUTABLE_PATH` environmental variable to point to the path to the browser. The easiest place to do this is in `.env`.  For example, it might look like this:
```sh
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
```

See if that changes anything.
