### ISSUE TITLE
Implement a filter for a telephone number

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#77]
There are a few places we need to display telephone numbers in the application (receipts, reports, lists of users, etc).   A handy component to have would be a telephone filter.  Something that could be easily embedded in a view such as this:

``` html
<span>{{ patient.telephone | telephone }}</span>
```

... to yield a nicely formatted telephone number (e.g. +243 821 453 233).

**Comment by DedrickEnc** [comment]
How the system will know about the code, we will deal with `locale.js` (**_locale.js is the right name ?**_)? because each country has is own code for telephone number.

**Comment by jniles** [comment]
This filter would only use information provided by the user.  So, if the user writes "0821238945", it would render `082 123 8945`, instead of trying to guess the country code.

... if we wanted to get all the information possible, on the telephone `<input type="telephone">` we might put a drop down for every country code, preloaded into the application.  But I think it is too much work for little benefit at the moment.  It's a good idea though!  Maybe we can plan it as a long-term feature to add polish.
