### ISSUE TITLE
(bug) Latest Bill should show 'No Invoices Recorded for this Patient'

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#771]
The Latest Bill for the patient shows an empty box when there is no bill recorded for the patient.  This leaves the application looking broken.  See the screenshot below.

![latestbillemptystate](https://cloud.githubusercontent.com/assets/896472/19071367/a932e4aa-8a27-11e6-84d3-9bb05621de96.png)
_Fig 1: Latest Invoice Empty State_

This state was specified by the design, but apparently unimplemented.  See #625 for the appropriate behavior.

**Steps to Reproduce**
1. Wipe all patient invoices or wipe invoices for a particular patient
2. Load the patient's record page.

**Expected Result**
1.  A 'No Invoices' message.  See #625 for more details.

**Actual Result**
1. An empty, broken page.  See Fig 1.

**Comment by sfount** [comment]
@jniles I believe this issue was resolved in a pull request over the last few weeks; can you confirm that?

EDIT
**Current Behaviour**
![screenshot 2016-11-14 at 10 56 43](https://cloud.githubusercontent.com/assets/2844572/20260253/18980d4c-aa59-11e6-9f63-eb80a9f20725.png)
