### ISSUE TITLE
(feature) Complex Vouchers should load Cash Payments

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#786]
The Complex Vouchers page allows a user to import records from Cash Payments, Patient Invoices, and previous Vouchers.  Currently, only the Patient Invoices and Voucher grids are defined, but not the Cash Payments grid.  See below:
![complexvouchercashpaymentsmodal](https://cloud.githubusercontent.com/assets/896472/19153578/09aadace-8bcf-11e6-91da-74718e52f6af.png)
_Fig 1: Empty Cash Payments Grid_

Before 2.x can be marked as complete, this grid must be finished, with the ability to import data from the cash payments table.

**Comment by mbayopanda** [comment]
@jniles i could take this one

**Comment by jniles** [comment]
Go for it! :+1:
