### ISSUE TITLE
(bug) 'Last Visit' column of the patient registry does not display last visit

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#789]
In the Patient Registry, the column `Last Visit` does not display the last visit.  In theory, it should give the most recent patient checkin date.

**Steps to Reproduce**
1. Register a new patient
2. Observe that the patient has no 'Last Visit' date in the patient registry
3. Check the patient in from the Patient Record page.
4. Return to the Patient Registry

**Expected Result**:
The patient should have the date in the 'Last Visit' column.

**Actual Result**:
The column remains blank.

**EDIT**
Just noticed that the Hospital Number column also does not work.  These are likely the same bugs.

**Comment by DedrickEnc** [comment]
Will take this one

**Comment by DedrickEnc** [comment]
After reproducing steps, I noticed the module works fine so I am closing this issue.
