### ISSUE TITLE
(feature) Add ui-grid aggregation footers to all registry pages.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#790]
Our `ui-grid` gives us a powerful footer to show aggregate data.  The documentation can be found [here](http://ui-grid.info/docs/#/tutorial/105_footer).

Our registry pages currently do not support aggregation, except through grouping.  This is often not appropriate.

I propose that we introduce footers with aggregation on most numeric columns.  For example, the Invoice Registry could sum the amount of money billed and count the number of records in the current view.  Similarly, the cash payments page should sum the amount of money paid.

**Comment by jniles** [comment]
@mbayopanda, can you work on this when you are done with your current task?

**Comment by mbayopanda** [comment]
it's LGTM 👍

**Comment by jniles** [comment]
Thanks!

**Comment by jniles** [comment]
I think this was closed in #798.
