### ISSUE TITLE
(feature) Implement the cash payment registry

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#799]
This issue is about an implementation of the cash payment registry with some ui elements as for `Patient invoices registry`

![patient invoice](https://cloud.githubusercontent.com/assets/5445251/19345274/85cb915c-90f2-11e6-91e8-2349361a49a4.png)

**Comment by sfount** [comment]
@mbayopanda Can you confirm this feature was merged with master?

**Comment by jniles** [comment]
@sfount, confirmed verbally.
