### ISSUE TITLE
(chore) setting up real accounts list

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#804]
This issue is about to set real and correct accounts list.

We have to set basic account list (until four digit in OHADA system), example : 

```
10 CAPITAL
   101 CAPITAL SOCIAL
      1011 Capital souscrit, non appelé
      1012 Capital souscrit, appelé, non versé
      1013 Capital souscrit, appelé, versé, non amorti
      1014 Capital souscrit, appelé, versé, amorti
      1018 Capital souscrit soumis à des conditions particulières
```

In the current state of BHIMA we must have real and correct basic list of accounts

**Comment by sfount** [comment]
This is a very good idea. I think this is a part of testing the integrity of the BHIMA 2.x data procedures. We have worked well with test data so far however setting up a realistic data set will ensure all of the processes/ validation work well.

**Comment by jniles** [comment]
I believe Patrick is working on this issue and will provide an Excel account list approved by the Ministry of Health.

**Comment by sfount** [comment]
A valid list of generic/ template accounts was started here https://github.com/IMA-WorldHealth/bhima-demo/blob/settup/data/core/account.sql 

This was actually requested months ago and what surfaced was just Tshikaji's chart of accounts - this list of accounts will be very valuable in validating system outputs/ reports.

**Comment by jniles** [comment]
I'll upload it to a shared(/public?)( Google Drive when we receive it.

**Comment by jniles** [comment]
.
