### ISSUE TITLE
(chore) Add filter and printing option for posting journal and general ledger

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#806]
This issue is about to have a mean of filtering transactions, sorting transactions and printing transactions in the posting journal and the general ledger.

In the current state of BHIMA we cannot filtering and printing transactions which are in the posting journal or in the general ledger.

And if it is possible to have transactions sorted by a descending order (the newest to oldest)

**Comment by jniles** [comment]
Closed in #819.
