### ISSUE TITLE
Balance Report Implementation

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#807]
## Description

The balance report is a list of account and their financial situation (the debit and credit for the previous period, current period, the total debit and the total credit) as shown at the picture.

![img_20161017_110909 1](https://cloud.githubusercontent.com/assets/5418919/19434211/217f7746-945c-11e6-910c-76075f2e0397.jpg)
The header of the balance report

![img_20161017_110957 1](https://cloud.githubusercontent.com/assets/5418919/19434897/eec6bcb6-945f-11e6-843d-47de9bf8512e.jpg)
The footer of the balance report
## Technical Info

The data must be fetched essentially from the general ledger table, and the report will be generated from the server side as PDF document.

What do you think? @IMA-WorldHealth/bhima-core

**Comment by jniles** [comment]
Closed in #853.
