### ISSUE TITLE
(feat) Handling automatically the CAUTION when invoicing a patient

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#808]
This issue is about to handle CAUTION of a patient automatically when invoicing the patient.

We must have a mean to signal to the user of BHIMA who makes invoice that the patient has a CAUTION and if we have to use this CAUTION for an invoice.

### Caution Steps: 

1. Client pay a caution via the `cash payment module`

    - The client will be `credited`
    - The cashbox will be `debited`
    - A caution receipt is generated as proof 

2. Bill the patient : 

    - Display the remaining caution amount, in reality the balance of the client which is `< 0`
    - In this step, the caution displayed is for `just notify` the user that the enterprise must money to the client
    - The caution amount doesn't affect the invoice, invoices are independent to cautions

3. Patient Financial Activities : 

    - Notify also for a remaining caution amount of the client

**Comment by mbayopanda** [comment]
Hi @DedrickEnc , 

What is the state of handling caution. 

Best regards

**Comment by jniles** [comment]
These steps look good to me.  I think you mean the balance of the client that is `> 0`. :)

**Comment by jniles** [comment]
@mbayopanda @DedrickEnc, I don't see a pull request referencing this issue.  I assume it hasn't been implemented and we should schedule someone to do it.

**Comment by jniles** [comment]
I'll be working on this.
