### ISSUE TITLE
Variation Income Expense report Implementation

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#810]
## Description

The Income Expense Variation report, presents all income expense accounts and their balances in the current and the previous fiscal year, there is also a variation number in percentage and in amount to show how each account  behaves through fiscal years (previous and current).
## Technical Info

The data will be fetched from the general ledger or period total (a decision can be made after discussion).
The report belongs to a financial group and must be fully configurable.
- It must give the possibility of subtracting an amount to a specific account
- It must give the possibility of viewing the result with/without an account group (subtracting the value of the account group from the result value)
- It should give possibility of ignoring a specific transaction in the current or previous fiscal year
- It should list incomes accounts in one side and expenses accounts in an other side 

![img_20161017_130120_1](https://cloud.githubusercontent.com/assets/5418919/19437004/3bbfc778-946b-11e6-985f-add4e5ec4487.jpg)

@IMA-WorldHealth/bhima-core

**Comment by jniles** [comment]
@DedrickEnc , what is the use case for ignoring a specific transaction?  That sounds really dangerous.
