### ISSUE TITLE
(chore) Refine translations for patient check in 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#811]
As suggested by @mbayopanda in https://github.com/IMA-WorldHealth/bhima-2.X/pull/795#pullrequestreview-4035736 .

The French used for the action 'check in' may be ambiguous and should be updated in the translation files. 
Suggestions provided: 
- Signaler visite du patient

**Comment by sfount** [comment]
@DedrickEnc This wasn't completed by #795 but was made to track the translation - was the translation done somewhere else?

**Comment by jniles** [comment]
@sfount, can this be closed since we landed patient visits?

**Comment by jniles** [comment]
Closing as outdated - we are now using Patient Visits that are fully translated.
