### ISSUE TITLE
Implement a debtor group age

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#812]
## Description

This issue concerns implementing a report for showing the debt of client by period, periods are : 
- previous fiscal year
- more than six month
- Between three and six month
- less than three month

The grouping period can be discussed, with there is a better suggestion
## Technical Info

The data will be fetched from the general ledger, the report belongs to a financial group, this issue references #636

**Comment by jniles** [comment]
This is kind of a duplicate of #635.

**Comment by jniles** [comment]
This was closed in a merge to master.
