### ISSUE TITLE
Providing a default description in patient invoice

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#820]
Our patient invoice User interface does not let you submit the bill if the description is not provided, so it can be boring for a user to provide a description every time, essentially if the hospital can records a big amount of record per day.
So the user can be lazy and provide a bad description just to be able to post their invoice, so I think a default description is worth.
@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
I agree that for most invoices there are no additional and _required_ notes. This should be auto generated for the posting journal description and can be added to/ changed if required. 

I'll take this one.

**Comment by jniles** [comment]
Sounds good to me.

I recommend that we avoid putting dates in the description, the user should rely on the record date (since that's what the computer will be using for ordering, etc), and if they get out of sync, it will be super confusing.

**Comment by jniles** [comment]
@sfount, have you tackled this?
