### ISSUE TITLE
(bug) Account module doesn't refresh in time the list of account

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#823]
When adding a new account, we must refresh manually the page for displaying the link for inserting children accounts.

Others considerations, if we can align account number on the left and increase the width of the column : 

![account](https://cloud.githubusercontent.com/assets/5445251/19618827/2b838d52-980a-11e6-9140-f976395f9f33.png)

**Comment by jniles** [comment]
This has been closed in master.
