### ISSUE TITLE
(chore) Add update the account type in account module

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#824]
This issue is about to add a mean for updating the account type 
![edit account](https://cloud.githubusercontent.com/assets/5445251/19622292/64d5f710-985b-11e6-99ad-dba509d185cd.png)

**Comment by sfount** [comment]
This feature was actually originally implemented in account management. However it does now make sense to change the account type from an accounting perspective, a balance account can never become a title account for example. As soon as a transaction has used an account it should not be possible to change the account type.

**Comment by mbayopanda** [comment]
Assume that the user make mistake when he did create a new account, and he
want to update the account. For example, the user adds a new account `{
number: 12011010, label: "Capital account", type: "title" }`, and he saw
that the type must be `balance`. How to proceed for update.

I see two possibilities:
- 1. Add another correct account. the bad account is still there.
- 1. Manipulate directly the database via SQL query

2016-10-22 13:47 GMT-07:00 Steven Fountain notifications@github.com:

**Comment by jniles** [comment]
@mbayopanda, @sfount we have supported this feature for some time now.  Closing this issue.
