### ISSUE TITLE
(chore) Add custom patient registration date

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#825]
This issue is about to add : 
- An input for setting a custom registration date 
- A column `created_at` in the `patient` table which track the real registration date

**Comment by jniles** [comment]
Why do we need to add a custom registration date?  What's the use case?

**Comment by mbayopanda** [comment]
In practice, it's can help to register patient who have been registered in physical registry in the past but who   are not in BHIMA, why ? for helping to track correct patient visit in the time, and produce correct report of patient visit.

For developers, we can generate patients as we want with any registration date for needs of demo or simulation data.

**Comment by jniles** [comment]
@IMA-WorldHealth/bhima-core what do you all think of this proposal?

If this is an installation-specific tool, I think it could be developed separately.  I worry about errors if we allow people to change the date on the patient registration module itself.

**Comment by sfount** [comment]
In my opinion any technical reasons for the demo have been resolved over at https://github.com/IMA-WorldHealth/bhima-demo/tree/settup - this uses a different system for ensuring all application times are set correctly. 

I can see the use case for registering a patient in the past but I don't think it's a priority. If we do implement it I recommend that we put it behind a hidden field (Like a 'show more' link) that lets advanced users specify it if they really need to.

**Comment by jniles** [comment]
Note: we implemented hidden fields in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2278.  If someone wants to tackle this issue in a PR, it should be fairly straightforward using the `bhHiddenField` logic.

**Comment by jniles** [comment]
Since this has only come up in the context of testing, I'm closing this issue.  If it comes up in production, we can re-open.
