### ISSUE TITLE
Complete example (standard) for testing component controller and view

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#835]
The pull request https://github.com/IMA-WorldHealth/bhima-2.X/pull/552 was designed to set an example for how to test both a components controller and the view using karma and angular. 

The comments on verifying the functionality of individual functions should be implemented before accepting this as a standard.

**Comment by jniles** [comment]
For services, please see [VoucherFormService](https://github.com/IMA-WorldHealth/bhima-2.X/pull/1687/files#diff-c32e7e35477d887d4c678f7cda50cd39) unit tests.  Implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1687.

For components, take a look at [bhDateEditor](https://github.com/IMA-WorldHealth/bhima-2.X/pull/2678/files).
