### ISSUE TITLE
Harmonize receipts and reports 

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#837]
This issue is about to provide an harmonized format for receipts and reports : 

Proposals: 

A. FOR RECEIPTS

1. Receipt for invoice : 

![facture](https://cloud.githubusercontent.com/assets/5445251/19851858/38dfcee2-9f1d-11e6-874a-582484f8dd52.png)

2. Receipt for cash payment : 

![paiement](https://cloud.githubusercontent.com/assets/5445251/19851870/4a801ed6-9f1d-11e6-9724-b7696798cb10.png)

3. Receipt for voucher : 

![voucher](https://cloud.githubusercontent.com/assets/5445251/19851880/58c1a0fa-9f1d-11e6-8d9c-24974c4ea543.png)

B. FOR REGISTRY 

![registry](https://cloud.githubusercontent.com/assets/5445251/19852313/da508fee-9f1f-11e6-9988-3b58efe6fb1d.png)

**Comment by mbayopanda** [comment]
@sfount what do you think about this.

**Comment by sfount** [comment]
@mbayopanda This looks excellent to me. 

The reason for this harmonisation is to provide a standard document output for BHIMA. Right now all documents produced have been temporarily designed to focus on functionality. 

An example of that can be seen with these three receipts - it is very difficult to know where to look for information on each one. 

![screenshot 2016-10-31 at 12 07 51](https://cloud.githubusercontent.com/assets/2844572/19852306/dce46cba-9f62-11e6-95d0-c493ab66a1cb.png)

**Comment by sfount** [comment]
I think that it would be good to be able to clearly identify the document ID and the date that the document was created on. 

On the current 'Patient Invoice' this is very big and centred right in the middle of the receipt. 

What do you think of putting the document ID (e.g F100) and the date in large text right aligned with the type of document? 

For example: 

FACTURE 
F100 
08/02/2016

**Comment by mbayopanda** [comment]
![date and id](https://cloud.githubusercontent.com/assets/5445251/19853022/e8627148-9f23-11e6-8a8a-0d9a894c330c.png)

**Comment by sfount** [comment]
@mbayopanda That looks great, the style can be refined in the future if required.
