### ISSUE TITLE
Review Filtering the Posting Journal

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#840]
We currently have very basic filtering on the posting journal. As this module will be used frequently to search for and manipulate transactions, this should be iterated on. This issue will track that development. 

- [ ] UI-Grid only totals on expanded groups (this isn't very clear). Currently filtering collapses rows when the inline filter is removed. 

**Features**
- [x] There is no way to know which server side filters have been applied from the client module. This could become very unclear after a number of filters have been applied. The module could use the standard bhima filter component/ utility bar.

**Comment by jniles** [comment]
I think saveState will help address the first issues of groups collapsing.  That feature is described in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1050 and referenced in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1473.
