### ISSUE TITLE
(Design) Advanced Journal Voucher Import Tool

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#843]
This is a design/ proposal for a tool to simplify repetitive and complicated journal vouchers that may take a lot of time and are prone to mistakes. 

This has been discussed before but I have not seen a formal plan to implement. 

The tool would allow an accountant to 'import' many transactions at once and would be responsible for correctly linking entity and reference documents to ensure that the correct procedures are followed.

A dropdown menu at the top would provide the different import tools available.
![journal voucher import](https://cloud.githubusercontent.com/assets/2844572/19928954/3eb1be58-a101-11e6-8ea4-9d8e2deee184.png)

Each import tool would define its own modal to configure and select what should be imported. 
![journal voucher import modal](https://cloud.githubusercontent.com/assets/2844572/19928955/404900be-a101-11e6-833a-b14d96990619.png)

In this example an accountant would be coming to pay all or some of the bills invoiced to patients covered by a convention. 
* Select the convention, this will bring up all remaining debts as individual invoices 
* Select which invoices are currently being paid 
* Each invoice is then imported as an individual line (in the journal voucher) debiting the casisse account, each one will correctly reference the invoice being paid 
* A line will be added against the convention account, crediting the convention for the money being received

This is an example of something that could take hours to individually fill in a journal voucher for but would be simple to automate. This follows the 2.X design principle of building robust tools instead of creating a module for every function that must be added.

**Comment by jniles** [comment]
I think this was closed in #860.
