### ISSUE TITLE
(bug) Invoice Registry does not extend to the bottom of the page.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#845]
The invoice registry does not extend to the bottom of the page when the util (filter) bar is hidden.  This leaves an awkward gap at the bottom of the module.  See below:

![awkwardregistrygap](https://cloud.githubusercontent.com/assets/896472/19967683/b54a14cc-a1d1-11e6-9635-5f6756b41ae7.png)
_Fig 1: Awkward Spacing at bottom of Invoice Registry_

**Comment by sfount** [comment]
👍. This behaviour should be standardised across all `ui-grid` pages that have a filter bar. A number of pages implement a permanent filter bar and others act like this; a standard experience would be a good improvement.

**Comment by jniles** [comment]
Closed in https://github.com/Vanga-Hospital/bhima-2.X/pull/42.
