### ISSUE TITLE
Proposal: Skip tests of unused modules

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#849]
I propose that we skip test for modules that are only partially developed or not yet designed to speed up our testing process.  The specific modules I have in mind are:
 1. Section Bilan
 2. Reference
 3. Reference Group
 4. Result Section
 5. Employee

If we remove these modules from tests until they are complete, we might see some nice speedups in our Travis testing.

@IMA-WorldHealth/bhima-core what do you all think?

**Comment by sfount** [comment]
Modules 1 - 4 have not designed to have a purpose in 2.X. Are they still relevent to BHIMA Core Administration, Hospital or Finance? 

If not then I propose that we don't need to keep the code in the repository. 
Nothing to do with employees has been designed however it will definitely need to be included eventually.

**Comment by jniles** [comment]
@sfount, how disruptive will it be to remove those modules all out?
