### ISSUE TITLE
Proposal: Implement uib-datepicker for certain date inputs.

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#85]
Angular UI's datepicker has come a long way in recent releases.  The advantages of using `uib-datepicker` for (certain, if not all) date inputs are the following:
1. Consistent cross-browser and cross-browser-versions behavior.
2. Custom styling can be applied to the `uib-datepicker` implementation, [whereas styling for the `<input type="date">` is limited and browser specific](http://stackoverflow.com/questions/14946091/are-there-any-style-options-for-the-html5-date-picker).
3. Custom date formats are possible. 
4. We can translate all the text on the `uib-datepicker` dynamically using `$translate`, which removes a dependency on the users' browser settings.
5. Large area leads to less user input errors.

May be related to #58.

**Comment by DedrickEnc** [comment]
Since we begin to use uib-datepicker, I can close it!

**Comment by jniles** [comment]
I would feel better about closing issues only when then land in master in the future.  A feature isn't worth anything until it has proper tests written and is actually being used in the application.
