### ISSUE TITLE
(fix) Reporting Modules must notify for file not found

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#854]
Reporting modules must notify user when document are not found on the disk. 

The deletion of reports must also be implemented.

**Comment by jniles** [comment]
I agree.  I think this is also a problem with patient documents and pictures, no?  Since it is shared between all three, maybe we should put this functionality into `NotifyService`?

**Comment by jniles** [comment]
I'll tackle the deletion part of this issue.

**Comment by jniles** [comment]
Delete was implemented in https://github.com/IMA-WorldHealth/bhima-2.X/pull/864.
