### ISSUE TITLE
(Bug) Paying an invoice in full causes a 400 Bad Request

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#858]
Fully paying an invoice in the enterprise currency causes a 400 Bad Request on 1/3 of requests - the issue on the server is a mismatched number of columns. This looks like an issue in the rounding on exchange code.

**Comment by jniles** [comment]
I think this has been fixed in #870.  @sfount can you confirm?

**Comment by sfount** [comment]
@jniles This should have been resolved by https://github.com/IMA-WorldHealth/bhima-2.X/pull/870  and https://github.com/IMA-WorldHealth/bhima-2.X/pull/882.
