### ISSUE TITLE
Convention Payment via Journal Voucher

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#860]
This issue is about to add tool for importing transaction rows for a convention payment. 

1. Click on the `convention payment` button in the toolbar for launching a modal : 

![convention invoices list](https://cloud.githubusercontent.com/assets/5445251/20097351/d2881130-a562-11e6-8a63-9cd50613b13b.png)

The modal contains : 

- An input for selecting the convention 
- When the convention is selected, then : 
  - display in a grid the list of all unpaid invoices of the convention

2. Select invoices to pay and click on the `Select invoices for payment` button

When proceed step 2, you'll see another modal : 

![invoices import confirm](https://cloud.githubusercontent.com/assets/5445251/20097574/f7e6c2f4-a563-11e6-871a-bd40b3545dd0.png)

In this modal, the user must set : 

- The amount to pay 
- The cashbox where the money must go

3. Click on the `import` button, which must : 

- Set the transaction type 
- Set the amount to debit for the selected cashbox 
- Credit convention for each selected invoices 
- Set correct entity and reference

![voucher grid](https://cloud.githubusercontent.com/assets/5445251/20097908/bf42dddc-a565-11e6-9ca7-95e763ac33e0.png)

In this step, we must be sure all credit must not exceed the amount to pay.

**Comment by sfount** [comment]
Personally I think we should avoid having modals on top of modals (as seen in the second mockup). It just becomes very hard to reason about what state you are in and how many layers there are. If we limit the UX to having one modal there is always a guarantee. 

@IMA-WorldHealth/bhima-core What do you think? 

This design is for convention payment implementing the tool proposal https://github.com/IMA-WorldHealth/bhima-2.X/issues/843. 

I would suggest that:
- Cash box selection can go above or below the list of invoices, this would then only use one state for the tool.
- I don't think we need to specify an amount to be paid - as long as all of the invoices are imported and referenced correctly the accountant can adjust the total if the convention is not paying everything fully.

**Comment by mbayopanda** [comment]
👍  I agree with the suggestion to don't specify the amount. Process will be simplified and clear
