### ISSUE TITLE
Ask for full birth date by default 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#862]
Following discussions with the team I suggest that during patient registration a patient's full date of birth is asked for by default and only if they have forgotten the month and day is a year adequate. From our test installation we have seen a lot of bad data around patient's date of birth - swapping this input method could encourage quality of data entry.

I also suggest that we add a flag to indicate that the birth month and day are unknown instead of simply defaulting to June 01 - there is no way in the 1.X dataset of differentiating an actual birth on this day and the default unknown value.

@jniles has suggested this before however I did not see an issue tracking it.

**Comment by jniles** [comment]
I'll take a look at this implementation.

**Comment by jniles** [comment]
Closed in #905.
