### ISSUE TITLE
(Feature) BHIMA Landing Proposal

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#865]
We currently have a placeholder landing page that demonstrates the ability of 2.x dashboards/ available information but does not implement anything useful to the enterprise. 

This mockup is a proposal for the initial landing implementation; this page is predominantly finance focused and shows:
* Current enterprise 
* Current project and project code 
* Enterprise currency 
* Exchange rate to other currencies 
* Currency fiscal year progression/ status
 
* Money that is owed from debtors broken down by groups
* Money that may be owed to creditors 

* Patient check ins
![home_mockup](https://cloud.githubusercontent.com/assets/2844572/20134708/b8c8ae98-a66c-11e6-975f-4f066e6c1788.png)

**Comment by sfount** [comment]
My proposal is that I take this initially and then individual components (graphs, other queries) can be picked up by other developers.

**Comment by jniles** [comment]
This looks like a really nice design.

If it were possible to display patient information to only medical users (doctors, receptionists, etc), that would be ideal.  Similarly, if it were possible to only show financial information to financial users (accountants, cashiers, etc) that would also be nice.  Potentially that requires more infrastructure than we want to implement at the moment.

**Comment by jniles** [comment]
This was mostly closed in #938.  Another issue should be opened if subsequent changes are to be made.
