### ISSUE TITLE
Refactor Cash Transfer

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#872]
Currently the cash transfer system in BHIMA is very manual and complex. As this is a process that will be carried potentially every day if not every week (Auxiliary cash windows into the primary cash box) I think that we should implement tools to mitigate common mistakes. 

My proposal is as follows (this should be updated or changed with any additional ideas). 
- [ ] Fix the cash transfer modules in cash windows
  - [ ] FROM and TO are displayed backwards
  - [ ] There has been an issue with ensuring FC and $ radio selects are up to date with the currency input, this should be verified
- [ ] Journal Voucher import tool as described here https://github.com/IMA-WorldHealth/bhima-2.X/issues/843 for cash transfers. This would allow the accountant to select the Transfer transaction created by the cash window. It would be responsible for: 
* Importing the transfer voucher lines
* Ensuring the caisse and transfer accounts are debited/ credited correctly 
* Linking the transfer in as the reference document correctly 
* Providing a meaningful description 
* Selecting the correct transfer voucher type

**Comment by jniles** [comment]
I'll take a look at the confusing text on this module.
