### ISSUE TITLE
(Bug) Journal Voucher Account Selection UX

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#873]
It is currently impossible to read the text when selecting an account on an advanced journal voucher. Because it is a combo box you cannot even scroll the text once it is selected. 

This is an impossible to use UX and an alternative should be explored. 

![screenshot 2016-11-10 at 10 51 57](https://cloud.githubusercontent.com/assets/2844572/20172079/dc681894-a733-11e6-86e3-0b2a38e4ea0f.png)

**Comment by jniles** [comment]
I'm tackling this.  It's an easy CSS fix.
