### ISSUE TITLE
(Feature Request) Display receipt on successful journal voucher

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#874]
Currently journal vouchers simply display a success notification on successful creation. However advanced journal may take some time to make and having the receipt/ proof of correct transfer would be useful upon completion. 

Current behaviour: 
![screenshot 2016-11-10 at 10 56 23](https://cloud.githubusercontent.com/assets/2844572/20172262/a0ad6b96-a734-11e6-807a-55fe4976f8b2.png)

Expected behaviour: 
Voucher receipt is displayed in standard receipt modal (success message in the top right of the modal)

**Comment by jniles** [comment]
I'll tackle this one after the journal filtering is complete.
