### ISSUE TITLE
(feature request) bhFilterBar component to show/hide filters

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#876]
The bhFiltersApplied component does a decent job of rendering filters.  However, we could do better!

I propose the creation of a new component, `bhFilterBar` that wraps the entire "flex-util" row.  In the HTML, it would look like this:
```html
<div class="flex-header">
  <div class="bhima-title">
   <!--- etc ... -->
  </div>
</div>

<bh-filter-bar
  filters="$ctrl.filtersFmt"
  on-remove-filter="$ctrl.onRemoveFilter(filter)"
  on-clear-filters="$ctrl.onClearFilters()"
  hide-empty="true"
  >
</bh-filter-bar>

<div class="flex-content">
  <!-- ui grid and stuff -->
</div>
```

This component would then allow all of the show/hide code to be contained within the filter bar.  If `hideEmpty` is true, the bar would collapse and the `ui-grid` would be free to take up the remaining space.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
Wrapping this utility in a component is a great idea. A useful feature and very little additional work per module. 
👍

**Comment by sfount** [comment]
As discussed here https://github.com/IMA-WorldHealth/bhima-2.X/pull/878#discussion_r87764156, the method for restricting the length of long filters should be investigated with this pull request. 

Currently descriptions are truncated using javascript, this works however the feasibility/ performance/ maintainability of doing this with HTML should be reviewed.

**Comment by jniles** [comment]
This is basically rendered obsolete with the `bhFilters` directive and classes for expanding/collapsing the ui-grid.  Closing.
