### ISSUE TITLE
(Bug) Invoice and Cash transactions are allowed without rounding enterprise settup

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#877]
An enterprise can be settup without a `gain_accont_id` and `loss_account_id`. These columns are essential for rounding cash transactions. 

Cash and invoice transactions can be made and posted without any of these values set up - this causes errors with NULL accounts being assigned and nonsensical transactions posted to the journal.

**Comment by lomamech** [comment]
I just checked in the management interface of the enterprise but also at the level of the database it is impossible to leave gain_accont_id and loss_account_id empties
