### ISSUE TITLE
(build) use yarn instead of NPM for packages

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#880]
A faster new alternative to NPM was developed by Facebook called [yarn](https://github.com/yarnpkg/yarn).  Probably the largest advantage is speed - [the benchmarks](https://www.berriart.com/blog/2016/10/npm-yarn-benchmark/) place it at 2-3 times faster than npm.

You can try it out by installing it with [windows](https://yarnpkg.com/en/docs/install#windows-tab) or [linux](https://yarnpkg.com/en/docs/install#linux-tab).

@IMA-WorldHealth/bhima-core what do you think?

**Comment by mbayopanda** [comment]
Thanks

**Comment by jniles** [comment]
Closing this as out of the current scope.

**Comment by jniles** [comment]
Reopening this after a discovery the NPM@5 is having [a real hard time](https://github.com/npm/npm/issues/16991) and facing several issues.  I have a feeling that many of my virtual machine builds this summer failed due to `npm install` not actually installing everything.
