### ISSUE TITLE
(refactor) Patient Group Management

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#881]
Patient group management was created before the implementation of individual module routing and `ui-router` module state management. This issue tracks refactor requirements for this module to be complete.

- [ ] Rename module to 'Patient Group Management' inline with 'Debtor Group Management' (or decide on naming convention)
- [ ] Use `ui-router` state based routes and structure
- [ ] List debtor groups with additional information as proposed in management structure design https://github.com/IMA-WorldHealth/bhima-2.X/issues/270

**Features**
- [x] Implemented billing service/ subsidy subscriptions for patient groups

**Comment by jniles** [comment]
Note - related to #256.

**Comment by jniles** [comment]
Note: Billing Service + Subsidy integration was complete in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2887.
