### ISSUE TITLE
(Bug) Cash payments rounds down to 0 given a small enough billl

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#883]
The database currently allows us to store currency values to 4 decimal places (19, 4). 
This allows us to store transactions to a precision of 0.001. 

In theory an invoice is allowed to be created for $0.001 according to the enterprise currency. If this is done in the current system the client will be billed rounding down by default, resulting in a bill of $0.00. 

It is impossible for the client to pay $0.00. 

**Current Behaviour**
Invoices under the minimum currency unit ($0.01) are charged $0.00 

**Expected Behaviour** 
Invoices under the minimum currency unit should always be rounded to the minimum currency unit no regardless of rounding up or down. This is the base case.

**Comment by lomamech** [comment]
In analyzing this issue, it would be better to block at the invoicing, the Invoices under the minimum currency unit

**Comment by jniles** [comment]
This can still happen if quinine costs 0.1 USD, then that is below the
minimum FC unit.

**Comment by lomamech** [comment]
For medicines that cost very much less, usually it is not sold per unit

**Comment by jniles** [comment]
@lomamech, you are right.  But I think it is better to have a policy for when a patient does have an account balance of a small amount (23 FC for example).  In my opinion, it would be best to round up to 50FC than it would be to round down to 0, as the system currently does.

**Comment by jniles** [comment]
Well, we've never been able to reproduce this issue, so I don't know if it is a relevant bug still. Closing until we discover another report of this bug.
