### ISSUE TITLE
(Bug) Journal Vouchers let you make transactions against title accounts

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#884]
Title accounts are currently shown with all other accounts types in the typeahead on journal vouchers. They can also be selected and vouchers can be made from and to title accounts without issue.

![screenshot 2016-11-11 at 09 26 22](https://cloud.githubusercontent.com/assets/2844572/20208826/f509e6b2-a7f0-11e6-8f60-06cffa4d1da6.png)

**Current Behaviour** 
Title accounts can be selected and are valid accounts for voucher transactions. 

**Expected Behaviour**
Title accounts show not be able to be selected in journal vouchers 
A voucher hitting a title account should be rejected and not posted to the journal

**Comment by jniles** [comment]
@sfount, do you propose that the title accounts are disabled, or not shown?

**Comment by jniles** [comment]
I'll take a look at this by disabling title accounts.

**Comment by sfount** [comment]
Disabled sounds good to me 👍 That still provides the title 'groups' context but does not allow the user to select accounts that cannot make up a transaction.

**Comment by jniles** [comment]
Cool.  I've implemented it in #898.

**Comment by sfount** [comment]
@jnilles @IMA-WorldHealth/bhima-core Do you think that the posting journal server methods should reject a transaction that tries to use a title account or should this just be implemented by limiting the client?  

I have no problem with limiting the client for now but I know there will always be a way until it is restricted on the server.

**Comment by jniles** [comment]
@sfount, limiting on the server is a good idea.

Ideally, `bhConstants` should be shared between the server/client.  I'm not sure how to do this yet.
