### ISSUE TITLE
(Bug) Journal vouchers let you submit values less than the stored accuracy

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#885]
The Journal Voucher module currently lets you enter and submit values that are less than the accuracy of the system's database. As the database does not support numbers this low they will be rounded to 0 and cause invalid transactions. 

These values should be rejected, both on the client and the server. 

![screenshot 2016-11-11 at 09 28 36](https://cloud.githubusercontent.com/assets/2844572/20208895/4c3c9d4e-a7f1-11e6-9f47-99ea1de6c38e.png)

**Comment by jniles** [comment]
I'll tackle this one once the bug in #878 is fixed.
