### ISSUE TITLE
(test) Run integration and end-to-end tests on separate CIs

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#887]
I propose that we shard our tests over multiple continuous integration services.  This would allow our tests to speed up overall, as well as limit the affect of a single network outage on our testing procedures.

I recommend Semaphore CI, as I've heard good things about its speed.  But we could explore our options.

I see the ideal testing like this:
 1. Travis -> installs dependencies and runs end-to-end tests
 2. Other Service -> runs Lint, Karma, and integration tests.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
This sounds like a good idea to me - as long as the additional service added is a reliable as Travis has proven to be over the last few months this should help speed up pull requests. 

I still think that the main bottleneck will be end to end tests; after the initial release we should investigate turning of angular browser synchronisation and moving to a perform action -> wait for result testing scheme. 

Waiting for Angular (digest, $http, etc.) can more than double the time it takes for tests to be performed.

**Comment by jniles** [comment]
Note that lint tests no longer exist.
