### ISSUE TITLE
(Bug) Patient Invoice totals UX

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#888]
If an invoice has items that are worth fractions of cents this can make invoice receipts very confusing. The currency filter is currently used on all invoices which rounds all values to the minimum currency. This can make it look like the calculations are incorrect. 

We should also consider all places currencies are rounded in the application to ensure it is consistent.

**Current behaviour**
Invoice displays medicine value of 0.0065 as $0.01 
$0.01 * 4 = $0.03

![screenshot 2016-11-11 at 11 17 40](https://cloud.githubusercontent.com/assets/2844572/20211881/dca69dc6-a800-11e6-9ed0-e92bbfabb26d.png)

**Expected behaviour**
0.0065 * 4 = $0.03

**Comment by jniles** [comment]
Might be related to #939.  They could be address in the same PR.

**Comment by sfount** [comment]
This issue is to do with showing the full unit price on invoices - the bug referenced is to do with the client side invoice modules. 

I think this was addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/904 however it has not been updated with `master` for merging.

**Comment by jniles** [comment]
Ah, okay.  That makes sense.
