### ISSUE TITLE
(refactor) Journal Vouchers should use the ReceiptService for voucher receipts

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#891]
At the moment, the complex voucher page and simple voucher page use Modal.openReports() to show their receipts.  A much cleaner way has been laid out in both the PatientInvoice and Cash modules, by calling the ReceiptModal service as follows:
```js
function openVoucherReceipt(uuid) {
  return Receipts.voucher(uuid, { lang : Session.lang });
}
```

This proposal:
 1. Keeps all our receipts in one location, which is easier to develop on.
 2. Ensure the controller doesn't have to know anything about rendering (at the moment, you have to specify 'pdf' in openReports).
 3. Less code in total, which is a :+1: for maintainability.

**Comment by sfount** [comment]
This refactor could be addressed in conjunction with https://github.com/IMA-WorldHealth/bhima-2.X/issues/874.

**Comment by jniles** [comment]
Alright, will do!
