### ISSUE TITLE
(feature request) "Download As CSV" for registries/reports

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#895]
We currently support PDF renderers, JSON, and HTML.  It would be nice to allow users to download all the information displayed in a ui-grid as CSV, for example.  Curious users could then make their own Excel-based reports and the patients, invoices, etc, of their system.

I imagine this feature as a dropdown button next to "Print" (or on the same button) that would allow the user to download the CSV file directly.  The CSV could be generated on either the server or the client - I'm in favor of using the server for greater flexibility.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
I think this feature should be prioritised soon for a number of reports/ data views. 

The CSV does not have to carefully formatted or concerned about view and user experience. When working with finances on many bank websites it is possible to download your transactions as CSV - this can give a more experienced user any view into the data they would like, using any software they choose. This feature would give the system a lot of flexibility without requiring much overhead.

**Comment by jniles** [comment]
It doesn't have to be carefully formatted, but it does have to be valid CSV ;)

**Comment by jniles** [comment]
Note: this was implemented in https://github.com/Vanga-Hospital/bhima-2.X/pull/89.

**Comment by jniles** [comment]
Closed as alive in master.
