### ISSUE TITLE
Upgrade to Angular 1.5

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#90]
Angular 1.5 was [just released](http://angularjs.blogspot.de/2016/02/angular-150-ennoblement-facilitation.html).  The most significant advantage is first-class support for `angular.component()` which we should seriously consider implementing anywhere we would use a directive (and potentially re-writing some of our old directives as components).

Both the [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md) and [migration guide](https://docs.angularjs.org/guide/migration) seem to suggest that we will not have any breaking changes - only security and potentially performance improvements.

**Comment by DedrickEnc** [comment]
As we are adding component in the system which is only compatible from angular 1.5.X we should migrate.

**Comment by jniles** [comment]
Once #95 lands, this issue will be closed.
