### ISSUE TITLE
Money transferred out of the cash window has no defined type

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#900]
The 'Money Transfer' type is not used for exporting money from a cashbox, currently it is written with an 'Undefined' type. 

![screenshot 2016-11-14 at 14 16 38](https://cloud.githubusercontent.com/assets/2844572/20266165/34bad722-aa75-11e6-8384-ddd479df38fa.png)

**Comment by jniles** [comment]
To fix this issue, [this function](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/CashService.js#L96) should be updated to put in a type ID.

**Comment by sfount** [comment]
Sounds good to me - I'll take this one.

**Comment by jniles** [comment]
@sfount, did this ever get fixed?

Otherwise, this is a good one to pass on.

**Comment by jniles** [comment]
I think this got hacked in with the rewrite of the transfer module.
