### ISSUE TITLE
Remove distributable type on invoices

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#903]
There is currently a flag in the invoices table and on the invoice client module that lets the user set if an invoice can be distributed or not. 

As this has not at all been implemented in stock control I suggest we remove it until it has significance. This could just result in confusion for users. 

The 2.x design also aims to make things less tightly coupled whilst still being able to track the same entities - I propose that invoices shouldn't be flagged as to be distributed or not but instead invoices are referenced by the stock distribution module optionally. This means that stock can be distributed with or without an invoice and the invoice is no longer central to the operation.

**Comment by jniles** [comment]
I'm fine with this change.  Seems logical to me!

**Comment by jniles** [comment]
@sfount,can you tackle this?

**Comment by jniles** [comment]
I think this was closed in the Vanga-Hospital repository.
