### ISSUE TITLE
(feature) Use webcam-directive to take patient pictures

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#909]
There is a very nice, compact module that handles webcam control very well called [webcam-directive](https://github.com/jonashartmann/webcam-directive).  I propose that we use it to take the patient image on the patient page with this directive hooked up to a webcam.  The user would have the option to take a new picture to replace the patient image.

**Comment by jeremielodi** [comment]
Hi @jniles, I implemented a snapeshot service that uses  webcam-directive. it returns the data_url of snapshort when the user try to save.
You can see how it looks like  in  the following picture
![snapshort](https://user-images.githubusercontent.com/25838121/32445939-94f6609c-c307-11e7-8b88-e07a7df776bf.PNG)

So, my question is : where I should exactly integrate this service in the patient module

**Comment by jniles** [comment]
Hi @jeremielodi, looks good!

The image should be available on the Patient Record page, where you would normally upload a photo.  Ideally, the user should have the option to either upload a photo or take a picture.  See below:

![patientrecord](https://user-images.githubusercontent.com/896472/32448007-6153fcc2-c316-11e7-8107-70a7adf03e3b.PNG)
_Fig 1: The webcam would be here_

**Comment by jniles** [comment]
It is also worth noting that the `webcam-directive` has not been updated since this issue was made ... so it might be abandoned.  If there is a better webcam module/component that you can find, feel free to use it.

**Comment by jeremielodi** [comment]
this issue should be closed, #2281 solved the problem
