### ISSUE TITLE
(refactor) Harmonize Complex Voucher and Patient Invoice UI

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#912]
The Patient Invoice and Complex Voucher UI handle adding items to the grid differently.  See below.

![patientinvoiceui](https://cloud.githubusercontent.com/assets/896472/20454652/2de44336-ae47-11e6-80a7-303510850098.png)
_Fig 1: Patient Invoice UI_

![complexvoucherui](https://cloud.githubusercontent.com/assets/896472/20454653/2dec423e-ae47-11e6-8bbf-f9cc760f83ef.png)
_Fig 2: Complex Voucher UI_

In order to streamline the interface, I propose that we adopt the Patient Invoice UI on the Complex Vouchers page.  It has the following advantages:
 1. Able to add multiple rows at a time.
 2. Clearly separates adding rows from tools on the grid (like caching of incomplete data).

This could be worked on whenever.

**Comment by sfount** [comment]
Agreed. Even something as simple as having it in the same place may make the different more complicated modules more manageable. This also sounds like a huge improvement to maintainability.

**Comment by jniles** [comment]
Closed in https://github.com/Vanga-Hospital/bhima-2.X/pull/91.
