### ISSUE TITLE
(refactor) Ensure account selection is uniform across core modules

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#914]
Following the work by @jniles in https://github.com/IMA-WorldHealth/bhima-2.X/pull/898 we should ensure all modules are up to the same standard with account selection. This goes a long way to reducing user introduced errors. 

I recommend that the work is wrapped up in a directive so that it can be used by developers on any and all modules. Suggested name `bhAccountSelect`

**Development** 
- [x] Implement `bhAccountSelect` component with the same standards as the journal voucher page 

**Implementation**
Ensure core modules use display account selection up to the latest standards (component)
 - ~~Fiscal Year Creation~~ (no longer applicable)
 - [x] Enterprise Set up
 - [x] Complex Vouchers
 - [x]  Cashbox management
 - [x] Debtor Group Management
 - ~~Inventory Group Management~~ (`bh-account-select doesn't need to support all the features required in this use case)

**Comment by jniles** [comment]
`bhAccountSelect` has been implemented and these can be tackled anytime.

**Comment by jniles** [comment]
@sfount, what is the progress with this?

**Comment by sfount** [comment]
It looks like everything here has been completed.
