### ISSUE TITLE
(refactor) Standardize create state URLs across the application

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#917]
For future developer's benefit, we should standardize our URL naming scheme.  At the moment, we have:
 1. `/purchases/create`
 2. `/fiscal/create`
 3. `/cashboxes/create`

The outstanding URLs are:
 1. `/invoices/patient`
 2. `/cash/:id` --> create state

This leads to bizarre other names, such as 
 1. `/finance/reports/cash_payment` for the cash payment registry (because `/cash` is taken).

I propose that we rename
 1. `/invoices/patient` --> `/invoices/create`.
 2. `/cash/:id` --> `/cash/:id/create`

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
I agree with this suggestion. I think `invoices/patient` was from a discussion about if patient invoicing should be part of the patients entity or an invoicing entity - it was half done and never followed up on. 

What do you think of the keyword `new` for the URL structure? I like `create` for the methods/ behind the scenes but new sounds more natural for some of the entities
'new patient', 'new fiscal year'

This is a very minor syntax issue as very few people will navigate with the URL.

**Comment by jniles** [comment]
We could use `new`.  Fewer characters to type is typically better in my mind.

My thoughts are that the URL will be mainly for developers, and since we already name all our files "module.create.js", it would be easier for me to search for create for both the URL and the file.

I propose that we do this in two steps:
 1. Standardize the $state URLs using `/create`.
 2. Convert all `create`s to `new`s after discussing it in an issue.

**Comment by jniles** [comment]
@sfount, what are your current thoughts on this?

**Comment by jniles** [comment]
This issue is also old enough to be irrelevant.  We may think about this more if/when we update BHIMA to a new router.
