### ISSUE TITLE
(feature) Show "Canceled" or "Void" on Invoices that have a credit note

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#918]
The invoices in 2.x can be canceled with a credit note, but there is no indication on the receipt that it has been revered.  I propose that we add a "VOID" stamp or "CANCELED" stamp to the invoice, so that  it shows clearly that it was canceled.  [See this link](https://visp.net/wp-content/uploads/2012/10/Void.png) for an idea of what it should look like.

We could do a similar thing for "PAID" invoices as well.

**Comment by sfount** [comment]
I think this was completed by @mbayopanda in a recent PR. 

**Invoice receipt that has an associated credit note**
![screenshot 2017-02-20 at 10 53 26](https://cloud.githubusercontent.com/assets/2844572/23120008/e09384ae-f75a-11e6-8c13-a4e1aeaa285a.png)
