### ISSUE TITLE
Reports using Enterprise currency 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#924]
This issue is to track ensuring all reports are provided in the enterprises set currency. 

**Required refactors**
- [x] Patient Invoice
- [ ] Cashflow (Requires controller refactor/ simplification for future maintenance) 
- [x] Patient financial activity
- [x] Customer Debts
- [x] Income vs. Expense 
- [x] Accounts Report

**Comment by jniles** [comment]
I'll look into the accounts report.
