### ISSUE TITLE
(refactor) Service configuration

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#927]
**Required Updates**
* `ui-router` latest standards `$state` management 
* Headercrumb standards
- [x] ID displaying for index in table - removed
- [x] [Bug] Overview crashses with 404 - routes not imlemented
* Optionally add cost and profit center instead of leaving blank
* Separate .route.js

**Comment by jniles** [comment]
Closing this as superseded by https://github.com/IMA-WorldHealth/bhima-2.X/issues/1369.
