### ISSUE TITLE
(bug) Debtor Group Select

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#928]
If there are no debtor groups available for assignment, the patient registration page's debtor group assignment breaks in a rather ugly way.  See below:

![debtorgroupbug](https://cloud.githubusercontent.com/assets/896472/20594230/a6c36736-b235-11e6-96ff-94312c589b15.png)
_Fig 1: Debtor Group Select Bug_

Ideally, this warning should be in red, with the ui-select completely hidden.

**Comment by jniles** [comment]
@lomamech, can you tackle this one?

**Comment by jniles** [comment]
@lomamech, did this get addressed?

**Comment by lomamech** [comment]
Yes it is already merged

**Comment by jniles** [comment]
Thanks!
