### ISSUE TITLE
(Feature) Optional (important) field selection

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#933]
Currently in service management cost and profit centers can be assigned using a normal select - they are optional fields but are essential to the correct functioning of the accounting. 
* Once a cost or profit center is allocated they can not be removed as the select has no null value, this is a bad user experience 
* No logic or rules exist considering if you can change a cost or profit center and the implications of that 

I suggest a component for important but optional data that allows the user to 'Add' the field, making the choice to add or remove the configuration makes it clear that it is optional. 

**Service management - optional fields not added**
![service](https://cloud.githubusercontent.com/assets/2844572/20607014/557aad04-b275-11e6-980c-d9a86babc610.png)

**Service management - add cost center configuration**
![service cost center](https://cloud.githubusercontent.com/assets/2844572/20607016/5d2305ba-b275-11e6-909d-b8af80feb449.png)

**Comment by jniles** [comment]
So, if I'm thinking about this correctly, it would look like this in code?

```html
<bh-hidden-field label="SERVICES.COST_CENTER">
  <div class="form-group">
      <label> ... </label>
       <input .... >
   </div>
</bh-hidden-field>
```

Something like that?

**Comment by jniles** [comment]
I'll work on this.  It will clean up our reports interface greatly.
