### ISSUE TITLE
(Bug) Patient Invoices do not recalculate totals when an item is removed

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#939]
When line items are removed from an invoice on the Patient Invoice module the totals remain the same. If a new line is added the totals are recalculated correctly. 

This is very important as it is assumed the total always reflects the items in the invoice.

**Comment by jniles** [comment]
This is probably due to a `fastWatch`.  Emitting a `uiGridConstants.dataChange.EDIT` will fix it.
