### ISSUE TITLE
(feature) SessionService.reload()

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#942]
When we make large changes to the user's session, they need to log out and re-login to gain them.  Changes such as project and module access and changes to the username, among others.

I propose we add the feature `SessionService.reload()`, which sends an HTTP request to get a new version of the user's session and store it in the `SessionService`.  The call would go to `/users/session` and return the same session object as login.  _It should use the same code as login_.

In the most complex case, if the session refresh removes the user access to all modules, the `Session.reload()` call should log the user out.  If the `Session.reload()` call simply removes privileges to the current module, the user should be redirected to the `home` state.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
This sounds like a very useful feature - especially for when a hospital is being set up or installed. 

To add to this we currently have a bug where the user is logged in successfully on the client but the server session is no longer valid - the client reports 'You are not authorised' but does not actually allow you to log out. Re-requesting the server in this case should allow the client to realise that the server session is no longer valid and force the user to log out.

**Comment by jniles** [comment]
@lomamech, can you take a look at this when you get a chance?

**Comment by jniles** [comment]
Closed in #1001.
