### ISSUE TITLE
(Bug) Negative values can be set for price list items

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#955]
Currently price lists can be set as values or as percentages. 

If set as a percentage this will be applied to the sale price of an inventory item, a negative percentage will reduce the price and a positive percentage will increase it.

If set as a value a negative value, this will be allowed by the client - this will be directly set at invoice. Although an invoice cannot be submitted with any value 0 or less this is still set. 

**Problem**
You can set a price list item as a value, less than 0 

**Expected Behavior**
Either the client or server will block a price list item being set as a value and less than 0

**Comment by jniles** [comment]
@sfount @mbayopanda, who is working on this?
