### ISSUE TITLE
(Bug) Inventory items can be submitted with values less than 0 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#956]
Currently inventory items can be set with 'price' less than 0. The client submits this and an inventory item is created with price '0'.

**Comment by jniles** [comment]
I got this one.

**Comment by sfount** [comment]
This may have been as a result of `STRICT_ALL_TABLES` not being correctly set on my development machine. I think the client UX could be greatly improved by not finding out that it cannot be negative through a `400 BAD REQUEST`.

**Comment by jniles** [comment]
I've implemented an `ngMin` so that there is client error message that appears.  I agree that the previous UX was terrible.

**Comment by jniles** [comment]
Closed in #981.
