### ISSUE TITLE
(bug) landing page throw an error for the debtors panel

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#960]
With Lukonga data, the debtor panel in the landing page throw an error : 

![error](https://cloud.githubusercontent.com/assets/5445251/20649492/428f616e-b476-11e6-9846-f707d523202b.png)

**Comment by sfount** [comment]
@mbayopanda This report is driven by the debtor aged report. This likely means that the report either breaks or does not return an `aggregates` (totals) property if there is no data. That is where I would look.

**Comment by mbayopanda** [comment]
@sfount Okay, i try BHIMA with `lukonga-latest.sql` file. Thanks
