### ISSUE TITLE
Patient Age Display

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#969]
Allow to display the age of the patient in the patient card, because several patients do not know their date of birth but have an idea about their age

**Comment by jniles** [comment]
I'm not sure it's a good idea to display the patient's age if on the patient card any hospital will actually use the card for identification.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by jniles** [comment]
Closing this as no longer relevant.  We support adding in "Year of Birth" instead of "Date of Birth" and that should be enough.
