### ISSUE TITLE
(Bug) UI selects do not select entity if 'debounced'

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#972]
Recently a number of account ui-selects have been updated with the property
`ng-model-options="{ debounce : 200 }"`

This helps ensure the account select works smoothly even with a very large number of accounts. However there is an issue with selecting accounts. Any time that you have typed to search for an account, the selected account will be ignored - **note this does not occur if you select an account before typing.**

With the debounce value of 200ms removed the accounts select as expected.

**Comment by jniles** [comment]
What's a good test case I can try on my machine?

**Comment by sfount** [comment]
* Navigate to enterprise page 
* Select (click on the) 'Gain on exchange rate' account select 
* Type '851'
* Click on the account 'DOTATIONS AUX PROVISIONS REGLEMANTEES87'

**Expected behaviour:**
Account 851 is selected for the gain account 

**Actual behaviour (on my machine):**
The account that was previously selected remains in the account select

**Comment by jniles** [comment]
:+1: Can reproduce.  That's annoying.

**Comment by jniles** [comment]
I think this might be fixed by ensuring that `debounce` on `blur` is 0.  See [this documentation](https://docs.angularjs.org/api/ng/directive/ngModelOptions).  I'll investigate.

**Comment by jniles** [comment]
Closing this as it is no longer relevant to the current code base.  Any implementation of `ngModelOptions` should bear this in mind.
