### ISSUE TITLE
(bug) Cashboxes page does not always load is_auxiliary properly

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#976]
In production, we are seeing the cashboxes radio select not always properly configured with "primary" or "auxiliary" cashboxes.  The database has a definition for this table, the radio buttons do not show it on the edit cashbox page.

**Comment by sfount** [comment]
I cannot reproduce this on my local machine, however I can observe the behavior on the server. I will debug this when there are no active users on the system.

**Comment by jniles** [comment]
I'll look into this one.
