### ISSUE TITLE
(Bug) Posting Invoices ignore inventory items without sales account

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#980]
If an invoice is created using inventory items without a sales account, nothing is written for the sale item. This causes invoices to not balance. 

This behavior should be blocked by the posting process and reported to the invoice creation module. It should be clear that there is no sales account for the inventory group used. 

- [ ] Block invalid sales account on the server; Imbalanced transactions cannot be created
- [ ] Block the client from requesting badly configured items

**Comment by jniles** [comment]
This was closed in #983.
