### ISSUE TITLE
(bug) Posting Journal sorts transactions as text instead of transaction ids

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#992]
The Posting Journal does not properly order Transaction IDs by their numeric ID.  Instead, it is sorted as text.  This leads to some bizarre sorting, such as shown below, where "10" is immediately under "1".

![journalsorttransids](https://cloud.githubusercontent.com/assets/896472/20749825/3870f0aa-b6f4-11e6-9b46-bfc618a1367c.png)
_Fig 1: Journal Sorting Trans IDs_

This should be fixed for maximum UX.

**Comment by jniles** [comment]
It should be noted that all registries have this problem.

**Comment by troyev** [comment]
I'll try to take a closer look at this in the next week or so. I've got the issue reproduced with a Vanga restored database. The code appears to already be parsing out the integer and sorting on that, so I suppose there's a subtle problem with it.

**Comment by troyev** [comment]
It looks like the sorting code in client/src/js/services/grid/GridSorting.js is not even being run. 
The registration functions are being called, but the transactionIds/sortByReference functions aren't called.
Next step is to find out why.

**Comment by jniles** [comment]
Hey @troyev, good investigation!

It looks like we are going to need a new sorting function.   The GridSorting function expects a string with two periods as separators - such as `IV.HEV.123`.  [Here is the failing line of code](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/grid/GridSorting.js#L104).

We use this type of identifier everywhere but the Posting Journal.  In the PJ, we simply use `HEV1234`.  It would be best to simply write a function that recognizes how to parse this string and sort it numerically.

**Comment by troyev** [comment]
I found out the Angular ui-grid is in fact calling the sortingAlgorithm if supplied (I put in an inline function and saw some log outputs). When sortingAlgorithm is undefined, it falls back to a default built-in sort.

The problem is that general-ledger.ctrl.js is getting an undefined function when it tries to get sortByReference or transactionIds from the sorting service. I suppose the functions aren't exposed/fetched correctly.

**Comment by troyev** [comment]
Proposed fix here:

https://github.com/IMA-WorldHealth/bhima-2.X/pull/1610

**Comment by jniles** [comment]
Closed in #1610
