### ISSUE TITLE
(Bug) Cash payment registry filters result in `400`

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#996]
The cash payment registry filtering requests cause the server to throw `400 BAD REQUEST` errors. 

On my build this is with the following filters
* Date interval 
* User (the user who created the cash payment)

That leaves reference, cash box and client, all of which seem to work.

**Comment by jniles** [comment]
I'll take a look.

**Comment by mbayopanda** [comment]
@sfount, @jniles it was caused by the missing of table name or alias in the `where` clause. I fix it, i'm doing a pull request for that

**Comment by jniles** [comment]
@mbayopanda, it's all yours!
